<?php

namespace Database\Seeders\Support;

/**
 * French word => its meaning in every native language the app supports.
 *
 * Exercise hints, prompts and word-bank tiles must appear in the LEARNER'S
 * native language, so nothing user-facing may be hardcoded to English. Seeders
 * pull from here and store the result as an ['i18n' => [...]] map, which
 * ExerciseContentService resolves per request.
 *
 * Add a word here once and every unit can use it.
 */
class FrenchVocabulary
{
    private const WORDS = [
        // --- Unit 1: café ---
        'café' => ['en' => 'coffee', 'es' => 'café', 'de' => 'Kaffee', 'ja' => 'コーヒー', 'ko' => '커피', 'tr' => 'kahve', 'ru' => 'кофе', 'ar' => 'قهوة', 'az' => 'qəhvə'],
        'thé' => ['en' => 'tea', 'es' => 'té', 'de' => 'Tee', 'ja' => 'お茶', 'ko' => '차', 'tr' => 'çay', 'ru' => 'чай', 'ar' => 'شاي', 'az' => 'çay'],
        'eau' => ['en' => 'water', 'es' => 'agua', 'de' => 'Wasser', 'ja' => '水', 'ko' => '물', 'tr' => 'su', 'ru' => 'вода', 'ar' => 'ماء', 'az' => 'su'],
        'lait' => ['en' => 'milk', 'es' => 'leche', 'de' => 'Milch', 'ja' => '牛乳', 'ko' => '우유', 'tr' => 'süt', 'ru' => 'молоко', 'ar' => 'حليب', 'az' => 'süd'],
        'croissant' => ['en' => 'croissant', 'es' => 'cruasán', 'de' => 'Croissant', 'ja' => 'クロワッサン', 'ko' => '크루아상', 'tr' => 'kruvasan', 'ru' => 'круассан', 'ar' => 'كرواسون', 'az' => 'kruassan'],
        'pain' => ['en' => 'bread', 'es' => 'pan', 'de' => 'Brot', 'ja' => 'パン', 'ko' => '빵', 'tr' => 'ekmek', 'ru' => 'хлеб', 'ar' => 'خبز', 'az' => 'çörək'],
        'éclair' => ['en' => 'eclair', 'es' => 'éclair', 'de' => 'Éclair', 'ja' => 'エクレア', 'ko' => '에클레어', 'tr' => 'ekler', 'ru' => 'эклер', 'ar' => 'إكلير', 'az' => 'ekler'],
        'sucre' => ['en' => 'sugar', 'es' => 'azúcar', 'de' => 'Zucker', 'ja' => '砂糖', 'ko' => '설탕', 'tr' => 'şeker', 'ru' => 'сахар', 'ar' => 'سكر', 'az' => 'şəkər'],
        'bonjour' => ['en' => 'hello', 'es' => 'hola', 'de' => 'hallo', 'ja' => 'こんにちは', 'ko' => '안녕하세요', 'tr' => 'merhaba', 'ru' => 'привет', 'ar' => 'مرحبا', 'az' => 'salam'],
        'merci' => ['en' => 'thank you', 'es' => 'gracias', 'de' => 'danke', 'ja' => 'ありがとう', 'ko' => '감사합니다', 'tr' => 'teşekkürler', 'ru' => 'спасибо', 'ar' => 'شكرا', 'az' => 'təşəkkür'],
        'oui' => ['en' => 'yes', 'es' => 'sí', 'de' => 'ja', 'ja' => 'はい', 'ko' => '네', 'tr' => 'evet', 'ru' => 'да', 'ar' => 'نعم', 'az' => 'bəli'],
        'non' => ['en' => 'no', 'es' => 'no', 'de' => 'nein', 'ja' => 'いいえ', 'ko' => '아니요', 'tr' => 'hayır', 'ru' => 'нет', 'ar' => 'لا', 'az' => 'xeyr'],
        "s'il vous plaît" => ['en' => 'please', 'es' => 'por favor', 'de' => 'bitte', 'ja' => 'お願いします', 'ko' => '부탁합니다', 'tr' => 'lütfen', 'ru' => 'пожалуйста', 'ar' => 'من فضلك', 'az' => 'zəhmət olmasa'],
        'au revoir' => ['en' => 'goodbye', 'es' => 'adiós', 'de' => 'auf Wiedersehen', 'ja' => 'さようなら', 'ko' => '안녕히 가세요', 'tr' => 'hoşça kal', 'ru' => 'до свидания', 'ar' => 'مع السلامة', 'az' => 'sağ ol'],
        'madame' => ['en' => 'madam', 'es' => 'señora', 'de' => 'gnädige Frau', 'ja' => 'マダム', 'ko' => '부인', 'tr' => 'hanımefendi', 'ru' => 'госпожа', 'ar' => 'سيدتي', 'az' => 'xanım'],
        'monsieur' => ['en' => 'sir', 'es' => 'señor', 'de' => 'mein Herr', 'ja' => 'ムッシュ', 'ko' => '선생님', 'tr' => 'beyefendi', 'ru' => 'господин', 'ar' => 'سيدي', 'az' => 'cənab'],
        'je voudrais' => ['en' => 'I would like', 'es' => 'quisiera', 'de' => 'ich möchte', 'ja' => 'ください', 'ko' => '주세요', 'tr' => 'istiyorum', 'ru' => 'я хочу', 'ar' => 'أريد', 'az' => 'istəyirəm'],
        'donnez-moi' => ['en' => 'give me', 'es' => 'deme', 'de' => 'geben Sie mir', 'ja' => 'ください', 'ko' => '주세요', 'tr' => 'bana ver', 'ru' => 'дайте мне', 'ar' => 'أعطني', 'az' => 'mənə ver'],
        "l'addition" => ['en' => 'the bill', 'es' => 'la cuenta', 'de' => 'die Rechnung', 'ja' => 'お会計', 'ko' => '계산서', 'tr' => 'hesap', 'ru' => 'счёт', 'ar' => 'الحساب', 'az' => 'hesab'],
        'un' => ['en' => 'a', 'es' => 'un', 'de' => 'ein', 'ja' => '一つの', 'ko' => '하나의', 'tr' => 'bir', 'ru' => 'один', 'ar' => 'واحد', 'az' => 'bir'],
        'je' => ['en' => 'I', 'es' => 'yo', 'de' => 'ich', 'ja' => '私', 'ko' => '나', 'tr' => 'ben', 'ru' => 'я', 'ar' => 'أنا', 'az' => 'mən'],
        'voudrais' => ['en' => 'would like', 'es' => 'quisiera', 'de' => 'möchte', 'ja' => 'ほしい', 'ko' => '원하다', 'tr' => 'istiyorum', 'ru' => 'хотел бы', 'ar' => 'أود', 'az' => 'istərdim'],
        'et' => ['en' => 'and', 'es' => 'y', 'de' => 'und', 'ja' => 'と', 'ko' => '그리고', 'tr' => 've', 'ru' => 'и', 'ar' => 'و', 'az' => 'və'],
        'avec' => ['en' => 'with', 'es' => 'con', 'de' => 'mit', 'ja' => 'と一緒に', 'ko' => '와 함께', 'tr' => 'ile', 'ru' => 'с', 'ar' => 'مع', 'az' => 'ilə'],
        // --- Unit 2: objects, colours, numbers ---
        'livre' => ['en' => 'book', 'es' => 'libro', 'de' => 'Buch', 'ja' => '本', 'ko' => '책', 'tr' => 'kitap', 'ru' => 'книга', 'ar' => 'كتاب', 'az' => 'kitab'],
        'stylo' => ['en' => 'pen', 'es' => 'bolígrafo', 'de' => 'Kugelschreiber', 'ja' => 'ペン', 'ko' => '펜', 'tr' => 'kalem', 'ru' => 'ручка', 'ar' => 'قلم', 'az' => 'qələm'],
        'rouge' => ['en' => 'red', 'es' => 'rojo', 'de' => 'rot', 'ja' => '赤', 'ko' => '빨간색', 'tr' => 'kırmızı', 'ru' => 'красный', 'ar' => 'أحمر', 'az' => 'qırmızı'],
        'bleu' => ['en' => 'blue', 'es' => 'azul', 'de' => 'blau', 'ja' => '青', 'ko' => '파란색', 'tr' => 'mavi', 'ru' => 'синий', 'ar' => 'أزرق', 'az' => 'mavi'],
        'vert' => ['en' => 'green', 'es' => 'verde', 'de' => 'grün', 'ja' => '緑', 'ko' => '초록색', 'tr' => 'yeşil', 'ru' => 'зелёный', 'ar' => 'أخضر', 'az' => 'yaşıl'],
        'jaune' => ['en' => 'yellow', 'es' => 'amarillo', 'de' => 'gelb', 'ja' => '黄色', 'ko' => '노란색', 'tr' => 'sarı', 'ru' => 'жёлтый', 'ar' => 'أصفر', 'az' => 'sarı'],
        'noir' => ['en' => 'black', 'es' => 'negro', 'de' => 'schwarz', 'ja' => '黒', 'ko' => '검은색', 'tr' => 'siyah', 'ru' => 'чёрный', 'ar' => 'أسود', 'az' => 'qara'],
        'blanc' => ['en' => 'white', 'es' => 'blanco', 'de' => 'weiß', 'ja' => '白', 'ko' => '하얀색', 'tr' => 'beyaz', 'ru' => 'белый', 'ar' => 'أبيض', 'az' => 'ağ'],
        'zéro' => ['en' => 'zero', 'es' => 'cero', 'de' => 'null', 'ja' => 'ゼロ', 'ko' => '영', 'tr' => 'sıfır', 'ru' => 'ноль', 'ar' => 'صفر', 'az' => 'sıfır'],
        'deux' => ['en' => 'two', 'es' => 'dos', 'de' => 'zwei', 'ja' => '二', 'ko' => '둘', 'tr' => 'iki', 'ru' => 'два', 'ar' => 'اثنان', 'az' => 'iki'],
        'trois' => ['en' => 'three', 'es' => 'tres', 'de' => 'drei', 'ja' => '三', 'ko' => '셋', 'tr' => 'üç', 'ru' => 'три', 'ar' => 'ثلاثة', 'az' => 'üç'],
        'quatre' => ['en' => 'four', 'es' => 'cuatro', 'de' => 'vier', 'ja' => '四', 'ko' => '넷', 'tr' => 'dört', 'ru' => 'четыре', 'ar' => 'أربعة', 'az' => 'dörd'],
        'cinq' => ['en' => 'five', 'es' => 'cinco', 'de' => 'fünf', 'ja' => '五', 'ko' => '다섯', 'tr' => 'beş', 'ru' => 'пять', 'ar' => 'خمسة', 'az' => 'beş'],
        'six' => ['en' => 'six', 'es' => 'seis', 'de' => 'sechs', 'ja' => '六', 'ko' => '여섯', 'tr' => 'altı', 'ru' => 'шесть', 'ar' => 'ستة', 'az' => 'altı'],
        'sept' => ['en' => 'seven', 'es' => 'siete', 'de' => 'sieben', 'ja' => '七', 'ko' => '일곱', 'tr' => 'yedi', 'ru' => 'семь', 'ar' => 'سبعة', 'az' => 'yeddi'],
        'huit' => ['en' => 'eight', 'es' => 'ocho', 'de' => 'acht', 'ja' => '八', 'ko' => '여덟', 'tr' => 'sekiz', 'ru' => 'восемь', 'ar' => 'ثمانية', 'az' => 'səkkiz'],
        'neuf' => ['en' => 'nine', 'es' => 'nueve', 'de' => 'neun', 'ja' => '九', 'ko' => '아홉', 'tr' => 'dokuz', 'ru' => 'девять', 'ar' => 'تسعة', 'az' => 'doqquz'],
        'dix' => ['en' => 'ten', 'es' => 'diez', 'de' => 'zehn', 'ja' => '十', 'ko' => '열', 'tr' => 'on', 'ru' => 'десять', 'ar' => 'عشرة', 'az' => 'on'],
        // --- Unit 3: family and people ---
        'mère' => ['en' => 'mother', 'es' => 'madre', 'de' => 'Mutter', 'ja' => '母', 'ko' => '어머니', 'tr' => 'anne', 'ru' => 'мама', 'ar' => 'أم', 'az' => 'ana'],
        'père' => ['en' => 'father', 'es' => 'padre', 'de' => 'Vater', 'ja' => '父', 'ko' => '아버지', 'tr' => 'baba', 'ru' => 'папа', 'ar' => 'أب', 'az' => 'ata'],
        'frère' => ['en' => 'brother', 'es' => 'hermano', 'de' => 'Bruder', 'ja' => '兄弟', 'ko' => '형제', 'tr' => 'erkek kardeş', 'ru' => 'брат', 'ar' => 'أخ', 'az' => 'qardaş'],
        'sœur' => ['en' => 'sister', 'es' => 'hermana', 'de' => 'Schwester', 'ja' => '姉妹', 'ko' => '자매', 'tr' => 'kız kardeş', 'ru' => 'сестра', 'ar' => 'أخت', 'az' => 'bacı'],
        'ami' => ['en' => 'friend', 'es' => 'amigo', 'de' => 'Freund', 'ja' => '友達', 'ko' => '친구', 'tr' => 'arkadaş', 'ru' => 'друг', 'ar' => 'صديق', 'az' => 'dost'],
        'voisin' => ['en' => 'neighbour', 'es' => 'vecino', 'de' => 'Nachbar', 'ja' => '隣人', 'ko' => '이웃', 'tr' => 'komşu', 'ru' => 'сосед', 'ar' => 'جار', 'az' => 'qonşu'],
        'professeur' => ['en' => 'teacher', 'es' => 'profesor', 'de' => 'Lehrer', 'ja' => '先生', 'ko' => '선생님', 'tr' => 'öğretmen', 'ru' => 'учитель', 'ar' => 'معلم', 'az' => 'müəllim'],
        'médecin' => ['en' => 'doctor', 'es' => 'médico', 'de' => 'Arzt', 'ja' => '医者', 'ko' => '의사', 'tr' => 'doktor', 'ru' => 'врач', 'ar' => 'طبيب', 'az' => 'həkim'],
        'mon' => ['en' => 'my', 'es' => 'mi', 'de' => 'mein', 'ja' => '私の', 'ko' => '나의', 'tr' => 'benim', 'ru' => 'мой', 'ar' => 'خاصتي', 'az' => 'mənim'],
        'ma' => ['en' => 'my', 'es' => 'mi', 'de' => 'meine', 'ja' => '私の', 'ko' => '나의', 'tr' => 'benim', 'ru' => 'мой', 'ar' => 'خاصتي', 'az' => 'mənim'],
        "c'est" => ['en' => 'this is', 'es' => 'este es', 'de' => 'das ist', 'ja' => 'これは', 'ko' => '이분은', 'tr' => 'bu', 'ru' => 'это', 'ar' => 'هذا', 'az' => 'bu'],
        'aussi' => ['en' => 'also', 'es' => 'también', 'de' => 'auch', 'ja' => 'も', 'ko' => '또한', 'tr' => 'de', 'ru' => 'тоже', 'ar' => 'أيضا', 'az' => 'həmçinin'],
        'il est' => ['en' => 'he is', 'es' => 'él es', 'de' => 'er ist', 'ja' => '彼は', 'ko' => '그는', 'tr' => 'o', 'ru' => 'он', 'ar' => 'هو', 'az' => 'o'],
        'elle est' => ['en' => 'she is', 'es' => 'ella es', 'de' => 'sie ist', 'ja' => '彼女は', 'ko' => '그녀는', 'tr' => 'o', 'ru' => 'она', 'ar' => 'هي', 'az' => 'o qadın'],
        'qui' => ['en' => 'who', 'es' => 'quién', 'de' => 'wer', 'ja' => '誰', 'ko' => '누구', 'tr' => 'kim', 'ru' => 'кто', 'ar' => 'مَن', 'az' => 'kim'],
        'très' => ['en' => 'very', 'es' => 'muy', 'de' => 'sehr', 'ja' => 'とても', 'ko' => '매우', 'tr' => 'çok', 'ru' => 'очень', 'ar' => 'جدا', 'az' => 'çox'],
        'mais' => ['en' => 'but', 'es' => 'pero', 'de' => 'aber', 'ja' => 'しかし', 'ko' => '하지만', 'tr' => 'ama', 'ru' => 'но', 'ar' => 'لكن', 'az' => 'amma'],
        'ou' => ['en' => 'or', 'es' => 'o', 'de' => 'oder', 'ja' => 'または', 'ko' => '또는', 'tr' => 'veya', 'ru' => 'или', 'ar' => 'أو', 'az' => 'və ya'],
        // --- Unit 4: home and objects ---
        'table' => ['en' => 'table', 'es' => 'mesa', 'de' => 'Tisch', 'ja' => 'テーブル', 'ko' => '탁자', 'tr' => 'masa', 'ru' => 'стол', 'ar' => 'طاولة', 'az' => 'masa'],
        'chaise' => ['en' => 'chair', 'es' => 'silla', 'de' => 'Stuhl', 'ja' => '椅子', 'ko' => '의자', 'tr' => 'sandalye', 'ru' => 'стул', 'ar' => 'كرسي', 'az' => 'stul'],
        'maison' => ['en' => 'house', 'es' => 'casa', 'de' => 'Haus', 'ja' => '家', 'ko' => '집', 'tr' => 'ev', 'ru' => 'дом', 'ar' => 'بيت', 'az' => 'ev'],
        'chien' => ['en' => 'dog', 'es' => 'perro', 'de' => 'Hund', 'ja' => '犬', 'ko' => '개', 'tr' => 'köpek', 'ru' => 'собака', 'ar' => 'كلب', 'az' => 'it'],
        'chat' => ['en' => 'cat', 'es' => 'gato', 'de' => 'Katze', 'ja' => '猫', 'ko' => '고양이', 'tr' => 'kedi', 'ru' => 'кот', 'ar' => 'قط', 'az' => 'pişik'],
        'le' => ['en' => 'the', 'es' => 'el', 'de' => 'der', 'ja' => 'その', 'ko' => '그', 'tr' => 'o', 'ru' => 'этот', 'ar' => 'هذا', 'az' => 'həmin'],
        'la' => ['en' => 'the', 'es' => 'la', 'de' => 'die', 'ja' => 'その', 'ko' => '그', 'tr' => 'o', 'ru' => 'этот', 'ar' => 'هذا', 'az' => 'həmin'],
        'dans' => ['en' => 'in', 'es' => 'en', 'de' => 'in', 'ja' => 'の中に', 'ko' => '안에', 'tr' => 'içinde', 'ru' => 'в', 'ar' => 'في', 'az' => 'içində'],
        'sur' => ['en' => 'on', 'es' => 'sobre', 'de' => 'auf', 'ja' => 'の上に', 'ko' => '위에', 'tr' => 'üzerinde', 'ru' => 'на', 'ar' => 'على', 'az' => 'üzərində'],
        'sous' => ['en' => 'under', 'es' => 'debajo', 'de' => 'unter', 'ja' => 'の下に', 'ko' => '아래에', 'tr' => 'altında', 'ru' => 'под', 'ar' => 'تحت', 'az' => 'altında'],
        "j'ai" => ['en' => 'I have', 'es' => 'tengo', 'de' => 'ich habe', 'ja' => '私は持っている', 'ko' => '나는 가지고 있다', 'tr' => 'var', 'ru' => 'у меня', 'ar' => 'عندي', 'az' => 'məndə var'],
        'où' => ['en' => 'where', 'es' => 'dónde', 'de' => 'wo', 'ja' => 'どこ', 'ko' => '어디', 'tr' => 'nerede', 'ru' => 'где', 'ar' => 'أين', 'az' => 'harada'],
        'voici' => ['en' => 'here is', 'es' => 'aquí está', 'de' => 'hier ist', 'ja' => 'これが', 'ko' => '여기', 'tr' => 'işte', 'ru' => 'здесь', 'ar' => 'هنا', 'az' => 'burada'],
        'ici' => ['en' => 'here', 'es' => 'aquí', 'de' => 'hier', 'ja' => 'ここ', 'ko' => '여기에', 'tr' => 'burada', 'ru' => 'здесь', 'ar' => 'هنا', 'az' => 'burada'],
        'là' => ['en' => 'there', 'es' => 'allí', 'de' => 'dort', 'ja' => 'そこ', 'ko' => '거기', 'tr' => 'orada', 'ru' => 'там', 'ar' => 'هناك', 'az' => 'orada'],
        'est' => ['en' => 'is', 'es' => 'está', 'de' => 'ist', 'ja' => 'です', 'ko' => '이다', 'tr' => 'dır', 'ru' => 'есть', 'ar' => 'يكون', 'az' => 'olmaq'],
        // --- Unit 5: days and time ---
        'soleil' => ['en' => 'sun', 'es' => 'sol', 'de' => 'Sonne', 'ja' => '太陽', 'ko' => '태양', 'tr' => 'güneş', 'ru' => 'солнце', 'ar' => 'شمس', 'az' => 'günəş'],
        'lune' => ['en' => 'moon', 'es' => 'luna', 'de' => 'Mond', 'ja' => '月', 'ko' => '달', 'tr' => 'ay', 'ru' => 'луна', 'ar' => 'قمر', 'az' => 'ay'],
        'horloge' => ['en' => 'clock', 'es' => 'reloj', 'de' => 'Uhr', 'ja' => '時計', 'ko' => '시계', 'tr' => 'saat', 'ru' => 'часы', 'ar' => 'ساعة', 'az' => 'saat'],
        'calendrier' => ['en' => 'calendar', 'es' => 'calendario', 'de' => 'Kalender', 'ja' => 'カレンダー', 'ko' => '달력', 'tr' => 'takvim', 'ru' => 'календарь', 'ar' => 'تقويم', 'az' => 'təqvim'],
        'matin' => ['en' => 'morning', 'es' => 'mañana', 'de' => 'Morgen', 'ja' => '朝', 'ko' => '아침', 'tr' => 'sabah', 'ru' => 'утро', 'ar' => 'صباح', 'az' => 'səhər'],
        'soir' => ['en' => 'evening', 'es' => 'tarde', 'de' => 'Abend', 'ja' => '夕方', 'ko' => '저녁', 'tr' => 'akşam', 'ru' => 'вечер', 'ar' => 'مساء', 'az' => 'axşam'],
        'heure' => ['en' => 'hour', 'es' => 'hora', 'de' => 'Stunde', 'ja' => '時間', 'ko' => '시간', 'tr' => 'saat', 'ru' => 'час', 'ar' => 'ساعة', 'az' => 'saat'],
        'jour' => ['en' => 'day', 'es' => 'día', 'de' => 'Tag', 'ja' => '日', 'ko' => '날', 'tr' => 'gün', 'ru' => 'день', 'ar' => 'يوم', 'az' => 'gün'],
        'lundi' => ['en' => 'Monday', 'es' => 'lunes', 'de' => 'Montag', 'ja' => '月曜日', 'ko' => '월요일', 'tr' => 'pazartesi', 'ru' => 'понедельник', 'ar' => 'الاثنين', 'az' => 'bazar ertəsi'],
        'mardi' => ['en' => 'Tuesday', 'es' => 'martes', 'de' => 'Dienstag', 'ja' => '火曜日', 'ko' => '화요일', 'tr' => 'salı', 'ru' => 'вторник', 'ar' => 'الثلاثاء', 'az' => 'çərşənbə axşamı'],
        "aujourd'hui" => ['en' => 'today', 'es' => 'hoy', 'de' => 'heute', 'ja' => '今日', 'ko' => '오늘', 'tr' => 'bugün', 'ru' => 'сегодня', 'ar' => 'اليوم', 'az' => 'bu gün'],
        'demain' => ['en' => 'tomorrow', 'es' => 'mañana', 'de' => 'morgen', 'ja' => '明日', 'ko' => '내일', 'tr' => 'yarın', 'ru' => 'завтра', 'ar' => 'غدا', 'az' => 'sabah'],
        'semaine' => ['en' => 'week', 'es' => 'semana', 'de' => 'Woche', 'ja' => '週', 'ko' => '주', 'tr' => 'hafta', 'ru' => 'неделя', 'ar' => 'أسبوع', 'az' => 'həftə'],
        'nuit' => ['en' => 'night', 'es' => 'noche', 'de' => 'Nacht', 'ja' => '夜', 'ko' => '밤', 'tr' => 'gece', 'ru' => 'ночь', 'ar' => 'ليل', 'az' => 'gecə'],
        // --- Unit 6: everyday verbs ---
        'manger' => ['en' => 'to eat', 'es' => 'comer', 'de' => 'essen', 'ja' => '食べる', 'ko' => '먹다', 'tr' => 'yemek', 'ru' => 'кушать', 'ar' => 'الأكل', 'az' => 'yemək yemək'],
        'boire' => ['en' => 'to drink', 'es' => 'beber', 'de' => 'trinken', 'ja' => '飲む', 'ko' => '마시다', 'tr' => 'içmek', 'ru' => 'пить', 'ar' => 'الشرب', 'az' => 'içmək'],
        'marcher' => ['en' => 'to walk', 'es' => 'caminar', 'de' => 'gehen', 'ja' => '歩く', 'ko' => '걷다', 'tr' => 'yürümek', 'ru' => 'гулять', 'ar' => 'التمشي', 'az' => 'gəzmək'],
        'parler' => ['en' => 'to speak', 'es' => 'hablar', 'de' => 'sprechen', 'ja' => '話す', 'ko' => '말하다', 'tr' => 'konuşmak', 'ru' => 'говорить', 'ar' => 'التكلم', 'az' => 'danışmaq'],
        'dormir' => ['en' => 'to sleep', 'es' => 'dormir', 'de' => 'schlafen', 'ja' => '寝る', 'ko' => '자다', 'tr' => 'uyumak', 'ru' => 'спать', 'ar' => 'النوم', 'az' => 'yatmaq'],
        'tu' => ['en' => 'you', 'es' => 'tú', 'de' => 'du', 'ja' => 'あなた', 'ko' => '너', 'tr' => 'sen', 'ru' => 'ты', 'ar' => 'أنت', 'az' => 'sən'],
        'nous' => ['en' => 'we', 'es' => 'nosotros', 'de' => 'wir', 'ja' => '私たち', 'ko' => '우리', 'tr' => 'biz', 'ru' => 'мы', 'ar' => 'نحن', 'az' => 'biz'],
        'beaucoup' => ['en' => 'a lot', 'es' => 'mucho', 'de' => 'viel', 'ja' => 'たくさん', 'ko' => '많이', 'tr' => 'çok', 'ru' => 'много', 'ar' => 'كثير', 'az' => 'çoxlu'],
        'toujours' => ['en' => 'always', 'es' => 'siempre', 'de' => 'immer', 'ja' => 'いつも', 'ko' => '항상', 'tr' => 'her zaman', 'ru' => 'всегда', 'ar' => 'دائما', 'az' => 'həmişə'],
        'bien' => ['en' => 'well', 'es' => 'bien', 'de' => 'gut', 'ja' => 'よく', 'ko' => '잘', 'tr' => 'iyi', 'ru' => 'хорошо', 'ar' => 'بخير', 'az' => 'yaxşıyam'],
        'vite' => ['en' => 'fast', 'es' => 'rápido', 'de' => 'schnell', 'ja' => '速く', 'ko' => '빨리', 'tr' => 'hızlı', 'ru' => 'быстро', 'ar' => 'بسرعة', 'az' => 'sürətli'],
        'souvent' => ['en' => 'often', 'es' => 'a menudo', 'de' => 'oft', 'ja' => 'しばしば', 'ko' => '자주', 'tr' => 'sık sık', 'ru' => 'часто', 'ar' => 'غالبا', 'az' => 'tez-tez'],
        'jamais' => ['en' => 'never', 'es' => 'nunca', 'de' => 'nie', 'ja' => '決して', 'ko' => '결코', 'tr' => 'asla', 'ru' => 'никогда', 'ar' => 'أبدا', 'az' => 'heç vaxt'],
        'lentement' => ['en' => 'slowly', 'es' => 'despacio', 'de' => 'langsam', 'ja' => 'ゆっくり', 'ko' => '천천히', 'tr' => 'yavaş', 'ru' => 'медленно', 'ar' => 'ببطء', 'az' => 'yavaş'],
        'maintenant' => ['en' => 'now', 'es' => 'ahora', 'de' => 'jetzt', 'ja' => '今', 'ko' => '지금', 'tr' => 'şimdi', 'ru' => 'сейчас', 'ar' => 'الآن', 'az' => 'indi'],
        'il' => ['en' => 'he', 'es' => 'él', 'de' => 'er', 'ja' => '彼', 'ko' => '그', 'tr' => 'o', 'ru' => 'он', 'ar' => 'هو', 'az' => 'o kişi'],
        'elle' => ['en' => 'she', 'es' => 'ella', 'de' => 'sie', 'ja' => '彼女', 'ko' => '그녀', 'tr' => 'o', 'ru' => 'она', 'ar' => 'هي', 'az' => 'o qadın'],
        // --- Unit 7: describing things ---
        'grand' => ['en' => 'big', 'es' => 'grande', 'de' => 'groß', 'ja' => '大きい', 'ko' => '큰', 'tr' => 'büyük', 'ru' => 'большой', 'ar' => 'كبير', 'az' => 'böyük'],
        'petit' => ['en' => 'small', 'es' => 'pequeño', 'de' => 'klein', 'ja' => '小さい', 'ko' => '작은', 'tr' => 'küçük', 'ru' => 'маленький', 'ar' => 'صغير', 'az' => 'kiçik'],
        'chaud' => ['en' => 'hot', 'es' => 'caliente', 'de' => 'heiß', 'ja' => '熱い', 'ko' => '뜨거운', 'tr' => 'sıcak', 'ru' => 'горячий', 'ar' => 'ساخن', 'az' => 'isti'],
        'froid' => ['en' => 'cold', 'es' => 'frío', 'de' => 'kalt', 'ja' => '冷たい', 'ko' => '차가운', 'tr' => 'soğuk', 'ru' => 'холодный', 'ar' => 'بارد', 'az' => 'soyuq'],
        'bon' => ['en' => 'good', 'es' => 'bueno', 'de' => 'gut', 'ja' => '良い', 'ko' => '좋은', 'tr' => 'iyi', 'ru' => 'хороший', 'ar' => 'جيد', 'az' => 'yaxşı'],
        'mauvais' => ['en' => 'bad', 'es' => 'malo', 'de' => 'schlecht', 'ja' => '悪い', 'ko' => '나쁜', 'tr' => 'kötü', 'ru' => 'плохой', 'ar' => 'سيء', 'az' => 'pis'],
        'nouveau' => ['en' => 'new', 'es' => 'nuevo', 'de' => 'neu', 'ja' => '新しい', 'ko' => '새로운', 'tr' => 'yeni', 'ru' => 'новый', 'ar' => 'جديد', 'az' => 'yeni'],
        'vieux' => ['en' => 'old', 'es' => 'viejo', 'de' => 'alt', 'ja' => '古い', 'ko' => '오래된', 'tr' => 'eski', 'ru' => 'старый', 'ar' => 'قديم', 'az' => 'köhnə'],
        'beau' => ['en' => 'beautiful', 'es' => 'hermoso', 'de' => 'schön', 'ja' => '美しい', 'ko' => '아름다운', 'tr' => 'güzel', 'ru' => 'красивый', 'ar' => 'جميل', 'az' => 'gözəl'],
        'joli' => ['en' => 'pretty', 'es' => 'bonito', 'de' => 'hübsch', 'ja' => 'かわいい', 'ko' => '예쁜', 'tr' => 'güzel', 'ru' => 'красивый', 'ar' => 'جميل', 'az' => 'gözəl'],
        'facile' => ['en' => 'easy', 'es' => 'fácil', 'de' => 'leicht', 'ja' => '簡単な', 'ko' => '쉬운', 'tr' => 'kolay', 'ru' => 'легко', 'ar' => 'سهل', 'az' => 'asan'],
        'difficile' => ['en' => 'difficult', 'es' => 'difícil', 'de' => 'schwierig', 'ja' => '難しい', 'ko' => '어려운', 'tr' => 'zor', 'ru' => 'трудно', 'ar' => 'صعب', 'az' => 'çətin'],
        'assez' => ['en' => 'quite', 'es' => 'bastante', 'de' => 'ziemlich', 'ja' => 'かなり', 'ko' => '꽤', 'tr' => 'oldukça', 'ru' => 'довольно', 'ar' => 'تماما', 'az' => 'kifayət qədər'],
        'trop' => ['en' => 'too much', 'es' => 'demasiado', 'de' => 'zu viel', 'ja' => '多すぎる', 'ko' => '너무', 'tr' => 'çok fazla', 'ru' => 'слишком много', 'ar' => 'كثير جدا', 'az' => 'çox artıq'],
        // --- Unit 8: places in town ---
        'école' => ['en' => 'school', 'es' => 'escuela', 'de' => 'Schule', 'ja' => '学校', 'ko' => '학교', 'tr' => 'okul', 'ru' => 'школа', 'ar' => 'مدرسة', 'az' => 'məktəb'],
        'magasin' => ['en' => 'shop', 'es' => 'tienda', 'de' => 'Geschäft', 'ja' => '店', 'ko' => '가게', 'tr' => 'dükkan', 'ru' => 'магазин', 'ar' => 'متجر', 'az' => 'mağaza'],
        'parc' => ['en' => 'park', 'es' => 'parque', 'de' => 'Park', 'ja' => '公園', 'ko' => '공원', 'tr' => 'park', 'ru' => 'парк', 'ar' => 'حديقة', 'az' => 'park'],
        'rue' => ['en' => 'street', 'es' => 'calle', 'de' => 'Straße', 'ja' => '通り', 'ko' => '거리', 'tr' => 'cadde', 'ru' => 'улица', 'ar' => 'شارع', 'az' => 'küçə'],
        'gare' => ['en' => 'station', 'es' => 'estación', 'de' => 'Bahnhof', 'ja' => '駅', 'ko' => '역', 'tr' => 'istasyon', 'ru' => 'станция', 'ar' => 'محطة', 'az' => 'stansiya'],
        'ville' => ['en' => 'city', 'es' => 'ciudad', 'de' => 'Stadt', 'ja' => '町', 'ko' => '도시', 'tr' => 'şehir', 'ru' => 'город', 'ar' => 'مدينة', 'az' => 'şəhər'],
        'village' => ['en' => 'village', 'es' => 'pueblo', 'de' => 'Dorf', 'ja' => '村', 'ko' => '마을', 'tr' => 'köy', 'ru' => 'деревня', 'ar' => 'قرية', 'az' => 'kənd'],
        'aller' => ['en' => 'to go', 'es' => 'ir', 'de' => 'gehen', 'ja' => '行く', 'ko' => '가다', 'tr' => 'gitmek', 'ru' => 'идти', 'ar' => 'الذهاب', 'az' => 'getmək'],
        'venir' => ['en' => 'to come', 'es' => 'venir', 'de' => 'kommen', 'ja' => '来る', 'ko' => '오다', 'tr' => 'gelmek', 'ru' => 'прийти', 'ar' => 'المجيء', 'az' => 'gəlmək'],
        'loin' => ['en' => 'far', 'es' => 'lejos', 'de' => 'weit', 'ja' => '遠い', 'ko' => '먼', 'tr' => 'uzak', 'ru' => 'далеко', 'ar' => 'بعيد', 'az' => 'uzaq'],
        'près' => ['en' => 'near', 'es' => 'cerca', 'de' => 'nah', 'ja' => '近い', 'ko' => '가까운', 'tr' => 'yakın', 'ru' => 'близко', 'ar' => 'قريب', 'az' => 'yaxın'],
        'gauche' => ['en' => 'left', 'es' => 'izquierda', 'de' => 'links', 'ja' => '左', 'ko' => '왼쪽', 'tr' => 'sol', 'ru' => 'левый', 'ar' => 'يسار', 'az' => 'sol'],
        'droite' => ['en' => 'right', 'es' => 'derecha', 'de' => 'rechts', 'ja' => '右', 'ko' => '오른쪽', 'tr' => 'sağ', 'ru' => 'правый', 'ar' => 'يمين', 'az' => 'sağ'],
        'à' => ['en' => 'to', 'es' => 'a', 'de' => 'zu', 'ja' => 'へ', 'ko' => '에', 'tr' => 'e', 'ru' => 'в', 'ar' => 'إلى', 'az' => 'doğru'],
        'ouvert' => ['en' => 'open', 'es' => 'abierto', 'de' => 'offen', 'ja' => '開いている', 'ko' => '열린', 'tr' => 'açık', 'ru' => 'открыто', 'ar' => 'مفتوح', 'az' => 'açıq'],
        'fermé' => ['en' => 'closed', 'es' => 'cerrado', 'de' => 'geschlossen', 'ja' => '閉まっている', 'ko' => '닫힌', 'tr' => 'kapalı', 'ru' => 'закрыто', 'ar' => 'مغلق', 'az' => 'bağlı'],
        'nuage' => ['en' => 'cloud', 'es' => 'nube', 'de' => 'Wolke', 'ja' => '雲', 'ko' => '구름', 'tr' => 'bulut', 'ru' => 'облако', 'ar' => 'سحابة', 'az' => 'bulud'],
        'ciel' => ['en' => 'sky', 'es' => 'cielo', 'de' => 'Himmel', 'ja' => '空', 'ko' => '하늘', 'tr' => 'gökyüzü', 'ru' => 'небо', 'ar' => 'سماء', 'az' => 'göy'],
        // --- Unit 9: weather and seasons ---
        'pluie' => ['en' => 'rain', 'es' => 'lluvia', 'de' => 'Regen', 'ja' => '雨', 'ko' => '비', 'tr' => 'yağmur', 'ru' => 'дождь', 'ar' => 'مطر', 'az' => 'yağış'],
        'neige' => ['en' => 'snow', 'es' => 'nieve', 'de' => 'Schnee', 'ja' => '雪', 'ko' => '눈', 'tr' => 'kar', 'ru' => 'снег', 'ar' => 'ثلج', 'az' => 'qar'],
        'vent' => ['en' => 'wind', 'es' => 'viento', 'de' => 'Wind', 'ja' => '風', 'ko' => '바람', 'tr' => 'rüzgâr', 'ru' => 'ветер', 'ar' => 'ريح', 'az' => 'külək'],
        'printemps' => ['en' => 'spring', 'es' => 'primavera', 'de' => 'Frühling', 'ja' => '春', 'ko' => '봄', 'tr' => 'ilkbahar', 'ru' => 'весна', 'ar' => 'ربيع', 'az' => 'yaz'],
        'été' => ['en' => 'summer', 'es' => 'verano', 'de' => 'Sommer', 'ja' => '夏', 'ko' => '여름', 'tr' => 'yaz', 'ru' => 'лето', 'ar' => 'صيف', 'az' => 'yay'],
        'automne' => ['en' => 'autumn', 'es' => 'otoño', 'de' => 'Herbst', 'ja' => '秋', 'ko' => '가을', 'tr' => 'sonbahar', 'ru' => 'осень', 'ar' => 'خريف', 'az' => 'payız'],
        'hiver' => ['en' => 'winter', 'es' => 'invierno', 'de' => 'Winter', 'ja' => '冬', 'ko' => '겨울', 'tr' => 'kış', 'ru' => 'зима', 'ar' => 'شتاء', 'az' => 'qış'],
        'saison' => ['en' => 'season', 'es' => 'estación', 'de' => 'Jahreszeit', 'ja' => '季節', 'ko' => '계절', 'tr' => 'mevsim', 'ru' => 'сезон', 'ar' => 'موسم', 'az' => 'mövsüm'],
        'mois' => ['en' => 'month', 'es' => 'mes', 'de' => 'Monat', 'ja' => '月', 'ko' => '달', 'tr' => 'ay', 'ru' => 'месяц', 'ar' => 'شهر', 'az' => 'ay'],
        'année' => ['en' => 'year', 'es' => 'año', 'de' => 'Jahr', 'ja' => '年', 'ko' => '년', 'tr' => 'yıl', 'ru' => 'год', 'ar' => 'سنة', 'az' => 'il'],
        'temps' => ['en' => 'weather', 'es' => 'tiempo', 'de' => 'Wetter', 'ja' => '天気', 'ko' => '날씨', 'tr' => 'hava', 'ru' => 'погода', 'ar' => 'طقس', 'az' => 'hava'],
        'parfois' => ['en' => 'sometimes', 'es' => 'a veces', 'de' => 'manchmal', 'ja' => '時々', 'ko' => '가끔', 'tr' => 'bazen', 'ru' => 'иногда', 'ar' => 'أحيانا', 'az' => 'bəzən'],
        'encore' => ['en' => 'again', 'es' => 'otra vez', 'de' => 'wieder', 'ja' => 'また', 'ko' => '다시', 'tr' => 'tekrar', 'ru' => 'снова', 'ar' => 'مرة أخرى', 'az' => 'yenidən'],
        // --- Unit 10: articles and demonstratives ---
        'une' => ['en' => 'a', 'es' => 'una', 'de' => 'eine', 'ja' => '一つの', 'ko' => '하나의', 'tr' => 'bir', 'ru' => 'один', 'ar' => 'واحد', 'az' => 'bir'],
        'les' => ['en' => 'the', 'es' => 'los', 'de' => 'die', 'ja' => 'その', 'ko' => '그', 'tr' => 'o', 'ru' => 'этот', 'ar' => 'هذا', 'az' => 'həmin'],
        'des' => ['en' => 'some', 'es' => 'unos', 'de' => 'einige', 'ja' => 'いくつかの', 'ko' => '몇몇', 'tr' => 'biraz', 'ru' => 'немного', 'ar' => 'بعض', 'az' => 'bir az'],
        'ce' => ['en' => 'this', 'es' => 'este', 'de' => 'dieser', 'ja' => 'この', 'ko' => '이', 'tr' => 'bu', 'ru' => 'это', 'ar' => 'هذا', 'az' => 'bu'],
        'cette' => ['en' => 'this', 'es' => 'esta', 'de' => 'diese', 'ja' => 'この', 'ko' => '이', 'tr' => 'bu', 'ru' => 'это', 'ar' => 'هذا', 'az' => 'bu'],
        'mes' => ['en' => 'my', 'es' => 'mis', 'de' => 'meine', 'ja' => '私の', 'ko' => '나의', 'tr' => 'benim', 'ru' => 'мой', 'ar' => 'خاصتي', 'az' => 'mənim'],
        'ces' => ['en' => 'these', 'es' => 'estos', 'de' => 'diese', 'ja' => 'これらの', 'ko' => '이', 'tr' => 'bunlar', 'ru' => 'эти', 'ar' => 'هذه', 'az' => 'bunlar'],
        'livres' => ['en' => 'books', 'es' => 'libros', 'de' => 'Bücher', 'ja' => '本', 'ko' => '책들', 'tr' => 'kitaplar', 'ru' => 'книги', 'ar' => 'كتب', 'az' => 'kitablar'],
        'stylos' => ['en' => 'pens', 'es' => 'bolígrafos', 'de' => 'Kugelschreiber', 'ja' => 'ペン', 'ko' => '펜들', 'tr' => 'kalemler', 'ru' => 'ручки', 'ar' => 'أقلام', 'az' => 'qələmlər'],
        // --- Chapter 2, Unit 1: introducing yourself ---
        'nom' => ['en' => 'name', 'es' => 'nombre', 'de' => 'Name', 'ja' => '名前', 'ko' => '이름', 'tr' => 'ad', 'ru' => 'имя', 'ar' => 'اسم', 'az' => 'ad'],
        'âge' => ['en' => 'age', 'es' => 'edad', 'de' => 'Alter', 'ja' => '年齢', 'ko' => '나이', 'tr' => 'yaş', 'ru' => 'возраст', 'ar' => 'عمر', 'az' => 'yaş'],
        'ans' => ['en' => 'years old', 'es' => 'años', 'de' => 'Jahre alt', 'ja' => '歳', 'ko' => '살', 'tr' => 'yaşında', 'ru' => 'лет старый', 'ar' => 'سنوات قديم', 'az' => 'yaşında köhnə'],
        'je suis' => ['en' => 'I am', 'es' => 'soy', 'de' => 'ich bin', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'ben', 'ru' => 'я', 'ar' => 'أنا', 'az' => 'mən'],
        'tu es' => ['en' => 'you are', 'es' => 'eres', 'de' => 'du bist', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'sensin', 'ru' => 'ты', 'ar' => 'أنت', 'az' => 'sən'],
        'ton' => ['en' => 'your', 'es' => 'tu', 'de' => 'dein', 'ja' => 'あなたの', 'ko' => '당신의', 'tr' => 'senin', 'ru' => 'твой', 'ar' => 'خاصتك', 'az' => 'sənin'],
        "j'habite" => ['en' => 'I live', 'es' => 'vivo', 'de' => 'ich wohne', 'ja' => '私は住んでいる', 'ko' => '나는 삽니다', 'tr' => 'yaşıyorum', 'ru' => 'я живу', 'ar' => 'أسكن', 'az' => 'yaşayıram'],
        'enchanté' => ['en' => 'nice to meet you', 'es' => 'encantado', 'de' => 'freut mich', 'ja' => 'はじめまして', 'ko' => '반갑습니다', 'tr' => 'memnun oldum', 'ru' => 'приятно познакомиться', 'ar' => 'تشرفنا', 'az' => 'tanış olmağa şadam'],
        'bienvenue' => ['en' => 'welcome', 'es' => 'bienvenido', 'de' => 'willkommen', 'ja' => 'ようこそ', 'ko' => '환영합니다', 'tr' => 'hoş geldin', 'ru' => 'добро пожаловать', 'ar' => 'أهلا وسهلا', 'az' => 'xoş gəlmisiniz'],
        // --- Chapter 2, Unit 2: asking questions ---
        'comment' => ['en' => 'how', 'es' => 'cómo', 'de' => 'wie', 'ja' => 'どう', 'ko' => '어떻게', 'tr' => 'nasıl', 'ru' => 'как', 'ar' => 'كيف', 'az' => 'necə'],
        'ça va' => ['en' => 'how is it going', 'es' => 'qué tal', 'de' => 'wie geht es', 'ja' => '元気ですか', 'ko' => '잘 지내요', 'tr' => 'nasıl gidiyor', 'ru' => 'как дела', 'ar' => 'كيف الحال', 'az' => 'necə gedir'],
        'quel' => ['en' => 'which', 'es' => 'cuál', 'de' => 'welcher', 'ja' => 'どの', 'ko' => '어떤', 'tr' => 'hangi', 'ru' => 'какой', 'ar' => 'أي', 'az' => 'hansı'],
        'combien' => ['en' => 'how many', 'es' => 'cuántos', 'de' => 'wie viele', 'ja' => 'いくつ', 'ko' => '얼마나', 'tr' => 'kaç', 'ru' => 'сколько', 'ar' => 'كم', 'az' => 'neçə'],
        'de' => ['en' => 'of', 'es' => 'de', 'de' => 'von', 'ja' => 'の', 'ko' => '의', 'tr' => 'in', 'ru' => 'из', 'ar' => 'من', 'az' => 'ın'],
        'pourquoi' => ['en' => 'why', 'es' => 'por qué', 'de' => 'warum', 'ja' => 'なぜ', 'ko' => '왜', 'tr' => 'neden', 'ru' => 'почему', 'ar' => 'لماذا', 'az' => 'niyə'],
        'quand' => ['en' => 'when', 'es' => 'cuándo', 'de' => 'wann', 'ja' => 'いつ', 'ko' => '언제', 'tr' => 'ne zaman', 'ru' => 'когда', 'ar' => 'متى', 'az' => 'nə vaxt'],
        'peut-être' => ['en' => 'maybe', 'es' => 'quizás', 'de' => 'vielleicht', 'ja' => 'たぶん', 'ko' => '아마도', 'tr' => 'belki', 'ru' => 'может быть', 'ar' => 'ربما', 'az' => 'bəlkə'],
        'bien sûr' => ['en' => 'of course', 'es' => 'por supuesto', 'de' => 'natürlich', 'ja' => 'もちろん', 'ko' => '물론', 'tr' => 'elbette', 'ru' => 'конечно', 'ar' => 'بالطبع', 'az' => 'əlbəttə'],
        // --- Chapter 2, Unit 3: making plans ---
        'allons' => ['en' => "let's go", 'es' => 'vamos', 'de' => 'lass uns gehen', 'ja' => '行きましょう', 'ko' => '갑시다', 'tr' => 'gidelim', 'ru' => 'пойдём', 'ar' => 'هيا بنا', 'az' => 'gedək'],
        'ensemble' => ['en' => 'together', 'es' => 'juntos', 'de' => 'zusammen', 'ja' => '一緒に', 'ko' => '함께', 'tr' => 'birlikte', 'ru' => 'вместе', 'ar' => 'معا', 'az' => 'birlikdə'],
        'bientôt' => ['en' => 'soon', 'es' => 'pronto', 'de' => 'bald', 'ja' => 'すぐに', 'ko' => '곧', 'tr' => 'yakında', 'ru' => 'скоро', 'ar' => 'قريبا', 'az' => 'tezliklə'],
        'ce soir' => ['en' => 'this evening', 'es' => 'esta tarde', 'de' => 'heute Abend', 'ja' => '今晩', 'ko' => '오늘 저녁', 'tr' => 'bu akşam', 'ru' => 'это вечер', 'ar' => 'هذا مساء', 'az' => 'bu axşam'],
        "d'accord" => ['en' => 'okay', 'es' => 'de acuerdo', 'de' => 'einverstanden', 'ja' => 'わかりました', 'ko' => '알겠습니다', 'tr' => 'tamam', 'ru' => 'хорошо', 'ar' => 'حسنا', 'az' => 'yaxşı'],
        'ensuite' => ['en' => 'then', 'es' => 'luego', 'de' => 'dann', 'ja' => 'それから', 'ko' => '그다음에', 'tr' => 'sonra', 'ru' => 'потом', 'ar' => 'ثم', 'az' => 'sonra'],
        'plus tard' => ['en' => 'later', 'es' => 'más tarde', 'de' => 'später', 'ja' => '後で', 'ko' => '나중에', 'tr' => 'sonra', 'ru' => 'позже', 'ar' => 'لاحقا', 'az' => 'sonradan'],
        'vraiment' => ['en' => 'really', 'es' => 'realmente', 'de' => 'wirklich', 'ja' => '本当に', 'ko' => '정말', 'tr' => 'gerçekten', 'ru' => 'действительно', 'ar' => 'حقا', 'az' => 'həqiqətən'],
        'film' => ['en' => 'film', 'es' => 'película', 'de' => 'Film', 'ja' => '映画', 'ko' => '영화', 'tr' => 'film', 'ru' => 'фильм', 'ar' => 'فيلم', 'az' => 'film'],
        'regarder' => ['en' => 'to watch', 'es' => 'mirar', 'de' => 'schauen', 'ja' => '見る', 'ko' => '보다', 'tr' => 'izlemek', 'ru' => 'смотреть', 'ar' => 'المشاهدة', 'az' => 'izləmək'],
        // --- Chapter 2, Unit 4: feelings ---
        'content' => ['en' => 'happy', 'es' => 'contento', 'de' => 'zufrieden', 'ja' => '満足した', 'ko' => '만족한', 'tr' => 'mutlu', 'ru' => 'счастливый', 'ar' => 'فرح', 'az' => 'xoşbəxt'],
        'triste' => ['en' => 'sad', 'es' => 'triste', 'de' => 'traurig', 'ja' => '悲しい', 'ko' => '슬픈', 'tr' => 'üzgün', 'ru' => 'грустный', 'ar' => 'حزين', 'az' => 'kədərli'],
        'fatigué' => ['en' => 'tired', 'es' => 'cansado', 'de' => 'müde', 'ja' => '疲れた', 'ko' => '피곤한', 'tr' => 'yorgun', 'ru' => 'усталый', 'ar' => 'متعب', 'az' => 'yorğun'],
        'malade' => ['en' => 'sick', 'es' => 'enfermo', 'de' => 'krank', 'ja' => '病気の', 'ko' => '아픈', 'tr' => 'hasta', 'ru' => 'больной', 'ar' => 'مريض', 'az' => 'xəstə'],
        'heureux' => ['en' => 'glad', 'es' => 'feliz', 'de' => 'glücklich', 'ja' => '嬉しい', 'ko' => '기쁜', 'tr' => 'memnun', 'ru' => 'рада', 'ar' => 'سعيد', 'az' => 'şad'],
        'calme' => ['en' => 'calm', 'es' => 'tranquilo', 'de' => 'ruhig', 'ja' => '落ち着いた', 'ko' => '차분한', 'tr' => 'sakin', 'ru' => 'спокойный', 'ar' => 'هادئ', 'az' => 'sakit'],
        'un peu' => ['en' => 'a little', 'es' => 'un poco', 'de' => 'ein wenig', 'ja' => '少し', 'ko' => '조금', 'tr' => 'biraz', 'ru' => 'немного', 'ar' => 'قليل', 'az' => 'az'],
        'parce que' => ['en' => 'because', 'es' => 'porque', 'de' => 'weil', 'ja' => 'なぜなら', 'ko' => '왜냐하면', 'tr' => 'çünkü', 'ru' => 'потому что', 'ar' => 'لأن', 'az' => 'çünki'],
        // --- Chapter 2, Unit 5: talking about the past ---
        // Past forms are taught whole ("j'ai mangé"), not as a conjugation
        // rule — a beginner needs to say it before they can analyse it.
        'hier' => ['en' => 'yesterday', 'es' => 'ayer', 'de' => 'gestern', 'ja' => '昨日', 'ko' => '어제', 'tr' => 'dün', 'ru' => 'вчера', 'ar' => 'أمس', 'az' => 'dünən'],
        "j'ai mangé" => ['en' => 'I ate', 'es' => 'comí', 'de' => 'ich habe gegessen', 'ja' => '私は食べた', 'ko' => '나는 먹었다', 'tr' => 'yedim', 'ru' => 'я ел', 'ar' => 'أكلت', 'az' => 'yedim'],
        "j'ai bu" => ['en' => 'I drank', 'es' => 'bebí', 'de' => 'ich habe getrunken', 'ja' => '私は飲んだ', 'ko' => '나는 마셨다', 'tr' => 'içtim', 'ru' => 'я пил', 'ar' => 'شربت', 'az' => 'içdim'],
        "j'ai vu" => ['en' => 'I saw', 'es' => 'vi', 'de' => 'ich habe gesehen', 'ja' => '私は見た', 'ko' => '나는 보았다', 'tr' => 'gördüm', 'ru' => 'я видел', 'ar' => 'رأيت', 'az' => 'gördüm'],
        "c'était" => ['en' => 'it was', 'es' => 'era', 'de' => 'es war', 'ja' => 'でした', 'ko' => '였습니다', 'tr' => 'idi', 'ru' => 'было', 'ar' => 'كان', 'az' => 'idi'],
        "j'étais" => ['en' => 'I was', 'es' => 'estaba', 'de' => 'ich war', 'ja' => 'でした', 'ko' => '였습니다', 'tr' => 'idim', 'ru' => 'я был', 'ar' => 'كنت', 'az' => 'idim'],
        'déjà' => ['en' => 'already', 'es' => 'ya', 'de' => 'schon', 'ja' => 'すでに', 'ko' => '이미', 'tr' => 'zaten', 'ru' => 'уже', 'ar' => 'بالفعل', 'az' => 'artıq'],
        'puis' => ['en' => 'then', 'es' => 'después', 'de' => 'danach', 'ja' => 'それから', 'ko' => '그러고 나서', 'tr' => 'sonra', 'ru' => 'потом', 'ar' => 'ثم', 'az' => 'sonra'],
        // --- Chapter 2, Unit 6: future plans ---
        'je vais' => ['en' => 'I am going', 'es' => 'voy', 'de' => 'ich gehe', 'ja' => '私は行く', 'ko' => '나는 간다', 'tr' => 'gidiyorum', 'ru' => 'я иду', 'ar' => 'أذهب', 'az' => 'gedirəm'],
        'prochain' => ['en' => 'next', 'es' => 'próximo', 'de' => 'nächste', 'ja' => '次の', 'ko' => '다음', 'tr' => 'sonraki', 'ru' => 'следующий', 'ar' => 'التالي', 'az' => 'növbəti'],
        'après' => ['en' => 'after', 'es' => 'después de', 'de' => 'nach', 'ja' => '後', 'ko' => '후에', 'tr' => 'sonra', 'ru' => 'после', 'ar' => 'بعد', 'az' => 'sonra'],
        'avant' => ['en' => 'before', 'es' => 'antes de', 'de' => 'vor', 'ja' => '前', 'ko' => '전에', 'tr' => 'önce', 'ru' => 'до', 'ar' => 'قبل', 'az' => 'əvvəl'],
        'vouloir' => ['en' => 'to want', 'es' => 'querer', 'de' => 'wollen', 'ja' => '欲しい', 'ko' => '원하다', 'tr' => 'istemek', 'ru' => 'хотеть', 'ar' => 'الرغبة', 'az' => 'istəmək'],
        'pouvoir' => ['en' => 'to be able', 'es' => 'poder', 'de' => 'können', 'ja' => 'できる', 'ko' => '할 수 있다', 'tr' => 'yapabilmek', 'ru' => 'мочь', 'ar' => 'القدرة', 'az' => 'bacarmaq'],
        'prêt' => ['en' => 'ready', 'es' => 'listo', 'de' => 'bereit', 'ja' => '準備ができた', 'ko' => '준비된', 'tr' => 'hazır', 'ru' => 'готов', 'ar' => 'جاهز', 'az' => 'hazır'],
        'libre' => ['en' => 'free', 'es' => 'libre', 'de' => 'frei', 'ja' => '自由な', 'ko' => '자유로운', 'tr' => 'boş', 'ru' => 'бесплатно', 'ar' => 'مجاني', 'az' => 'pulsuz'],
        // --- Chapter 2, Unit 7: giving directions ---
        'tout droit' => ['en' => 'straight ahead', 'es' => 'todo recto', 'de' => 'geradeaus', 'ja' => 'まっすぐ', 'ko' => '직진', 'tr' => 'düz ileri', 'ru' => 'прямо', 'ar' => 'مباشرة', 'az' => 'düz irəli'],
        'tourner' => ['en' => 'to turn', 'es' => 'girar', 'de' => 'abbiegen', 'ja' => '曲がる', 'ko' => '돌다', 'tr' => 'dönmek', 'ru' => 'в поворот', 'ar' => 'إلى منعطف', 'az' => 'dönüş'],
        'traverser' => ['en' => 'to cross', 'es' => 'cruzar', 'de' => 'überqueren', 'ja' => '渡る', 'ko' => '건너다', 'tr' => 'geçmek', 'ru' => 'перейти', 'ar' => 'العبور', 'az' => 'keçmək'],
        'continuer' => ['en' => 'to continue', 'es' => 'continuar', 'de' => 'weitergehen', 'ja' => '続ける', 'ko' => '계속하다', 'tr' => 'devam etmek', 'ru' => 'продолжить', 'ar' => 'المتابعة', 'az' => 'davam etmək'],
        'devant' => ['en' => 'in front of', 'es' => 'delante de', 'de' => 'vor', 'ja' => '前に', 'ko' => '앞에', 'tr' => 'önünde', 'ru' => 'перед', 'ar' => 'أمام', 'az' => 'qarşısında'],
        'derrière' => ['en' => 'behind', 'es' => 'detrás de', 'de' => 'hinter', 'ja' => '後ろに', 'ko' => '뒤에', 'tr' => 'arkasında', 'ru' => 'сзади', 'ar' => 'خلف', 'az' => 'arxada'],
        'nord' => ['en' => 'north', 'es' => 'norte', 'de' => 'Norden', 'ja' => '北', 'ko' => '북쪽', 'tr' => 'kuzey', 'ru' => 'север', 'ar' => 'شمال', 'az' => 'şimal'],
        'sud' => ['en' => 'south', 'es' => 'sur', 'de' => 'Süden', 'ja' => '南', 'ko' => '남쪽', 'tr' => 'güney', 'ru' => 'юг', 'ar' => 'جنوب', 'az' => 'cənub'],
        // --- Chapter 2, Unit 8: phone conversations ---
        'allô' => ['en' => 'hello', 'es' => 'aló', 'de' => 'hallo', 'ja' => 'もしもし', 'ko' => '여보세요', 'tr' => 'merhaba', 'ru' => 'привет', 'ar' => 'مرحبا', 'az' => 'salam'],
        'téléphone' => ['en' => 'telephone', 'es' => 'teléfono', 'de' => 'Telefon', 'ja' => '電話', 'ko' => '전화', 'tr' => 'telefon', 'ru' => 'телефон', 'ar' => 'هاتف', 'az' => 'telefon'],
        'appeler' => ['en' => 'to call', 'es' => 'llamar', 'de' => 'anrufen', 'ja' => '電話する', 'ko' => '전화하다', 'tr' => 'aramak', 'ru' => 'звонить', 'ar' => 'الاتصال', 'az' => 'zəng etmək'],
        'attendre' => ['en' => 'to wait', 'es' => 'esperar', 'de' => 'warten', 'ja' => '待つ', 'ko' => '기다리다', 'tr' => 'beklemek', 'ru' => 'ждать', 'ar' => 'الانتظار', 'az' => 'gözləmək'],
        'message' => ['en' => 'message', 'es' => 'mensaje', 'de' => 'Nachricht', 'ja' => 'メッセージ', 'ko' => '메시지', 'tr' => 'mesaj', 'ru' => 'сообщение', 'ar' => 'رسالة', 'az' => 'mesaj'],
        'rappeler' => ['en' => 'to call back', 'es' => 'volver a llamar', 'de' => 'zurückrufen', 'ja' => '折り返す', 'ko' => '다시 전화하다', 'tr' => 'tekrar aramak', 'ru' => 'перезвонить', 'ar' => 'معاودة الاتصال', 'az' => 'geri zəng etmək'],
        'occupé' => ['en' => 'busy', 'es' => 'ocupado', 'de' => 'beschäftigt', 'ja' => '忙しい', 'ko' => '바쁜', 'tr' => 'meşgul', 'ru' => 'занят', 'ar' => 'مشغول', 'az' => 'məşğul'],
        'désolé' => ['en' => 'sorry', 'es' => 'lo siento', 'de' => 'entschuldigung', 'ja' => 'ごめんなさい', 'ko' => '미안합니다', 'tr' => 'üzgünüm', 'ru' => 'извините', 'ar' => 'آسف', 'az' => 'bağışlayın'],
        // --- Chapter 2, Unit 9: expressing opinions ---
        'je pense' => ['en' => 'I think', 'es' => 'pienso', 'de' => 'ich denke', 'ja' => '私は思う', 'ko' => '나는 생각한다', 'tr' => 'düşünüyorum', 'ru' => 'я думаю', 'ar' => 'أفكر', 'az' => 'düşünürəm'],
        'je crois' => ['en' => 'I believe', 'es' => 'creo', 'de' => 'ich glaube', 'ja' => '私は信じる', 'ko' => '나는 믿는다', 'tr' => 'bence', 'ru' => 'я думаю', 'ar' => 'أعتقد', 'az' => 'inanıram'],
        'que' => ['en' => 'that', 'es' => 'que', 'de' => 'dass', 'ja' => 'ということ', 'ko' => '라고', 'tr' => 'o', 'ru' => 'тот', 'ar' => 'ذلك', 'az' => 'o'],
        'intéressant' => ['en' => 'interesting', 'es' => 'interesante', 'de' => 'interessant', 'ja' => '面白い', 'ko' => '흥미로운', 'tr' => 'ilginç', 'ru' => 'интересно', 'ar' => 'مثير للاهتمام', 'az' => 'maraqlı'],
        'important' => ['en' => 'important', 'es' => 'importante', 'de' => 'wichtig', 'ja' => '重要な', 'ko' => '중요한', 'tr' => 'önemli', 'ru' => 'важно', 'ar' => 'مهم', 'az' => 'vacib'],
        'vrai' => ['en' => 'true', 'es' => 'verdadero', 'de' => 'wahr', 'ja' => '本当の', 'ko' => '진실한', 'tr' => 'doğru', 'ru' => 'правильно', 'ar' => 'صحيح', 'az' => 'düzgün'],
        'faux' => ['en' => 'false', 'es' => 'falso', 'de' => 'falsch', 'ja' => '偽の', 'ko' => '거짓의', 'tr' => 'yanlış', 'ru' => 'неверно', 'ar' => 'خطأ', 'az' => 'səhv'],
        'préférer' => ['en' => 'to prefer', 'es' => 'preferir', 'de' => 'bevorzugen', 'ja' => '好む', 'ko' => '선호하다', 'tr' => 'tercih etmek', 'ru' => 'в предпочитаю', 'ar' => 'إلى أفضل', 'az' => 'üstünlük verirəm'],
        'meilleur' => ['en' => 'better', 'es' => 'mejor', 'de' => 'besser', 'ja' => 'より良い', 'ko' => '더 좋은', 'tr' => 'daha iyi', 'ru' => 'лучше', 'ar' => 'أحسن', 'az' => 'daha yaxşı'],
        // --- Chapter 2, Unit 10: comparisons and preferences ---
        'plus' => ['en' => 'more', 'es' => 'más', 'de' => 'mehr', 'ja' => 'もっと', 'ko' => '더', 'tr' => 'daha çok', 'ru' => 'больше', 'ar' => 'أكثر', 'az' => 'daha'],
        'moins' => ['en' => 'less', 'es' => 'menos', 'de' => 'weniger', 'ja' => 'より少ない', 'ko' => '덜', 'tr' => 'daha az', 'ru' => 'меньше', 'ar' => 'أقل', 'az' => 'daha az'],
        'comme' => ['en' => 'like', 'es' => 'como', 'de' => 'wie', 'ja' => 'のように', 'ko' => '처럼', 'tr' => 'gibi', 'ru' => 'нравится', 'ar' => 'يعجبني', 'az' => 'xoşuma gəlir'],
        'même' => ['en' => 'same', 'es' => 'mismo', 'de' => 'gleich', 'ja' => '同じ', 'ko' => '같은', 'tr' => 'aynı', 'ru' => 'такой же', 'ar' => 'نفسه', 'az' => 'eyni'],
        'mieux' => ['en' => 'better', 'es' => 'mejor', 'de' => 'besser', 'ja' => 'もっと良い', 'ko' => '더 잘', 'tr' => 'daha iyi', 'ru' => 'лучше', 'ar' => 'أحسن', 'az' => 'daha yaxşı'],
        'pire' => ['en' => 'worse', 'es' => 'peor', 'de' => 'schlechter', 'ja' => 'より悪い', 'ko' => '더 나쁜', 'tr' => 'daha kötü', 'ru' => 'хуже', 'ar' => 'أسوأ', 'az' => 'daha pis'],
        'autant' => ['en' => 'as much', 'es' => 'tanto', 'de' => 'genauso viel', 'ja' => '同じくらい', 'ko' => '그만큼', 'tr' => 'bu kadar', 'ru' => 'столько же', 'ar' => 'بقدر', 'az' => 'qədər'],
        'surtout' => ['en' => 'especially', 'es' => 'sobre todo', 'de' => 'besonders', 'ja' => '特に', 'ko' => '특히', 'tr' => 'özellikle', 'ru' => 'особенно', 'ar' => 'خاصة', 'az' => 'xüsusilə'],
        'chats' => ['en' => 'cats', 'es' => 'gatos', 'de' => 'Katzen', 'ja' => '猫', 'ko' => '고양이들', 'tr' => 'kediler', 'ru' => 'коты', 'ar' => 'قطط', 'az' => 'pişiklər'],
        'chiens' => ['en' => 'dogs', 'es' => 'perros', 'de' => 'Hunde', 'ja' => '犬', 'ko' => '개들', 'tr' => 'köpekler', 'ru' => 'собаки', 'ar' => 'كلاب', 'az' => 'itlər'],
        'au' => ['en' => 'to the', 'es' => 'al', 'de' => 'zum', 'ja' => 'に', 'ko' => '에', 'tr' => 'e', 'ru' => 'в', 'ar' => 'إلى', 'az' => 'doğru'],
        'aux' => ['en' => 'to the', 'es' => 'a los', 'de' => 'zu den', 'ja' => 'に', 'ko' => '에', 'tr' => 'e', 'ru' => 'в', 'ar' => 'إلى', 'az' => 'doğru'],
        'glaçons' => ['en' => 'ice cubes', 'es' => 'hielo', 'de' => 'Eiswürfel', 'ja' => '氷', 'ko' => '얼음', 'tr' => 'buz', 'ru' => 'кубики льда', 'ar' => 'مكعبات ثلج', 'az' => 'buz parçaları'],
        'enfants' => ['en' => 'children', 'es' => 'niños', 'de' => 'Kinder', 'ja' => '子供たち', 'ko' => '아이들', 'tr' => 'çocuklar', 'ru' => 'дети', 'ar' => 'أطفال', 'az' => 'uşaqlar'],
        // --- Chapter 3: restaurant — food ---
        'soupe' => ['en' => 'soup', 'es' => 'sopa', 'de' => 'Suppe', 'ja' => 'スープ', 'ko' => '수프', 'tr' => 'çorba', 'ru' => 'суп', 'ar' => 'حساء', 'az' => 'şorba'],
        'salade' => ['en' => 'salad', 'es' => 'ensalada', 'de' => 'Salat', 'ja' => 'サラダ', 'ko' => '샐러드', 'tr' => 'salata', 'ru' => 'салат', 'ar' => 'سلطة', 'az' => 'salat'],
        'poulet' => ['en' => 'chicken', 'es' => 'pollo', 'de' => 'Hähnchen', 'ja' => '鶏肉', 'ko' => '닭고기', 'tr' => 'tavuk', 'ru' => 'курица', 'ar' => 'دجاج', 'az' => 'toyuq'],
        'poisson' => ['en' => 'fish', 'es' => 'pescado', 'de' => 'Fisch', 'ja' => '魚', 'ko' => '생선', 'tr' => 'balık', 'ru' => 'рыба', 'ar' => 'سمك', 'az' => 'balıq'],
        'viande' => ['en' => 'meat', 'es' => 'carne', 'de' => 'Fleisch', 'ja' => '肉', 'ko' => '고기', 'tr' => 'et', 'ru' => 'мясо', 'ar' => 'لحم', 'az' => 'ət'],
        'riz' => ['en' => 'rice', 'es' => 'arroz', 'de' => 'Reis', 'ja' => 'ご飯', 'ko' => '밥', 'tr' => 'pirinç', 'ru' => 'рис', 'ar' => 'أرز', 'az' => 'düyü'],
        'fromage' => ['en' => 'cheese', 'es' => 'queso', 'de' => 'Käse', 'ja' => 'チーズ', 'ko' => '치즈', 'tr' => 'peynir', 'ru' => 'сыр', 'ar' => 'جبن', 'az' => 'pendir'],
        'pomme' => ['en' => 'apple', 'es' => 'manzana', 'de' => 'Apfel', 'ja' => 'りんご', 'ko' => '사과', 'tr' => 'elma', 'ru' => 'яблоко', 'ar' => 'تفاحة', 'az' => 'alma'],
        'gâteau' => ['en' => 'cake', 'es' => 'pastel', 'de' => 'Kuchen', 'ja' => 'ケーキ', 'ko' => '케이크', 'tr' => 'pasta', 'ru' => 'торт', 'ar' => 'كعكة', 'az' => 'tort'],
        'glace' => ['en' => 'ice cream', 'es' => 'helado', 'de' => 'Eis', 'ja' => 'アイスクリーム', 'ko' => '아이스크림', 'tr' => 'dondurma', 'ru' => 'мороженое', 'ar' => 'آيس كريم', 'az' => 'dondurma'],
        'sandwich' => ['en' => 'sandwich', 'es' => 'sándwich', 'de' => 'Sandwich', 'ja' => 'サンドイッチ', 'ko' => '샌드위치', 'tr' => 'sandviç', 'ru' => 'сэндвич', 'ar' => 'شطيرة', 'az' => 'sendviç'],
        'frites' => ['en' => 'fries', 'es' => 'patatas fritas', 'de' => 'Pommes', 'ja' => 'フライドポテト', 'ko' => '감자튀김', 'tr' => 'patates kızartması', 'ru' => 'картошка фри', 'ar' => 'بطاطا مقلية', 'az' => 'kartof fri'],
        'hamburger' => ['en' => 'burger', 'es' => 'hamburguesa', 'de' => 'Burger', 'ja' => 'ハンバーガー', 'ko' => '햄버거', 'tr' => 'hamburger', 'ru' => 'бургер', 'ar' => 'برجر', 'az' => 'burger'],
        'jus' => ['en' => 'juice', 'es' => 'zumo', 'de' => 'Saft', 'ja' => 'ジュース', 'ko' => '주스', 'tr' => 'meyve suyu', 'ru' => 'сок', 'ar' => 'عصير', 'az' => 'şirə'],
        'vin' => ['en' => 'wine', 'es' => 'vino', 'de' => 'Wein', 'ja' => 'ワイン', 'ko' => '와인', 'tr' => 'şarap', 'ru' => 'вино', 'ar' => 'نبيذ', 'az' => 'şərab'],
        'bière' => ['en' => 'beer', 'es' => 'cerveza', 'de' => 'Bier', 'ja' => 'ビール', 'ko' => '맥주', 'tr' => 'bira', 'ru' => 'пиво', 'ar' => 'بيرة', 'az' => 'pivə'],
        'chocolat' => ['en' => 'chocolate', 'es' => 'chocolate', 'de' => 'Schokolade', 'ja' => 'チョコレート', 'ko' => '초콜릿', 'tr' => 'çikolata', 'ru' => 'шоколад', 'ar' => 'شوكولاتة', 'az' => 'şokolad'],
        'tarte' => ['en' => 'tart', 'es' => 'tarta', 'de' => 'Torte', 'ja' => 'タルト', 'ko' => '타르트', 'tr' => 'turta', 'ru' => 'тарт', 'ar' => 'فطيرة', 'az' => 'tart'],
        'crème' => ['en' => 'cream', 'es' => 'nata', 'de' => 'Sahne', 'ja' => 'クリーム', 'ko' => '크림', 'tr' => 'krema', 'ru' => 'сливки', 'ar' => 'كريمة', 'az' => 'qaymaq'],
        'vanille' => ['en' => 'vanilla', 'es' => 'vainilla', 'de' => 'Vanille', 'ja' => 'バニラ', 'ko' => '바닐라', 'tr' => 'vanilya', 'ru' => 'ванильный', 'ar' => 'فانيليا', 'az' => 'vanil'],
        'fraise' => ['en' => 'strawberry', 'es' => 'fresa', 'de' => 'Erdbeere', 'ja' => 'いちご', 'ko' => '딸기', 'tr' => 'çilek', 'ru' => 'клубничный', 'ar' => 'فراولة', 'az' => 'çiyələk'],
        'légumes' => ['en' => 'vegetables', 'es' => 'verduras', 'de' => 'Gemüse', 'ja' => '野菜', 'ko' => '채소', 'tr' => 'sebze', 'ru' => 'овощи', 'ar' => 'خضروات', 'az' => 'tərəvəzlər'],
        'fruit' => ['en' => 'fruit', 'es' => 'fruta', 'de' => 'Obst', 'ja' => '果物', 'ko' => '과일', 'tr' => 'meyve', 'ru' => 'фрукт', 'ar' => 'فاكهة', 'az' => 'meyvə'],
        'œuf' => ['en' => 'egg', 'es' => 'huevo', 'de' => 'Ei', 'ja' => '卵', 'ko' => '계란', 'tr' => 'yumurta', 'ru' => 'яйцо', 'ar' => 'بيضة', 'az' => 'yumurta'],
        'sel' => ['en' => 'salt', 'es' => 'sal', 'de' => 'Salz', 'ja' => '塩', 'ko' => '소금', 'tr' => 'tuz', 'ru' => 'соль', 'ar' => 'ملح', 'az' => 'duz'],
        'poivre' => ['en' => 'pepper', 'es' => 'pimienta', 'de' => 'Pfeffer', 'ja' => 'こしょう', 'ko' => '후추', 'tr' => 'biber', 'ru' => 'перец', 'ar' => 'فلفل', 'az' => 'bibər'],
        'beurre' => ['en' => 'butter', 'es' => 'mantequilla', 'de' => 'Butter', 'ja' => 'バター', 'ko' => '버터', 'tr' => 'tereyağı', 'ru' => 'масло', 'ar' => 'زبدة', 'az' => 'kərə yağı'],
        // --- Chapter 3: restaurant — table and tableware ---
        'assiette' => ['en' => 'plate', 'es' => 'plato', 'de' => 'Teller', 'ja' => 'お皿', 'ko' => '접시', 'tr' => 'tabak', 'ru' => 'тарелка', 'ar' => 'صحن', 'az' => 'boşqab'],
        'fourchette' => ['en' => 'fork', 'es' => 'tenedor', 'de' => 'Gabel', 'ja' => 'フォーク', 'ko' => '포크', 'tr' => 'çatal', 'ru' => 'вилка', 'ar' => 'شوكة', 'az' => 'çəngəl'],
        'couteau' => ['en' => 'knife', 'es' => 'cuchillo', 'de' => 'Messer', 'ja' => 'ナイフ', 'ko' => '나이프', 'tr' => 'bıçak', 'ru' => 'нож', 'ar' => 'سكين', 'az' => 'bıçaq'],
        'cuillère' => ['en' => 'spoon', 'es' => 'cuchara', 'de' => 'Löffel', 'ja' => 'スプーン', 'ko' => '숟가락', 'tr' => 'kaşık', 'ru' => 'ложка', 'ar' => 'ملعقة', 'az' => 'qaşıq'],
        'verre' => ['en' => 'glass', 'es' => 'vaso', 'de' => 'Glas', 'ja' => 'グラス', 'ko' => '유리잔', 'tr' => 'bardak', 'ru' => 'стакан', 'ar' => 'كوب', 'az' => 'stəkan'],
        'bouteille' => ['en' => 'bottle', 'es' => 'botella', 'de' => 'Flasche', 'ja' => 'ボトル', 'ko' => '병', 'tr' => 'şişe', 'ru' => 'бутылка', 'ar' => 'زجاجة', 'az' => 'şüşə'],
        'serviette' => ['en' => 'napkin', 'es' => 'servilleta', 'de' => 'Serviette', 'ja' => 'ナプキン', 'ko' => '냅킨', 'tr' => 'peçete', 'ru' => 'салфетка', 'ar' => 'منديل', 'az' => 'salfet'],
        'nappe' => ['en' => 'tablecloth', 'es' => 'mantel', 'de' => 'Tischdecke', 'ja' => 'テーブルクロス', 'ko' => '식탁보', 'tr' => 'masa örtüsü', 'ru' => 'скатерть', 'ar' => 'مفرش', 'az' => 'süfrə'],
        'menu' => ['en' => 'menu', 'es' => 'menú', 'de' => 'Menü', 'ja' => 'メニュー', 'ko' => '메뉴', 'tr' => 'menü', 'ru' => 'меню', 'ar' => 'قائمة الطعام', 'az' => 'menyu'],
        'carte' => ['en' => 'menu card', 'es' => 'carta', 'de' => 'Speisekarte', 'ja' => 'メニュー表', 'ko' => '메뉴판', 'tr' => 'menü', 'ru' => 'меню карта', 'ar' => 'قائمة الطعام بطاقة', 'az' => 'menyu kart'],
        'serveur' => ['en' => 'waiter', 'es' => 'camarero', 'de' => 'Kellner', 'ja' => 'ウェイター', 'ko' => '웨이터', 'tr' => 'garson', 'ru' => 'официант', 'ar' => 'نادل', 'az' => 'ofisiant'],
        'cuisine' => ['en' => 'kitchen', 'es' => 'cocina', 'de' => 'Küche', 'ja' => '厨房', 'ko' => '주방', 'tr' => 'mutfak', 'ru' => 'кухня', 'ar' => 'مطبخ', 'az' => 'mətbəx'],
        'restaurant' => ['en' => 'restaurant', 'es' => 'restaurante', 'de' => 'Restaurant', 'ja' => 'レストラン', 'ko' => '식당', 'tr' => 'restoran', 'ru' => 'ресторан', 'ar' => 'مطعم', 'az' => 'restoran'],
        // --- Chapter 3: restaurant — ordering ---
        'commander' => ['en' => 'to order', 'es' => 'pedir', 'de' => 'bestellen', 'ja' => '注文する', 'ko' => '주문하다', 'tr' => 'sipariş vermek', 'ru' => 'заказать', 'ar' => 'الطلب', 'az' => 'sifariş vermək'],
        'commande' => ['en' => 'order', 'es' => 'pedido', 'de' => 'Bestellung', 'ja' => '注文', 'ko' => '주문', 'tr' => 'sipariş', 'ru' => 'заказ', 'ar' => 'طلب', 'az' => 'sifariş'],
        'prendre' => ['en' => 'to have', 'es' => 'tomar', 'de' => 'nehmen', 'ja' => '取る', 'ko' => '먹다', 'tr' => 'almak', 'ru' => 'иметь', 'ar' => 'امتلاك', 'az' => 'sahib olmaq'],
        'je prends' => ['en' => "I'll have", 'es' => 'tomo', 'de' => 'ich nehme', 'ja' => 'にします', 'ko' => '하겠습니다', 'tr' => 'alayım', 'ru' => 'я возьму', 'ar' => 'سآخذ', 'az' => 'götürəcəyəm'],
        'plat' => ['en' => 'dish', 'es' => 'plato', 'de' => 'Gericht', 'ja' => '料理', 'ko' => '요리', 'tr' => 'yemek', 'ru' => 'блюдо', 'ar' => 'طبق', 'az' => 'yemək'],
        'entrée' => ['en' => 'starter', 'es' => 'entrante', 'de' => 'Vorspeise', 'ja' => '前菜', 'ko' => '전채', 'tr' => 'başlangıç', 'ru' => 'закуска', 'ar' => 'مقبلات', 'az' => 'qəlyanaltı'],
        'dessert' => ['en' => 'dessert', 'es' => 'postre', 'de' => 'Nachtisch', 'ja' => 'デザート', 'ko' => '디저트', 'tr' => 'tatlı', 'ru' => 'десерт', 'ar' => 'حلوى', 'az' => 'şirniyyat'],
        'boisson' => ['en' => 'drink', 'es' => 'bebida', 'de' => 'Getränk', 'ja' => '飲み物', 'ko' => '음료', 'tr' => 'iç', 'ru' => 'напиток', 'ar' => 'مشروب', 'az' => 'içki'],
        'part' => ['en' => 'slice', 'es' => 'trozo', 'de' => 'Stück', 'ja' => '一切れ', 'ko' => '한 조각', 'tr' => 'dilim', 'ru' => 'кусок', 'ar' => 'شريحة', 'az' => 'dilim'],
        'partager' => ['en' => 'to share', 'es' => 'compartir', 'de' => 'teilen', 'ja' => '分ける', 'ko' => '나누다', 'tr' => 'paylaşmak', 'ru' => 'разделить', 'ar' => 'المشاركة', 'az' => 'bölüşmək'],
        'choisir' => ['en' => 'to choose', 'es' => 'elegir', 'de' => 'wählen', 'ja' => '選ぶ', 'ko' => '고르다', 'tr' => 'seçmek', 'ru' => 'выбрать', 'ar' => 'الاختيار', 'az' => 'seçmək'],
        'apporter' => ['en' => 'to bring', 'es' => 'traer', 'de' => 'bringen', 'ja' => '持ってくる', 'ko' => '가져오다', 'tr' => 'getirmek', 'ru' => 'принести', 'ar' => 'الإحضار', 'az' => 'gətirmək'],
        'apportez-moi' => ['en' => 'bring me', 'es' => 'tráigame', 'de' => 'bringen Sie mir', 'ja' => '持ってきてください', 'ko' => '가져다주세요', 'tr' => 'bana getirin', 'ru' => 'принесите мне', 'ar' => 'أحضر لي', 'az' => 'mənə gətir'],
        'pouvez-vous' => ['en' => 'can you', 'es' => 'puede usted', 'de' => 'können Sie', 'ja' => 'できますか', 'ko' => '주시겠어요', 'tr' => 'yapabilir misiniz', 'ru' => 'могу ты', 'ar' => 'أستطيع أنت', 'az' => 'bacarıram sən'],
        'je peux' => ['en' => 'I can', 'es' => 'puedo', 'de' => 'ich kann', 'ja' => '私はできる', 'ko' => '저는 할 수 있습니다', 'tr' => 'yapabilirim', 'ru' => 'я могу', 'ar' => 'أنا أستطيع', 'az' => 'mən bacarıram'],
        'excusez-moi' => ['en' => 'excuse me', 'es' => 'disculpe', 'de' => 'entschuldigen Sie', 'ja' => 'すみません', 'ko' => '실례합니다', 'tr' => 'affedersiniz', 'ru' => 'извините', 'ar' => 'عفوا', 'az' => 'bağışlayın'],
        'pour' => ['en' => 'for', 'es' => 'para', 'de' => 'für', 'ja' => 'のために', 'ko' => '위해', 'tr' => 'için', 'ru' => 'для', 'ar' => 'لأجل', 'az' => 'üçün'],
        'pour moi' => ['en' => 'for me', 'es' => 'para mí', 'de' => 'für mich', 'ja' => '私に', 'ko' => '저에게', 'tr' => 'benim için', 'ru' => 'для меня', 'ar' => 'لأجل لي', 'az' => 'üçün mənə'],
        'sans' => ['en' => 'without', 'es' => 'sin', 'de' => 'ohne', 'ja' => 'なし', 'ko' => '없이', 'tr' => 'sız', 'ru' => 'без', 'ar' => 'بدون', 'az' => 'olmadan'],
        'du' => ['en' => 'some', 'es' => 'algo de', 'de' => 'etwas', 'ja' => '少しの', 'ko' => '약간의', 'tr' => 'biraz', 'ru' => 'немного', 'ar' => 'بعض', 'az' => 'bir az'],
        'moi' => ['en' => 'me', 'es' => 'mí', 'de' => 'mich', 'ja' => '私', 'ko' => '저', 'tr' => 'ben', 'ru' => 'меня', 'ar' => 'لي', 'az' => 'mənə'],
        'chaque' => ['en' => 'each', 'es' => 'cada', 'de' => 'jeder', 'ja' => 'それぞれの', 'ko' => '각각의', 'tr' => 'her', 'ru' => 'каждый', 'ar' => 'كل', 'az' => 'hər biri'],
        'faim' => ['en' => 'hunger', 'es' => 'hambre', 'de' => 'Hunger', 'ja' => '空腹', 'ko' => '배고픔', 'tr' => 'açlık', 'ru' => 'голод', 'ar' => 'جوع', 'az' => 'aclıq'],
        'soif' => ['en' => 'thirst', 'es' => 'sed', 'de' => 'Durst', 'ja' => 'のどの渇き', 'ko' => '갈증', 'tr' => 'susuzluk', 'ru' => 'жажда', 'ar' => 'عطش', 'az' => 'susuzluq'],
        // --- Chapter 3: restaurant — money ---
        'prix' => ['en' => 'price', 'es' => 'precio', 'de' => 'Preis', 'ja' => '値段', 'ko' => '가격', 'tr' => 'fiyat', 'ru' => 'цена', 'ar' => 'سعر', 'az' => 'qiymət'],
        'argent' => ['en' => 'money', 'es' => 'dinero', 'de' => 'Geld', 'ja' => 'お金', 'ko' => '돈', 'tr' => 'para', 'ru' => 'деньги', 'ar' => 'نقود', 'az' => 'pul'],
        'euros' => ['en' => 'euros', 'es' => 'euros', 'de' => 'Euro', 'ja' => 'ユーロ', 'ko' => '유로', 'tr' => 'euro', 'ru' => 'евро', 'ar' => 'يورو', 'az' => 'avro'],
        'cher' => ['en' => 'expensive', 'es' => 'caro', 'de' => 'teuer', 'ja' => '高い', 'ko' => '비싼', 'tr' => 'pahalı', 'ru' => 'дорогой', 'ar' => 'غالي', 'az' => 'bahalı'],
        'coûte' => ['en' => 'costs', 'es' => 'cuesta', 'de' => 'kostet', 'ja' => 'かかります', 'ko' => '입니다', 'tr' => 'tutar', 'ru' => 'стоит', 'ar' => 'يكلف', 'az' => 'qiyməti'],
        'total' => ['en' => 'total', 'es' => 'total', 'de' => 'Gesamt', 'ja' => '合計', 'ko' => '총액', 'tr' => 'toplam', 'ru' => 'итого', 'ar' => 'المجموع', 'az' => 'cəmi'],
        'addition' => ['en' => 'bill', 'es' => 'cuenta', 'de' => 'Rechnung', 'ja' => 'お会計', 'ko' => '계산서', 'tr' => 'hesap', 'ru' => 'счёт', 'ar' => 'الحساب', 'az' => 'hesab'],
        'payer' => ['en' => 'to pay', 'es' => 'pagar', 'de' => 'bezahlen', 'ja' => '払う', 'ko' => '지불하다', 'tr' => 'ödemek', 'ru' => 'платить', 'ar' => 'الدفع', 'az' => 'ödəmək'],
        'je paie' => ['en' => 'I pay', 'es' => 'pago', 'de' => 'ich bezahle', 'ja' => '私が払う', 'ko' => '제가 냅니다', 'tr' => 'ödüyorum', 'ru' => 'я плачу', 'ar' => 'أدفع', 'az' => 'ödəyirəm'],
        'monnaie' => ['en' => 'change', 'es' => 'cambio', 'de' => 'Wechselgeld', 'ja' => 'おつり', 'ko' => '거스름돈', 'tr' => 'para üstü', 'ru' => 'сдача', 'ar' => 'الباقي', 'az' => 'qalıq'],
        'espèces' => ['en' => 'cash', 'es' => 'efectivo', 'de' => 'Bargeld', 'ja' => '現金', 'ko' => '현금', 'tr' => 'nakit', 'ru' => 'наличные', 'ar' => 'كاش', 'az' => 'nağd'],
        'en espèces' => ['en' => 'in cash', 'es' => 'en efectivo', 'de' => 'in bar', 'ja' => '現金で', 'ko' => '현금으로', 'tr' => 'nakit', 'ru' => 'в наличные', 'ar' => 'في كاش', 'az' => 'içində nağd'],
        'pourboire' => ['en' => 'tip', 'es' => 'propina', 'de' => 'Trinkgeld', 'ja' => 'チップ', 'ko' => '팁', 'tr' => 'bahşiş', 'ru' => 'чаевые', 'ar' => 'بقشيش', 'az' => 'çaypulu'],
        'reçu' => ['en' => 'receipt', 'es' => 'recibo', 'de' => 'Quittung', 'ja' => 'レシート', 'ko' => '영수증', 'tr' => 'fiş', 'ru' => 'чек', 'ar' => 'إيصال', 'az' => 'qəbz'],
        'séparément' => ['en' => 'separately', 'es' => 'por separado', 'de' => 'getrennt', 'ja' => '別々に', 'ko' => '따로', 'tr' => 'ayrı', 'ru' => 'отдельно', 'ar' => 'منفصل', 'az' => 'ayrıca'],
        // --- Chapter 3: restaurant — reservations ---
        'réserver' => ['en' => 'to book', 'es' => 'reservar', 'de' => 'reservieren', 'ja' => '予約する', 'ko' => '예약하다', 'tr' => 'ayırtmak', 'ru' => 'в книга', 'ar' => 'إلى كتاب', 'az' => 'kitab'],
        'réservation' => ['en' => 'booking', 'es' => 'reserva', 'de' => 'Reservierung', 'ja' => '予約', 'ko' => '예약', 'tr' => 'rezervasyon', 'ru' => 'бронь', 'ar' => 'حجز', 'az' => 'rezervasiya'],
        'personnes' => ['en' => 'people', 'es' => 'personas', 'de' => 'Personen', 'ja' => '人', 'ko' => '명', 'tr' => 'kişi', 'ru' => 'люди', 'ar' => 'ناس', 'az' => 'insanlar'],
        'place' => ['en' => 'seat', 'es' => 'sitio', 'de' => 'Platz', 'ja' => '席', 'ko' => '자리', 'tr' => 'koltuk', 'ru' => 'место', 'ar' => 'مقعد', 'az' => 'yer'],
        'annuler' => ['en' => 'to cancel', 'es' => 'cancelar', 'de' => 'stornieren', 'ja' => 'キャンセルする', 'ko' => '취소하다', 'tr' => 'iptal etmek', 'ru' => 'отменить', 'ar' => 'الإلغاء', 'az' => 'ləğv etmək'],
        'confirmer' => ['en' => 'to confirm', 'es' => 'confirmar', 'de' => 'bestätigen', 'ja' => '確認する', 'ko' => '확인하다', 'tr' => 'onaylamak', 'ru' => 'подтвердить', 'ar' => 'التأكيد', 'az' => 'təsdiqləmək'],
        'midi' => ['en' => 'noon', 'es' => 'mediodía', 'de' => 'Mittag', 'ja' => '正午', 'ko' => '정오', 'tr' => 'öğlen', 'ru' => 'полдень', 'ar' => 'ظهرا', 'az' => 'günorta'],
        'heures' => ['en' => "o'clock", 'es' => 'en punto', 'de' => 'Uhr', 'ja' => '時', 'ko' => '시', 'tr' => 'saat', 'ru' => 'часов', 'ar' => 'الساعة', 'az' => 'saat'],
        // --- Chapter 3: restaurant — taste and complaints ---
        'délicieux' => ['en' => 'delicious', 'es' => 'delicioso', 'de' => 'köstlich', 'ja' => 'おいしい', 'ko' => '맛있는', 'tr' => 'lezzetli', 'ru' => 'вкусный', 'ar' => 'لذيذ', 'az' => 'dadlı'],
        'excellent' => ['en' => 'excellent', 'es' => 'excelente', 'de' => 'ausgezeichnet', 'ja' => '素晴らしい', 'ko' => '훌륭한', 'tr' => 'mükemmel', 'ru' => 'отлично', 'ar' => 'ممتاز', 'az' => 'əla'],
        'parfait' => ['en' => 'perfect', 'es' => 'perfecto', 'de' => 'perfekt', 'ja' => '完璧', 'ko' => '완벽한', 'tr' => 'mükemmel', 'ru' => 'идеально', 'ar' => 'مثالي', 'az' => 'mükəmməl'],
        'salé' => ['en' => 'salty', 'es' => 'salado', 'de' => 'salzig', 'ja' => 'しょっぱい', 'ko' => '짠', 'tr' => 'tuzlu', 'ru' => 'солёный', 'ar' => 'مالح', 'az' => 'duzlu'],
        'sucré' => ['en' => 'sweet', 'es' => 'dulce', 'de' => 'süß', 'ja' => '甘い', 'ko' => '단', 'tr' => 'tatlı', 'ru' => 'сладкий', 'ar' => 'حلو', 'az' => 'şirin'],
        'épicé' => ['en' => 'spicy', 'es' => 'picante', 'de' => 'scharf', 'ja' => '辛い', 'ko' => '매운', 'tr' => 'acılı', 'ru' => 'острый', 'ar' => 'حار', 'az' => 'acılı'],
        'cuit' => ['en' => 'cooked', 'es' => 'cocido', 'de' => 'gegart', 'ja' => '火が通った', 'ko' => '익힌', 'tr' => 'pişmiş', 'ru' => 'приготовленный', 'ar' => 'مطبوخ', 'az' => 'bişmiş'],
        'goût' => ['en' => 'taste', 'es' => 'sabor', 'de' => 'Geschmack', 'ja' => '味', 'ko' => '맛', 'tr' => 'tat', 'ru' => 'вкус', 'ar' => 'مذاق', 'az' => 'dad'],
        'problème' => ['en' => 'problem', 'es' => 'problema', 'de' => 'Problem', 'ja' => '問題', 'ko' => '문제', 'tr' => 'sorun', 'ru' => 'проблема', 'ar' => 'مشكلة', 'az' => 'problem'],
        'propre' => ['en' => 'clean', 'es' => 'limpio', 'de' => 'sauber', 'ja' => 'きれい', 'ko' => '깨끗한', 'tr' => 'temiz', 'ru' => 'чистый', 'ar' => 'نظيف', 'az' => 'təmiz'],
        'sale' => ['en' => 'dirty', 'es' => 'sucio', 'de' => 'schmutzig', 'ja' => '汚い', 'ko' => '더러운', 'tr' => 'kirli', 'ru' => 'грязный', 'ar' => 'متسخ', 'az' => 'çirkli'],
        'frais' => ['en' => 'fresh', 'es' => 'fresco', 'de' => 'frisch', 'ja' => '新鮮', 'ko' => '신선한', 'tr' => 'taze', 'ru' => 'свежий', 'ar' => 'طازج', 'az' => 'təzə'],
        // --- Chapter 3: restaurant — diet and allergies ---
        'végétarien' => ['en' => 'vegetarian', 'es' => 'vegetariano', 'de' => 'vegetarisch', 'ja' => 'ベジタリアン', 'ko' => '채식주의자', 'tr' => 'vejetaryen', 'ru' => 'вегетарианец', 'ar' => 'نباتي', 'az' => 'vegetarian'],
        'allergique' => ['en' => 'allergic', 'es' => 'alérgico', 'de' => 'allergisch', 'ja' => 'アレルギーの', 'ko' => '알레르기가 있는', 'tr' => 'alerjik', 'ru' => 'аллергия', 'ar' => 'حساسية', 'az' => 'allergiya'],
        'allergie' => ['en' => 'allergy', 'es' => 'alergia', 'de' => 'Allergie', 'ja' => 'アレルギー', 'ko' => '알레르기', 'tr' => 'alerji', 'ru' => 'аллергия', 'ar' => 'حساسية', 'az' => 'allergiya'],
        'gluten' => ['en' => 'gluten', 'es' => 'gluten', 'de' => 'Gluten', 'ja' => 'グルテン', 'ko' => '글루텐', 'tr' => 'gluten', 'ru' => 'глютен', 'ar' => 'غلوتين', 'az' => 'qlüten'],
        'noix' => ['en' => 'nuts', 'es' => 'nueces', 'de' => 'Nüsse', 'ja' => 'ナッツ', 'ko' => '견과류', 'tr' => 'fındık', 'ru' => 'орехи', 'ar' => 'مكسرات', 'az' => 'qoz'],
        'régime' => ['en' => 'diet', 'es' => 'dieta', 'de' => 'Diät', 'ja' => '食事制限', 'ko' => '식단', 'tr' => 'beslenme', 'ru' => 'диета', 'ar' => 'حمية', 'az' => 'pəhriz'],
        'ingrédients' => ['en' => 'ingredients', 'es' => 'ingredientes', 'de' => 'Zutaten', 'ja' => '材料', 'ko' => '재료', 'tr' => 'içindekiler', 'ru' => 'ингредиенты', 'ar' => 'مكونات', 'az' => 'tərkib'],
        'lactose' => ['en' => 'lactose', 'es' => 'lactosa', 'de' => 'Laktose', 'ja' => '乳糖', 'ko' => '유당', 'tr' => 'laktoz', 'ru' => 'лактоза', 'ar' => 'لاكتوز', 'az' => 'laktoza'],
        'éviter' => ['en' => 'to avoid', 'es' => 'evitar', 'de' => 'vermeiden', 'ja' => '避ける', 'ko' => '피하다', 'tr' => 'kaçınmak', 'ru' => 'избегать', 'ar' => 'التجنب', 'az' => 'qaçınmaq'],
        'contient' => ['en' => 'contains', 'es' => 'contiene', 'de' => 'enthält', 'ja' => '含む', 'ko' => '들어있다', 'tr' => 'içerir', 'ru' => 'содержит', 'ar' => 'يحتوي', 'az' => 'tərkibində var'],
        // --- Chapter 3: restaurant — fast food ---
        'emporter' => ['en' => 'to take away', 'es' => 'para llevar', 'de' => 'zum Mitnehmen', 'ja' => '持ち帰り', 'ko' => '포장', 'tr' => 'paket almak', 'ru' => 'с собой', 'ar' => 'للخارج', 'az' => 'özümlə'],
        'sur place' => ['en' => 'eat in', 'es' => 'para tomar aquí', 'de' => 'zum Hieressen', 'ja' => '店内で', 'ko' => '매장에서', 'tr' => 'burada ye', 'ru' => 'ем в', 'ar' => 'آكل في', 'az' => 'yeyirəm içində'],
        'minutes' => ['en' => 'minutes', 'es' => 'minutos', 'de' => 'Minuten', 'ja' => '分', 'ko' => '분', 'tr' => 'dakika', 'ru' => 'минут', 'ar' => 'دقائق', 'az' => 'dəqiqə'],
        'rapide' => ['en' => 'fast', 'es' => 'rápido', 'de' => 'schnell', 'ja' => '速い', 'ko' => '빠른', 'tr' => 'hızlı', 'ru' => 'быстро', 'ar' => 'بسرعة', 'az' => 'sürətli'],
        'sac' => ['en' => 'bag', 'es' => 'bolsa', 'de' => 'Tüte', 'ja' => '袋', 'ko' => '봉투', 'tr' => 'poşet', 'ru' => 'пакет', 'ar' => 'كيس', 'az' => 'torba'],
        'enfant' => ['en' => 'child', 'es' => 'niño', 'de' => 'Kind', 'ja' => '子供', 'ko' => '아이', 'tr' => 'çocuk', 'ru' => 'ребёнок', 'ar' => 'طفل', 'az' => 'uşaq'],
        // --- Chapter 4: supermarket — the shop itself ---
        "d'argent" => ['en' => 'of money', 'es' => 'de dinero', 'de' => 'Geld', 'ja' => 'お金の', 'ko' => '돈의', 'tr' => 'para', 'ru' => 'деньги', 'ar' => 'نقود', 'az' => 'pul'],
        "d'eau" => ['en' => 'of water', 'es' => 'de agua', 'de' => 'Wasser', 'ja' => '水の', 'ko' => '물의', 'tr' => 'su', 'ru' => 'воды', 'ar' => 'الماء', 'az' => 'suyun'],
        'supermarché' => ['en' => 'supermarket', 'es' => 'supermercado', 'de' => 'Supermarkt', 'ja' => 'スーパー', 'ko' => '슈퍼마켓', 'tr' => 'market', 'ru' => 'супермаркет', 'ar' => 'سوبرماركت', 'az' => 'supermarket'],
        'rayon' => ['en' => 'aisle', 'es' => 'pasillo', 'de' => 'Regal', 'ja' => '売り場', 'ko' => '진열대', 'tr' => 'reyon', 'ru' => 'отдел', 'ar' => 'قسم', 'az' => 'şöbə'],
        'liste' => ['en' => 'list', 'es' => 'lista', 'de' => 'Liste', 'ja' => 'リスト', 'ko' => '목록', 'tr' => 'liste', 'ru' => 'список', 'ar' => 'قائمة', 'az' => 'siyahı'],
        'chariot' => ['en' => 'trolley', 'es' => 'carrito', 'de' => 'Einkaufswagen', 'ja' => 'カート', 'ko' => '카트', 'tr' => 'araba', 'ru' => 'тележка', 'ar' => 'عربة', 'az' => 'araba'],
        'panier' => ['en' => 'basket', 'es' => 'cesta', 'de' => 'Korb', 'ja' => 'かご', 'ko' => '바구니', 'tr' => 'sepet', 'ru' => 'корзина', 'ar' => 'سلة', 'az' => 'səbət'],
        'caisse' => ['en' => 'checkout', 'es' => 'caja', 'de' => 'Kasse', 'ja' => 'レジ', 'ko' => '계산대', 'tr' => 'kasa', 'ru' => 'касса', 'ar' => 'صندوق الدفع', 'az' => 'kassa'],
        'carte bancaire' => ['en' => 'bank card', 'es' => 'tarjeta', 'de' => 'Bankkarte', 'ja' => 'カード', 'ko' => '카드', 'tr' => 'banka kartı', 'ru' => 'банковская карта', 'ar' => 'بطاقة بنكية', 'az' => 'bank kartı'],
        'longue' => ['en' => 'long', 'es' => 'larga', 'de' => 'lang', 'ja' => '長い', 'ko' => '긴', 'tr' => 'uzun', 'ru' => 'длинный', 'ar' => 'طويل', 'az' => 'uzun'],
        'caissier' => ['en' => 'cashier', 'es' => 'cajero', 'de' => 'Kassierer', 'ja' => 'レジ係', 'ko' => '계산원', 'tr' => 'kasiyer', 'ru' => 'кассир', 'ar' => 'أمين الصندوق', 'az' => 'kassir'],
        'file' => ['en' => 'queue', 'es' => 'cola', 'de' => 'Schlange', 'ja' => '列', 'ko' => '줄', 'tr' => 'sıra', 'ru' => 'очередь', 'ar' => 'طابور', 'az' => 'növbə'],
        'produit' => ['en' => 'product', 'es' => 'producto', 'de' => 'Produkt', 'ja' => '商品', 'ko' => '상품', 'tr' => 'ürün', 'ru' => 'продукт', 'ar' => 'منتج', 'az' => 'məhsul'],
        // --- Chapter 4: supermarket — fruit and vegetables ---
        'banane' => ['en' => 'banana', 'es' => 'plátano', 'de' => 'Banane', 'ja' => 'バナナ', 'ko' => '바나나', 'tr' => 'muz', 'ru' => 'банан', 'ar' => 'موزة', 'az' => 'banan'],
        'orange' => ['en' => 'orange', 'es' => 'naranja', 'de' => 'Orange', 'ja' => 'オレンジ', 'ko' => '오렌지', 'tr' => 'portakal', 'ru' => 'апельсин', 'ar' => 'برتقالة', 'az' => 'portağal'],
        'raisin' => ['en' => 'grapes', 'es' => 'uvas', 'de' => 'Trauben', 'ja' => 'ぶどう', 'ko' => '포도', 'tr' => 'üzüm', 'ru' => 'виноград', 'ar' => 'عنب', 'az' => 'üzüm'],
        'carotte' => ['en' => 'carrot', 'es' => 'zanahoria', 'de' => 'Karotte', 'ja' => 'にんじん', 'ko' => '당근', 'tr' => 'havuç', 'ru' => 'морковь', 'ar' => 'جزر', 'az' => 'yerkökü'],
        'tomate' => ['en' => 'tomato', 'es' => 'tomate', 'de' => 'Tomate', 'ja' => 'トマト', 'ko' => '토마토', 'tr' => 'domates', 'ru' => 'помидор', 'ar' => 'طماطم', 'az' => 'pomidor'],
        'pomme de terre' => ['en' => 'potato', 'es' => 'patata', 'de' => 'Kartoffel', 'ja' => 'じゃがいも', 'ko' => '감자', 'tr' => 'patates', 'ru' => 'картофель', 'ar' => 'بطاطا', 'az' => 'kartof'],
        'oignon' => ['en' => 'onion', 'es' => 'cebolla', 'de' => 'Zwiebel', 'ja' => '玉ねぎ', 'ko' => '양파', 'tr' => 'soğan', 'ru' => 'лук', 'ar' => 'بصل', 'az' => 'soğan'],
        'œufs' => ['en' => 'eggs', 'es' => 'huevos', 'de' => 'Eier', 'ja' => '卵', 'ko' => '계란', 'tr' => 'yumurta', 'ru' => 'яйца', 'ar' => 'بيض', 'az' => 'yumurtalar'],
        'fruits' => ['en' => 'fruits', 'es' => 'frutas', 'de' => 'Früchte', 'ja' => '果物', 'ko' => '과일', 'tr' => 'meyveler', 'ru' => 'фрукты', 'ar' => 'فواكه', 'az' => 'meyvələr'],
        // --- Chapter 4: supermarket — quantities ---
        'kilo' => ['en' => 'kilo', 'es' => 'kilo', 'de' => 'Kilo', 'ja' => 'キロ', 'ko' => '킬로', 'tr' => 'kilo', 'ru' => 'кило', 'ar' => 'كيلو', 'az' => 'kilo'],
        'gramme' => ['en' => 'gram', 'es' => 'gramo', 'de' => 'Gramm', 'ja' => 'グラム', 'ko' => '그램', 'tr' => 'gram', 'ru' => 'грамм', 'ar' => 'غرام', 'az' => 'qram'],
        'litre' => ['en' => 'litre', 'es' => 'litro', 'de' => 'Liter', 'ja' => 'リットル', 'ko' => '리터', 'tr' => 'litre', 'ru' => 'литр', 'ar' => 'لتر', 'az' => 'litr'],
        'boîte' => ['en' => 'box', 'es' => 'caja', 'de' => 'Schachtel', 'ja' => '箱', 'ko' => '상자', 'tr' => 'kutu', 'ru' => 'коробка', 'ar' => 'علبة', 'az' => 'qutu'],
        'plein' => ['en' => 'full', 'es' => 'lleno', 'de' => 'voll', 'ja' => 'いっぱい', 'ko' => '가득한', 'tr' => 'dolu', 'ru' => 'полный', 'ar' => 'ممتلئ', 'az' => 'dolu'],
        'vide' => ['en' => 'empty', 'es' => 'vacío', 'de' => 'leer', 'ja' => '空', 'ko' => '빈', 'tr' => 'boş', 'ru' => 'пустой', 'ar' => 'فارغ', 'az' => 'boş'],
        'lourd' => ['en' => 'heavy', 'es' => 'pesado', 'de' => 'schwer', 'ja' => '重い', 'ko' => '무거운', 'tr' => 'ağır', 'ru' => 'тяжёлый', 'ar' => 'ثقيل', 'az' => 'ağır'],
        'léger' => ['en' => 'light', 'es' => 'ligero', 'de' => 'leicht', 'ja' => '軽い', 'ko' => '가벼운', 'tr' => 'hafif', 'ru' => 'лёгкий', 'ar' => 'خفيف', 'az' => 'yüngül'],
        // --- Chapter 4: supermarket — shopping ---
        'acheter' => ['en' => 'to buy', 'es' => 'comprar', 'de' => 'kaufen', 'ja' => '買う', 'ko' => '사다', 'tr' => 'almak', 'ru' => 'купить', 'ar' => 'الشراء', 'az' => 'almaq'],
        'chercher' => ['en' => 'to look for', 'es' => 'buscar', 'de' => 'suchen', 'ja' => '探す', 'ko' => '찾다', 'tr' => 'aramak', 'ru' => 'искать', 'ar' => 'البحث', 'az' => 'axtarmaq'],
        'trouver' => ['en' => 'to find', 'es' => 'encontrar', 'de' => 'finden', 'ja' => '見つける', 'ko' => '발견하다', 'tr' => 'bulmak', 'ru' => 'найти', 'ar' => 'العثور', 'az' => 'tapmaq'],
        'besoin' => ['en' => 'need', 'es' => 'necesidad', 'de' => 'Bedarf', 'ja' => '必要', 'ko' => '필요', 'tr' => 'ihtiyaç', 'ru' => 'нужно', 'ar' => 'حاجة', 'az' => 'ehtiyac'],
        'comparer' => ['en' => 'to compare', 'es' => 'comparar', 'de' => 'vergleichen', 'ja' => '比べる', 'ko' => '비교하다', 'tr' => 'karşılaştırmak', 'ru' => 'сравнить', 'ar' => 'المقارنة', 'az' => 'müqayisə etmək'],
        'bon marché' => ['en' => 'cheap', 'es' => 'barato', 'de' => 'billig', 'ja' => '安い', 'ko' => '싼', 'tr' => 'ucuz', 'ru' => 'дешёвый', 'ar' => 'رخيص', 'az' => 'ucuz'],
        'réduction' => ['en' => 'discount', 'es' => 'descuento', 'de' => 'Rabatt', 'ja' => '割引', 'ko' => '할인', 'tr' => 'indirim', 'ru' => 'скидка', 'ar' => 'خصم', 'az' => 'endirim'],
        'mettre' => ['en' => 'to put', 'es' => 'poner', 'de' => 'legen', 'ja' => '入れる', 'ko' => '넣다', 'tr' => 'koymak', 'ru' => 'положить', 'ar' => 'وضع', 'az' => 'qoymaq'],
        'peser' => ['en' => 'to weigh', 'es' => 'pesar', 'de' => 'wiegen', 'ja' => '量る', 'ko' => '무게를 재다', 'tr' => 'tartmak', 'ru' => 'взвесить', 'ar' => 'الوزن', 'az' => 'çəkmək'],
        'balance' => ['en' => 'scales', 'es' => 'balanza', 'de' => 'Waage', 'ja' => 'はかり', 'ko' => '저울', 'tr' => 'terazi', 'ru' => 'весы', 'ar' => 'ميزان', 'az' => 'tərəzi'],
        'gratuit' => ['en' => 'free', 'es' => 'gratis', 'de' => 'kostenlos', 'ja' => '無料', 'ko' => '무료', 'tr' => 'boş', 'ru' => 'бесплатно', 'ar' => 'مجاني', 'az' => 'pulsuz'],
        'boulangerie' => ['en' => 'bakery', 'es' => 'panadería', 'de' => 'Bäckerei', 'ja' => 'パン屋', 'ko' => '빵집', 'tr' => 'fırın', 'ru' => 'пекарня', 'ar' => 'مخبز', 'az' => 'çörəkxana'],
        'demander' => ['en' => 'to ask', 'es' => 'preguntar', 'de' => 'fragen', 'ja' => '尋ねる', 'ko' => '묻다', 'tr' => 'sormak', 'ru' => 'спросить', 'ar' => 'السؤال', 'az' => 'soruşmaq'],
        'donner' => ['en' => 'to give', 'es' => 'dar', 'de' => 'geben', 'ja' => '与える', 'ko' => '주다', 'tr' => 'vermek', 'ru' => 'дать', 'ar' => 'الإعطاء', 'az' => 'vermək'],
        'porter' => ['en' => 'to carry', 'es' => 'llevar', 'de' => 'tragen', 'ja' => '運ぶ', 'ko' => '나르다', 'tr' => 'taşımak', 'ru' => 'нести', 'ar' => 'الحمل', 'az' => 'daşımaq'],
    ];

    /**
     * The ['i18n' => [...]] map for a French word, ready to store in exercise
     * data. Falls back to the word itself if it isn't in the dictionary yet.
     *
     * @return array{i18n: array<string, string>}
     */
    public static function hint(string $french): array
    {
        return ['i18n' => self::meanings($french)];
    }

    /**
     * @return array<string, string>
     */
    public static function meanings(string $french): array
    {
        $key = mb_strtolower(trim($french));

        return self::WORDS[$key] ?? ['en' => $french];
    }

    /** Every French word the dictionary knows (used for wrong-answer options). */
    public static function all(): array
    {
        return array_keys(self::WORDS);
    }

    public static function knows(string $french): bool
    {
        return isset(self::WORDS[mb_strtolower(trim($french))]);
    }
}
