<?php

namespace Database\Seeders\Support;

/**
 * German word => its meaning in every native language a German course supports
 * (English, Spanish, French, Japanese, Korean).
 *
 * German is the LEARNING language here, so exercise content (words, phrases,
 * tiles) is authored in German, and only the hints/prompts are shown in the
 * learner's own language. Nothing user-facing is hardcoded: seeders pull from
 * here and store the result as an ['i18n' => [...]] map, which
 * ExerciseContentService resolves per request.
 *
 * This mirrors EnglishVocabulary and FrenchVocabulary exactly, only the language
 * roles are swapped. Add a word here once and every unit can use it.
 */
class GermanVocabulary
{
    private const WORDS = [
        'Abend' => ['en' => 'evening', 'es' => 'tarde', 'fr' => 'soir', 'ja' => '夕方', 'ko' => '저녁'],
        'Allergie' => ['en' => 'allergy', 'es' => 'alergia', 'fr' => 'allergie', 'ja' => 'アレルギー', 'ko' => '알레르기'],
        'Alter' => ['en' => 'age', 'es' => 'edad', 'fr' => 'âge', 'ja' => '年齢', 'ko' => '나이'],
        'Apfel' => ['en' => 'apple', 'es' => 'manzana', 'fr' => 'pomme', 'ja' => 'りんご', 'ko' => '사과'],
        'Arzt' => ['en' => 'doctor', 'es' => 'médico', 'fr' => 'médecin', 'ja' => '医者', 'ko' => '의사'],
        'Bahnhof' => ['en' => 'station', 'es' => 'estación', 'fr' => 'gare', 'ja' => '駅', 'ko' => '역'],
        'Banane' => ['en' => 'banana', 'es' => 'plátano', 'fr' => 'banane', 'ja' => 'バナナ', 'ko' => '바나나'],
        'Bestellung' => ['en' => 'order', 'es' => 'pedido', 'fr' => 'commande', 'ja' => '注文', 'ko' => '주문'],
        'Bier' => ['en' => 'beer', 'es' => 'cerveza', 'fr' => 'bière', 'ja' => 'ビール', 'ko' => '맥주'],
        'Brot' => ['en' => 'bread', 'es' => 'pan', 'fr' => 'pain', 'ja' => 'パン', 'ko' => '빵'],
        'Bruder' => ['en' => 'brother', 'es' => 'hermano', 'fr' => 'frère', 'ja' => '兄弟', 'ko' => '형제'],
        'Buch' => ['en' => 'book', 'es' => 'libro', 'fr' => 'livre', 'ja' => '本', 'ko' => '책'],
        'Burger' => ['en' => 'burger', 'es' => 'hamburguesa', 'fr' => 'hamburger', 'ja' => 'ハンバーガー', 'ko' => '햄버거'],
        'Butter' => ['en' => 'butter', 'es' => 'mantequilla', 'fr' => 'beurre', 'ja' => 'バター', 'ko' => '버터'],
        'Bäckerei' => ['en' => 'bakery', 'es' => 'panadería', 'fr' => 'boulangerie', 'ja' => 'パン屋', 'ko' => '빵집'],
        'Bücher' => ['en' => 'books', 'es' => 'libros', 'fr' => 'livres', 'ja' => '本', 'ko' => '책들'],
        'Dienstag' => ['en' => 'Tuesday', 'es' => 'martes', 'fr' => 'mardi', 'ja' => '火曜日', 'ko' => '화요일'],
        'Diät' => ['en' => 'diet', 'es' => 'dieta', 'fr' => 'régime', 'ja' => '食事制限', 'ko' => '식단'],
        'Dollar' => ['en' => 'dollars', 'es' => 'dólares', 'fr' => 'dollars', 'ja' => 'ドル', 'ko' => '달러'],
        'Dorf' => ['en' => 'village', 'es' => 'pueblo', 'fr' => 'village', 'ja' => '村', 'ko' => '마을'],
        'Ei' => ['en' => 'egg', 'es' => 'huevo', 'fr' => 'œuf', 'ja' => '卵', 'ko' => '계란'],
        'Eier' => ['en' => 'eggs', 'es' => 'huevos', 'fr' => 'œufs', 'ja' => '卵', 'ko' => '계란'],
        'Einkaufswagen' => ['en' => 'trolley', 'es' => 'carrito', 'fr' => 'chariot', 'ja' => 'カート', 'ko' => '카트'],
        'Eis' => ['en' => 'ice cream', 'es' => 'helado', 'fr' => 'glace', 'ja' => 'アイスクリーム', 'ko' => '아이스크림'],
        'Eiswürfel' => ['en' => 'ice', 'es' => 'hielo', 'fr' => 'glaçons', 'ja' => '氷', 'ko' => '얼음'],
        'Entschuldigung' => ['en' => 'sorry', 'es' => 'lo siento', 'fr' => 'désolé', 'ja' => 'ごめんなさい', 'ko' => '죄송합니다'],
        'Erdbeere' => ['en' => 'strawberry', 'es' => 'fresa', 'fr' => 'fraise', 'ja' => 'いちご', 'ko' => '딸기'],
        'Film' => ['en' => 'film', 'es' => 'película', 'fr' => 'film', 'ja' => '映画', 'ko' => '영화'],
        'Fisch' => ['en' => 'fish', 'es' => 'pescado', 'fr' => 'poisson', 'ja' => '魚', 'ko' => '생선'],
        'Flasche' => ['en' => 'bottle', 'es' => 'botella', 'fr' => 'bouteille', 'ja' => 'ボトル', 'ko' => '병'],
        'Fleisch' => ['en' => 'meat', 'es' => 'carne', 'fr' => 'viande', 'ja' => '肉', 'ko' => '고기'],
        'Freund' => ['en' => 'friend', 'es' => 'amigo', 'fr' => 'ami', 'ja' => '友達', 'ko' => '친구'],
        'Früchte' => ['en' => 'fruits', 'es' => 'frutas', 'fr' => 'fruits', 'ja' => '果物', 'ko' => '과일'],
        'Frühling' => ['en' => 'spring', 'es' => 'primavera', 'fr' => 'printemps', 'ja' => '春', 'ko' => '봄'],
        'Gabel' => ['en' => 'fork', 'es' => 'tenedor', 'fr' => 'fourchette', 'ja' => 'フォーク', 'ko' => '포크'],
        'Geld' => ['en' => 'money', 'es' => 'dinero', 'fr' => 'argent', 'ja' => 'お金', 'ko' => '돈'],
        'Gemüse' => ['en' => 'vegetables', 'es' => 'verduras', 'fr' => 'légumes', 'ja' => '野菜', 'ko' => '채소'],
        'Gericht' => ['en' => 'dish', 'es' => 'plato', 'fr' => 'plat', 'ja' => '料理', 'ko' => '요리'],
        'Gesamt' => ['en' => 'total', 'es' => 'total', 'fr' => 'total', 'ja' => '合計', 'ko' => '총액'],
        'Geschmack' => ['en' => 'taste', 'es' => 'sabor', 'fr' => 'goût', 'ja' => '味', 'ko' => '맛'],
        'Geschäft' => ['en' => 'shop', 'es' => 'tienda', 'fr' => 'magasin', 'ja' => '店', 'ko' => '가게'],
        'Glas' => ['en' => 'glass', 'es' => 'vaso', 'fr' => 'verre', 'ja' => 'グラス', 'ko' => '유리잔'],
        'Gluten' => ['en' => 'gluten', 'es' => 'gluten', 'fr' => 'gluten', 'ja' => 'グルテン', 'ko' => '글루텐'],
        'Gramm' => ['en' => 'gram', 'es' => 'gramo', 'fr' => 'gramme', 'ja' => 'グラム', 'ko' => '그램'],
        'Haus' => ['en' => 'house', 'es' => 'casa', 'fr' => 'maison', 'ja' => '家', 'ko' => '집'],
        'Herbst' => ['en' => 'autumn', 'es' => 'otoño', 'fr' => 'automne', 'ja' => '秋', 'ko' => '가을'],
        'Himmel' => ['en' => 'sky', 'es' => 'cielo', 'fr' => 'ciel', 'ja' => '空', 'ko' => '하늘'],
        'Hund' => ['en' => 'dog', 'es' => 'perro', 'fr' => 'chien', 'ja' => '犬', 'ko' => '개'],
        'Hunde' => ['en' => 'dogs', 'es' => 'perros', 'fr' => 'chiens', 'ja' => '犬', 'ko' => '개들'],
        'Hähnchen' => ['en' => 'chicken', 'es' => 'pollo', 'fr' => 'poulet', 'ja' => '鶏肉', 'ko' => '닭고기'],
        'Jahre alt' => ['en' => 'years old', 'es' => 'años', 'fr' => 'ans', 'ja' => '歳', 'ko' => '살'],
        'Jahreszeit' => ['en' => 'season', 'es' => 'estación', 'fr' => 'saison', 'ja' => '季節', 'ko' => '계절'],
        'Kaffee' => ['en' => 'coffee', 'es' => 'café', 'fr' => 'café', 'ja' => 'コーヒー', 'ko' => '커피'],
        'Kalender' => ['en' => 'calendar', 'es' => 'calendario', 'fr' => 'calendrier', 'ja' => 'カレンダー', 'ko' => '달력'],
        'Karotte' => ['en' => 'carrot', 'es' => 'zanahoria', 'fr' => 'carotte', 'ja' => 'にんじん', 'ko' => '당근'],
        'Karte' => ['en' => 'card', 'es' => 'tarjeta', 'fr' => 'carte', 'ja' => 'カード', 'ko' => '카드'],
        'Kartoffel' => ['en' => 'potato', 'es' => 'patata', 'fr' => 'pomme de terre', 'ja' => 'じゃがいも', 'ko' => '감자'],
        'Kasse' => ['en' => 'checkout', 'es' => 'caja', 'fr' => 'caisse', 'ja' => 'レジ', 'ko' => '계산대'],
        'Kassierer' => ['en' => 'cashier', 'es' => 'cajero', 'fr' => 'caissier', 'ja' => 'レジ係', 'ko' => '계산원'],
        'Katze' => ['en' => 'cat', 'es' => 'gato', 'fr' => 'chat', 'ja' => '猫', 'ko' => '고양이'],
        'Katzen' => ['en' => 'cats', 'es' => 'gatos', 'fr' => 'chats', 'ja' => '猫', 'ko' => '고양이들'],
        'Kellner' => ['en' => 'waiter', 'es' => 'camarero', 'fr' => 'serveur', 'ja' => 'ウェイター', 'ko' => '웨이터'],
        'Kilo' => ['en' => 'kilo', 'es' => 'kilo', 'fr' => 'kilo', 'ja' => 'キロ', 'ko' => '킬로'],
        'Kind' => ['en' => 'child', 'es' => 'niño', 'fr' => 'enfant', 'ja' => '子供', 'ko' => '아이'],
        'Korb' => ['en' => 'basket', 'es' => 'cesta', 'fr' => 'panier', 'ja' => 'かご', 'ko' => '바구니'],
        'Kuchen' => ['en' => 'cake', 'es' => 'pastel', 'fr' => 'gâteau', 'ja' => 'ケーキ', 'ko' => '케이크'],
        'Kugelschreiber' => ['en' => 'pen', 'es' => 'bolígrafo', 'fr' => 'stylo', 'ja' => 'ペン', 'ko' => '펜'],
        'Käse' => ['en' => 'cheese', 'es' => 'queso', 'fr' => 'fromage', 'ja' => 'チーズ', 'ko' => '치즈'],
        'Küche' => ['en' => 'kitchen', 'es' => 'cocina', 'fr' => 'cuisine', 'ja' => '厨房', 'ko' => '주방'],
        'Lehrer' => ['en' => 'teacher', 'es' => 'profesor', 'fr' => 'professeur', 'ja' => '先生', 'ko' => '선생님'],
        'Liste' => ['en' => 'list', 'es' => 'lista', 'fr' => 'liste', 'ja' => 'リスト', 'ko' => '목록'],
        'Liter' => ['en' => 'litre', 'es' => 'litro', 'fr' => 'litre', 'ja' => 'リットル', 'ko' => '리터'],
        'Löffel' => ['en' => 'spoon', 'es' => 'cuchara', 'fr' => 'cuillère', 'ja' => 'スプーン', 'ko' => '숟가락'],
        'Menü' => ['en' => 'menu', 'es' => 'menú', 'fr' => 'menu', 'ja' => 'メニュー', 'ko' => '메뉴'],
        'Messer' => ['en' => 'knife', 'es' => 'cuchillo', 'fr' => 'couteau', 'ja' => 'ナイフ', 'ko' => '나이프'],
        'Milch' => ['en' => 'milk', 'es' => 'leche', 'fr' => 'lait', 'ja' => '牛乳', 'ko' => '우유'],
        'Minuten' => ['en' => 'minutes', 'es' => 'minutos', 'fr' => 'minutes', 'ja' => '分', 'ko' => '분'],
        'Mittag' => ['en' => 'noon', 'es' => 'mediodía', 'fr' => 'midi', 'ja' => '正午', 'ko' => '정오'],
        'Montag' => ['en' => 'Monday', 'es' => 'lunes', 'fr' => 'lundi', 'ja' => '月曜日', 'ko' => '월요일'],
        'Morgen' => ['en' => 'morning', 'es' => 'mañana', 'fr' => 'matin', 'ja' => '朝', 'ko' => '아침'],
        'Mutter' => ['en' => 'mother', 'es' => 'madre', 'fr' => 'mère', 'ja' => '母', 'ko' => '어머니'],
        'Nachbar' => ['en' => 'neighbour', 'es' => 'vecino', 'fr' => 'voisin', 'ja' => '隣人', 'ko' => '이웃'],
        'Nachricht' => ['en' => 'message', 'es' => 'mensaje', 'fr' => 'message', 'ja' => 'メッセージ', 'ko' => '메시지'],
        'Nacht' => ['en' => 'night', 'es' => 'noche', 'fr' => 'nuit', 'ja' => '夜', 'ko' => '밤'],
        'Nachtisch' => ['en' => 'dessert', 'es' => 'postre', 'fr' => 'dessert', 'ja' => 'デザート', 'ko' => '디저트'],
        'Name' => ['en' => 'name', 'es' => 'nombre', 'fr' => 'nom', 'ja' => '名前', 'ko' => '이름'],
        'Norden' => ['en' => 'north', 'es' => 'norte', 'fr' => 'nord', 'ja' => '北', 'ko' => '북쪽'],
        'Nüsse' => ['en' => 'nuts', 'es' => 'nueces', 'fr' => 'noix', 'ja' => 'ナッツ', 'ko' => '견과류'],
        'Obst' => ['en' => 'fruit', 'es' => 'fruta', 'fr' => 'fruit', 'ja' => '果物', 'ko' => '과일'],
        'Orange' => ['en' => 'orange', 'es' => 'naranja', 'fr' => 'orange', 'ja' => 'オレンジ', 'ko' => '오렌지'],
        'Park' => ['en' => 'park', 'es' => 'parque', 'fr' => 'parc', 'ja' => '公園', 'ko' => '공원'],
        'Personen' => ['en' => 'people', 'es' => 'personas', 'fr' => 'personnes', 'ja' => '人', 'ko' => '명'],
        'Pfeffer' => ['en' => 'pepper', 'es' => 'pimienta', 'fr' => 'poivre', 'ja' => 'こしょう', 'ko' => '후추'],
        'Platz' => ['en' => 'seat', 'es' => 'sitio', 'fr' => 'place', 'ja' => '席', 'ko' => '자리'],
        'Pommes' => ['en' => 'fries', 'es' => 'patatas fritas', 'fr' => 'frites', 'ja' => 'フライドポテト', 'ko' => '감자튀김'],
        'Preis' => ['en' => 'price', 'es' => 'precio', 'fr' => 'prix', 'ja' => '値段', 'ko' => '가격'],
        'Preise' => ['en' => 'prices', 'es' => 'precios', 'fr' => 'prix', 'ja' => '値段', 'ko' => '가격'],
        'Problem' => ['en' => 'problem', 'es' => 'problema', 'fr' => 'problème', 'ja' => '問題', 'ko' => '문제'],
        'Produkt' => ['en' => 'product', 'es' => 'producto', 'fr' => 'produit', 'ja' => '商品', 'ko' => '상품'],
        'Quittung' => ['en' => 'receipt', 'es' => 'recibo', 'fr' => 'reçu', 'ja' => 'レシート', 'ko' => '영수증'],
        'Rabatt' => ['en' => 'discount', 'es' => 'descuento', 'fr' => 'réduction', 'ja' => '割引', 'ko' => '할인'],
        'Regal' => ['en' => 'aisle', 'es' => 'pasillo', 'fr' => 'rayon', 'ja' => '売り場', 'ko' => '진열대'],
        'Regen' => ['en' => 'rain', 'es' => 'lluvia', 'fr' => 'pluie', 'ja' => '雨', 'ko' => '비'],
        'Reis' => ['en' => 'rice', 'es' => 'arroz', 'fr' => 'riz', 'ja' => 'ご飯', 'ko' => '밥'],
        'Reservierung' => ['en' => 'booking', 'es' => 'reserva', 'fr' => 'réservation', 'ja' => '予約', 'ko' => '예약'],
        'Restaurant' => ['en' => 'restaurant', 'es' => 'restaurante', 'fr' => 'restaurant', 'ja' => 'レストラン', 'ko' => '식당'],
        'Saft' => ['en' => 'juice', 'es' => 'zumo', 'fr' => 'jus', 'ja' => 'ジュース', 'ko' => '주스'],
        'Sahne' => ['en' => 'cream', 'es' => 'nata', 'fr' => 'crème', 'ja' => 'クリーム', 'ko' => '크림'],
        'Salat' => ['en' => 'salad', 'es' => 'ensalada', 'fr' => 'salade', 'ja' => 'サラダ', 'ko' => '샐러드'],
        'Salz' => ['en' => 'salt', 'es' => 'sal', 'fr' => 'sel', 'ja' => '塩', 'ko' => '소금'],
        'Sandwich' => ['en' => 'sandwich', 'es' => 'sándwich', 'fr' => 'sandwich', 'ja' => 'サンドイッチ', 'ko' => '샌드위치'],
        'Schachtel' => ['en' => 'box', 'es' => 'caja', 'fr' => 'boîte', 'ja' => '箱', 'ko' => '상자'],
        'Schlange' => ['en' => 'queue', 'es' => 'cola', 'fr' => 'file', 'ja' => '列', 'ko' => '줄'],
        'Schnee' => ['en' => 'snow', 'es' => 'nieve', 'fr' => 'neige', 'ja' => '雪', 'ko' => '눈'],
        'Schokolade' => ['en' => 'chocolate', 'es' => 'chocolate', 'fr' => 'chocolat', 'ja' => 'チョコレート', 'ko' => '초콜릿'],
        'Schule' => ['en' => 'school', 'es' => 'escuela', 'fr' => 'école', 'ja' => '学校', 'ko' => '학교'],
        'Schwester' => ['en' => 'sister', 'es' => 'hermana', 'fr' => 'sœur', 'ja' => '姉妹', 'ko' => '자매'],
        'Serviette' => ['en' => 'napkin', 'es' => 'servilleta', 'fr' => 'serviette', 'ja' => 'ナプキン', 'ko' => '냅킨'],
        'Sommer' => ['en' => 'summer', 'es' => 'verano', 'fr' => 'été', 'ja' => '夏', 'ko' => '여름'],
        'Sonne' => ['en' => 'sun', 'es' => 'sol', 'fr' => 'soleil', 'ja' => '太陽', 'ko' => '해'],
        'Stadt' => ['en' => 'town', 'es' => 'ciudad', 'fr' => 'ville', 'ja' => '町', 'ko' => '도시'],
        'Straße' => ['en' => 'street', 'es' => 'calle', 'fr' => 'rue', 'ja' => '通り', 'ko' => '거리'],
        'Stuhl' => ['en' => 'chair', 'es' => 'silla', 'fr' => 'chaise', 'ja' => '椅子', 'ko' => '의자'],
        'Stunde' => ['en' => 'hour', 'es' => 'hora', 'fr' => 'heure', 'ja' => '時間', 'ko' => '시간'],
        'Stück' => ['en' => 'slice', 'es' => 'trozo', 'fr' => 'part', 'ja' => '一切れ', 'ko' => '한 조각'],
        'Supermarkt' => ['en' => 'supermarket', 'es' => 'supermercado', 'fr' => 'supermarché', 'ja' => 'スーパー', 'ko' => '슈퍼마켓'],
        'Suppe' => ['en' => 'soup', 'es' => 'sopa', 'fr' => 'soupe', 'ja' => 'スープ', 'ko' => '수프'],
        'Süden' => ['en' => 'south', 'es' => 'sur', 'fr' => 'sud', 'ja' => '南', 'ko' => '남쪽'],
        'Tag' => ['en' => 'day', 'es' => 'día', 'fr' => 'jour', 'ja' => '日', 'ko' => '날'],
        'Tee' => ['en' => 'tea', 'es' => 'té', 'fr' => 'thé', 'ja' => 'お茶', 'ko' => '차'],
        'Telefon' => ['en' => 'phone', 'es' => 'teléfono', 'fr' => 'téléphone', 'ja' => '電話', 'ko' => '전화'],
        'Teller' => ['en' => 'plate', 'es' => 'plato', 'fr' => 'assiette', 'ja' => 'お皿', 'ko' => '접시'],
        'Tisch' => ['en' => 'table', 'es' => 'mesa', 'fr' => 'table', 'ja' => 'テーブル', 'ko' => '탁자'],
        'Tomate' => ['en' => 'tomato', 'es' => 'tomate', 'fr' => 'tomate', 'ja' => 'トマト', 'ko' => '토마토'],
        'Torte' => ['en' => 'tart', 'es' => 'tarta', 'fr' => 'tarte', 'ja' => 'タルト', 'ko' => '타르트'],
        'Trauben' => ['en' => 'grapes', 'es' => 'uvas', 'fr' => 'raisin', 'ja' => 'ぶどう', 'ko' => '포도'],
        'Trinkgeld' => ['en' => 'tip', 'es' => 'propina', 'fr' => 'pourboire', 'ja' => 'チップ', 'ko' => '팁'],
        'Tüte' => ['en' => 'bag', 'es' => 'bolsa', 'fr' => 'sac', 'ja' => '袋', 'ko' => '봉투'],
        'Uhr' => ['en' => 'clock', 'es' => 'reloj', 'fr' => 'horloge', 'ja' => '時計', 'ko' => '시계'],
        'Vanille' => ['en' => 'vanilla', 'es' => 'vainilla', 'fr' => 'vanille', 'ja' => 'バニラ', 'ko' => '바닐라'],
        'Vater' => ['en' => 'father', 'es' => 'padre', 'fr' => 'père', 'ja' => '父', 'ko' => '아버지'],
        'Vorspeise' => ['en' => 'starter', 'es' => 'entrante', 'fr' => 'entrée', 'ja' => '前菜', 'ko' => '전채'],
        'Waage' => ['en' => 'scales', 'es' => 'balanza', 'fr' => 'balance', 'ja' => 'はかり', 'ko' => '저울'],
        'Wasser' => ['en' => 'water', 'es' => 'agua', 'fr' => 'eau', 'ja' => '水', 'ko' => '물'],
        'Wechselgeld' => ['en' => 'change', 'es' => 'cambio', 'fr' => 'monnaie', 'ja' => 'おつり', 'ko' => '거스름돈'],
        'Wein' => ['en' => 'wine', 'es' => 'vino', 'fr' => 'vin', 'ja' => 'ワイン', 'ko' => '와인'],
        'Wetter' => ['en' => 'weather', 'es' => 'tiempo', 'fr' => 'temps', 'ja' => '天気', 'ko' => '날씨'],
        'Wind' => ['en' => 'wind', 'es' => 'viento', 'fr' => 'vent', 'ja' => '風', 'ko' => '바람'],
        'Winter' => ['en' => 'winter', 'es' => 'invierno', 'fr' => 'hiver', 'ja' => '冬', 'ko' => '겨울'],
        'Woche' => ['en' => 'week', 'es' => 'semana', 'fr' => 'semaine', 'ja' => '週', 'ko' => '주'],
        'Wolke' => ['en' => 'cloud', 'es' => 'nube', 'fr' => 'nuage', 'ja' => '雲', 'ko' => '구름'],
        'Zucker' => ['en' => 'sugar', 'es' => 'azúcar', 'fr' => 'sucre', 'ja' => '砂糖', 'ko' => '설탕'],
        'Zutaten' => ['en' => 'ingredients', 'es' => 'ingredientes', 'fr' => 'ingrédients', 'ja' => '材料', 'ko' => '재료'],
        'Zwiebel' => ['en' => 'onion', 'es' => 'cebolla', 'fr' => 'oignon', 'ja' => '玉ねぎ', 'ko' => '양파'],
        'ab' => ['en' => 'off', 'es' => 'gira', 'fr' => 'tourne', 'ja' => '曲がって', 'ko' => '꺾어'],
        'abbiegen' => ['en' => 'turn', 'es' => 'girar', 'fr' => 'tourner', 'ja' => '曲がる', 'ko' => '돌다'],
        'aber' => ['en' => 'but', 'es' => 'pero', 'fr' => 'mais', 'ja' => 'しかし', 'ko' => '하지만'],
        'acht' => ['en' => 'eight', 'es' => 'ocho', 'fr' => 'huit', 'ja' => '八', 'ko' => '여덟'],
        'allergisch' => ['en' => 'allergic', 'es' => 'alérgico', 'fr' => 'allergique', 'ja' => 'アレルギーの', 'ko' => '알레르기가 있는'],
        'als' => ['en' => 'than', 'es' => 'que', 'fr' => 'que', 'ja' => 'より', 'ko' => '보다'],
        'alt' => ['en' => 'old', 'es' => 'viejo', 'fr' => 'vieux', 'ja' => '古い', 'ko' => '오래된'],
        'am' => ['en' => 'at the', 'es' => 'en el', 'fr' => 'au', 'ja' => 'に', 'ko' => '에'],
        'an' => ['en' => 'at', 'es' => 'en', 'fr' => 'à', 'ja' => 'で', 'ko' => '에서'],
        'anrufen' => ['en' => 'call', 'es' => 'llamar', 'fr' => 'appeler', 'ja' => '電話する', 'ko' => '전화하다'],
        'apfels' => ['en' => 'apple', 'es' => 'manzana', 'fr' => 'pomme', 'ja' => 'りんご', 'ko' => '사과'],
        'apfeltorte' => ['en' => 'apple tart', 'es' => 'tarta de manzana', 'fr' => 'tarte aux pommes', 'ja' => 'アップルタルト', 'ko' => '사과 타르트'],
        'auch' => ['en' => 'also', 'es' => 'también', 'fr' => 'aussi', 'ja' => 'も', 'ko' => '또한'],
        'auf' => ['en' => 'on', 'es' => 'sobre', 'fr' => 'sur', 'ja' => 'の上に', 'ko' => '위에'],
        'auf Wiedersehen' => ['en' => 'goodbye', 'es' => 'adiós', 'fr' => 'au revoir', 'ja' => 'さようなら', 'ko' => '안녕히 가세요'],
        'aus' => ['en' => 'from', 'es' => 'de', 'fr' => 'de', 'ja' => 'から', 'ko' => '에서'],
        'ausgezeichnet' => ['en' => 'excellent', 'es' => 'excelente', 'fr' => 'excellent', 'ja' => '素晴らしい', 'ko' => '훌륭한'],
        'ausgezeichneter' => ['en' => 'excellent', 'es' => 'excelente', 'fr' => 'excellent', 'ja' => '素晴らしい', 'ko' => '훌륭한'],
        'aß' => ['en' => 'ate', 'es' => 'comí', 'fr' => 'mangé', 'ja' => '食べた', 'ko' => '먹었다'],
        'bald' => ['en' => 'soon', 'es' => 'pronto', 'fr' => 'bientôt', 'ja' => 'すぐに', 'ko' => '곧'],
        'bar' => ['en' => 'cash', 'es' => 'efectivo', 'fr' => 'espèces', 'ja' => '現金', 'ko' => '현금'],
        'beim' => ['en' => 'at the', 'es' => 'en el', 'fr' => 'au', 'ja' => 'で', 'ko' => '에서'],
        'bereit' => ['en' => 'ready', 'es' => 'listo', 'fr' => 'prêt', 'ja' => '準備ができた', 'ko' => '준비된'],
        'beschäftigt' => ['en' => 'busy', 'es' => 'ocupado', 'fr' => 'occupé', 'ja' => '忙しい', 'ko' => '바쁜'],
        'besonders' => ['en' => 'especially', 'es' => 'sobre todo', 'fr' => 'surtout', 'ja' => '特に', 'ko' => '특히'],
        'besser' => ['en' => 'better', 'es' => 'mejor', 'fr' => 'meilleur', 'ja' => 'もっと良い', 'ko' => '더 좋은'],
        'bestellen' => ['en' => 'to order', 'es' => 'pedir', 'fr' => 'commander', 'ja' => '注文する', 'ko' => '주문하다'],
        'bestätigen' => ['en' => 'to confirm', 'es' => 'confirmar', 'fr' => 'confirmer', 'ja' => '確認する', 'ko' => '확인하다'],
        'bevorzuge' => ['en' => 'prefer', 'es' => 'prefiero', 'fr' => 'préfère', 'ja' => '好む', 'ko' => '선호하다'],
        'bezahle' => ['en' => 'pay', 'es' => 'pagar', 'fr' => 'payer', 'ja' => '払う', 'ko' => '지불하다'],
        'bezahlen' => ['en' => 'pay', 'es' => 'pagar', 'fr' => 'payer', 'ja' => '払う', 'ko' => '지불하다'],
        'bieg' => ['en' => 'turn', 'es' => 'gira', 'fr' => 'tourne', 'ja' => '曲がる', 'ko' => '돌다'],
        'biege' => ['en' => 'turn', 'es' => 'giro', 'fr' => 'tourne', 'ja' => '曲がる', 'ko' => '돌다'],
        'billig' => ['en' => 'cheap', 'es' => 'barato', 'fr' => 'bon marché', 'ja' => '安い', 'ko' => '싼'],
        'billige' => ['en' => 'cheap', 'es' => 'barato', 'fr' => 'bon marché', 'ja' => '安い', 'ko' => '싼'],
        'billiger' => ['en' => 'cheap', 'es' => 'barato', 'fr' => 'bon marché', 'ja' => '安い', 'ko' => '싼'],
        'billiges' => ['en' => 'cheap', 'es' => 'barato', 'fr' => 'bon marché', 'ja' => '安い', 'ko' => '싼'],
        'bin' => ['en' => 'am', 'es' => 'estoy', 'fr' => 'suis', 'ja' => 'です', 'ko' => '입니다'],
        'bisschen' => ['en' => 'bit', 'es' => 'poco', 'fr' => 'peu', 'ja' => '少し', 'ko' => '조금'],
        'bist' => ['en' => 'are', 'es' => 'estás', 'fr' => 'es', 'ja' => 'です', 'ko' => '입니다'],
        'bitte' => ['en' => 'please', 'es' => 'por favor', 'fr' => 's\'il vous plaît', 'ja' => 'お願いします', 'ko' => '부탁합니다'],
        'blau' => ['en' => 'blue', 'es' => 'azul', 'fr' => 'bleu', 'ja' => '青', 'ko' => '파란색'],
        'blauer' => ['en' => 'blue', 'es' => 'azul', 'fr' => 'bleu', 'ja' => '青', 'ko' => '파란색'],
        'brauche' => ['en' => 'need', 'es' => 'necesito', 'fr' => 'ai besoin', 'ja' => '必要', 'ko' => '필요하다'],
        'bringen' => ['en' => 'to bring', 'es' => 'traer', 'fr' => 'apporter', 'ja' => '持ってくる', 'ko' => '가져오다'],
        'bringen Sie mir' => ['en' => 'bring me', 'es' => 'tráigame', 'fr' => 'apportez-moi', 'ja' => '持ってきてください', 'ko' => '가져다주세요'],
        'danke' => ['en' => 'thank you', 'es' => 'gracias', 'fr' => 'merci', 'ja' => 'ありがとう', 'ko' => '감사합니다'],
        'dann' => ['en' => 'then', 'es' => 'entonces', 'fr' => 'ensuite', 'ja' => 'それから', 'ko' => '그러면'],
        'das' => ['en' => 'the', 'es' => 'el', 'fr' => 'le', 'ja' => 'その', 'ko' => '그'],
        'das ist' => ['en' => 'this is', 'es' => 'este es', 'fr' => 'c\'est', 'ja' => 'これは', 'ko' => '이분은'],
        'dein' => ['en' => 'your', 'es' => 'tu', 'fr' => 'ton', 'ja' => 'あなたの', 'ko' => '당신의'],
        'dem' => ['en' => 'the', 'es' => 'el', 'fr' => 'le', 'ja' => 'その', 'ko' => '그'],
        'den' => ['en' => 'the', 'es' => 'el', 'fr' => 'le', 'ja' => 'その', 'ko' => '그'],
        'denke' => ['en' => 'think', 'es' => 'creo', 'fr' => 'pense', 'ja' => '思う', 'ko' => '생각하다'],
        'der' => ['en' => 'the', 'es' => 'el', 'fr' => 'le', 'ja' => 'その', 'ko' => '그'],
        'des' => ['en' => 'of the', 'es' => 'del', 'fr' => 'du', 'ja' => 'の', 'ko' => '의'],
        'die' => ['en' => 'the', 'es' => 'la', 'fr' => 'la', 'ja' => 'その', 'ko' => '그'],
        'die Rechnung' => ['en' => 'the bill', 'es' => 'la cuenta', 'fr' => 'l\'addition', 'ja' => 'お会計', 'ko' => '계산서'],
        'diese' => ['en' => 'these', 'es' => 'estos', 'fr' => 'ces', 'ja' => 'これらの', 'ko' => '이것들'],
        'dieser' => ['en' => 'this', 'es' => 'este', 'fr' => 'ce', 'ja' => 'この', 'ko' => '이'],
        'dieses' => ['en' => 'this', 'es' => 'este', 'fr' => 'ce', 'ja' => 'この', 'ko' => '이'],
        'dir' => ['en' => 'you', 'es' => 'te', 'fr' => 'toi', 'ja' => 'あなたに', 'ko' => '당신에게'],
        'drei' => ['en' => 'three', 'es' => 'tres', 'fr' => 'trois', 'ja' => '三', 'ko' => '셋'],
        'du' => ['en' => 'you', 'es' => 'tú', 'fr' => 'tu', 'ja' => 'あなた', 'ko' => '당신'],
        'du bist' => ['en' => 'you are', 'es' => 'eres', 'fr' => 'tu es', 'ja' => 'です', 'ko' => '입니다'],
        'durstig' => ['en' => 'thirsty', 'es' => 'sediento', 'fr' => 'assoiffé', 'ja' => 'のどが渇いた', 'ko' => '목마른'],
        'ein' => ['en' => 'a', 'es' => 'un', 'fr' => 'un', 'ja' => '一つの', 'ko' => '하나의'],
        'ein Getränk' => ['en' => 'a drink', 'es' => 'una bebida', 'fr' => 'une boisson', 'ja' => '飲み物', 'ko' => '음료'],
        'ein bisschen' => ['en' => 'a little', 'es' => 'un poco', 'fr' => 'un peu', 'ja' => '少し', 'ko' => '조금'],
        'eine' => ['en' => 'a', 'es' => 'una', 'fr' => 'une', 'ja' => '一つの', 'ko' => '하나의'],
        'einem' => ['en' => 'a', 'es' => 'un', 'fr' => 'un', 'ja' => '一つの', 'ko' => '하나의'],
        'einen' => ['en' => 'a', 'es' => 'un', 'fr' => 'un', 'ja' => '一つの', 'ko' => '하나의'],
        'einer' => ['en' => 'a', 'es' => 'un', 'fr' => 'un', 'ja' => '一つの', 'ko' => '하나의'],
        'einfach' => ['en' => 'easy', 'es' => 'fácil', 'fr' => 'facile', 'ja' => '簡単', 'ko' => '쉬운'],
        'einfaches' => ['en' => 'easy', 'es' => 'fácil', 'fr' => 'facile', 'ja' => '簡単', 'ko' => '쉬운'],
        'eins' => ['en' => 'one', 'es' => 'uno', 'fr' => 'un', 'ja' => '一', 'ko' => '하나'],
        'eiswürfeln' => ['en' => 'ice cubes', 'es' => 'cubitos de hielo', 'fr' => 'glaçons', 'ja' => '氷', 'ko' => '얼음'],
        'enthält' => ['en' => 'contains', 'es' => 'contiene', 'fr' => 'contient', 'ja' => '含む', 'ko' => '들어있다'],
        'entschuldigen' => ['en' => 'excuse', 'es' => 'disculpe', 'fr' => 'excusez', 'ja' => 'すみません', 'ko' => '실례'],
        'entschuldigen Sie' => ['en' => 'excuse me', 'es' => 'disculpe', 'fr' => 'excusez-moi', 'ja' => 'すみません', 'ko' => '실례합니다'],
        'er' => ['en' => 'he', 'es' => 'él', 'fr' => 'il', 'ja' => '彼', 'ko' => '그'],
        'er ist' => ['en' => 'he is', 'es' => 'él es', 'fr' => 'il est', 'ja' => '彼は', 'ko' => '그는'],
        'es' => ['en' => 'it', 'es' => 'eso', 'fr' => 'ce', 'ja' => 'それ', 'ko' => '그것'],
        'es war' => ['en' => 'it was', 'es' => 'fue', 'fr' => 'c\'était', 'ja' => 'でした', 'ko' => '였습니다'],
        'esse' => ['en' => 'eat', 'es' => 'comer', 'fr' => 'manger', 'ja' => '食べる', 'ko' => '먹다'],
        'essen' => ['en' => 'eat', 'es' => 'comer', 'fr' => 'manger', 'ja' => '食べる', 'ko' => '먹다'],
        'etwas' => ['en' => 'some', 'es' => 'algo de', 'fr' => 'du', 'ja' => '少しの', 'ko' => '약간의'],
        'falsch' => ['en' => 'false', 'es' => 'falso', 'fr' => 'faux', 'ja' => '偽', 'ko' => '거짓'],
        'fertig' => ['en' => 'ready', 'es' => 'listo', 'fr' => 'prêt', 'ja' => 'できた', 'ko' => '준비된'],
        'finden' => ['en' => 'to find', 'es' => 'encontrar', 'fr' => 'trouver', 'ja' => '見つける', 'ko' => '발견하다'],
        'fisches' => ['en' => 'fish', 'es' => 'pescado', 'fr' => 'poisson', 'ja' => '魚', 'ko' => '생선'],
        'flaschen' => ['en' => 'bottles', 'es' => 'botellas', 'fr' => 'bouteilles', 'ja' => 'ボトル', 'ko' => '병'],
        'frei' => ['en' => 'free', 'es' => 'libre', 'fr' => 'libre', 'ja' => '暇', 'ko' => '한가한'],
        'freut' => ['en' => 'glad', 'es' => 'encanta', 'fr' => 'ravi', 'ja' => '嬉しい', 'ko' => '기쁘다'],
        'freut mich' => ['en' => 'nice to meet you', 'es' => 'encantado', 'fr' => 'enchanté', 'ja' => 'はじめまして', 'ko' => '반갑습니다'],
        'frisch' => ['en' => 'fresh', 'es' => 'fresco', 'fr' => 'frais', 'ja' => '新鮮', 'ko' => '신선한'],
        'frische' => ['en' => 'fresh', 'es' => 'fresco', 'fr' => 'frais', 'ja' => '新鮮', 'ko' => '신선한'],
        'frischer' => ['en' => 'fresh', 'es' => 'fresco', 'fr' => 'frais', 'ja' => '新鮮', 'ko' => '신선한'],
        'frisches' => ['en' => 'fresh', 'es' => 'fresco', 'fr' => 'frais', 'ja' => '新鮮', 'ko' => '신선한'],
        'froh' => ['en' => 'glad', 'es' => 'contento', 'fr' => 'content', 'ja' => '嬉しい', 'ko' => '기쁜'],
        'fühle' => ['en' => 'feel', 'es' => 'siento', 'fr' => 'sens', 'ja' => '感じる', 'ko' => '느끼다'],
        'fünf' => ['en' => 'five', 'es' => 'cinco', 'fr' => 'cinq', 'ja' => '五', 'ko' => '다섯'],
        'für' => ['en' => 'for', 'es' => 'para', 'fr' => 'pour', 'ja' => 'のために', 'ko' => '위해'],
        'geben Sie mir' => ['en' => 'give me', 'es' => 'deme', 'fr' => 'donnez-moi', 'ja' => 'ください', 'ko' => '주세요'],
        'gegen' => ['en' => 'against', 'es' => 'contra', 'fr' => 'contre', 'ja' => 'に対して', 'ko' => '에 대해'],
        'geh' => ['en' => 'walk', 'es' => 'caminar', 'fr' => 'marcher', 'ja' => '歩く', 'ko' => '걷다'],
        'gehe' => ['en' => 'walk', 'es' => 'caminar', 'fr' => 'marcher', 'ja' => '歩く', 'ko' => '걷다'],
        'gehen' => ['en' => 'walk', 'es' => 'caminar', 'fr' => 'marcher', 'ja' => '歩く', 'ko' => '걷다'],
        'geht' => ['en' => 'walk', 'es' => 'caminar', 'fr' => 'marcher', 'ja' => '歩く', 'ko' => '걷다'],
        'gelb' => ['en' => 'yellow', 'es' => 'amarillo', 'fr' => 'jaune', 'ja' => '黄色', 'ko' => '노란색'],
        'gelber' => ['en' => 'yellow', 'es' => 'amarillo', 'fr' => 'jaune', 'ja' => '黄色', 'ko' => '노란색'],
        'gelbes' => ['en' => 'yellow', 'es' => 'amarillo', 'fr' => 'jaune', 'ja' => '黄色', 'ko' => '노란색'],
        'genauso' => ['en' => 'just as', 'es' => 'igual', 'fr' => 'aussi', 'ja' => '同じくらい', 'ko' => '똑같이'],
        'genauso viel' => ['en' => 'as much', 'es' => 'tanto', 'fr' => 'autant', 'ja' => '同じくらい', 'ko' => '그만큼'],
        'genug' => ['en' => 'enough', 'es' => 'bastante', 'fr' => 'assez', 'ja' => '十分に', 'ko' => '충분히'],
        'geradeaus' => ['en' => 'straight', 'es' => 'recto', 'fr' => 'tout droit', 'ja' => 'まっすぐ', 'ko' => '똑바로'],
        'geschlossen' => ['en' => 'closed', 'es' => 'cerrado', 'fr' => 'fermé', 'ja' => '閉じた', 'ko' => '닫힌'],
        'gestern' => ['en' => 'yesterday', 'es' => 'ayer', 'fr' => 'hier', 'ja' => '昨日', 'ko' => '어제'],
        'getrennt' => ['en' => 'separately', 'es' => 'por separado', 'fr' => 'séparément', 'ja' => '別々に', 'ko' => '따로'],
        'getränk' => ['en' => 'drink', 'es' => 'bebida', 'fr' => 'boisson', 'ja' => '飲み物', 'ko' => '음료'],
        'glaube' => ['en' => 'believe', 'es' => 'creo', 'fr' => 'crois', 'ja' => '信じる', 'ko' => '믿다'],
        'gleich' => ['en' => 'same', 'es' => 'mismo', 'fr' => 'même', 'ja' => '同じ', 'ko' => '같은'],
        'gleiche' => ['en' => 'same', 'es' => 'mismo', 'fr' => 'même', 'ja' => '同じ', 'ko' => '같은'],
        'glücklich' => ['en' => 'happy', 'es' => 'feliz', 'fr' => 'heureux', 'ja' => '幸せ', 'ko' => '행복한'],
        'gnädige Frau' => ['en' => 'madam', 'es' => 'señora', 'fr' => 'madame', 'ja' => 'マダム', 'ko' => '부인'],
        'groß' => ['en' => 'big', 'es' => 'grande', 'fr' => 'grand', 'ja' => '大きい', 'ko' => '큰'],
        'große' => ['en' => 'big', 'es' => 'grande', 'fr' => 'grand', 'ja' => '大きい', 'ko' => '큰'],
        'großes' => ['en' => 'big', 'es' => 'grande', 'fr' => 'grand', 'ja' => '大きい', 'ko' => '큰'],
        'grün' => ['en' => 'green', 'es' => 'verde', 'fr' => 'vert', 'ja' => '緑', 'ko' => '초록색'],
        'grüner' => ['en' => 'green', 'es' => 'verde', 'fr' => 'vert', 'ja' => '緑', 'ko' => '초록색'],
        'grünes' => ['en' => 'green', 'es' => 'verde', 'fr' => 'vert', 'ja' => '緑', 'ko' => '초록색'],
        'gut' => ['en' => 'well', 'es' => 'bien', 'fr' => 'bien', 'ja' => '元気', 'ko' => '잘'],
        'guter' => ['en' => 'well', 'es' => 'bien', 'fr' => 'bien', 'ja' => '元気', 'ko' => '잘'],
        'gutes' => ['en' => 'well', 'es' => 'bien', 'fr' => 'bien', 'ja' => '元気', 'ko' => '잘'],
        'habe' => ['en' => 'have', 'es' => 'tengo', 'fr' => 'ai', 'ja' => '持つ', 'ko' => '가지다'],
        'hallo' => ['en' => 'hello', 'es' => 'hola', 'fr' => 'bonjour', 'ja' => 'こんにちは', 'ko' => '안녕하세요'],
        'harter' => ['en' => 'hard', 'es' => 'duro', 'fr' => 'dur', 'ja' => '硬い', 'ko' => '단단한'],
        'hause' => ['en' => 'house', 'es' => 'casa', 'fr' => 'maison', 'ja' => '家', 'ko' => '집'],
        'heiß' => ['en' => 'hot', 'es' => 'caliente', 'fr' => 'chaud', 'ja' => '熱い', 'ko' => '뜨거운'],
        'heißen' => ['en' => 'hot', 'es' => 'caliente', 'fr' => 'chaud', 'ja' => '熱い', 'ko' => '뜨거운'],
        'heißer' => ['en' => 'hot', 'es' => 'caliente', 'fr' => 'chaud', 'ja' => '熱い', 'ko' => '뜨거운'],
        'heute' => ['en' => 'today', 'es' => 'hoy', 'fr' => 'aujourd\'hui', 'ja' => '今日', 'ko' => '오늘'],
        'heute Abend' => ['en' => 'tonight', 'es' => 'esta noche', 'fr' => 'ce soir', 'ja' => '今夜', 'ko' => '오늘 밤'],
        'hier' => ['en' => 'here', 'es' => 'aquí', 'fr' => 'ici', 'ja' => 'ここ', 'ko' => '여기'],
        'hier ist' => ['en' => 'here is', 'es' => 'aquí está', 'fr' => 'voici', 'ja' => 'これが', 'ko' => '여기'],
        'hieressen' => ['en' => 'eat in', 'es' => 'tomar aquí', 'fr' => 'sur place', 'ja' => '店内で', 'ko' => '매장에서'],
        'hinten' => ['en' => 'behind', 'es' => 'detrás', 'fr' => 'derrière', 'ja' => '後ろに', 'ko' => '뒤에'],
        'hinter' => ['en' => 'behind', 'es' => 'detrás', 'fr' => 'derrière', 'ja' => '後ろ', 'ko' => '뒤에'],
        'hungrig' => ['en' => 'hungry', 'es' => 'hambriento', 'fr' => 'affamé', 'ja' => 'お腹がすいた', 'ko' => '배고픈'],
        'hähnchens' => ['en' => 'chicken', 'es' => 'pollo', 'fr' => 'poulet', 'ja' => '鶏肉', 'ko' => '닭고기'],
        'hübsch' => ['en' => 'pretty', 'es' => 'bonito', 'fr' => 'joli', 'ja' => 'かわいい', 'ko' => '예쁜'],
        'hübscher' => ['en' => 'pretty', 'es' => 'bonito', 'fr' => 'joli', 'ja' => 'かわいい', 'ko' => '예쁜'],
        'ich' => ['en' => 'I', 'es' => 'yo', 'fr' => 'je', 'ja' => '私', 'ko' => '나'],
        'ich aß' => ['en' => 'I ate', 'es' => 'comí', 'fr' => 'j\'ai mangé', 'ja' => '私は食べた', 'ko' => '나는 먹었다'],
        'ich bevorzuge' => ['en' => 'I prefer', 'es' => 'prefiero', 'fr' => 'je préfère', 'ja' => '私は好む', 'ko' => '나는 선호한다'],
        'ich bezahle' => ['en' => 'I pay', 'es' => 'pago', 'fr' => 'je paie', 'ja' => '私が払う', 'ko' => '제가 냅니다'],
        'ich bin' => ['en' => 'I am', 'es' => 'soy', 'fr' => 'je suis', 'ja' => 'です', 'ko' => '입니다'],
        'ich brauche' => ['en' => 'I need', 'es' => 'necesito', 'fr' => 'j\'ai besoin', 'ja' => '必要です', 'ko' => '필요합니다'],
        'ich denke' => ['en' => 'I think', 'es' => 'creo', 'fr' => 'je pense', 'ja' => '私は思う', 'ko' => '나는 생각한다'],
        'ich fühle mich' => ['en' => 'I feel', 'es' => 'me siento', 'fr' => 'je me sens', 'ja' => '私は感じる', 'ko' => '나는 느낍니다'],
        'ich gehe' => ['en' => 'I am going', 'es' => 'voy', 'fr' => 'je vais', 'ja' => '私は行く', 'ko' => '나는 갈 것이다'],
        'ich glaube' => ['en' => 'I believe', 'es' => 'creo que', 'fr' => 'je crois', 'ja' => '私は信じる', 'ko' => '나는 믿는다'],
        'ich habe' => ['en' => 'I have', 'es' => 'tengo', 'fr' => 'j\'ai', 'ja' => '私は持っている', 'ko' => '나는 가지고 있다'],
        'ich kann' => ['en' => 'I can', 'es' => 'puedo', 'fr' => 'je peux', 'ja' => '私はできる', 'ko' => '나는 할 수 있다'],
        'ich möchte' => ['en' => 'I would like', 'es' => 'quisiera', 'fr' => 'je voudrais', 'ja' => 'ください', 'ko' => '주세요'],
        'ich nehme' => ['en' => 'I\'ll have', 'es' => 'tomo', 'fr' => 'je prends', 'ja' => 'にします', 'ko' => '하겠습니다'],
        'ich sah' => ['en' => 'I saw', 'es' => 'vi', 'fr' => 'j\'ai vu', 'ja' => '私は見た', 'ko' => '나는 보았다'],
        'ich trank' => ['en' => 'I drank', 'es' => 'bebí', 'fr' => 'j\'ai bu', 'ja' => '私は飲んだ', 'ko' => '나는 마셨다'],
        'ich war' => ['en' => 'I was', 'es' => 'estaba', 'fr' => 'j\'étais', 'ja' => 'でした', 'ko' => '였습니다'],
        'ich will' => ['en' => 'I want', 'es' => 'quiero', 'fr' => 'je veux', 'ja' => 'たいです', 'ko' => '나는 원한다'],
        'ich wohne' => ['en' => 'I live', 'es' => 'vivo', 'fr' => 'j\'habite', 'ja' => '私は住んでいる', 'ko' => '나는 삽니다'],
        'im' => ['en' => 'in the', 'es' => 'en el', 'fr' => 'dans le', 'ja' => 'の中に', 'ko' => '안에'],
        'in' => ['en' => 'in', 'es' => 'en', 'fr' => 'dans', 'ja' => 'の中に', 'ko' => '안에'],
        'in bar' => ['en' => 'cash', 'es' => 'en efectivo', 'fr' => 'en espèces', 'ja' => '現金で', 'ko' => '현금으로'],
        'iss' => ['en' => 'eat', 'es' => 'come', 'fr' => 'mange', 'ja' => '食べる', 'ko' => '먹다'],
        'ist' => ['en' => 'is', 'es' => 'es', 'fr' => 'est', 'ja' => 'です', 'ko' => '입니다'],
        'ja' => ['en' => 'yes', 'es' => 'sí', 'fr' => 'oui', 'ja' => 'はい', 'ko' => '네'],
        'jahre' => ['en' => 'years', 'es' => 'años', 'fr' => 'ans', 'ja' => '歳', 'ko' => '살'],
        'jeder' => ['en' => 'each', 'es' => 'cada', 'fr' => 'chaque', 'ja' => 'それぞれの', 'ko' => '각각의'],
        'jedes' => ['en' => 'each', 'es' => 'cada', 'fr' => 'chaque', 'ja' => 'それぞれ', 'ko' => '각각'],
        'jene' => ['en' => 'those', 'es' => 'esos', 'fr' => 'ces', 'ja' => 'あれらの', 'ko' => '저것들'],
        'jener' => ['en' => 'that', 'es' => 'ese', 'fr' => 'cette', 'ja' => 'あの', 'ko' => '저'],
        'jenes' => ['en' => 'that', 'es' => 'ese', 'fr' => 'ce', 'ja' => 'あの', 'ko' => '저'],
        'jetzt' => ['en' => 'now', 'es' => 'ahora', 'fr' => 'maintenant', 'ja' => '今', 'ko' => '지금'],
        'kalt' => ['en' => 'cold', 'es' => 'frío', 'fr' => 'froid', 'ja' => '冷たい', 'ko' => '차가운'],
        'kalter' => ['en' => 'cold', 'es' => 'frío', 'fr' => 'froid', 'ja' => '冷たい', 'ko' => '차가운'],
        'kaltes' => ['en' => 'cold', 'es' => 'frío', 'fr' => 'froid', 'ja' => '冷たい', 'ko' => '차가운'],
        'kann' => ['en' => 'can', 'es' => 'puedo', 'fr' => 'peux', 'ja' => 'できる', 'ko' => '할 수 있다'],
        'kaufen' => ['en' => 'to buy', 'es' => 'comprar', 'fr' => 'acheter', 'ja' => '買う', 'ko' => '사다'],
        'keine' => ['en' => 'no', 'es' => 'ninguna', 'fr' => 'pas de', 'ja' => 'ない', 'ko' => '없는'],
        'kindermenü' => ['en' => 'kids menu', 'es' => 'menú infantil', 'fr' => 'menu enfant', 'ja' => 'キッズメニュー', 'ko' => '어린이 메뉴'],
        'klein' => ['en' => 'small', 'es' => 'pequeño', 'fr' => 'petit', 'ja' => '小さい', 'ko' => '작은'],
        'kleine' => ['en' => 'small', 'es' => 'pequeño', 'fr' => 'petit', 'ja' => '小さい', 'ko' => '작은'],
        'kommen' => ['en' => 'come', 'es' => 'venir', 'fr' => 'venir', 'ja' => '来る', 'ko' => '오다'],
        'kostet' => ['en' => 'costs', 'es' => 'cuesta', 'fr' => 'coûte', 'ja' => 'かかる', 'ko' => '입니다'],
        'krank' => ['en' => 'sick', 'es' => 'enfermo', 'fr' => 'malade', 'ja' => '病気', 'ko' => '아픈'],
        'kuchens' => ['en' => 'cake', 'es' => 'pastel', 'fr' => 'gâteau', 'ja' => 'ケーキ', 'ko' => '케이크'],
        'können' => ['en' => 'can', 'es' => 'puede', 'fr' => 'pouvez', 'ja' => 'できる', 'ko' => '할 수 있다'],
        'können Sie' => ['en' => 'can you', 'es' => 'puede usted', 'fr' => 'pouvez-vous', 'ja' => 'できますか', 'ko' => '주시겠어요'],
        'köstlich' => ['en' => 'delicious', 'es' => 'delicioso', 'fr' => 'délicieux', 'ja' => 'おいしい', 'ko' => '맛있는'],
        'köstlicher' => ['en' => 'delicious', 'es' => 'delicioso', 'fr' => 'délicieux', 'ja' => 'おいしい', 'ko' => '맛있는'],
        'langsam' => ['en' => 'slowly', 'es' => 'despacio', 'fr' => 'lentement', 'ja' => 'ゆっくり', 'ko' => '천천히'],
        'lass' => ['en' => 'let', 'es' => 'deja', 'fr' => 'laisse', 'ja' => 'させる', 'ko' => '하자'],
        'lass uns gehen' => ['en' => 'let\'s go', 'es' => 'vamos', 'fr' => 'allons-y', 'ja' => '行きましょう', 'ko' => '갑시다'],
        'leer' => ['en' => 'empty', 'es' => 'vacío', 'fr' => 'vide', 'ja' => '空', 'ko' => '빈'],
        'legen' => ['en' => 'to put', 'es' => 'poner', 'fr' => 'mettre', 'ja' => '入れる', 'ko' => '넣다'],
        'leicht' => ['en' => 'light', 'es' => 'ligero', 'fr' => 'léger', 'ja' => '軽い', 'ko' => '가벼운'],
        'lese' => ['en' => 'read', 'es' => 'leer', 'fr' => 'lire', 'ja' => '読む', 'ko' => '읽다'],
        'lesen' => ['en' => 'read', 'es' => 'leer', 'fr' => 'lire', 'ja' => '読む', 'ko' => '읽다'],
        'links' => ['en' => 'left', 'es' => 'izquierda', 'fr' => 'gauche', 'ja' => '左', 'ko' => '왼쪽'],
        'mehr' => ['en' => 'more', 'es' => 'más', 'fr' => 'plus', 'ja' => 'もっと', 'ko' => '더'],
        'mein' => ['en' => 'my', 'es' => 'mi', 'fr' => 'mon', 'ja' => '私の', 'ko' => '나의'],
        'mein Herr' => ['en' => 'sir', 'es' => 'señor', 'fr' => 'monsieur', 'ja' => 'ムッシュ', 'ko' => '선생님'],
        'meine' => ['en' => 'my', 'es' => 'mi', 'fr' => 'ma', 'ja' => '私の', 'ko' => '나의'],
        'meinem' => ['en' => 'my', 'es' => 'mi', 'fr' => 'mon', 'ja' => '私の', 'ko' => '나의'],
        'meinen' => ['en' => 'my', 'es' => 'mi', 'fr' => 'mon', 'ja' => '私の', 'ko' => '나의'],
        'meiner' => ['en' => 'my', 'es' => 'mi', 'fr' => 'mon', 'ja' => '私の', 'ko' => '나의'],
        'menüs' => ['en' => 'menu', 'es' => 'menú', 'fr' => 'menu', 'ja' => 'メニュー', 'ko' => '메뉴'],
        'mich' => ['en' => 'me', 'es' => 'me', 'fr' => 'moi', 'ja' => '私', 'ko' => '저'],
        'mir' => ['en' => 'me', 'es' => 'me', 'fr' => 'moi', 'ja' => '私に', 'ko' => '나에게'],
        'mit' => ['en' => 'with', 'es' => 'con', 'fr' => 'avec', 'ja' => 'と一緒に', 'ko' => '와 함께'],
        'mitnehmen' => ['en' => 'take away', 'es' => 'para llevar', 'fr' => 'à emporter', 'ja' => '持ち帰り', 'ko' => '포장'],
        'morgen' => ['en' => 'tomorrow', 'es' => 'mañana', 'fr' => 'demain', 'ja' => '明日', 'ko' => '내일'],
        'möchte' => ['en' => 'would like', 'es' => 'quisiera', 'fr' => 'voudrais', 'ja' => 'ほしい', 'ko' => '원하다'],
        'müde' => ['en' => 'tired', 'es' => 'cansado', 'fr' => 'fatigué', 'ja' => '疲れた', 'ko' => '피곤한'],
        'nach' => ['en' => 'after', 'es' => 'después', 'fr' => 'après', 'ja' => '後に', 'ko' => '후에'],
        'nah' => ['en' => 'near', 'es' => 'cerca', 'fr' => 'près', 'ja' => '近く', 'ko' => '가까이'],
        'natürlich' => ['en' => 'of course', 'es' => 'por supuesto', 'fr' => 'bien sûr', 'ja' => 'もちろん', 'ko' => '물론'],
        'nehme' => ['en' => 'take', 'es' => 'tomo', 'fr' => 'prends', 'ja' => 'にします', 'ko' => '하겠습니다'],
        'nein' => ['en' => 'no', 'es' => 'no', 'fr' => 'non', 'ja' => 'いいえ', 'ko' => '아니요'],
        'neu' => ['en' => 'new', 'es' => 'nuevo', 'fr' => 'nouveau', 'ja' => '新しい', 'ko' => '새로운'],
        'neues' => ['en' => 'new', 'es' => 'nuevo', 'fr' => 'nouveau', 'ja' => '新しい', 'ko' => '새로운'],
        'neun' => ['en' => 'nine', 'es' => 'nueve', 'fr' => 'neuf', 'ja' => '九', 'ko' => '아홉'],
        'noch' => ['en' => 'another', 'es' => 'otro', 'fr' => 'encore', 'ja' => 'もう', 'ko' => '더'],
        'noch ein' => ['en' => 'another', 'es' => 'otro', 'fr' => 'encore', 'ja' => 'もう一つの', 'ko' => '하나 더'],
        'nächste' => ['en' => 'next', 'es' => 'próximo', 'fr' => 'prochain', 'ja' => '次の', 'ko' => '다음'],
        'oder' => ['en' => 'or', 'es' => 'o', 'fr' => 'ou', 'ja' => 'または', 'ko' => '또는'],
        'offen' => ['en' => 'open', 'es' => 'abierto', 'fr' => 'ouvert', 'ja' => '開いた', 'ko' => '열린'],
        'ohne' => ['en' => 'without', 'es' => 'sin', 'fr' => 'sans', 'ja' => 'なし', 'ko' => '없이'],
        'okay' => ['en' => 'okay', 'es' => 'vale', 'fr' => 'd\'accord', 'ja' => 'いいよ', 'ko' => '좋아요'],
        'perfekt' => ['en' => 'perfect', 'es' => 'perfecto', 'fr' => 'parfait', 'ja' => '完璧', 'ko' => '완벽한'],
        'rechnung' => ['en' => 'bill', 'es' => 'cuenta', 'fr' => 'addition', 'ja' => '会計', 'ko' => '계산서'],
        'rechts' => ['en' => 'right', 'es' => 'derecha', 'fr' => 'droite', 'ja' => '右', 'ko' => '오른쪽'],
        'reises' => ['en' => 'rice', 'es' => 'arroz', 'fr' => 'riz', 'ja' => 'ご飯', 'ko' => '밥'],
        'reservieren' => ['en' => 'to book', 'es' => 'reservar', 'fr' => 'réserver', 'ja' => '予約する', 'ko' => '예약하다'],
        'rot' => ['en' => 'red', 'es' => 'rojo', 'fr' => 'rouge', 'ja' => '赤', 'ko' => '빨간색'],
        'rotes' => ['en' => 'red', 'es' => 'rojo', 'fr' => 'rouge', 'ja' => '赤', 'ko' => '빨간색'],
        'rotwein' => ['en' => 'red wine', 'es' => 'vino tinto', 'fr' => 'vin rouge', 'ja' => '赤ワイン', 'ko' => '레드와인'],
        'ruf' => ['en' => 'call', 'es' => 'llama', 'fr' => 'appelle', 'ja' => '電話して', 'ko' => '전화해'],
        'ruhig' => ['en' => 'calm', 'es' => 'tranquilo', 'fr' => 'calme', 'ja' => '落ち着いた', 'ko' => '차분한'],
        'sah' => ['en' => 'saw', 'es' => 'vi', 'fr' => 'vu', 'ja' => '見た', 'ko' => '보았다'],
        'salzig' => ['en' => 'salty', 'es' => 'salado', 'fr' => 'salé', 'ja' => 'しょっぱい', 'ko' => '짠'],
        'salziger' => ['en' => 'salty', 'es' => 'salado', 'fr' => 'salé', 'ja' => 'しょっぱい', 'ko' => '짠'],
        'sauber' => ['en' => 'clean', 'es' => 'limpio', 'fr' => 'propre', 'ja' => 'きれい', 'ko' => '깨끗한'],
        'sauberen' => ['en' => 'clean', 'es' => 'limpio', 'fr' => 'propre', 'ja' => 'きれい', 'ko' => '깨끗한'],
        'sauberes' => ['en' => 'clean', 'es' => 'limpio', 'fr' => 'propre', 'ja' => 'きれい', 'ko' => '깨끗한'],
        'scharf' => ['en' => 'spicy', 'es' => 'picante', 'fr' => 'épicé', 'ja' => '辛い', 'ko' => '매운'],
        'scharfes' => ['en' => 'spicy', 'es' => 'picante', 'fr' => 'épicé', 'ja' => '辛い', 'ko' => '매운'],
        'schauen' => ['en' => 'watch', 'es' => 'mirar', 'fr' => 'regarder', 'ja' => '見る', 'ko' => '보다'],
        'schlaf' => ['en' => 'sleep', 'es' => 'dormir', 'fr' => 'dormir', 'ja' => '眠る', 'ko' => '자다'],
        'schlafe' => ['en' => 'sleep', 'es' => 'dormir', 'fr' => 'dormir', 'ja' => '眠る', 'ko' => '자다'],
        'schlafen' => ['en' => 'sleep', 'es' => 'dormir', 'fr' => 'dormir', 'ja' => '眠る', 'ko' => '자다'],
        'schlechter' => ['en' => 'worse', 'es' => 'peor', 'fr' => 'pire', 'ja' => 'もっと悪い', 'ko' => '더 나쁜'],
        'schmutzig' => ['en' => 'dirty', 'es' => 'sucio', 'fr' => 'sale', 'ja' => '汚い', 'ko' => '더러운'],
        'schmutziger' => ['en' => 'dirty', 'es' => 'sucio', 'fr' => 'sale', 'ja' => '汚い', 'ko' => '더러운'],
        'schnell' => ['en' => 'fast', 'es' => 'rápido', 'fr' => 'rapide', 'ja' => '速い', 'ko' => '빠른'],
        'schneller' => ['en' => 'fast', 'es' => 'rápido', 'fr' => 'rapide', 'ja' => '速い', 'ko' => '빠른'],
        'schokoladeneis' => ['en' => 'chocolate ice cream', 'es' => 'helado de chocolate', 'fr' => 'glace au chocolat', 'ja' => 'チョコアイス', 'ko' => '초콜릿 아이스크림'],
        'schokoladenkuchen' => ['en' => 'chocolate cake', 'es' => 'pastel de chocolate', 'fr' => 'gâteau au chocolat', 'ja' => 'チョコレートケーキ', 'ko' => '초콜릿 케이크'],
        'schon' => ['en' => 'already', 'es' => 'ya', 'fr' => 'déjà', 'ja' => 'もう', 'ko' => '이미'],
        'schwarz' => ['en' => 'black', 'es' => 'negro', 'fr' => 'noir', 'ja' => '黒', 'ko' => '검은색'],
        'schwarzer' => ['en' => 'black', 'es' => 'negro', 'fr' => 'noir', 'ja' => '黒', 'ko' => '검은색'],
        'schwarzes' => ['en' => 'black', 'es' => 'negro', 'fr' => 'noir', 'ja' => '黒', 'ko' => '검은색'],
        'schwer' => ['en' => 'hard', 'es' => 'difícil', 'fr' => 'difficile', 'ja' => '難しい', 'ko' => '어려운'],
        'schwere' => ['en' => 'hard', 'es' => 'difícil', 'fr' => 'difficile', 'ja' => '難しい', 'ko' => '어려운'],
        'schwerer' => ['en' => 'hard', 'es' => 'difícil', 'fr' => 'difficile', 'ja' => '難しい', 'ko' => '어려운'],
        'schön' => ['en' => 'beautiful', 'es' => 'hermoso', 'fr' => 'beau', 'ja' => '美しい', 'ko' => '아름다운'],
        'schöner' => ['en' => 'beautiful', 'es' => 'hermoso', 'fr' => 'beau', 'ja' => '美しい', 'ko' => '아름다운'],
        'schönes' => ['en' => 'beautiful', 'es' => 'hermoso', 'fr' => 'beau', 'ja' => '美しい', 'ko' => '아름다운'],
        'sechs' => ['en' => 'six', 'es' => 'seis', 'fr' => 'six', 'ja' => '六', 'ko' => '여섯'],
        'sehr' => ['en' => 'very', 'es' => 'muy', 'fr' => 'très', 'ja' => 'とても', 'ko' => '매우'],
        'sie' => ['en' => 'she', 'es' => 'ella', 'fr' => 'elle', 'ja' => '彼女', 'ko' => '그녀'],
        'sie ist' => ['en' => 'she is', 'es' => 'ella es', 'fr' => 'elle est', 'ja' => '彼女は', 'ko' => '그녀는'],
        'sieben' => ['en' => 'seven', 'es' => 'siete', 'fr' => 'sept', 'ja' => '七', 'ko' => '일곱'],
        'sind' => ['en' => 'are', 'es' => 'son', 'fr' => 'sont', 'ja' => 'です', 'ko' => '입니다'],
        'sprechen' => ['en' => 'speak', 'es' => 'hablar', 'fr' => 'parler', 'ja' => '話す', 'ko' => '말하다'],
        'sprich' => ['en' => 'speak', 'es' => 'habla', 'fr' => 'parle', 'ja' => '話す', 'ko' => '말하다'],
        'später' => ['en' => 'later', 'es' => 'más tarde', 'fr' => 'plus tard', 'ja' => '後で', 'ko' => '나중에'],
        'stornieren' => ['en' => 'to cancel', 'es' => 'cancelar', 'fr' => 'annuler', 'ja' => 'キャンセルする', 'ko' => '취소하다'],
        'suchen' => ['en' => 'to look for', 'es' => 'buscar', 'fr' => 'chercher', 'ja' => '探す', 'ko' => '찾다'],
        'süß' => ['en' => 'sweet', 'es' => 'dulce', 'fr' => 'sucré', 'ja' => '甘い', 'ko' => '단'],
        'süßer' => ['en' => 'sweet', 'es' => 'dulce', 'fr' => 'sucré', 'ja' => '甘い', 'ko' => '단'],
        'süßes' => ['en' => 'sweet', 'es' => 'dulce', 'fr' => 'sucré', 'ja' => '甘い', 'ko' => '단'],
        'tages' => ['en' => 'day', 'es' => 'día', 'fr' => 'jour', 'ja' => '日', 'ko' => '날'],
        'teilen' => ['en' => 'to share', 'es' => 'compartir', 'fr' => 'partager', 'ja' => '分ける', 'ko' => '나누다'],
        'teuer' => ['en' => 'expensive', 'es' => 'caro', 'fr' => 'cher', 'ja' => '高い', 'ko' => '비싼'],
        'tragen' => ['en' => 'to carry', 'es' => 'llevar', 'fr' => 'porter', 'ja' => '運ぶ', 'ko' => '나르다'],
        'trank' => ['en' => 'drank', 'es' => 'bebí', 'fr' => 'bu', 'ja' => '飲んだ', 'ko' => '마셨다'],
        'traurig' => ['en' => 'sad', 'es' => 'triste', 'fr' => 'triste', 'ja' => '悲しい', 'ko' => '슬픈'],
        'trinke' => ['en' => 'drink', 'es' => 'beber', 'fr' => 'boire', 'ja' => '飲む', 'ko' => '마시다'],
        'trinken' => ['en' => 'drink', 'es' => 'beber', 'fr' => 'boire', 'ja' => '飲む', 'ko' => '마시다'],
        'um' => ['en' => 'at', 'es' => 'a', 'fr' => 'à', 'ja' => 'に', 'ko' => '에'],
        'und' => ['en' => 'and', 'es' => 'y', 'fr' => 'et', 'ja' => 'と', 'ko' => '그리고'],
        'uns' => ['en' => 'us', 'es' => 'nos', 'fr' => 'nous', 'ja' => '私たち', 'ko' => '우리'],
        'unter' => ['en' => 'under', 'es' => 'debajo', 'fr' => 'sous', 'ja' => 'の下に', 'ko' => '아래에'],
        'vanilleeis' => ['en' => 'vanilla ice cream', 'es' => 'helado de vainilla', 'fr' => 'glace à la vanille', 'ja' => 'バニラアイス', 'ko' => '바닐라 아이스크림'],
        'vegetarisch' => ['en' => 'vegetarian', 'es' => 'vegetariano', 'fr' => 'végétarien', 'ja' => 'ベジタリアン', 'ko' => '채식주의자'],
        'vergleichen' => ['en' => 'to compare', 'es' => 'comparar', 'fr' => 'comparer', 'ja' => '比べる', 'ko' => '비교하다'],
        'vermeiden' => ['en' => 'to avoid', 'es' => 'evitar', 'fr' => 'éviter', 'ja' => '避ける', 'ko' => '피하다'],
        'viel' => ['en' => 'much', 'es' => 'mucho', 'fr' => 'beaucoup', 'ja' => 'たくさん', 'ko' => '많이'],
        'viele' => ['en' => 'many', 'es' => 'muchos', 'fr' => 'beaucoup', 'ja' => '多くの', 'ko' => '많은'],
        'vielleicht' => ['en' => 'maybe', 'es' => 'quizás', 'fr' => 'peut-être', 'ja' => 'たぶん', 'ko' => '아마도'],
        'vier' => ['en' => 'four', 'es' => 'cuatro', 'fr' => 'quatre', 'ja' => '四', 'ko' => '넷'],
        'voll' => ['en' => 'full', 'es' => 'lleno', 'fr' => 'plein', 'ja' => 'いっぱい', 'ko' => '가득한'],
        'voller' => ['en' => 'full', 'es' => 'lleno', 'fr' => 'plein', 'ja' => 'いっぱい', 'ko' => '가득한'],
        'von' => ['en' => 'of', 'es' => 'de', 'fr' => 'de', 'ja' => 'の', 'ko' => '의'],
        'vor' => ['en' => 'before', 'es' => 'antes', 'fr' => 'avant', 'ja' => '前に', 'ko' => '전에'],
        'vorne' => ['en' => 'in front', 'es' => 'delante', 'fr' => 'devant', 'ja' => '前に', 'ko' => '앞에'],
        'wahr' => ['en' => 'true', 'es' => 'verdadero', 'fr' => 'vrai', 'ja' => '本当', 'ko' => '사실'],
        'wann' => ['en' => 'when', 'es' => 'cuándo', 'fr' => 'quand', 'ja' => 'いつ', 'ko' => '언제'],
        'war' => ['en' => 'was', 'es' => 'era', 'fr' => 'était', 'ja' => 'だった', 'ko' => '였다'],
        'warm' => ['en' => 'warm', 'es' => 'cálido', 'fr' => 'doux', 'ja' => '暖かい', 'ko' => '따뜻한'],
        'warme' => ['en' => 'warm', 'es' => 'cálido', 'fr' => 'doux', 'ja' => '暖かい', 'ko' => '따뜻한'],
        'warte' => ['en' => 'wait', 'es' => 'esperar', 'fr' => 'attendre', 'ja' => '待つ', 'ko' => '기다리다'],
        'warten' => ['en' => 'wait', 'es' => 'esperar', 'fr' => 'attendre', 'ja' => '待つ', 'ko' => '기다리다'],
        'warum' => ['en' => 'why', 'es' => 'por qué', 'fr' => 'pourquoi', 'ja' => 'なぜ', 'ko' => '왜'],
        'weil' => ['en' => 'because', 'es' => 'porque', 'fr' => 'parce que', 'ja' => 'なぜなら', 'ko' => '왜냐하면'],
        'weit' => ['en' => 'far', 'es' => 'lejos', 'fr' => 'loin', 'ja' => '遠く', 'ko' => '멀리'],
        'weiter' => ['en' => 'far', 'es' => 'lejos', 'fr' => 'loin', 'ja' => '遠く', 'ko' => '멀리'],
        'weitergehen' => ['en' => 'continue', 'es' => 'continuar', 'fr' => 'continuer', 'ja' => '続ける', 'ko' => '계속하다'],
        'weiß' => ['en' => 'white', 'es' => 'blanco', 'fr' => 'blanc', 'ja' => '白', 'ko' => '하얀색'],
        'weißer' => ['en' => 'white', 'es' => 'blanco', 'fr' => 'blanc', 'ja' => '白', 'ko' => '하얀색'],
        'weißes' => ['en' => 'white', 'es' => 'blanco', 'fr' => 'blanc', 'ja' => '白', 'ko' => '하얀색'],
        'welcher' => ['en' => 'which', 'es' => 'cuál', 'fr' => 'quel', 'ja' => 'どれ', 'ko' => '어느'],
        'weniger' => ['en' => 'less', 'es' => 'menos', 'fr' => 'moins', 'ja' => 'より少ない', 'ko' => '덜'],
        'wer' => ['en' => 'who', 'es' => 'quién', 'fr' => 'qui', 'ja' => '誰', 'ko' => '누구'],
        'wie' => ['en' => 'like', 'es' => 'como', 'fr' => 'comme', 'ja' => 'のように', 'ko' => '처럼'],
        'wie geht es dir' => ['en' => 'how are you', 'es' => 'cómo estás', 'fr' => 'comment ça va', 'ja' => 'お元気ですか', 'ko' => '어떻게 지내세요'],
        'wie viele' => ['en' => 'how many', 'es' => 'cuántos', 'fr' => 'combien', 'ja' => 'いくつ', 'ko' => '몇 개'],
        'wiegen' => ['en' => 'to weigh', 'es' => 'pesar', 'fr' => 'peser', 'ja' => '量る', 'ko' => '무게를 재다'],
        'will' => ['en' => 'want', 'es' => 'quiero', 'fr' => 'veux', 'ja' => 'したい', 'ko' => '원하다'],
        'willkommen' => ['en' => 'welcome', 'es' => 'bienvenido', 'fr' => 'bienvenue', 'ja' => 'ようこそ', 'ko' => '환영합니다'],
        'wirklich' => ['en' => 'really', 'es' => 'de verdad', 'fr' => 'vraiment', 'ja' => '本当に', 'ko' => '정말'],
        'wo' => ['en' => 'where', 'es' => 'dónde', 'fr' => 'où', 'ja' => 'どこ', 'ko' => '어디'],
        'wo ist' => ['en' => 'where is', 'es' => 'dónde está', 'fr' => 'où est', 'ja' => 'どこですか', 'ko' => '어디입니까'],
        'wohne' => ['en' => 'live', 'es' => 'vivo', 'fr' => 'habite', 'ja' => '住む', 'ko' => '살다'],
        'wählen' => ['en' => 'to choose', 'es' => 'elegir', 'fr' => 'choisir', 'ja' => '選ぶ', 'ko' => '고르다'],
        'zehn' => ['en' => 'ten', 'es' => 'diez', 'fr' => 'dix', 'ja' => '十', 'ko' => '열'],
        'zu' => ['en' => 'to', 'es' => 'a', 'fr' => 'à', 'ja' => 'へ', 'ko' => '로'],
        'zu viel' => ['en' => 'too much', 'es' => 'demasiado', 'fr' => 'trop', 'ja' => 'すぎます', 'ko' => '너무'],
        'zum' => ['en' => 'to the', 'es' => 'al', 'fr' => 'au', 'ja' => 'へ', 'ko' => '로'],
        'zum Hieressen' => ['en' => 'eat in', 'es' => 'para tomar aquí', 'fr' => 'sur place', 'ja' => '店内で', 'ko' => '매장에서'],
        'zum Mitnehmen' => ['en' => 'takeaway', 'es' => 'para llevar', 'fr' => 'à emporter', 'ja' => '持ち帰り', 'ko' => '포장'],
        'zur' => ['en' => 'to the', 'es' => 'a la', 'fr' => 'à la', 'ja' => 'へ', 'ko' => '로'],
        'zurück' => ['en' => 'back', 'es' => 'de vuelta', 'fr' => 'en retour', 'ja' => '戻って', 'ko' => '다시'],
        'zurückrufen' => ['en' => 'call back', 'es' => 'devolver la llamada', 'fr' => 'rappeler', 'ja' => '折り返す', 'ko' => '다시 전화하다'],
        'zusammen' => ['en' => 'together', 'es' => 'juntos', 'fr' => 'ensemble', 'ja' => '一緒に', 'ko' => '함께'],
        'zwei' => ['en' => 'two', 'es' => 'dos', 'fr' => 'deux', 'ja' => '二', 'ko' => '둘'],
        'zwei Bücher' => ['en' => 'two books', 'es' => 'dos libros', 'fr' => 'deux livres', 'ja' => '二冊の本', 'ko' => '책 두 권'],
        'überquere' => ['en' => 'cross', 'es' => 'cruzar', 'fr' => 'traverser', 'ja' => '渡る', 'ko' => '건너다'],
        'überqueren' => ['en' => 'cross', 'es' => 'cruzar', 'fr' => 'traverser', 'ja' => '渡る', 'ko' => '건너다'],
    ];

    /** Native languages a learner can take a German course in. */
    private const LANGS = ['en', 'es', 'fr', 'ja', 'ko'];

    /**
     * The ['i18n' => [...]] map for a German word, ready to store in exercise
     * data. Falls back to the word itself if it isn't in the dictionary yet.
     *
     * @return array{i18n: array<string, string>}
     */
    public static function hint(string $german): array
    {
        return ['i18n' => self::meanings($german)];
    }

    /**
     * @return array<string, string>
     */
    public static function meanings(string $german): array
    {
        $key = mb_strtolower(trim($german));

        foreach (self::WORDS as $word => $translations) {
            if (mb_strtolower($word) === $key) {
                return $translations;
            }
        }

        // Not in the dictionary: show the German word itself to every learner.
        return array_fill_keys(self::LANGS, $german);
    }

    /** Every German word the dictionary knows (used for wrong-answer options). */
    public static function all(): array
    {
        return array_keys(self::WORDS);
    }

    public static function knows(string $german): bool
    {
        $key = mb_strtolower(trim($german));

        foreach (array_keys(self::WORDS) as $word) {
            if (mb_strtolower($word) === $key) {
                return true;
            }
        }

        return false;
    }
}
