<?php

namespace Database\Seeders\Support;

/**
 * German word => its meaning in every native language a German course supports
 * (English, Spanish, French, Japanese, Korean).
 *
 * German is the LEARNING language here, so exercise content (words, phrases,
 * tiles) is authored in German, and only the hints/prompts are shown in the
 * learner's own language. Nothing user-facing is hardcoded: seeders pull from
 * here and store the result as an ['i18n' => [...]] map, which
 * ExerciseContentService resolves per request.
 *
 * This mirrors EnglishVocabulary and FrenchVocabulary exactly, only the language
 * roles are swapped. Add a word here once and every unit can use it.
 */
class GermanVocabulary
{
    private const WORDS = [
        'Abend' => ['en' => 'evening', 'es' => 'tarde', 'fr' => 'soir', 'ja' => '夕方', 'ko' => '저녁', 'tr' => 'akşam', 'ru' => 'вечер', 'ar' => 'مساء', 'az' => 'axşam'],
        'Allergie' => ['en' => 'allergy', 'es' => 'alergia', 'fr' => 'allergie', 'ja' => 'アレルギー', 'ko' => '알레르기', 'tr' => 'alerji', 'ru' => 'аллергия', 'ar' => 'حساسية', 'az' => 'allergiya'],
        'Alter' => ['en' => 'age', 'es' => 'edad', 'fr' => 'âge', 'ja' => '年齢', 'ko' => '나이', 'tr' => 'yaş', 'ru' => 'возраст', 'ar' => 'عمر', 'az' => 'yaş'],
        'Apfel' => ['en' => 'apple', 'es' => 'manzana', 'fr' => 'pomme', 'ja' => 'りんご', 'ko' => '사과', 'tr' => 'elma', 'ru' => 'яблоко', 'ar' => 'تفاحة', 'az' => 'alma'],
        'Arzt' => ['en' => 'doctor', 'es' => 'médico', 'fr' => 'médecin', 'ja' => '医者', 'ko' => '의사', 'tr' => 'doktor', 'ru' => 'врач', 'ar' => 'طبيب', 'az' => 'həkim'],
        'Bahnhof' => ['en' => 'station', 'es' => 'estación', 'fr' => 'gare', 'ja' => '駅', 'ko' => '역', 'tr' => 'istasyon', 'ru' => 'станция', 'ar' => 'محطة', 'az' => 'stansiya'],
        'Banane' => ['en' => 'banana', 'es' => 'plátano', 'fr' => 'banane', 'ja' => 'バナナ', 'ko' => '바나나', 'tr' => 'muz', 'ru' => 'банан', 'ar' => 'موزة', 'az' => 'banan'],
        'Bestellung' => ['en' => 'order', 'es' => 'pedido', 'fr' => 'commande', 'ja' => '注文', 'ko' => '주문', 'tr' => 'sipariş', 'ru' => 'заказ', 'ar' => 'طلب', 'az' => 'sifariş'],
        'Bier' => ['en' => 'beer', 'es' => 'cerveza', 'fr' => 'bière', 'ja' => 'ビール', 'ko' => '맥주', 'tr' => 'bira', 'ru' => 'пиво', 'ar' => 'بيرة', 'az' => 'pivə'],
        'Brot' => ['en' => 'bread', 'es' => 'pan', 'fr' => 'pain', 'ja' => 'パン', 'ko' => '빵', 'tr' => 'ekmek', 'ru' => 'хлеб', 'ar' => 'خبز', 'az' => 'çörək'],
        'Bruder' => ['en' => 'brother', 'es' => 'hermano', 'fr' => 'frère', 'ja' => '兄弟', 'ko' => '형제', 'tr' => 'erkek kardeş', 'ru' => 'брат', 'ar' => 'أخ', 'az' => 'qardaş'],
        'Buch' => ['en' => 'book', 'es' => 'libro', 'fr' => 'livre', 'ja' => '本', 'ko' => '책', 'tr' => 'kitap', 'ru' => 'книга', 'ar' => 'كتاب', 'az' => 'kitab'],
        'Burger' => ['en' => 'burger', 'es' => 'hamburguesa', 'fr' => 'hamburger', 'ja' => 'ハンバーガー', 'ko' => '햄버거', 'tr' => 'hamburger', 'ru' => 'бургер', 'ar' => 'برجر', 'az' => 'burger'],
        'Butter' => ['en' => 'butter', 'es' => 'mantequilla', 'fr' => 'beurre', 'ja' => 'バター', 'ko' => '버터', 'tr' => 'tereyağı', 'ru' => 'масло', 'ar' => 'زبدة', 'az' => 'kərə yağı'],
        'Bäckerei' => ['en' => 'bakery', 'es' => 'panadería', 'fr' => 'boulangerie', 'ja' => 'パン屋', 'ko' => '빵집', 'tr' => 'fırın', 'ru' => 'пекарня', 'ar' => 'مخبز', 'az' => 'çörəkxana'],
        'Bücher' => ['en' => 'books', 'es' => 'libros', 'fr' => 'livres', 'ja' => '本', 'ko' => '책들', 'tr' => 'kitaplar', 'ru' => 'книги', 'ar' => 'كتب', 'az' => 'kitablar'],
        'Dienstag' => ['en' => 'Tuesday', 'es' => 'martes', 'fr' => 'mardi', 'ja' => '火曜日', 'ko' => '화요일', 'tr' => 'salı', 'ru' => 'вторник', 'ar' => 'الثلاثاء', 'az' => 'çərşənbə axşamı'],
        'Diät' => ['en' => 'diet', 'es' => 'dieta', 'fr' => 'régime', 'ja' => '食事制限', 'ko' => '식단', 'tr' => 'beslenme', 'ru' => 'диета', 'ar' => 'حمية', 'az' => 'pəhriz'],
        'Dollar' => ['en' => 'dollars', 'es' => 'dólares', 'fr' => 'dollars', 'ja' => 'ドル', 'ko' => '달러', 'tr' => 'dolar', 'ru' => 'долларов', 'ar' => 'دولارات', 'az' => 'dollar'],
        'Dorf' => ['en' => 'village', 'es' => 'pueblo', 'fr' => 'village', 'ja' => '村', 'ko' => '마을', 'tr' => 'köy', 'ru' => 'деревня', 'ar' => 'قرية', 'az' => 'kənd'],
        'Ei' => ['en' => 'egg', 'es' => 'huevo', 'fr' => 'œuf', 'ja' => '卵', 'ko' => '계란', 'tr' => 'yumurta', 'ru' => 'яйцо', 'ar' => 'بيضة', 'az' => 'yumurta'],
        'Eier' => ['en' => 'eggs', 'es' => 'huevos', 'fr' => 'œufs', 'ja' => '卵', 'ko' => '계란', 'tr' => 'yumurta', 'ru' => 'яйца', 'ar' => 'بيض', 'az' => 'yumurtalar'],
        'Einkaufswagen' => ['en' => 'trolley', 'es' => 'carrito', 'fr' => 'chariot', 'ja' => 'カート', 'ko' => '카트', 'tr' => 'araba', 'ru' => 'тележка', 'ar' => 'عربة', 'az' => 'araba'],
        'Eis' => ['en' => 'ice cream', 'es' => 'helado', 'fr' => 'glace', 'ja' => 'アイスクリーム', 'ko' => '아이스크림', 'tr' => 'dondurma', 'ru' => 'мороженое', 'ar' => 'آيس كريم', 'az' => 'dondurma'],
        'Eiswürfel' => ['en' => 'ice', 'es' => 'hielo', 'fr' => 'glaçons', 'ja' => '氷', 'ko' => '얼음', 'tr' => 'buz', 'ru' => 'лёд', 'ar' => 'الثلج', 'az' => 'buz'],
        'Entschuldigung' => ['en' => 'sorry', 'es' => 'lo siento', 'fr' => 'désolé', 'ja' => 'ごめんなさい', 'ko' => '죄송합니다', 'tr' => 'üzgünüm', 'ru' => 'извините', 'ar' => 'آسف', 'az' => 'bağışlayın'],
        'Erdbeere' => ['en' => 'strawberry', 'es' => 'fresa', 'fr' => 'fraise', 'ja' => 'いちご', 'ko' => '딸기', 'tr' => 'çilek', 'ru' => 'клубничный', 'ar' => 'فراولة', 'az' => 'çiyələk'],
        'Film' => ['en' => 'film', 'es' => 'película', 'fr' => 'film', 'ja' => '映画', 'ko' => '영화', 'tr' => 'film', 'ru' => 'фильм', 'ar' => 'فيلم', 'az' => 'film'],
        'Fisch' => ['en' => 'fish', 'es' => 'pescado', 'fr' => 'poisson', 'ja' => '魚', 'ko' => '생선', 'tr' => 'balık', 'ru' => 'рыба', 'ar' => 'سمك', 'az' => 'balıq'],
        'Flasche' => ['en' => 'bottle', 'es' => 'botella', 'fr' => 'bouteille', 'ja' => 'ボトル', 'ko' => '병', 'tr' => 'şişe', 'ru' => 'бутылка', 'ar' => 'زجاجة', 'az' => 'şüşə'],
        'Fleisch' => ['en' => 'meat', 'es' => 'carne', 'fr' => 'viande', 'ja' => '肉', 'ko' => '고기', 'tr' => 'et', 'ru' => 'мясо', 'ar' => 'لحم', 'az' => 'ət'],
        'Freund' => ['en' => 'friend', 'es' => 'amigo', 'fr' => 'ami', 'ja' => '友達', 'ko' => '친구', 'tr' => 'arkadaş', 'ru' => 'друг', 'ar' => 'صديق', 'az' => 'dost'],
        'Früchte' => ['en' => 'fruits', 'es' => 'frutas', 'fr' => 'fruits', 'ja' => '果物', 'ko' => '과일', 'tr' => 'meyveler', 'ru' => 'фрукты', 'ar' => 'فواكه', 'az' => 'meyvələr'],
        'Frühling' => ['en' => 'spring', 'es' => 'primavera', 'fr' => 'printemps', 'ja' => '春', 'ko' => '봄', 'tr' => 'ilkbahar', 'ru' => 'весна', 'ar' => 'ربيع', 'az' => 'yaz'],
        'Gabel' => ['en' => 'fork', 'es' => 'tenedor', 'fr' => 'fourchette', 'ja' => 'フォーク', 'ko' => '포크', 'tr' => 'çatal', 'ru' => 'вилка', 'ar' => 'شوكة', 'az' => 'çəngəl'],
        'Geld' => ['en' => 'money', 'es' => 'dinero', 'fr' => 'argent', 'ja' => 'お金', 'ko' => '돈', 'tr' => 'para', 'ru' => 'деньги', 'ar' => 'نقود', 'az' => 'pul'],
        'Gemüse' => ['en' => 'vegetables', 'es' => 'verduras', 'fr' => 'légumes', 'ja' => '野菜', 'ko' => '채소', 'tr' => 'sebze', 'ru' => 'овощи', 'ar' => 'خضروات', 'az' => 'tərəvəzlər'],
        'Gericht' => ['en' => 'dish', 'es' => 'plato', 'fr' => 'plat', 'ja' => '料理', 'ko' => '요리', 'tr' => 'yemek', 'ru' => 'блюдо', 'ar' => 'طبق', 'az' => 'yemək'],
        'Gesamt' => ['en' => 'total', 'es' => 'total', 'fr' => 'total', 'ja' => '合計', 'ko' => '총액', 'tr' => 'toplam', 'ru' => 'итого', 'ar' => 'المجموع', 'az' => 'cəmi'],
        'Geschmack' => ['en' => 'taste', 'es' => 'sabor', 'fr' => 'goût', 'ja' => '味', 'ko' => '맛', 'tr' => 'tat', 'ru' => 'вкус', 'ar' => 'مذاق', 'az' => 'dad'],
        'Geschäft' => ['en' => 'shop', 'es' => 'tienda', 'fr' => 'magasin', 'ja' => '店', 'ko' => '가게', 'tr' => 'dükkan', 'ru' => 'магазин', 'ar' => 'متجر', 'az' => 'mağaza'],
        'Glas' => ['en' => 'glass', 'es' => 'vaso', 'fr' => 'verre', 'ja' => 'グラス', 'ko' => '유리잔', 'tr' => 'bardak', 'ru' => 'стакан', 'ar' => 'كوب', 'az' => 'stəkan'],
        'Gluten' => ['en' => 'gluten', 'es' => 'gluten', 'fr' => 'gluten', 'ja' => 'グルテン', 'ko' => '글루텐', 'tr' => 'gluten', 'ru' => 'глютен', 'ar' => 'غلوتين', 'az' => 'qlüten'],
        'Gramm' => ['en' => 'gram', 'es' => 'gramo', 'fr' => 'gramme', 'ja' => 'グラム', 'ko' => '그램', 'tr' => 'gram', 'ru' => 'грамм', 'ar' => 'غرام', 'az' => 'qram'],
        'Haus' => ['en' => 'house', 'es' => 'casa', 'fr' => 'maison', 'ja' => '家', 'ko' => '집', 'tr' => 'ev', 'ru' => 'дом', 'ar' => 'بيت', 'az' => 'ev'],
        'Herbst' => ['en' => 'autumn', 'es' => 'otoño', 'fr' => 'automne', 'ja' => '秋', 'ko' => '가을', 'tr' => 'sonbahar', 'ru' => 'осень', 'ar' => 'خريف', 'az' => 'payız'],
        'Himmel' => ['en' => 'sky', 'es' => 'cielo', 'fr' => 'ciel', 'ja' => '空', 'ko' => '하늘', 'tr' => 'gökyüzü', 'ru' => 'небо', 'ar' => 'سماء', 'az' => 'göy'],
        'Hund' => ['en' => 'dog', 'es' => 'perro', 'fr' => 'chien', 'ja' => '犬', 'ko' => '개', 'tr' => 'köpek', 'ru' => 'собака', 'ar' => 'كلب', 'az' => 'it'],
        'Hunde' => ['en' => 'dogs', 'es' => 'perros', 'fr' => 'chiens', 'ja' => '犬', 'ko' => '개들', 'tr' => 'köpekler', 'ru' => 'собаки', 'ar' => 'كلاب', 'az' => 'itlər'],
        'Hähnchen' => ['en' => 'chicken', 'es' => 'pollo', 'fr' => 'poulet', 'ja' => '鶏肉', 'ko' => '닭고기', 'tr' => 'tavuk', 'ru' => 'курица', 'ar' => 'دجاج', 'az' => 'toyuq'],
        'Jahre alt' => ['en' => 'years old', 'es' => 'años', 'fr' => 'ans', 'ja' => '歳', 'ko' => '살', 'tr' => 'yaşında', 'ru' => 'лет старый', 'ar' => 'سنوات قديم', 'az' => 'yaşında köhnə'],
        'Jahreszeit' => ['en' => 'season', 'es' => 'estación', 'fr' => 'saison', 'ja' => '季節', 'ko' => '계절', 'tr' => 'mevsim', 'ru' => 'сезон', 'ar' => 'موسم', 'az' => 'mövsüm'],
        'Kaffee' => ['en' => 'coffee', 'es' => 'café', 'fr' => 'café', 'ja' => 'コーヒー', 'ko' => '커피', 'tr' => 'kahve', 'ru' => 'кофе', 'ar' => 'قهوة', 'az' => 'qəhvə'],
        'Kalender' => ['en' => 'calendar', 'es' => 'calendario', 'fr' => 'calendrier', 'ja' => 'カレンダー', 'ko' => '달력', 'tr' => 'takvim', 'ru' => 'календарь', 'ar' => 'تقويم', 'az' => 'təqvim'],
        'Karotte' => ['en' => 'carrot', 'es' => 'zanahoria', 'fr' => 'carotte', 'ja' => 'にんじん', 'ko' => '당근', 'tr' => 'havuç', 'ru' => 'морковь', 'ar' => 'جزر', 'az' => 'yerkökü'],
        'Karte' => ['en' => 'card', 'es' => 'tarjeta', 'fr' => 'carte', 'ja' => 'カード', 'ko' => '카드', 'tr' => 'kart', 'ru' => 'карта', 'ar' => 'بطاقة', 'az' => 'kart'],
        'Kartoffel' => ['en' => 'potato', 'es' => 'patata', 'fr' => 'pomme de terre', 'ja' => 'じゃがいも', 'ko' => '감자', 'tr' => 'patates', 'ru' => 'картофель', 'ar' => 'بطاطا', 'az' => 'kartof'],
        'Kasse' => ['en' => 'checkout', 'es' => 'caja', 'fr' => 'caisse', 'ja' => 'レジ', 'ko' => '계산대', 'tr' => 'kasa', 'ru' => 'касса', 'ar' => 'صندوق الدفع', 'az' => 'kassa'],
        'Kassierer' => ['en' => 'cashier', 'es' => 'cajero', 'fr' => 'caissier', 'ja' => 'レジ係', 'ko' => '계산원', 'tr' => 'kasiyer', 'ru' => 'кассир', 'ar' => 'أمين الصندوق', 'az' => 'kassir'],
        'Katze' => ['en' => 'cat', 'es' => 'gato', 'fr' => 'chat', 'ja' => '猫', 'ko' => '고양이', 'tr' => 'kedi', 'ru' => 'кот', 'ar' => 'قط', 'az' => 'pişik'],
        'Katzen' => ['en' => 'cats', 'es' => 'gatos', 'fr' => 'chats', 'ja' => '猫', 'ko' => '고양이들', 'tr' => 'kediler', 'ru' => 'коты', 'ar' => 'قطط', 'az' => 'pişiklər'],
        'Kellner' => ['en' => 'waiter', 'es' => 'camarero', 'fr' => 'serveur', 'ja' => 'ウェイター', 'ko' => '웨이터', 'tr' => 'garson', 'ru' => 'официант', 'ar' => 'نادل', 'az' => 'ofisiant'],
        'Kilo' => ['en' => 'kilo', 'es' => 'kilo', 'fr' => 'kilo', 'ja' => 'キロ', 'ko' => '킬로', 'tr' => 'kilo', 'ru' => 'кило', 'ar' => 'كيلو', 'az' => 'kilo'],
        'Kind' => ['en' => 'child', 'es' => 'niño', 'fr' => 'enfant', 'ja' => '子供', 'ko' => '아이', 'tr' => 'çocuk', 'ru' => 'ребёнок', 'ar' => 'طفل', 'az' => 'uşaq'],
        'Korb' => ['en' => 'basket', 'es' => 'cesta', 'fr' => 'panier', 'ja' => 'かご', 'ko' => '바구니', 'tr' => 'sepet', 'ru' => 'корзина', 'ar' => 'سلة', 'az' => 'səbət'],
        'Kuchen' => ['en' => 'cake', 'es' => 'pastel', 'fr' => 'gâteau', 'ja' => 'ケーキ', 'ko' => '케이크', 'tr' => 'pasta', 'ru' => 'торт', 'ar' => 'كعكة', 'az' => 'tort'],
        'Kugelschreiber' => ['en' => 'pen', 'es' => 'bolígrafo', 'fr' => 'stylo', 'ja' => 'ペン', 'ko' => '펜', 'tr' => 'kalem', 'ru' => 'ручка', 'ar' => 'قلم', 'az' => 'qələm'],
        'Käse' => ['en' => 'cheese', 'es' => 'queso', 'fr' => 'fromage', 'ja' => 'チーズ', 'ko' => '치즈', 'tr' => 'peynir', 'ru' => 'сыр', 'ar' => 'جبن', 'az' => 'pendir'],
        'Küche' => ['en' => 'kitchen', 'es' => 'cocina', 'fr' => 'cuisine', 'ja' => '厨房', 'ko' => '주방', 'tr' => 'mutfak', 'ru' => 'кухня', 'ar' => 'مطبخ', 'az' => 'mətbəx'],
        'Lehrer' => ['en' => 'teacher', 'es' => 'profesor', 'fr' => 'professeur', 'ja' => '先生', 'ko' => '선생님', 'tr' => 'öğretmen', 'ru' => 'учитель', 'ar' => 'معلم', 'az' => 'müəllim'],
        'Liste' => ['en' => 'list', 'es' => 'lista', 'fr' => 'liste', 'ja' => 'リスト', 'ko' => '목록', 'tr' => 'liste', 'ru' => 'список', 'ar' => 'قائمة', 'az' => 'siyahı'],
        'Liter' => ['en' => 'litre', 'es' => 'litro', 'fr' => 'litre', 'ja' => 'リットル', 'ko' => '리터', 'tr' => 'litre', 'ru' => 'литр', 'ar' => 'لتر', 'az' => 'litr'],
        'Löffel' => ['en' => 'spoon', 'es' => 'cuchara', 'fr' => 'cuillère', 'ja' => 'スプーン', 'ko' => '숟가락', 'tr' => 'kaşık', 'ru' => 'ложка', 'ar' => 'ملعقة', 'az' => 'qaşıq'],
        'Menü' => ['en' => 'menu', 'es' => 'menú', 'fr' => 'menu', 'ja' => 'メニュー', 'ko' => '메뉴', 'tr' => 'menü', 'ru' => 'меню', 'ar' => 'قائمة الطعام', 'az' => 'menyu'],
        'Messer' => ['en' => 'knife', 'es' => 'cuchillo', 'fr' => 'couteau', 'ja' => 'ナイフ', 'ko' => '나이프', 'tr' => 'bıçak', 'ru' => 'нож', 'ar' => 'سكين', 'az' => 'bıçaq'],
        'Milch' => ['en' => 'milk', 'es' => 'leche', 'fr' => 'lait', 'ja' => '牛乳', 'ko' => '우유', 'tr' => 'süt', 'ru' => 'молоко', 'ar' => 'حليب', 'az' => 'süd'],
        'Minuten' => ['en' => 'minutes', 'es' => 'minutos', 'fr' => 'minutes', 'ja' => '分', 'ko' => '분', 'tr' => 'dakika', 'ru' => 'минут', 'ar' => 'دقائق', 'az' => 'dəqiqə'],
        'Mittag' => ['en' => 'noon', 'es' => 'mediodía', 'fr' => 'midi', 'ja' => '正午', 'ko' => '정오', 'tr' => 'öğlen', 'ru' => 'полдень', 'ar' => 'ظهرا', 'az' => 'günorta'],
        'Montag' => ['en' => 'Monday', 'es' => 'lunes', 'fr' => 'lundi', 'ja' => '月曜日', 'ko' => '월요일', 'tr' => 'pazartesi', 'ru' => 'понедельник', 'ar' => 'الاثنين', 'az' => 'bazar ertəsi'],
        'Morgen' => ['en' => 'morning', 'es' => 'mañana', 'fr' => 'matin', 'ja' => '朝', 'ko' => '아침', 'tr' => 'sabah', 'ru' => 'утро', 'ar' => 'صباح', 'az' => 'səhər'],
        'Mutter' => ['en' => 'mother', 'es' => 'madre', 'fr' => 'mère', 'ja' => '母', 'ko' => '어머니', 'tr' => 'anne', 'ru' => 'мама', 'ar' => 'أم', 'az' => 'ana'],
        'Nachbar' => ['en' => 'neighbour', 'es' => 'vecino', 'fr' => 'voisin', 'ja' => '隣人', 'ko' => '이웃', 'tr' => 'komşu', 'ru' => 'сосед', 'ar' => 'جار', 'az' => 'qonşu'],
        'Nachricht' => ['en' => 'message', 'es' => 'mensaje', 'fr' => 'message', 'ja' => 'メッセージ', 'ko' => '메시지', 'tr' => 'mesaj', 'ru' => 'сообщение', 'ar' => 'رسالة', 'az' => 'mesaj'],
        'Nacht' => ['en' => 'night', 'es' => 'noche', 'fr' => 'nuit', 'ja' => '夜', 'ko' => '밤', 'tr' => 'gece', 'ru' => 'ночь', 'ar' => 'ليل', 'az' => 'gecə'],
        'Nachtisch' => ['en' => 'dessert', 'es' => 'postre', 'fr' => 'dessert', 'ja' => 'デザート', 'ko' => '디저트', 'tr' => 'tatlı', 'ru' => 'десерт', 'ar' => 'حلوى', 'az' => 'şirniyyat'],
        'Name' => ['en' => 'name', 'es' => 'nombre', 'fr' => 'nom', 'ja' => '名前', 'ko' => '이름', 'tr' => 'ad', 'ru' => 'имя', 'ar' => 'اسم', 'az' => 'ad'],
        'Norden' => ['en' => 'north', 'es' => 'norte', 'fr' => 'nord', 'ja' => '北', 'ko' => '북쪽', 'tr' => 'kuzey', 'ru' => 'север', 'ar' => 'شمال', 'az' => 'şimal'],
        'Nüsse' => ['en' => 'nuts', 'es' => 'nueces', 'fr' => 'noix', 'ja' => 'ナッツ', 'ko' => '견과류', 'tr' => 'fındık', 'ru' => 'орехи', 'ar' => 'مكسرات', 'az' => 'qoz'],
        'Obst' => ['en' => 'fruit', 'es' => 'fruta', 'fr' => 'fruit', 'ja' => '果物', 'ko' => '과일', 'tr' => 'meyve', 'ru' => 'фрукт', 'ar' => 'فاكهة', 'az' => 'meyvə'],
        'Orange' => ['en' => 'orange', 'es' => 'naranja', 'fr' => 'orange', 'ja' => 'オレンジ', 'ko' => '오렌지', 'tr' => 'portakal', 'ru' => 'апельсин', 'ar' => 'برتقالة', 'az' => 'portağal'],
        'Park' => ['en' => 'park', 'es' => 'parque', 'fr' => 'parc', 'ja' => '公園', 'ko' => '공원', 'tr' => 'park', 'ru' => 'парк', 'ar' => 'حديقة', 'az' => 'park'],
        'Personen' => ['en' => 'people', 'es' => 'personas', 'fr' => 'personnes', 'ja' => '人', 'ko' => '명', 'tr' => 'kişi', 'ru' => 'люди', 'ar' => 'ناس', 'az' => 'insanlar'],
        'Pfeffer' => ['en' => 'pepper', 'es' => 'pimienta', 'fr' => 'poivre', 'ja' => 'こしょう', 'ko' => '후추', 'tr' => 'biber', 'ru' => 'перец', 'ar' => 'فلفل', 'az' => 'bibər'],
        'Platz' => ['en' => 'seat', 'es' => 'sitio', 'fr' => 'place', 'ja' => '席', 'ko' => '자리', 'tr' => 'koltuk', 'ru' => 'место', 'ar' => 'مقعد', 'az' => 'yer'],
        'Pommes' => ['en' => 'fries', 'es' => 'patatas fritas', 'fr' => 'frites', 'ja' => 'フライドポテト', 'ko' => '감자튀김', 'tr' => 'patates kızartması', 'ru' => 'картошка фри', 'ar' => 'بطاطا مقلية', 'az' => 'kartof fri'],
        'Preis' => ['en' => 'price', 'es' => 'precio', 'fr' => 'prix', 'ja' => '値段', 'ko' => '가격', 'tr' => 'fiyat', 'ru' => 'цена', 'ar' => 'سعر', 'az' => 'qiymət'],
        'Preise' => ['en' => 'prices', 'es' => 'precios', 'fr' => 'prix', 'ja' => '値段', 'ko' => '가격', 'tr' => 'fiyatlar', 'ru' => 'цены', 'ar' => 'أسعار', 'az' => 'qiymətlər'],
        'Problem' => ['en' => 'problem', 'es' => 'problema', 'fr' => 'problème', 'ja' => '問題', 'ko' => '문제', 'tr' => 'sorun', 'ru' => 'проблема', 'ar' => 'مشكلة', 'az' => 'problem'],
        'Produkt' => ['en' => 'product', 'es' => 'producto', 'fr' => 'produit', 'ja' => '商品', 'ko' => '상품', 'tr' => 'ürün', 'ru' => 'продукт', 'ar' => 'منتج', 'az' => 'məhsul'],
        'Quittung' => ['en' => 'receipt', 'es' => 'recibo', 'fr' => 'reçu', 'ja' => 'レシート', 'ko' => '영수증', 'tr' => 'fiş', 'ru' => 'чек', 'ar' => 'إيصال', 'az' => 'qəbz'],
        'Rabatt' => ['en' => 'discount', 'es' => 'descuento', 'fr' => 'réduction', 'ja' => '割引', 'ko' => '할인', 'tr' => 'indirim', 'ru' => 'скидка', 'ar' => 'خصم', 'az' => 'endirim'],
        'Regal' => ['en' => 'aisle', 'es' => 'pasillo', 'fr' => 'rayon', 'ja' => '売り場', 'ko' => '진열대', 'tr' => 'reyon', 'ru' => 'отдел', 'ar' => 'قسم', 'az' => 'şöbə'],
        'Regen' => ['en' => 'rain', 'es' => 'lluvia', 'fr' => 'pluie', 'ja' => '雨', 'ko' => '비', 'tr' => 'yağmur', 'ru' => 'дождь', 'ar' => 'مطر', 'az' => 'yağış'],
        'Reis' => ['en' => 'rice', 'es' => 'arroz', 'fr' => 'riz', 'ja' => 'ご飯', 'ko' => '밥', 'tr' => 'pirinç', 'ru' => 'рис', 'ar' => 'أرز', 'az' => 'düyü'],
        'Reservierung' => ['en' => 'booking', 'es' => 'reserva', 'fr' => 'réservation', 'ja' => '予約', 'ko' => '예약', 'tr' => 'rezervasyon', 'ru' => 'бронь', 'ar' => 'حجز', 'az' => 'rezervasiya'],
        'Restaurant' => ['en' => 'restaurant', 'es' => 'restaurante', 'fr' => 'restaurant', 'ja' => 'レストラン', 'ko' => '식당', 'tr' => 'restoran', 'ru' => 'ресторан', 'ar' => 'مطعم', 'az' => 'restoran'],
        'Saft' => ['en' => 'juice', 'es' => 'zumo', 'fr' => 'jus', 'ja' => 'ジュース', 'ko' => '주스', 'tr' => 'meyve suyu', 'ru' => 'сок', 'ar' => 'عصير', 'az' => 'şirə'],
        'Sahne' => ['en' => 'cream', 'es' => 'nata', 'fr' => 'crème', 'ja' => 'クリーム', 'ko' => '크림', 'tr' => 'krema', 'ru' => 'сливки', 'ar' => 'كريمة', 'az' => 'qaymaq'],
        'Salat' => ['en' => 'salad', 'es' => 'ensalada', 'fr' => 'salade', 'ja' => 'サラダ', 'ko' => '샐러드', 'tr' => 'salata', 'ru' => 'салат', 'ar' => 'سلطة', 'az' => 'salat'],
        'Salz' => ['en' => 'salt', 'es' => 'sal', 'fr' => 'sel', 'ja' => '塩', 'ko' => '소금', 'tr' => 'tuz', 'ru' => 'соль', 'ar' => 'ملح', 'az' => 'duz'],
        'Sandwich' => ['en' => 'sandwich', 'es' => 'sándwich', 'fr' => 'sandwich', 'ja' => 'サンドイッチ', 'ko' => '샌드위치', 'tr' => 'sandviç', 'ru' => 'сэндвич', 'ar' => 'شطيرة', 'az' => 'sendviç'],
        'Schachtel' => ['en' => 'box', 'es' => 'caja', 'fr' => 'boîte', 'ja' => '箱', 'ko' => '상자', 'tr' => 'kutu', 'ru' => 'коробка', 'ar' => 'علبة', 'az' => 'qutu'],
        'Schlange' => ['en' => 'queue', 'es' => 'cola', 'fr' => 'file', 'ja' => '列', 'ko' => '줄', 'tr' => 'sıra', 'ru' => 'очередь', 'ar' => 'طابور', 'az' => 'növbə'],
        'Schnee' => ['en' => 'snow', 'es' => 'nieve', 'fr' => 'neige', 'ja' => '雪', 'ko' => '눈', 'tr' => 'kar', 'ru' => 'снег', 'ar' => 'ثلج', 'az' => 'qar'],
        'Schokolade' => ['en' => 'chocolate', 'es' => 'chocolate', 'fr' => 'chocolat', 'ja' => 'チョコレート', 'ko' => '초콜릿', 'tr' => 'çikolata', 'ru' => 'шоколад', 'ar' => 'شوكولاتة', 'az' => 'şokolad'],
        'Schule' => ['en' => 'school', 'es' => 'escuela', 'fr' => 'école', 'ja' => '学校', 'ko' => '학교', 'tr' => 'okul', 'ru' => 'школа', 'ar' => 'مدرسة', 'az' => 'məktəb'],
        'Schwester' => ['en' => 'sister', 'es' => 'hermana', 'fr' => 'sœur', 'ja' => '姉妹', 'ko' => '자매', 'tr' => 'kız kardeş', 'ru' => 'сестра', 'ar' => 'أخت', 'az' => 'bacı'],
        'Serviette' => ['en' => 'napkin', 'es' => 'servilleta', 'fr' => 'serviette', 'ja' => 'ナプキン', 'ko' => '냅킨', 'tr' => 'peçete', 'ru' => 'салфетка', 'ar' => 'منديل', 'az' => 'salfet'],
        'Sommer' => ['en' => 'summer', 'es' => 'verano', 'fr' => 'été', 'ja' => '夏', 'ko' => '여름', 'tr' => 'yaz', 'ru' => 'лето', 'ar' => 'صيف', 'az' => 'yay'],
        'Sonne' => ['en' => 'sun', 'es' => 'sol', 'fr' => 'soleil', 'ja' => '太陽', 'ko' => '해', 'tr' => 'güneş', 'ru' => 'солнце', 'ar' => 'شمس', 'az' => 'günəş'],
        'Stadt' => ['en' => 'town', 'es' => 'ciudad', 'fr' => 'ville', 'ja' => '町', 'ko' => '도시', 'tr' => 'şehir', 'ru' => 'город', 'ar' => 'بلدة', 'az' => 'qəsəbə'],
        'Straße' => ['en' => 'street', 'es' => 'calle', 'fr' => 'rue', 'ja' => '通り', 'ko' => '거리', 'tr' => 'cadde', 'ru' => 'улица', 'ar' => 'شارع', 'az' => 'küçə'],
        'Stuhl' => ['en' => 'chair', 'es' => 'silla', 'fr' => 'chaise', 'ja' => '椅子', 'ko' => '의자', 'tr' => 'sandalye', 'ru' => 'стул', 'ar' => 'كرسي', 'az' => 'stul'],
        'Stunde' => ['en' => 'hour', 'es' => 'hora', 'fr' => 'heure', 'ja' => '時間', 'ko' => '시간', 'tr' => 'saat', 'ru' => 'час', 'ar' => 'ساعة', 'az' => 'saat'],
        'Stück' => ['en' => 'slice', 'es' => 'trozo', 'fr' => 'part', 'ja' => '一切れ', 'ko' => '한 조각', 'tr' => 'dilim', 'ru' => 'кусок', 'ar' => 'شريحة', 'az' => 'dilim'],
        'Supermarkt' => ['en' => 'supermarket', 'es' => 'supermercado', 'fr' => 'supermarché', 'ja' => 'スーパー', 'ko' => '슈퍼마켓', 'tr' => 'market', 'ru' => 'супермаркет', 'ar' => 'سوبرماركت', 'az' => 'supermarket'],
        'Suppe' => ['en' => 'soup', 'es' => 'sopa', 'fr' => 'soupe', 'ja' => 'スープ', 'ko' => '수프', 'tr' => 'çorba', 'ru' => 'суп', 'ar' => 'حساء', 'az' => 'şorba'],
        'Süden' => ['en' => 'south', 'es' => 'sur', 'fr' => 'sud', 'ja' => '南', 'ko' => '남쪽', 'tr' => 'güney', 'ru' => 'юг', 'ar' => 'جنوب', 'az' => 'cənub'],
        'Tag' => ['en' => 'day', 'es' => 'día', 'fr' => 'jour', 'ja' => '日', 'ko' => '날', 'tr' => 'gün', 'ru' => 'день', 'ar' => 'يوم', 'az' => 'gün'],
        'Tee' => ['en' => 'tea', 'es' => 'té', 'fr' => 'thé', 'ja' => 'お茶', 'ko' => '차', 'tr' => 'çay', 'ru' => 'чай', 'ar' => 'شاي', 'az' => 'çay'],
        'Telefon' => ['en' => 'phone', 'es' => 'teléfono', 'fr' => 'téléphone', 'ja' => '電話', 'ko' => '전화', 'tr' => 'telefon', 'ru' => 'телефон', 'ar' => 'هاتف', 'az' => 'telefon'],
        'Teller' => ['en' => 'plate', 'es' => 'plato', 'fr' => 'assiette', 'ja' => 'お皿', 'ko' => '접시', 'tr' => 'tabak', 'ru' => 'тарелка', 'ar' => 'صحن', 'az' => 'boşqab'],
        'Tisch' => ['en' => 'table', 'es' => 'mesa', 'fr' => 'table', 'ja' => 'テーブル', 'ko' => '탁자', 'tr' => 'masa', 'ru' => 'стол', 'ar' => 'طاولة', 'az' => 'masa'],
        'Tomate' => ['en' => 'tomato', 'es' => 'tomate', 'fr' => 'tomate', 'ja' => 'トマト', 'ko' => '토마토', 'tr' => 'domates', 'ru' => 'помидор', 'ar' => 'طماطم', 'az' => 'pomidor'],
        'Torte' => ['en' => 'tart', 'es' => 'tarta', 'fr' => 'tarte', 'ja' => 'タルト', 'ko' => '타르트', 'tr' => 'turta', 'ru' => 'тарт', 'ar' => 'فطيرة', 'az' => 'tart'],
        'Trauben' => ['en' => 'grapes', 'es' => 'uvas', 'fr' => 'raisin', 'ja' => 'ぶどう', 'ko' => '포도', 'tr' => 'üzüm', 'ru' => 'виноград', 'ar' => 'عنب', 'az' => 'üzüm'],
        'Trinkgeld' => ['en' => 'tip', 'es' => 'propina', 'fr' => 'pourboire', 'ja' => 'チップ', 'ko' => '팁', 'tr' => 'bahşiş', 'ru' => 'чаевые', 'ar' => 'بقشيش', 'az' => 'çaypulu'],
        'Tüte' => ['en' => 'bag', 'es' => 'bolsa', 'fr' => 'sac', 'ja' => '袋', 'ko' => '봉투', 'tr' => 'poşet', 'ru' => 'пакет', 'ar' => 'كيس', 'az' => 'torba'],
        'Uhr' => ['en' => 'clock', 'es' => 'reloj', 'fr' => 'horloge', 'ja' => '時計', 'ko' => '시계', 'tr' => 'saat', 'ru' => 'часы', 'ar' => 'ساعة', 'az' => 'saat'],
        'Vanille' => ['en' => 'vanilla', 'es' => 'vainilla', 'fr' => 'vanille', 'ja' => 'バニラ', 'ko' => '바닐라', 'tr' => 'vanilya', 'ru' => 'ванильный', 'ar' => 'فانيليا', 'az' => 'vanil'],
        'Vater' => ['en' => 'father', 'es' => 'padre', 'fr' => 'père', 'ja' => '父', 'ko' => '아버지', 'tr' => 'baba', 'ru' => 'папа', 'ar' => 'أب', 'az' => 'ata'],
        'Vorspeise' => ['en' => 'starter', 'es' => 'entrante', 'fr' => 'entrée', 'ja' => '前菜', 'ko' => '전채', 'tr' => 'başlangıç', 'ru' => 'закуска', 'ar' => 'مقبلات', 'az' => 'qəlyanaltı'],
        'Waage' => ['en' => 'scales', 'es' => 'balanza', 'fr' => 'balance', 'ja' => 'はかり', 'ko' => '저울', 'tr' => 'terazi', 'ru' => 'весы', 'ar' => 'ميزان', 'az' => 'tərəzi'],
        'Wasser' => ['en' => 'water', 'es' => 'agua', 'fr' => 'eau', 'ja' => '水', 'ko' => '물', 'tr' => 'su', 'ru' => 'вода', 'ar' => 'ماء', 'az' => 'su'],
        'Wechselgeld' => ['en' => 'change', 'es' => 'cambio', 'fr' => 'monnaie', 'ja' => 'おつり', 'ko' => '거스름돈', 'tr' => 'para üstü', 'ru' => 'сдача', 'ar' => 'الباقي', 'az' => 'qalıq'],
        'Wein' => ['en' => 'wine', 'es' => 'vino', 'fr' => 'vin', 'ja' => 'ワイン', 'ko' => '와인', 'tr' => 'şarap', 'ru' => 'вино', 'ar' => 'نبيذ', 'az' => 'şərab'],
        'Wetter' => ['en' => 'weather', 'es' => 'tiempo', 'fr' => 'temps', 'ja' => '天気', 'ko' => '날씨', 'tr' => 'hava', 'ru' => 'погода', 'ar' => 'طقس', 'az' => 'hava'],
        'Wind' => ['en' => 'wind', 'es' => 'viento', 'fr' => 'vent', 'ja' => '風', 'ko' => '바람', 'tr' => 'rüzgâr', 'ru' => 'ветер', 'ar' => 'ريح', 'az' => 'külək'],
        'Winter' => ['en' => 'winter', 'es' => 'invierno', 'fr' => 'hiver', 'ja' => '冬', 'ko' => '겨울', 'tr' => 'kış', 'ru' => 'зима', 'ar' => 'شتاء', 'az' => 'qış'],
        'Woche' => ['en' => 'week', 'es' => 'semana', 'fr' => 'semaine', 'ja' => '週', 'ko' => '주', 'tr' => 'hafta', 'ru' => 'неделя', 'ar' => 'أسبوع', 'az' => 'həftə'],
        'Wolke' => ['en' => 'cloud', 'es' => 'nube', 'fr' => 'nuage', 'ja' => '雲', 'ko' => '구름', 'tr' => 'bulut', 'ru' => 'облако', 'ar' => 'سحابة', 'az' => 'bulud'],
        'Zucker' => ['en' => 'sugar', 'es' => 'azúcar', 'fr' => 'sucre', 'ja' => '砂糖', 'ko' => '설탕', 'tr' => 'şeker', 'ru' => 'сахар', 'ar' => 'سكر', 'az' => 'şəkər'],
        'Zutaten' => ['en' => 'ingredients', 'es' => 'ingredientes', 'fr' => 'ingrédients', 'ja' => '材料', 'ko' => '재료', 'tr' => 'içindekiler', 'ru' => 'ингредиенты', 'ar' => 'مكونات', 'az' => 'tərkib'],
        'Zwiebel' => ['en' => 'onion', 'es' => 'cebolla', 'fr' => 'oignon', 'ja' => '玉ねぎ', 'ko' => '양파', 'tr' => 'soğan', 'ru' => 'лук', 'ar' => 'بصل', 'az' => 'soğan'],
        'ab' => ['en' => 'off', 'es' => 'gira', 'fr' => 'tourne', 'ja' => '曲がって', 'ko' => '꺾어', 'tr' => 'indirim', 'ru' => 'скидка', 'ar' => 'خصم', 'az' => 'endirim'],
        'abbiegen' => ['en' => 'turn', 'es' => 'girar', 'fr' => 'tourner', 'ja' => '曲がる', 'ko' => '돌다', 'tr' => 'dön', 'ru' => 'поворот', 'ar' => 'منعطف', 'az' => 'dönüş'],
        'aber' => ['en' => 'but', 'es' => 'pero', 'fr' => 'mais', 'ja' => 'しかし', 'ko' => '하지만', 'tr' => 'ama', 'ru' => 'но', 'ar' => 'لكن', 'az' => 'amma'],
        'acht' => ['en' => 'eight', 'es' => 'ocho', 'fr' => 'huit', 'ja' => '八', 'ko' => '여덟', 'tr' => 'sekiz', 'ru' => 'восемь', 'ar' => 'ثمانية', 'az' => 'səkkiz'],
        'allergisch' => ['en' => 'allergic', 'es' => 'alérgico', 'fr' => 'allergique', 'ja' => 'アレルギーの', 'ko' => '알레르기가 있는', 'tr' => 'alerjik', 'ru' => 'аллергия', 'ar' => 'حساسية', 'az' => 'allergiya'],
        'als' => ['en' => 'than', 'es' => 'que', 'fr' => 'que', 'ja' => 'より', 'ko' => '보다', 'tr' => 'den', 'ru' => 'чем', 'ar' => 'من', 'az' => 'dan'],
        'alt' => ['en' => 'old', 'es' => 'viejo', 'fr' => 'vieux', 'ja' => '古い', 'ko' => '오래된', 'tr' => 'eski', 'ru' => 'старый', 'ar' => 'قديم', 'az' => 'köhnə'],
        'am' => ['en' => 'at the', 'es' => 'en el', 'fr' => 'au', 'ja' => 'に', 'ko' => '에', 'tr' => 'de', 'ru' => 'на', 'ar' => 'على', 'az' => 'yanında'],
        'an' => ['en' => 'at', 'es' => 'en', 'fr' => 'à', 'ja' => 'で', 'ko' => '에서', 'tr' => 'de', 'ru' => 'на', 'ar' => 'على', 'az' => 'yanında'],
        'anrufen' => ['en' => 'call', 'es' => 'llamar', 'fr' => 'appeler', 'ja' => '電話する', 'ko' => '전화하다', 'tr' => 'ara', 'ru' => 'позвони', 'ar' => 'اتصل', 'az' => 'zəng et'],
        'apfels' => ['en' => 'apple', 'es' => 'manzana', 'fr' => 'pomme', 'ja' => 'りんご', 'ko' => '사과', 'tr' => 'elma', 'ru' => 'яблоко', 'ar' => 'تفاحة', 'az' => 'alma'],
        'apfeltorte' => ['en' => 'apple tart', 'es' => 'tarta de manzana', 'fr' => 'tarte aux pommes', 'ja' => 'アップルタルト', 'ko' => '사과 타르트', 'tr' => 'elmalı turta', 'ru' => 'яблочный тарт', 'ar' => 'فطيرة تفاح', 'az' => 'almalı tart'],
        'auch' => ['en' => 'also', 'es' => 'también', 'fr' => 'aussi', 'ja' => 'も', 'ko' => '또한', 'tr' => 'de', 'ru' => 'тоже', 'ar' => 'أيضا', 'az' => 'həmçinin'],
        'auf' => ['en' => 'on', 'es' => 'sobre', 'fr' => 'sur', 'ja' => 'の上に', 'ko' => '위에', 'tr' => 'üzerinde', 'ru' => 'на', 'ar' => 'على', 'az' => 'üzərində'],
        'auf Wiedersehen' => ['en' => 'goodbye', 'es' => 'adiós', 'fr' => 'au revoir', 'ja' => 'さようなら', 'ko' => '안녕히 가세요', 'tr' => 'hoşça kal', 'ru' => 'до свидания', 'ar' => 'مع السلامة', 'az' => 'sağ ol'],
        'aus' => ['en' => 'from', 'es' => 'de', 'fr' => 'de', 'ja' => 'から', 'ko' => '에서', 'tr' => 'den', 'ru' => 'из', 'ar' => 'من', 'az' => 'dan'],
        'ausgezeichnet' => ['en' => 'excellent', 'es' => 'excelente', 'fr' => 'excellent', 'ja' => '素晴らしい', 'ko' => '훌륭한', 'tr' => 'mükemmel', 'ru' => 'отлично', 'ar' => 'ممتاز', 'az' => 'əla'],
        'ausgezeichneter' => ['en' => 'excellent', 'es' => 'excelente', 'fr' => 'excellent', 'ja' => '素晴らしい', 'ko' => '훌륭한', 'tr' => 'mükemmel', 'ru' => 'отлично', 'ar' => 'ممتاز', 'az' => 'əla'],
        'aß' => ['en' => 'ate', 'es' => 'comí', 'fr' => 'mangé', 'ja' => '食べた', 'ko' => '먹었다', 'tr' => 'yedi', 'ru' => 'ел', 'ar' => 'أكل', 'az' => 'yedi'],
        'bald' => ['en' => 'soon', 'es' => 'pronto', 'fr' => 'bientôt', 'ja' => 'すぐに', 'ko' => '곧', 'tr' => 'yakında', 'ru' => 'скоро', 'ar' => 'قريبا', 'az' => 'tezliklə'],
        'bar' => ['en' => 'cash', 'es' => 'efectivo', 'fr' => 'espèces', 'ja' => '現金', 'ko' => '현금', 'tr' => 'nakit', 'ru' => 'наличные', 'ar' => 'كاش', 'az' => 'nağd'],
        'beim' => ['en' => 'at the', 'es' => 'en el', 'fr' => 'au', 'ja' => 'で', 'ko' => '에서', 'tr' => 'de', 'ru' => 'на', 'ar' => 'على', 'az' => 'yanında'],
        'bereit' => ['en' => 'ready', 'es' => 'listo', 'fr' => 'prêt', 'ja' => '準備ができた', 'ko' => '준비된', 'tr' => 'hazır', 'ru' => 'готов', 'ar' => 'جاهز', 'az' => 'hazır'],
        'beschäftigt' => ['en' => 'busy', 'es' => 'ocupado', 'fr' => 'occupé', 'ja' => '忙しい', 'ko' => '바쁜', 'tr' => 'meşgul', 'ru' => 'занят', 'ar' => 'مشغول', 'az' => 'məşğul'],
        'besonders' => ['en' => 'especially', 'es' => 'sobre todo', 'fr' => 'surtout', 'ja' => '特に', 'ko' => '특히', 'tr' => 'özellikle', 'ru' => 'особенно', 'ar' => 'خاصة', 'az' => 'xüsusilə'],
        'besser' => ['en' => 'better', 'es' => 'mejor', 'fr' => 'meilleur', 'ja' => 'もっと良い', 'ko' => '더 좋은', 'tr' => 'daha iyi', 'ru' => 'лучше', 'ar' => 'أحسن', 'az' => 'daha yaxşı'],
        'bestellen' => ['en' => 'to order', 'es' => 'pedir', 'fr' => 'commander', 'ja' => '注文する', 'ko' => '주문하다', 'tr' => 'sipariş vermek', 'ru' => 'заказать', 'ar' => 'الطلب', 'az' => 'sifariş vermək'],
        'bestätigen' => ['en' => 'to confirm', 'es' => 'confirmar', 'fr' => 'confirmer', 'ja' => '確認する', 'ko' => '확인하다', 'tr' => 'onaylamak', 'ru' => 'подтвердить', 'ar' => 'التأكيد', 'az' => 'təsdiqləmək'],
        'bevorzuge' => ['en' => 'prefer', 'es' => 'prefiero', 'fr' => 'préfère', 'ja' => '好む', 'ko' => '선호하다', 'tr' => 'tercih et', 'ru' => 'предпочитаю', 'ar' => 'أفضل', 'az' => 'üstünlük verirəm'],
        'bezahle' => ['en' => 'pay', 'es' => 'pagar', 'fr' => 'payer', 'ja' => '払う', 'ko' => '지불하다', 'tr' => 'öde', 'ru' => 'плати', 'ar' => 'ادفع', 'az' => 'ödə'],
        'bezahlen' => ['en' => 'pay', 'es' => 'pagar', 'fr' => 'payer', 'ja' => '払う', 'ko' => '지불하다', 'tr' => 'öde', 'ru' => 'плати', 'ar' => 'ادفع', 'az' => 'ödə'],
        'bieg' => ['en' => 'turn', 'es' => 'gira', 'fr' => 'tourne', 'ja' => '曲がる', 'ko' => '돌다', 'tr' => 'dön', 'ru' => 'поворот', 'ar' => 'منعطف', 'az' => 'dönüş'],
        'biege' => ['en' => 'turn', 'es' => 'giro', 'fr' => 'tourne', 'ja' => '曲がる', 'ko' => '돌다', 'tr' => 'dön', 'ru' => 'поворот', 'ar' => 'منعطف', 'az' => 'dönüş'],
        'billig' => ['en' => 'cheap', 'es' => 'barato', 'fr' => 'bon marché', 'ja' => '安い', 'ko' => '싼', 'tr' => 'ucuz', 'ru' => 'дешёвый', 'ar' => 'رخيص', 'az' => 'ucuz'],
        'billige' => ['en' => 'cheap', 'es' => 'barato', 'fr' => 'bon marché', 'ja' => '安い', 'ko' => '싼', 'tr' => 'ucuz', 'ru' => 'дешёвый', 'ar' => 'رخيص', 'az' => 'ucuz'],
        'billiger' => ['en' => 'cheap', 'es' => 'barato', 'fr' => 'bon marché', 'ja' => '安い', 'ko' => '싼', 'tr' => 'ucuz', 'ru' => 'дешёвый', 'ar' => 'رخيص', 'az' => 'ucuz'],
        'billiges' => ['en' => 'cheap', 'es' => 'barato', 'fr' => 'bon marché', 'ja' => '安い', 'ko' => '싼', 'tr' => 'ucuz', 'ru' => 'дешёвый', 'ar' => 'رخيص', 'az' => 'ucuz'],
        'bin' => ['en' => 'am', 'es' => 'estoy', 'fr' => 'suis', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'im', 'ru' => 'есть', 'ar' => 'يكون', 'az' => 'olmaq'],
        'bisschen' => ['en' => 'bit', 'es' => 'poco', 'fr' => 'peu', 'ja' => '少し', 'ko' => '조금', 'tr' => 'biraz', 'ru' => 'немного', 'ar' => 'قليلا', 'az' => 'bir az'],
        'bist' => ['en' => 'are', 'es' => 'estás', 'fr' => 'es', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'sin', 'ru' => 'есть', 'ar' => 'يكون', 'az' => 'olmaq'],
        'bitte' => ['en' => 'please', 'es' => 'por favor', 'fr' => 's\'il vous plaît', 'ja' => 'お願いします', 'ko' => '부탁합니다', 'tr' => 'lütfen', 'ru' => 'пожалуйста', 'ar' => 'من فضلك', 'az' => 'zəhmət olmasa'],
        'blau' => ['en' => 'blue', 'es' => 'azul', 'fr' => 'bleu', 'ja' => '青', 'ko' => '파란색', 'tr' => 'mavi', 'ru' => 'синий', 'ar' => 'أزرق', 'az' => 'mavi'],
        'blauer' => ['en' => 'blue', 'es' => 'azul', 'fr' => 'bleu', 'ja' => '青', 'ko' => '파란색', 'tr' => 'mavi', 'ru' => 'синий', 'ar' => 'أزرق', 'az' => 'mavi'],
        'brauche' => ['en' => 'need', 'es' => 'necesito', 'fr' => 'ai besoin', 'ja' => '必要', 'ko' => '필요하다', 'tr' => 'ihtiyaç', 'ru' => 'нужно', 'ar' => 'حاجة', 'az' => 'ehtiyac'],
        'bringen' => ['en' => 'to bring', 'es' => 'traer', 'fr' => 'apporter', 'ja' => '持ってくる', 'ko' => '가져오다', 'tr' => 'getirmek', 'ru' => 'принести', 'ar' => 'الإحضار', 'az' => 'gətirmək'],
        'bringen Sie mir' => ['en' => 'bring me', 'es' => 'tráigame', 'fr' => 'apportez-moi', 'ja' => '持ってきてください', 'ko' => '가져다주세요', 'tr' => 'bana getirin', 'ru' => 'принесите мне', 'ar' => 'أحضر لي', 'az' => 'mənə gətir'],
        'danke' => ['en' => 'thank you', 'es' => 'gracias', 'fr' => 'merci', 'ja' => 'ありがとう', 'ko' => '감사합니다', 'tr' => 'teşekkürler', 'ru' => 'спасибо', 'ar' => 'شكرا', 'az' => 'təşəkkür'],
        'dann' => ['en' => 'then', 'es' => 'entonces', 'fr' => 'ensuite', 'ja' => 'それから', 'ko' => '그러면', 'tr' => 'sonra', 'ru' => 'потом', 'ar' => 'ثم', 'az' => 'sonra'],
        'das' => ['en' => 'the', 'es' => 'el', 'fr' => 'le', 'ja' => 'その', 'ko' => '그', 'tr' => 'o', 'ru' => 'этот', 'ar' => 'هذا', 'az' => 'həmin'],
        'das ist' => ['en' => 'this is', 'es' => 'este es', 'fr' => 'c\'est', 'ja' => 'これは', 'ko' => '이분은', 'tr' => 'bu', 'ru' => 'это', 'ar' => 'هذا', 'az' => 'bu'],
        'dein' => ['en' => 'your', 'es' => 'tu', 'fr' => 'ton', 'ja' => 'あなたの', 'ko' => '당신의', 'tr' => 'senin', 'ru' => 'твой', 'ar' => 'خاصتك', 'az' => 'sənin'],
        'dem' => ['en' => 'the', 'es' => 'el', 'fr' => 'le', 'ja' => 'その', 'ko' => '그', 'tr' => 'o', 'ru' => 'этот', 'ar' => 'هذا', 'az' => 'həmin'],
        'den' => ['en' => 'the', 'es' => 'el', 'fr' => 'le', 'ja' => 'その', 'ko' => '그', 'tr' => 'o', 'ru' => 'этот', 'ar' => 'هذا', 'az' => 'həmin'],
        'denke' => ['en' => 'think', 'es' => 'creo', 'fr' => 'pense', 'ja' => '思う', 'ko' => '생각하다', 'tr' => 'düşün', 'ru' => 'думаю', 'ar' => 'أفكر', 'az' => 'düşünürəm'],
        'der' => ['en' => 'the', 'es' => 'el', 'fr' => 'le', 'ja' => 'その', 'ko' => '그', 'tr' => 'o', 'ru' => 'этот', 'ar' => 'هذا', 'az' => 'həmin'],
        'des' => ['en' => 'of the', 'es' => 'del', 'fr' => 'du', 'ja' => 'の', 'ko' => '의', 'tr' => 'in', 'ru' => 'из', 'ar' => 'من', 'az' => 'ın'],
        'die' => ['en' => 'the', 'es' => 'la', 'fr' => 'la', 'ja' => 'その', 'ko' => '그', 'tr' => 'o', 'ru' => 'этот', 'ar' => 'هذا', 'az' => 'həmin'],
        'die Rechnung' => ['en' => 'the bill', 'es' => 'la cuenta', 'fr' => 'l\'addition', 'ja' => 'お会計', 'ko' => '계산서', 'tr' => 'hesap', 'ru' => 'счёт', 'ar' => 'الحساب', 'az' => 'hesab'],
        'diese' => ['en' => 'these', 'es' => 'estos', 'fr' => 'ces', 'ja' => 'これらの', 'ko' => '이것들', 'tr' => 'bunlar', 'ru' => 'эти', 'ar' => 'هذه', 'az' => 'bunlar'],
        'dieser' => ['en' => 'this', 'es' => 'este', 'fr' => 'ce', 'ja' => 'この', 'ko' => '이', 'tr' => 'bu', 'ru' => 'это', 'ar' => 'هذا', 'az' => 'bu'],
        'dieses' => ['en' => 'this', 'es' => 'este', 'fr' => 'ce', 'ja' => 'この', 'ko' => '이', 'tr' => 'bu', 'ru' => 'это', 'ar' => 'هذا', 'az' => 'bu'],
        'dir' => ['en' => 'you', 'es' => 'te', 'fr' => 'toi', 'ja' => 'あなたに', 'ko' => '당신에게', 'tr' => 'sen', 'ru' => 'ты', 'ar' => 'أنت', 'az' => 'sən'],
        'drei' => ['en' => 'three', 'es' => 'tres', 'fr' => 'trois', 'ja' => '三', 'ko' => '셋', 'tr' => 'üç', 'ru' => 'три', 'ar' => 'ثلاثة', 'az' => 'üç'],
        'du' => ['en' => 'you', 'es' => 'tú', 'fr' => 'tu', 'ja' => 'あなた', 'ko' => '당신', 'tr' => 'sen', 'ru' => 'ты', 'ar' => 'أنت', 'az' => 'sən'],
        'du bist' => ['en' => 'you are', 'es' => 'eres', 'fr' => 'tu es', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'sensin', 'ru' => 'ты', 'ar' => 'أنت', 'az' => 'sən'],
        'durstig' => ['en' => 'thirsty', 'es' => 'sediento', 'fr' => 'assoiffé', 'ja' => 'のどが渇いた', 'ko' => '목마른', 'tr' => 'susamış', 'ru' => 'хочу пить', 'ar' => 'عطشان', 'az' => 'susuz'],
        'ein' => ['en' => 'a', 'es' => 'un', 'fr' => 'un', 'ja' => '一つの', 'ko' => '하나의', 'tr' => 'bir', 'ru' => 'один', 'ar' => 'واحد', 'az' => 'bir'],
        'ein Getränk' => ['en' => 'a drink', 'es' => 'una bebida', 'fr' => 'une boisson', 'ja' => '飲み物', 'ko' => '음료', 'tr' => 'bir içecek', 'ru' => 'напиток', 'ar' => 'مشروب', 'az' => 'içki'],
        'ein bisschen' => ['en' => 'a little', 'es' => 'un poco', 'fr' => 'un peu', 'ja' => '少し', 'ko' => '조금', 'tr' => 'biraz', 'ru' => 'немного', 'ar' => 'قليل', 'az' => 'az'],
        'eine' => ['en' => 'a', 'es' => 'una', 'fr' => 'une', 'ja' => '一つの', 'ko' => '하나의', 'tr' => 'bir', 'ru' => 'один', 'ar' => 'واحد', 'az' => 'bir'],
        'einem' => ['en' => 'a', 'es' => 'un', 'fr' => 'un', 'ja' => '一つの', 'ko' => '하나의', 'tr' => 'bir', 'ru' => 'один', 'ar' => 'واحد', 'az' => 'bir'],
        'einen' => ['en' => 'a', 'es' => 'un', 'fr' => 'un', 'ja' => '一つの', 'ko' => '하나의', 'tr' => 'bir', 'ru' => 'один', 'ar' => 'واحد', 'az' => 'bir'],
        'einer' => ['en' => 'a', 'es' => 'un', 'fr' => 'un', 'ja' => '一つの', 'ko' => '하나의', 'tr' => 'bir', 'ru' => 'один', 'ar' => 'واحد', 'az' => 'bir'],
        'einfach' => ['en' => 'easy', 'es' => 'fácil', 'fr' => 'facile', 'ja' => '簡単', 'ko' => '쉬운', 'tr' => 'kolay', 'ru' => 'легко', 'ar' => 'سهل', 'az' => 'asan'],
        'einfaches' => ['en' => 'easy', 'es' => 'fácil', 'fr' => 'facile', 'ja' => '簡単', 'ko' => '쉬운', 'tr' => 'kolay', 'ru' => 'легко', 'ar' => 'سهل', 'az' => 'asan'],
        'eins' => ['en' => 'one', 'es' => 'uno', 'fr' => 'un', 'ja' => '一', 'ko' => '하나', 'tr' => 'bir', 'ru' => 'один', 'ar' => 'واحد', 'az' => 'bir'],
        'eiswürfeln' => ['en' => 'ice cubes', 'es' => 'cubitos de hielo', 'fr' => 'glaçons', 'ja' => '氷', 'ko' => '얼음', 'tr' => 'buz', 'ru' => 'кубики льда', 'ar' => 'مكعبات ثلج', 'az' => 'buz parçaları'],
        'enthält' => ['en' => 'contains', 'es' => 'contiene', 'fr' => 'contient', 'ja' => '含む', 'ko' => '들어있다', 'tr' => 'içerir', 'ru' => 'содержит', 'ar' => 'يحتوي', 'az' => 'tərkibində var'],
        'entschuldigen' => ['en' => 'excuse', 'es' => 'disculpe', 'fr' => 'excusez', 'ja' => 'すみません', 'ko' => '실례', 'tr' => 'affedersiniz', 'ru' => 'извините', 'ar' => 'عفوا', 'az' => 'bağışlayın'],
        'entschuldigen Sie' => ['en' => 'excuse me', 'es' => 'disculpe', 'fr' => 'excusez-moi', 'ja' => 'すみません', 'ko' => '실례합니다', 'tr' => 'affedersiniz', 'ru' => 'извините', 'ar' => 'عفوا', 'az' => 'bağışlayın'],
        'er' => ['en' => 'he', 'es' => 'él', 'fr' => 'il', 'ja' => '彼', 'ko' => '그', 'tr' => 'o', 'ru' => 'он', 'ar' => 'هو', 'az' => 'o kişi'],
        'er ist' => ['en' => 'he is', 'es' => 'él es', 'fr' => 'il est', 'ja' => '彼は', 'ko' => '그는', 'tr' => 'o', 'ru' => 'он', 'ar' => 'هو', 'az' => 'o'],
        'es' => ['en' => 'it', 'es' => 'eso', 'fr' => 'ce', 'ja' => 'それ', 'ko' => '그것', 'tr' => 'o', 'ru' => 'оно', 'ar' => 'هو', 'az' => 'o'],
        'es war' => ['en' => 'it was', 'es' => 'fue', 'fr' => 'c\'était', 'ja' => 'でした', 'ko' => '였습니다', 'tr' => 'idi', 'ru' => 'было', 'ar' => 'كان', 'az' => 'idi'],
        'esse' => ['en' => 'eat', 'es' => 'comer', 'fr' => 'manger', 'ja' => '食べる', 'ko' => '먹다', 'tr' => 'ye', 'ru' => 'ем', 'ar' => 'آكل', 'az' => 'yeyirəm'],
        'essen' => ['en' => 'eat', 'es' => 'comer', 'fr' => 'manger', 'ja' => '食べる', 'ko' => '먹다', 'tr' => 'ye', 'ru' => 'ем', 'ar' => 'آكل', 'az' => 'yeyirəm'],
        'etwas' => ['en' => 'some', 'es' => 'algo de', 'fr' => 'du', 'ja' => '少しの', 'ko' => '약간의', 'tr' => 'biraz', 'ru' => 'немного', 'ar' => 'بعض', 'az' => 'bir az'],
        'falsch' => ['en' => 'false', 'es' => 'falso', 'fr' => 'faux', 'ja' => '偽', 'ko' => '거짓', 'tr' => 'yanlış', 'ru' => 'неверно', 'ar' => 'خطأ', 'az' => 'səhv'],
        'fertig' => ['en' => 'ready', 'es' => 'listo', 'fr' => 'prêt', 'ja' => 'できた', 'ko' => '준비된', 'tr' => 'hazır', 'ru' => 'готов', 'ar' => 'جاهز', 'az' => 'hazır'],
        'finden' => ['en' => 'to find', 'es' => 'encontrar', 'fr' => 'trouver', 'ja' => '見つける', 'ko' => '발견하다', 'tr' => 'bulmak', 'ru' => 'найти', 'ar' => 'العثور', 'az' => 'tapmaq'],
        'fisches' => ['en' => 'fish', 'es' => 'pescado', 'fr' => 'poisson', 'ja' => '魚', 'ko' => '생선', 'tr' => 'balık', 'ru' => 'рыба', 'ar' => 'سمك', 'az' => 'balıq'],
        'flaschen' => ['en' => 'bottles', 'es' => 'botellas', 'fr' => 'bouteilles', 'ja' => 'ボトル', 'ko' => '병', 'tr' => 'şişeler', 'ru' => 'бутылки', 'ar' => 'زجاجات', 'az' => 'şüşələr'],
        'frei' => ['en' => 'free', 'es' => 'libre', 'fr' => 'libre', 'ja' => '暇', 'ko' => '한가한', 'tr' => 'boş', 'ru' => 'бесплатно', 'ar' => 'مجاني', 'az' => 'pulsuz'],
        'freut' => ['en' => 'glad', 'es' => 'encanta', 'fr' => 'ravi', 'ja' => '嬉しい', 'ko' => '기쁘다', 'tr' => 'memnun', 'ru' => 'рада', 'ar' => 'سعيد', 'az' => 'şad'],
        'freut mich' => ['en' => 'nice to meet you', 'es' => 'encantado', 'fr' => 'enchanté', 'ja' => 'はじめまして', 'ko' => '반갑습니다', 'tr' => 'memnun oldum', 'ru' => 'приятно познакомиться', 'ar' => 'تشرفنا', 'az' => 'tanış olmağa şadam'],
        'frisch' => ['en' => 'fresh', 'es' => 'fresco', 'fr' => 'frais', 'ja' => '新鮮', 'ko' => '신선한', 'tr' => 'taze', 'ru' => 'свежий', 'ar' => 'طازج', 'az' => 'təzə'],
        'frische' => ['en' => 'fresh', 'es' => 'fresco', 'fr' => 'frais', 'ja' => '新鮮', 'ko' => '신선한', 'tr' => 'taze', 'ru' => 'свежий', 'ar' => 'طازج', 'az' => 'təzə'],
        'frischer' => ['en' => 'fresh', 'es' => 'fresco', 'fr' => 'frais', 'ja' => '新鮮', 'ko' => '신선한', 'tr' => 'taze', 'ru' => 'свежий', 'ar' => 'طازج', 'az' => 'təzə'],
        'frisches' => ['en' => 'fresh', 'es' => 'fresco', 'fr' => 'frais', 'ja' => '新鮮', 'ko' => '신선한', 'tr' => 'taze', 'ru' => 'свежий', 'ar' => 'طازج', 'az' => 'təzə'],
        'froh' => ['en' => 'glad', 'es' => 'contento', 'fr' => 'content', 'ja' => '嬉しい', 'ko' => '기쁜', 'tr' => 'memnun', 'ru' => 'рада', 'ar' => 'سعيد', 'az' => 'şad'],
        'fühle' => ['en' => 'feel', 'es' => 'siento', 'fr' => 'sens', 'ja' => '感じる', 'ko' => '느끼다', 'tr' => 'hisset', 'ru' => 'чувствую', 'ar' => 'أشعر', 'az' => 'hiss edirəm'],
        'fünf' => ['en' => 'five', 'es' => 'cinco', 'fr' => 'cinq', 'ja' => '五', 'ko' => '다섯', 'tr' => 'beş', 'ru' => 'пять', 'ar' => 'خمسة', 'az' => 'beş'],
        'für' => ['en' => 'for', 'es' => 'para', 'fr' => 'pour', 'ja' => 'のために', 'ko' => '위해', 'tr' => 'için', 'ru' => 'для', 'ar' => 'لأجل', 'az' => 'üçün'],
        'geben Sie mir' => ['en' => 'give me', 'es' => 'deme', 'fr' => 'donnez-moi', 'ja' => 'ください', 'ko' => '주세요', 'tr' => 'bana ver', 'ru' => 'дайте мне', 'ar' => 'أعطني', 'az' => 'mənə ver'],
        'gegen' => ['en' => 'against', 'es' => 'contra', 'fr' => 'contre', 'ja' => 'に対して', 'ko' => '에 대해', 'tr' => 'karşı', 'ru' => 'против', 'ar' => 'ضد', 'az' => 'qarşı'],
        'geh' => ['en' => 'walk', 'es' => 'caminar', 'fr' => 'marcher', 'ja' => '歩く', 'ko' => '걷다', 'tr' => 'yürü', 'ru' => 'гуляю', 'ar' => 'أتمشى', 'az' => 'gəzirəm'],
        'gehe' => ['en' => 'walk', 'es' => 'caminar', 'fr' => 'marcher', 'ja' => '歩く', 'ko' => '걷다', 'tr' => 'yürü', 'ru' => 'гуляю', 'ar' => 'أتمشى', 'az' => 'gəzirəm'],
        'gehen' => ['en' => 'walk', 'es' => 'caminar', 'fr' => 'marcher', 'ja' => '歩く', 'ko' => '걷다', 'tr' => 'yürü', 'ru' => 'гуляю', 'ar' => 'أتمشى', 'az' => 'gəzirəm'],
        'geht' => ['en' => 'walk', 'es' => 'caminar', 'fr' => 'marcher', 'ja' => '歩く', 'ko' => '걷다', 'tr' => 'yürü', 'ru' => 'гуляю', 'ar' => 'أتمشى', 'az' => 'gəzirəm'],
        'gelb' => ['en' => 'yellow', 'es' => 'amarillo', 'fr' => 'jaune', 'ja' => '黄色', 'ko' => '노란색', 'tr' => 'sarı', 'ru' => 'жёлтый', 'ar' => 'أصفر', 'az' => 'sarı'],
        'gelber' => ['en' => 'yellow', 'es' => 'amarillo', 'fr' => 'jaune', 'ja' => '黄色', 'ko' => '노란색', 'tr' => 'sarı', 'ru' => 'жёлтый', 'ar' => 'أصفر', 'az' => 'sarı'],
        'gelbes' => ['en' => 'yellow', 'es' => 'amarillo', 'fr' => 'jaune', 'ja' => '黄色', 'ko' => '노란색', 'tr' => 'sarı', 'ru' => 'жёлтый', 'ar' => 'أصفر', 'az' => 'sarı'],
        'genauso' => ['en' => 'just as', 'es' => 'igual', 'fr' => 'aussi', 'ja' => '同じくらい', 'ko' => '똑같이', 'tr' => 'tıpkı', 'ru' => 'как', 'ar' => 'مثل', 'az' => 'kimi'],
        'genauso viel' => ['en' => 'as much', 'es' => 'tanto', 'fr' => 'autant', 'ja' => '同じくらい', 'ko' => '그만큼', 'tr' => 'bu kadar', 'ru' => 'столько же', 'ar' => 'بقدر', 'az' => 'qədər'],
        'genug' => ['en' => 'enough', 'es' => 'bastante', 'fr' => 'assez', 'ja' => '十分に', 'ko' => '충분히', 'tr' => 'yeterli', 'ru' => 'достаточно', 'ar' => 'كفى', 'az' => 'kifayət'],
        'geradeaus' => ['en' => 'straight', 'es' => 'recto', 'fr' => 'tout droit', 'ja' => 'まっすぐ', 'ko' => '똑바로', 'tr' => 'düz', 'ru' => 'прямо', 'ar' => 'مباشرة', 'az' => 'düz'],
        'geschlossen' => ['en' => 'closed', 'es' => 'cerrado', 'fr' => 'fermé', 'ja' => '閉じた', 'ko' => '닫힌', 'tr' => 'kapalı', 'ru' => 'закрыто', 'ar' => 'مغلق', 'az' => 'bağlı'],
        'gestern' => ['en' => 'yesterday', 'es' => 'ayer', 'fr' => 'hier', 'ja' => '昨日', 'ko' => '어제', 'tr' => 'dün', 'ru' => 'вчера', 'ar' => 'أمس', 'az' => 'dünən'],
        'getrennt' => ['en' => 'separately', 'es' => 'por separado', 'fr' => 'séparément', 'ja' => '別々に', 'ko' => '따로', 'tr' => 'ayrı', 'ru' => 'отдельно', 'ar' => 'منفصل', 'az' => 'ayrıca'],
        'getränk' => ['en' => 'drink', 'es' => 'bebida', 'fr' => 'boisson', 'ja' => '飲み物', 'ko' => '음료', 'tr' => 'iç', 'ru' => 'напиток', 'ar' => 'مشروب', 'az' => 'içki'],
        'glaube' => ['en' => 'believe', 'es' => 'creo', 'fr' => 'crois', 'ja' => '信じる', 'ko' => '믿다', 'tr' => 'inanmak', 'ru' => 'верю', 'ar' => 'أعتقد', 'az' => 'inanıram'],
        'gleich' => ['en' => 'same', 'es' => 'mismo', 'fr' => 'même', 'ja' => '同じ', 'ko' => '같은', 'tr' => 'aynı', 'ru' => 'такой же', 'ar' => 'نفسه', 'az' => 'eyni'],
        'gleiche' => ['en' => 'same', 'es' => 'mismo', 'fr' => 'même', 'ja' => '同じ', 'ko' => '같은', 'tr' => 'aynı', 'ru' => 'такой же', 'ar' => 'نفسه', 'az' => 'eyni'],
        'glücklich' => ['en' => 'happy', 'es' => 'feliz', 'fr' => 'heureux', 'ja' => '幸せ', 'ko' => '행복한', 'tr' => 'mutlu', 'ru' => 'счастливый', 'ar' => 'فرح', 'az' => 'xoşbəxt'],
        'gnädige Frau' => ['en' => 'madam', 'es' => 'señora', 'fr' => 'madame', 'ja' => 'マダム', 'ko' => '부인', 'tr' => 'hanımefendi', 'ru' => 'госпожа', 'ar' => 'سيدتي', 'az' => 'xanım'],
        'groß' => ['en' => 'big', 'es' => 'grande', 'fr' => 'grand', 'ja' => '大きい', 'ko' => '큰', 'tr' => 'büyük', 'ru' => 'большой', 'ar' => 'كبير', 'az' => 'böyük'],
        'große' => ['en' => 'big', 'es' => 'grande', 'fr' => 'grand', 'ja' => '大きい', 'ko' => '큰', 'tr' => 'büyük', 'ru' => 'большой', 'ar' => 'كبير', 'az' => 'böyük'],
        'großes' => ['en' => 'big', 'es' => 'grande', 'fr' => 'grand', 'ja' => '大きい', 'ko' => '큰', 'tr' => 'büyük', 'ru' => 'большой', 'ar' => 'كبير', 'az' => 'böyük'],
        'grün' => ['en' => 'green', 'es' => 'verde', 'fr' => 'vert', 'ja' => '緑', 'ko' => '초록색', 'tr' => 'yeşil', 'ru' => 'зелёный', 'ar' => 'أخضر', 'az' => 'yaşıl'],
        'grüner' => ['en' => 'green', 'es' => 'verde', 'fr' => 'vert', 'ja' => '緑', 'ko' => '초록색', 'tr' => 'yeşil', 'ru' => 'зелёный', 'ar' => 'أخضر', 'az' => 'yaşıl'],
        'grünes' => ['en' => 'green', 'es' => 'verde', 'fr' => 'vert', 'ja' => '緑', 'ko' => '초록색', 'tr' => 'yeşil', 'ru' => 'зелёный', 'ar' => 'أخضر', 'az' => 'yaşıl'],
        'gut' => ['en' => 'well', 'es' => 'bien', 'fr' => 'bien', 'ja' => '元気', 'ko' => '잘', 'tr' => 'iyi', 'ru' => 'хорошо', 'ar' => 'بخير', 'az' => 'yaxşıyam'],
        'guter' => ['en' => 'well', 'es' => 'bien', 'fr' => 'bien', 'ja' => '元気', 'ko' => '잘', 'tr' => 'iyi', 'ru' => 'хорошо', 'ar' => 'بخير', 'az' => 'yaxşıyam'],
        'gutes' => ['en' => 'well', 'es' => 'bien', 'fr' => 'bien', 'ja' => '元気', 'ko' => '잘', 'tr' => 'iyi', 'ru' => 'хорошо', 'ar' => 'بخير', 'az' => 'yaxşıyam'],
        'habe' => ['en' => 'have', 'es' => 'tengo', 'fr' => 'ai', 'ja' => '持つ', 'ko' => '가지다', 'tr' => 'sahip ol', 'ru' => 'есть', 'ar' => 'عند', 'az' => 'var'],
        'hallo' => ['en' => 'hello', 'es' => 'hola', 'fr' => 'bonjour', 'ja' => 'こんにちは', 'ko' => '안녕하세요', 'tr' => 'merhaba', 'ru' => 'привет', 'ar' => 'مرحبا', 'az' => 'salam'],
        'harter' => ['en' => 'hard', 'es' => 'duro', 'fr' => 'dur', 'ja' => '硬い', 'ko' => '단단한', 'tr' => 'zor', 'ru' => 'трудно', 'ar' => 'صعب', 'az' => 'çətin'],
        'hause' => ['en' => 'house', 'es' => 'casa', 'fr' => 'maison', 'ja' => '家', 'ko' => '집', 'tr' => 'ev', 'ru' => 'дом', 'ar' => 'بيت', 'az' => 'ev'],
        'heiß' => ['en' => 'hot', 'es' => 'caliente', 'fr' => 'chaud', 'ja' => '熱い', 'ko' => '뜨거운', 'tr' => 'sıcak', 'ru' => 'горячий', 'ar' => 'ساخن', 'az' => 'isti'],
        'heißen' => ['en' => 'hot', 'es' => 'caliente', 'fr' => 'chaud', 'ja' => '熱い', 'ko' => '뜨거운', 'tr' => 'sıcak', 'ru' => 'горячий', 'ar' => 'ساخن', 'az' => 'isti'],
        'heißer' => ['en' => 'hot', 'es' => 'caliente', 'fr' => 'chaud', 'ja' => '熱い', 'ko' => '뜨거운', 'tr' => 'sıcak', 'ru' => 'горячий', 'ar' => 'ساخن', 'az' => 'isti'],
        'heute' => ['en' => 'today', 'es' => 'hoy', 'fr' => 'aujourd\'hui', 'ja' => '今日', 'ko' => '오늘', 'tr' => 'bugün', 'ru' => 'сегодня', 'ar' => 'اليوم', 'az' => 'bu gün'],
        'heute Abend' => ['en' => 'tonight', 'es' => 'esta noche', 'fr' => 'ce soir', 'ja' => '今夜', 'ko' => '오늘 밤', 'tr' => 'bu akşam', 'ru' => 'сегодня вечером', 'ar' => 'الليلة', 'az' => 'bu axşam'],
        'hier' => ['en' => 'here', 'es' => 'aquí', 'fr' => 'ici', 'ja' => 'ここ', 'ko' => '여기', 'tr' => 'burada', 'ru' => 'здесь', 'ar' => 'هنا', 'az' => 'burada'],
        'hier ist' => ['en' => 'here is', 'es' => 'aquí está', 'fr' => 'voici', 'ja' => 'これが', 'ko' => '여기', 'tr' => 'işte', 'ru' => 'здесь', 'ar' => 'هنا', 'az' => 'burada'],
        'hieressen' => ['en' => 'eat in', 'es' => 'tomar aquí', 'fr' => 'sur place', 'ja' => '店内で', 'ko' => '매장에서', 'tr' => 'burada ye', 'ru' => 'ем в', 'ar' => 'آكل في', 'az' => 'yeyirəm içində'],
        'hinten' => ['en' => 'behind', 'es' => 'detrás', 'fr' => 'derrière', 'ja' => '後ろに', 'ko' => '뒤에', 'tr' => 'arkasında', 'ru' => 'сзади', 'ar' => 'خلف', 'az' => 'arxada'],
        'hinter' => ['en' => 'behind', 'es' => 'detrás', 'fr' => 'derrière', 'ja' => '後ろ', 'ko' => '뒤에', 'tr' => 'arkasında', 'ru' => 'сзади', 'ar' => 'خلف', 'az' => 'arxada'],
        'hungrig' => ['en' => 'hungry', 'es' => 'hambriento', 'fr' => 'affamé', 'ja' => 'お腹がすいた', 'ko' => '배고픈', 'tr' => 'aç', 'ru' => 'голодный', 'ar' => 'جائع', 'az' => 'ac'],
        'hähnchens' => ['en' => 'chicken', 'es' => 'pollo', 'fr' => 'poulet', 'ja' => '鶏肉', 'ko' => '닭고기', 'tr' => 'tavuk', 'ru' => 'курица', 'ar' => 'دجاج', 'az' => 'toyuq'],
        'hübsch' => ['en' => 'pretty', 'es' => 'bonito', 'fr' => 'joli', 'ja' => 'かわいい', 'ko' => '예쁜', 'tr' => 'güzel', 'ru' => 'красивый', 'ar' => 'جميل', 'az' => 'gözəl'],
        'hübscher' => ['en' => 'pretty', 'es' => 'bonito', 'fr' => 'joli', 'ja' => 'かわいい', 'ko' => '예쁜', 'tr' => 'güzel', 'ru' => 'красивый', 'ar' => 'جميل', 'az' => 'gözəl'],
        'ich' => ['en' => 'I', 'es' => 'yo', 'fr' => 'je', 'ja' => '私', 'ko' => '나', 'tr' => 'ben', 'ru' => 'я', 'ar' => 'أنا', 'az' => 'mən'],
        'ich aß' => ['en' => 'I ate', 'es' => 'comí', 'fr' => 'j\'ai mangé', 'ja' => '私は食べた', 'ko' => '나는 먹었다', 'tr' => 'yedim', 'ru' => 'я ел', 'ar' => 'أكلت', 'az' => 'yedim'],
        'ich bevorzuge' => ['en' => 'I prefer', 'es' => 'prefiero', 'fr' => 'je préfère', 'ja' => '私は好む', 'ko' => '나는 선호한다', 'tr' => 'tercih ederim', 'ru' => 'я предпочитаю', 'ar' => 'أفضل', 'az' => 'üstünlük verirəm'],
        'ich bezahle' => ['en' => 'I pay', 'es' => 'pago', 'fr' => 'je paie', 'ja' => '私が払う', 'ko' => '제가 냅니다', 'tr' => 'ödüyorum', 'ru' => 'я плачу', 'ar' => 'أدفع', 'az' => 'ödəyirəm'],
        'ich bin' => ['en' => 'I am', 'es' => 'soy', 'fr' => 'je suis', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'ben', 'ru' => 'я', 'ar' => 'أنا', 'az' => 'mən'],
        'ich brauche' => ['en' => 'I need', 'es' => 'necesito', 'fr' => 'j\'ai besoin', 'ja' => '必要です', 'ko' => '필요합니다', 'tr' => 'ihtiyacım var', 'ru' => 'мне нужно', 'ar' => 'أحتاج', 'az' => 'lazımdır'],
        'ich denke' => ['en' => 'I think', 'es' => 'creo', 'fr' => 'je pense', 'ja' => '私は思う', 'ko' => '나는 생각한다', 'tr' => 'düşünüyorum', 'ru' => 'я думаю', 'ar' => 'أفكر', 'az' => 'düşünürəm'],
        'ich fühle mich' => ['en' => 'I feel', 'es' => 'me siento', 'fr' => 'je me sens', 'ja' => '私は感じる', 'ko' => '나는 느낍니다', 'tr' => 'hissediyorum', 'ru' => 'я чувствую', 'ar' => 'أشعر', 'az' => 'hiss edirəm'],
        'ich gehe' => ['en' => 'I am going', 'es' => 'voy', 'fr' => 'je vais', 'ja' => '私は行く', 'ko' => '나는 갈 것이다', 'tr' => 'gidiyorum', 'ru' => 'я иду', 'ar' => 'أذهب', 'az' => 'gedirəm'],
        'ich glaube' => ['en' => 'I believe', 'es' => 'creo que', 'fr' => 'je crois', 'ja' => '私は信じる', 'ko' => '나는 믿는다', 'tr' => 'bence', 'ru' => 'я думаю', 'ar' => 'أعتقد', 'az' => 'inanıram'],
        'ich habe' => ['en' => 'I have', 'es' => 'tengo', 'fr' => 'j\'ai', 'ja' => '私は持っている', 'ko' => '나는 가지고 있다', 'tr' => 'var', 'ru' => 'у меня', 'ar' => 'عندي', 'az' => 'məndə var'],
        'ich kann' => ['en' => 'I can', 'es' => 'puedo', 'fr' => 'je peux', 'ja' => '私はできる', 'ko' => '나는 할 수 있다', 'tr' => 'yapabilirim', 'ru' => 'я могу', 'ar' => 'أنا أستطيع', 'az' => 'mən bacarıram'],
        'ich möchte' => ['en' => 'I would like', 'es' => 'quisiera', 'fr' => 'je voudrais', 'ja' => 'ください', 'ko' => '주세요', 'tr' => 'istiyorum', 'ru' => 'я хочу', 'ar' => 'أريد', 'az' => 'istəyirəm'],
        'ich nehme' => ['en' => 'I\'ll have', 'es' => 'tomo', 'fr' => 'je prends', 'ja' => 'にします', 'ko' => '하겠습니다', 'tr' => 'alayım', 'ru' => 'я возьму', 'ar' => 'سآخذ', 'az' => 'götürəcəyəm'],
        'ich sah' => ['en' => 'I saw', 'es' => 'vi', 'fr' => 'j\'ai vu', 'ja' => '私は見た', 'ko' => '나는 보았다', 'tr' => 'gördüm', 'ru' => 'я видел', 'ar' => 'رأيت', 'az' => 'gördüm'],
        'ich trank' => ['en' => 'I drank', 'es' => 'bebí', 'fr' => 'j\'ai bu', 'ja' => '私は飲んだ', 'ko' => '나는 마셨다', 'tr' => 'içtim', 'ru' => 'я пил', 'ar' => 'شربت', 'az' => 'içdim'],
        'ich war' => ['en' => 'I was', 'es' => 'estaba', 'fr' => 'j\'étais', 'ja' => 'でした', 'ko' => '였습니다', 'tr' => 'idim', 'ru' => 'я был', 'ar' => 'كنت', 'az' => 'idim'],
        'ich will' => ['en' => 'I want', 'es' => 'quiero', 'fr' => 'je veux', 'ja' => 'たいです', 'ko' => '나는 원한다', 'tr' => 'istiyorum', 'ru' => 'я хочу', 'ar' => 'أريد', 'az' => 'istəyirəm'],
        'ich wohne' => ['en' => 'I live', 'es' => 'vivo', 'fr' => 'j\'habite', 'ja' => '私は住んでいる', 'ko' => '나는 삽니다', 'tr' => 'yaşıyorum', 'ru' => 'я живу', 'ar' => 'أسكن', 'az' => 'yaşayıram'],
        'im' => ['en' => 'in the', 'es' => 'en el', 'fr' => 'dans le', 'ja' => 'の中に', 'ko' => '안에', 'tr' => 'içinde', 'ru' => 'в', 'ar' => 'في', 'az' => 'içində'],
        'in' => ['en' => 'in', 'es' => 'en', 'fr' => 'dans', 'ja' => 'の中に', 'ko' => '안에', 'tr' => 'içinde', 'ru' => 'в', 'ar' => 'في', 'az' => 'içində'],
        'in bar' => ['en' => 'cash', 'es' => 'en efectivo', 'fr' => 'en espèces', 'ja' => '現金で', 'ko' => '현금으로', 'tr' => 'nakit', 'ru' => 'наличные', 'ar' => 'كاش', 'az' => 'nağd'],
        'iss' => ['en' => 'eat', 'es' => 'come', 'fr' => 'mange', 'ja' => '食べる', 'ko' => '먹다', 'tr' => 'ye', 'ru' => 'ем', 'ar' => 'آكل', 'az' => 'yeyirəm'],
        'ist' => ['en' => 'is', 'es' => 'es', 'fr' => 'est', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'dır', 'ru' => 'есть', 'ar' => 'يكون', 'az' => 'olmaq'],
        'ja' => ['en' => 'yes', 'es' => 'sí', 'fr' => 'oui', 'ja' => 'はい', 'ko' => '네', 'tr' => 'evet', 'ru' => 'да', 'ar' => 'نعم', 'az' => 'bəli'],
        'jahre' => ['en' => 'years', 'es' => 'años', 'fr' => 'ans', 'ja' => '歳', 'ko' => '살', 'tr' => 'yıl', 'ru' => 'лет', 'ar' => 'سنوات', 'az' => 'yaşında'],
        'jeder' => ['en' => 'each', 'es' => 'cada', 'fr' => 'chaque', 'ja' => 'それぞれの', 'ko' => '각각의', 'tr' => 'her', 'ru' => 'каждый', 'ar' => 'كل', 'az' => 'hər biri'],
        'jedes' => ['en' => 'each', 'es' => 'cada', 'fr' => 'chaque', 'ja' => 'それぞれ', 'ko' => '각각', 'tr' => 'her', 'ru' => 'каждый', 'ar' => 'كل', 'az' => 'hər biri'],
        'jene' => ['en' => 'those', 'es' => 'esos', 'fr' => 'ces', 'ja' => 'あれらの', 'ko' => '저것들', 'tr' => 'onlar', 'ru' => 'те', 'ar' => 'تلك', 'az' => 'onlar'],
        'jener' => ['en' => 'that', 'es' => 'ese', 'fr' => 'cette', 'ja' => 'あの', 'ko' => '저', 'tr' => 'o', 'ru' => 'тот', 'ar' => 'ذلك', 'az' => 'o'],
        'jenes' => ['en' => 'that', 'es' => 'ese', 'fr' => 'ce', 'ja' => 'あの', 'ko' => '저', 'tr' => 'o', 'ru' => 'тот', 'ar' => 'ذلك', 'az' => 'o'],
        'jetzt' => ['en' => 'now', 'es' => 'ahora', 'fr' => 'maintenant', 'ja' => '今', 'ko' => '지금', 'tr' => 'şimdi', 'ru' => 'сейчас', 'ar' => 'الآن', 'az' => 'indi'],
        'kalt' => ['en' => 'cold', 'es' => 'frío', 'fr' => 'froid', 'ja' => '冷たい', 'ko' => '차가운', 'tr' => 'soğuk', 'ru' => 'холодный', 'ar' => 'بارد', 'az' => 'soyuq'],
        'kalter' => ['en' => 'cold', 'es' => 'frío', 'fr' => 'froid', 'ja' => '冷たい', 'ko' => '차가운', 'tr' => 'soğuk', 'ru' => 'холодный', 'ar' => 'بارد', 'az' => 'soyuq'],
        'kaltes' => ['en' => 'cold', 'es' => 'frío', 'fr' => 'froid', 'ja' => '冷たい', 'ko' => '차가운', 'tr' => 'soğuk', 'ru' => 'холодный', 'ar' => 'بارد', 'az' => 'soyuq'],
        'kann' => ['en' => 'can', 'es' => 'puedo', 'fr' => 'peux', 'ja' => 'できる', 'ko' => '할 수 있다', 'tr' => 'yapabilir', 'ru' => 'могу', 'ar' => 'أستطيع', 'az' => 'bacarıram'],
        'kaufen' => ['en' => 'to buy', 'es' => 'comprar', 'fr' => 'acheter', 'ja' => '買う', 'ko' => '사다', 'tr' => 'almak', 'ru' => 'купить', 'ar' => 'الشراء', 'az' => 'almaq'],
        'keine' => ['en' => 'no', 'es' => 'ninguna', 'fr' => 'pas de', 'ja' => 'ない', 'ko' => '없는', 'tr' => 'hayır', 'ru' => 'нет', 'ar' => 'لا', 'az' => 'xeyr'],
        'kindermenü' => ['en' => 'kids menu', 'es' => 'menú infantil', 'fr' => 'menu enfant', 'ja' => 'キッズメニュー', 'ko' => '어린이 메뉴', 'tr' => 'çocuk menüsü', 'ru' => 'детское меню', 'ar' => 'قائمة الأطفال', 'az' => 'uşaq menyusu'],
        'klein' => ['en' => 'small', 'es' => 'pequeño', 'fr' => 'petit', 'ja' => '小さい', 'ko' => '작은', 'tr' => 'küçük', 'ru' => 'маленький', 'ar' => 'صغير', 'az' => 'kiçik'],
        'kleine' => ['en' => 'small', 'es' => 'pequeño', 'fr' => 'petit', 'ja' => '小さい', 'ko' => '작은', 'tr' => 'küçük', 'ru' => 'маленький', 'ar' => 'صغير', 'az' => 'kiçik'],
        'kommen' => ['en' => 'come', 'es' => 'venir', 'fr' => 'venir', 'ja' => '来る', 'ko' => '오다', 'tr' => 'gel', 'ru' => 'приходи', 'ar' => 'تعال', 'az' => 'gəl'],
        'kostet' => ['en' => 'costs', 'es' => 'cuesta', 'fr' => 'coûte', 'ja' => 'かかる', 'ko' => '입니다', 'tr' => 'tutar', 'ru' => 'стоит', 'ar' => 'يكلف', 'az' => 'qiyməti'],
        'krank' => ['en' => 'sick', 'es' => 'enfermo', 'fr' => 'malade', 'ja' => '病気', 'ko' => '아픈', 'tr' => 'hasta', 'ru' => 'больной', 'ar' => 'مريض', 'az' => 'xəstə'],
        'kuchens' => ['en' => 'cake', 'es' => 'pastel', 'fr' => 'gâteau', 'ja' => 'ケーキ', 'ko' => '케이크', 'tr' => 'pasta', 'ru' => 'торт', 'ar' => 'كعكة', 'az' => 'tort'],
        'können' => ['en' => 'can', 'es' => 'puede', 'fr' => 'pouvez', 'ja' => 'できる', 'ko' => '할 수 있다', 'tr' => 'yapabilir', 'ru' => 'могу', 'ar' => 'أستطيع', 'az' => 'bacarıram'],
        'können Sie' => ['en' => 'can you', 'es' => 'puede usted', 'fr' => 'pouvez-vous', 'ja' => 'できますか', 'ko' => '주시겠어요', 'tr' => 'yapabilir misiniz', 'ru' => 'могу ты', 'ar' => 'أستطيع أنت', 'az' => 'bacarıram sən'],
        'köstlich' => ['en' => 'delicious', 'es' => 'delicioso', 'fr' => 'délicieux', 'ja' => 'おいしい', 'ko' => '맛있는', 'tr' => 'lezzetli', 'ru' => 'вкусный', 'ar' => 'لذيذ', 'az' => 'dadlı'],
        'köstlicher' => ['en' => 'delicious', 'es' => 'delicioso', 'fr' => 'délicieux', 'ja' => 'おいしい', 'ko' => '맛있는', 'tr' => 'lezzetli', 'ru' => 'вкусный', 'ar' => 'لذيذ', 'az' => 'dadlı'],
        'langsam' => ['en' => 'slowly', 'es' => 'despacio', 'fr' => 'lentement', 'ja' => 'ゆっくり', 'ko' => '천천히', 'tr' => 'yavaş', 'ru' => 'медленно', 'ar' => 'ببطء', 'az' => 'yavaş'],
        'lass' => ['en' => 'let', 'es' => 'deja', 'fr' => 'laisse', 'ja' => 'させる', 'ko' => '하자', 'tr' => 'izin ver', 'ru' => 'пусть', 'ar' => 'دع', 'az' => 'qoy'],
        'lass uns gehen' => ['en' => 'let\'s go', 'es' => 'vamos', 'fr' => 'allons-y', 'ja' => '行きましょう', 'ko' => '갑시다', 'tr' => 'gidelim', 'ru' => 'пойдём', 'ar' => 'هيا بنا', 'az' => 'gedək'],
        'leer' => ['en' => 'empty', 'es' => 'vacío', 'fr' => 'vide', 'ja' => '空', 'ko' => '빈', 'tr' => 'boş', 'ru' => 'пустой', 'ar' => 'فارغ', 'az' => 'boş'],
        'legen' => ['en' => 'to put', 'es' => 'poner', 'fr' => 'mettre', 'ja' => '入れる', 'ko' => '넣다', 'tr' => 'koymak', 'ru' => 'положить', 'ar' => 'وضع', 'az' => 'qoymaq'],
        'leicht' => ['en' => 'light', 'es' => 'ligero', 'fr' => 'léger', 'ja' => '軽い', 'ko' => '가벼운', 'tr' => 'hafif', 'ru' => 'лёгкий', 'ar' => 'خفيف', 'az' => 'yüngül'],
        'lese' => ['en' => 'read', 'es' => 'leer', 'fr' => 'lire', 'ja' => '読む', 'ko' => '읽다', 'tr' => 'oku', 'ru' => 'читаю', 'ar' => 'أقرأ', 'az' => 'oxuyuram'],
        'lesen' => ['en' => 'read', 'es' => 'leer', 'fr' => 'lire', 'ja' => '読む', 'ko' => '읽다', 'tr' => 'oku', 'ru' => 'читаю', 'ar' => 'أقرأ', 'az' => 'oxuyuram'],
        'links' => ['en' => 'left', 'es' => 'izquierda', 'fr' => 'gauche', 'ja' => '左', 'ko' => '왼쪽', 'tr' => 'sol', 'ru' => 'левый', 'ar' => 'يسار', 'az' => 'sol'],
        'mehr' => ['en' => 'more', 'es' => 'más', 'fr' => 'plus', 'ja' => 'もっと', 'ko' => '더', 'tr' => 'daha çok', 'ru' => 'больше', 'ar' => 'أكثر', 'az' => 'daha'],
        'mein' => ['en' => 'my', 'es' => 'mi', 'fr' => 'mon', 'ja' => '私の', 'ko' => '나의', 'tr' => 'benim', 'ru' => 'мой', 'ar' => 'خاصتي', 'az' => 'mənim'],
        'mein Herr' => ['en' => 'sir', 'es' => 'señor', 'fr' => 'monsieur', 'ja' => 'ムッシュ', 'ko' => '선생님', 'tr' => 'beyefendi', 'ru' => 'господин', 'ar' => 'سيدي', 'az' => 'cənab'],
        'meine' => ['en' => 'my', 'es' => 'mi', 'fr' => 'ma', 'ja' => '私の', 'ko' => '나의', 'tr' => 'benim', 'ru' => 'мой', 'ar' => 'خاصتي', 'az' => 'mənim'],
        'meinem' => ['en' => 'my', 'es' => 'mi', 'fr' => 'mon', 'ja' => '私の', 'ko' => '나의', 'tr' => 'benim', 'ru' => 'мой', 'ar' => 'خاصتي', 'az' => 'mənim'],
        'meinen' => ['en' => 'my', 'es' => 'mi', 'fr' => 'mon', 'ja' => '私の', 'ko' => '나의', 'tr' => 'benim', 'ru' => 'мой', 'ar' => 'خاصتي', 'az' => 'mənim'],
        'meiner' => ['en' => 'my', 'es' => 'mi', 'fr' => 'mon', 'ja' => '私の', 'ko' => '나의', 'tr' => 'benim', 'ru' => 'мой', 'ar' => 'خاصتي', 'az' => 'mənim'],
        'menüs' => ['en' => 'menu', 'es' => 'menú', 'fr' => 'menu', 'ja' => 'メニュー', 'ko' => '메뉴', 'tr' => 'menü', 'ru' => 'меню', 'ar' => 'قائمة الطعام', 'az' => 'menyu'],
        'mich' => ['en' => 'me', 'es' => 'me', 'fr' => 'moi', 'ja' => '私', 'ko' => '저', 'tr' => 'ben', 'ru' => 'меня', 'ar' => 'لي', 'az' => 'mənə'],
        'mir' => ['en' => 'me', 'es' => 'me', 'fr' => 'moi', 'ja' => '私に', 'ko' => '나에게', 'tr' => 'ben', 'ru' => 'меня', 'ar' => 'لي', 'az' => 'mənə'],
        'mit' => ['en' => 'with', 'es' => 'con', 'fr' => 'avec', 'ja' => 'と一緒に', 'ko' => '와 함께', 'tr' => 'ile', 'ru' => 'с', 'ar' => 'مع', 'az' => 'ilə'],
        'mitnehmen' => ['en' => 'take away', 'es' => 'para llevar', 'fr' => 'à emporter', 'ja' => '持ち帰り', 'ko' => '포장', 'tr' => 'paket', 'ru' => 'с собой', 'ar' => 'للخارج', 'az' => 'özümlə'],
        'morgen' => ['en' => 'tomorrow', 'es' => 'mañana', 'fr' => 'demain', 'ja' => '明日', 'ko' => '내일', 'tr' => 'yarın', 'ru' => 'завтра', 'ar' => 'غدا', 'az' => 'sabah'],
        'möchte' => ['en' => 'would like', 'es' => 'quisiera', 'fr' => 'voudrais', 'ja' => 'ほしい', 'ko' => '원하다', 'tr' => 'istiyorum', 'ru' => 'хотел бы', 'ar' => 'أود', 'az' => 'istərdim'],
        'müde' => ['en' => 'tired', 'es' => 'cansado', 'fr' => 'fatigué', 'ja' => '疲れた', 'ko' => '피곤한', 'tr' => 'yorgun', 'ru' => 'усталый', 'ar' => 'متعب', 'az' => 'yorğun'],
        'nach' => ['en' => 'after', 'es' => 'después', 'fr' => 'après', 'ja' => '後に', 'ko' => '후에', 'tr' => 'sonra', 'ru' => 'после', 'ar' => 'بعد', 'az' => 'sonra'],
        'nah' => ['en' => 'near', 'es' => 'cerca', 'fr' => 'près', 'ja' => '近く', 'ko' => '가까이', 'tr' => 'yakın', 'ru' => 'близко', 'ar' => 'قريب', 'az' => 'yaxın'],
        'natürlich' => ['en' => 'of course', 'es' => 'por supuesto', 'fr' => 'bien sûr', 'ja' => 'もちろん', 'ko' => '물론', 'tr' => 'elbette', 'ru' => 'конечно', 'ar' => 'بالطبع', 'az' => 'əlbəttə'],
        'nehme' => ['en' => 'take', 'es' => 'tomo', 'fr' => 'prends', 'ja' => 'にします', 'ko' => '하겠습니다', 'tr' => 'al', 'ru' => 'взять', 'ar' => 'خذ', 'az' => 'götür'],
        'nein' => ['en' => 'no', 'es' => 'no', 'fr' => 'non', 'ja' => 'いいえ', 'ko' => '아니요', 'tr' => 'hayır', 'ru' => 'нет', 'ar' => 'لا', 'az' => 'xeyr'],
        'neu' => ['en' => 'new', 'es' => 'nuevo', 'fr' => 'nouveau', 'ja' => '新しい', 'ko' => '새로운', 'tr' => 'yeni', 'ru' => 'новый', 'ar' => 'جديد', 'az' => 'yeni'],
        'neues' => ['en' => 'new', 'es' => 'nuevo', 'fr' => 'nouveau', 'ja' => '新しい', 'ko' => '새로운', 'tr' => 'yeni', 'ru' => 'новый', 'ar' => 'جديد', 'az' => 'yeni'],
        'neun' => ['en' => 'nine', 'es' => 'nueve', 'fr' => 'neuf', 'ja' => '九', 'ko' => '아홉', 'tr' => 'dokuz', 'ru' => 'девять', 'ar' => 'تسعة', 'az' => 'doqquz'],
        'noch' => ['en' => 'another', 'es' => 'otro', 'fr' => 'encore', 'ja' => 'もう', 'ko' => '더', 'tr' => 'başka', 'ru' => 'другой', 'ar' => 'آخر', 'az' => 'başqa'],
        'noch ein' => ['en' => 'another', 'es' => 'otro', 'fr' => 'encore', 'ja' => 'もう一つの', 'ko' => '하나 더', 'tr' => 'başka', 'ru' => 'другой', 'ar' => 'آخر', 'az' => 'başqa'],
        'nächste' => ['en' => 'next', 'es' => 'próximo', 'fr' => 'prochain', 'ja' => '次の', 'ko' => '다음', 'tr' => 'sonraki', 'ru' => 'следующий', 'ar' => 'التالي', 'az' => 'növbəti'],
        'oder' => ['en' => 'or', 'es' => 'o', 'fr' => 'ou', 'ja' => 'または', 'ko' => '또는', 'tr' => 'veya', 'ru' => 'или', 'ar' => 'أو', 'az' => 'və ya'],
        'offen' => ['en' => 'open', 'es' => 'abierto', 'fr' => 'ouvert', 'ja' => '開いた', 'ko' => '열린', 'tr' => 'açık', 'ru' => 'открыто', 'ar' => 'مفتوح', 'az' => 'açıq'],
        'ohne' => ['en' => 'without', 'es' => 'sin', 'fr' => 'sans', 'ja' => 'なし', 'ko' => '없이', 'tr' => 'sız', 'ru' => 'без', 'ar' => 'بدون', 'az' => 'olmadan'],
        'okay' => ['en' => 'okay', 'es' => 'vale', 'fr' => 'd\'accord', 'ja' => 'いいよ', 'ko' => '좋아요', 'tr' => 'tamam', 'ru' => 'хорошо', 'ar' => 'حسنا', 'az' => 'yaxşı'],
        'perfekt' => ['en' => 'perfect', 'es' => 'perfecto', 'fr' => 'parfait', 'ja' => '完璧', 'ko' => '완벽한', 'tr' => 'mükemmel', 'ru' => 'идеально', 'ar' => 'مثالي', 'az' => 'mükəmməl'],
        'rechnung' => ['en' => 'bill', 'es' => 'cuenta', 'fr' => 'addition', 'ja' => '会計', 'ko' => '계산서', 'tr' => 'hesap', 'ru' => 'счёт', 'ar' => 'الحساب', 'az' => 'hesab'],
        'rechts' => ['en' => 'right', 'es' => 'derecha', 'fr' => 'droite', 'ja' => '右', 'ko' => '오른쪽', 'tr' => 'sağ', 'ru' => 'правый', 'ar' => 'يمين', 'az' => 'sağ'],
        'reises' => ['en' => 'rice', 'es' => 'arroz', 'fr' => 'riz', 'ja' => 'ご飯', 'ko' => '밥', 'tr' => 'pirinç', 'ru' => 'рис', 'ar' => 'أرز', 'az' => 'düyü'],
        'reservieren' => ['en' => 'to book', 'es' => 'reservar', 'fr' => 'réserver', 'ja' => '予約する', 'ko' => '예약하다', 'tr' => 'ayırtmak', 'ru' => 'в книга', 'ar' => 'إلى كتاب', 'az' => 'kitab'],
        'rot' => ['en' => 'red', 'es' => 'rojo', 'fr' => 'rouge', 'ja' => '赤', 'ko' => '빨간색', 'tr' => 'kırmızı', 'ru' => 'красный', 'ar' => 'أحمر', 'az' => 'qırmızı'],
        'rotes' => ['en' => 'red', 'es' => 'rojo', 'fr' => 'rouge', 'ja' => '赤', 'ko' => '빨간색', 'tr' => 'kırmızı', 'ru' => 'красный', 'ar' => 'أحمر', 'az' => 'qırmızı'],
        'rotwein' => ['en' => 'red wine', 'es' => 'vino tinto', 'fr' => 'vin rouge', 'ja' => '赤ワイン', 'ko' => '레드와인', 'tr' => 'kırmızı şarap', 'ru' => 'красный вино', 'ar' => 'أحمر نبيذ', 'az' => 'qırmızı şərab'],
        'ruf' => ['en' => 'call', 'es' => 'llama', 'fr' => 'appelle', 'ja' => '電話して', 'ko' => '전화해', 'tr' => 'ara', 'ru' => 'позвони', 'ar' => 'اتصل', 'az' => 'zəng et'],
        'ruhig' => ['en' => 'calm', 'es' => 'tranquilo', 'fr' => 'calme', 'ja' => '落ち着いた', 'ko' => '차분한', 'tr' => 'sakin', 'ru' => 'спокойный', 'ar' => 'هادئ', 'az' => 'sakit'],
        'sah' => ['en' => 'saw', 'es' => 'vi', 'fr' => 'vu', 'ja' => '見た', 'ko' => '보았다', 'tr' => 'gördü', 'ru' => 'видела', 'ar' => 'رأى', 'az' => 'gördü'],
        'salzig' => ['en' => 'salty', 'es' => 'salado', 'fr' => 'salé', 'ja' => 'しょっぱい', 'ko' => '짠', 'tr' => 'tuzlu', 'ru' => 'солёный', 'ar' => 'مالح', 'az' => 'duzlu'],
        'salziger' => ['en' => 'salty', 'es' => 'salado', 'fr' => 'salé', 'ja' => 'しょっぱい', 'ko' => '짠', 'tr' => 'tuzlu', 'ru' => 'солёный', 'ar' => 'مالح', 'az' => 'duzlu'],
        'sauber' => ['en' => 'clean', 'es' => 'limpio', 'fr' => 'propre', 'ja' => 'きれい', 'ko' => '깨끗한', 'tr' => 'temiz', 'ru' => 'чистый', 'ar' => 'نظيف', 'az' => 'təmiz'],
        'sauberen' => ['en' => 'clean', 'es' => 'limpio', 'fr' => 'propre', 'ja' => 'きれい', 'ko' => '깨끗한', 'tr' => 'temiz', 'ru' => 'чистый', 'ar' => 'نظيف', 'az' => 'təmiz'],
        'sauberes' => ['en' => 'clean', 'es' => 'limpio', 'fr' => 'propre', 'ja' => 'きれい', 'ko' => '깨끗한', 'tr' => 'temiz', 'ru' => 'чистый', 'ar' => 'نظيف', 'az' => 'təmiz'],
        'scharf' => ['en' => 'spicy', 'es' => 'picante', 'fr' => 'épicé', 'ja' => '辛い', 'ko' => '매운', 'tr' => 'acılı', 'ru' => 'острый', 'ar' => 'حار', 'az' => 'acılı'],
        'scharfes' => ['en' => 'spicy', 'es' => 'picante', 'fr' => 'épicé', 'ja' => '辛い', 'ko' => '매운', 'tr' => 'acılı', 'ru' => 'острый', 'ar' => 'حار', 'az' => 'acılı'],
        'schauen' => ['en' => 'watch', 'es' => 'mirar', 'fr' => 'regarder', 'ja' => '見る', 'ko' => '보다', 'tr' => 'izle', 'ru' => 'смотри', 'ar' => 'شاهد', 'az' => 'izlə'],
        'schlaf' => ['en' => 'sleep', 'es' => 'dormir', 'fr' => 'dormir', 'ja' => '眠る', 'ko' => '자다', 'tr' => 'uyu', 'ru' => 'сплю', 'ar' => 'أنام', 'az' => 'yatıram'],
        'schlafe' => ['en' => 'sleep', 'es' => 'dormir', 'fr' => 'dormir', 'ja' => '眠る', 'ko' => '자다', 'tr' => 'uyu', 'ru' => 'сплю', 'ar' => 'أنام', 'az' => 'yatıram'],
        'schlafen' => ['en' => 'sleep', 'es' => 'dormir', 'fr' => 'dormir', 'ja' => '眠る', 'ko' => '자다', 'tr' => 'uyu', 'ru' => 'сплю', 'ar' => 'أنام', 'az' => 'yatıram'],
        'schlechter' => ['en' => 'worse', 'es' => 'peor', 'fr' => 'pire', 'ja' => 'もっと悪い', 'ko' => '더 나쁜', 'tr' => 'daha kötü', 'ru' => 'хуже', 'ar' => 'أسوأ', 'az' => 'daha pis'],
        'schmutzig' => ['en' => 'dirty', 'es' => 'sucio', 'fr' => 'sale', 'ja' => '汚い', 'ko' => '더러운', 'tr' => 'kirli', 'ru' => 'грязный', 'ar' => 'متسخ', 'az' => 'çirkli'],
        'schmutziger' => ['en' => 'dirty', 'es' => 'sucio', 'fr' => 'sale', 'ja' => '汚い', 'ko' => '더러운', 'tr' => 'kirli', 'ru' => 'грязный', 'ar' => 'متسخ', 'az' => 'çirkli'],
        'schnell' => ['en' => 'fast', 'es' => 'rápido', 'fr' => 'rapide', 'ja' => '速い', 'ko' => '빠른', 'tr' => 'hızlı', 'ru' => 'быстро', 'ar' => 'بسرعة', 'az' => 'sürətli'],
        'schneller' => ['en' => 'fast', 'es' => 'rápido', 'fr' => 'rapide', 'ja' => '速い', 'ko' => '빠른', 'tr' => 'hızlı', 'ru' => 'быстро', 'ar' => 'بسرعة', 'az' => 'sürətli'],
        'schokoladeneis' => ['en' => 'chocolate ice cream', 'es' => 'helado de chocolate', 'fr' => 'glace au chocolat', 'ja' => 'チョコアイス', 'ko' => '초콜릿 아이스크림', 'tr' => 'çikolatalı dondurma', 'ru' => 'шоколадное мороженое', 'ar' => 'آيس كريم شوكولاتة', 'az' => 'şokoladlı dondurma'],
        'schokoladenkuchen' => ['en' => 'chocolate cake', 'es' => 'pastel de chocolate', 'fr' => 'gâteau au chocolat', 'ja' => 'チョコレートケーキ', 'ko' => '초콜릿 케이크', 'tr' => 'çikolatalı pasta', 'ru' => 'шоколад торт', 'ar' => 'شوكولاتة كعكة', 'az' => 'şokolad tort'],
        'schon' => ['en' => 'already', 'es' => 'ya', 'fr' => 'déjà', 'ja' => 'もう', 'ko' => '이미', 'tr' => 'zaten', 'ru' => 'уже', 'ar' => 'بالفعل', 'az' => 'artıq'],
        'schwarz' => ['en' => 'black', 'es' => 'negro', 'fr' => 'noir', 'ja' => '黒', 'ko' => '검은색', 'tr' => 'siyah', 'ru' => 'чёрный', 'ar' => 'أسود', 'az' => 'qara'],
        'schwarzer' => ['en' => 'black', 'es' => 'negro', 'fr' => 'noir', 'ja' => '黒', 'ko' => '검은색', 'tr' => 'siyah', 'ru' => 'чёрный', 'ar' => 'أسود', 'az' => 'qara'],
        'schwarzes' => ['en' => 'black', 'es' => 'negro', 'fr' => 'noir', 'ja' => '黒', 'ko' => '검은색', 'tr' => 'siyah', 'ru' => 'чёрный', 'ar' => 'أسود', 'az' => 'qara'],
        'schwer' => ['en' => 'hard', 'es' => 'difícil', 'fr' => 'difficile', 'ja' => '難しい', 'ko' => '어려운', 'tr' => 'zor', 'ru' => 'трудно', 'ar' => 'صعب', 'az' => 'çətin'],
        'schwere' => ['en' => 'hard', 'es' => 'difícil', 'fr' => 'difficile', 'ja' => '難しい', 'ko' => '어려운', 'tr' => 'zor', 'ru' => 'трудно', 'ar' => 'صعب', 'az' => 'çətin'],
        'schwerer' => ['en' => 'hard', 'es' => 'difícil', 'fr' => 'difficile', 'ja' => '難しい', 'ko' => '어려운', 'tr' => 'zor', 'ru' => 'трудно', 'ar' => 'صعب', 'az' => 'çətin'],
        'schön' => ['en' => 'beautiful', 'es' => 'hermoso', 'fr' => 'beau', 'ja' => '美しい', 'ko' => '아름다운', 'tr' => 'güzel', 'ru' => 'красивый', 'ar' => 'جميل', 'az' => 'gözəl'],
        'schöner' => ['en' => 'beautiful', 'es' => 'hermoso', 'fr' => 'beau', 'ja' => '美しい', 'ko' => '아름다운', 'tr' => 'güzel', 'ru' => 'красивый', 'ar' => 'جميل', 'az' => 'gözəl'],
        'schönes' => ['en' => 'beautiful', 'es' => 'hermoso', 'fr' => 'beau', 'ja' => '美しい', 'ko' => '아름다운', 'tr' => 'güzel', 'ru' => 'красивый', 'ar' => 'جميل', 'az' => 'gözəl'],
        'sechs' => ['en' => 'six', 'es' => 'seis', 'fr' => 'six', 'ja' => '六', 'ko' => '여섯', 'tr' => 'altı', 'ru' => 'шесть', 'ar' => 'ستة', 'az' => 'altı'],
        'sehr' => ['en' => 'very', 'es' => 'muy', 'fr' => 'très', 'ja' => 'とても', 'ko' => '매우', 'tr' => 'çok', 'ru' => 'очень', 'ar' => 'جدا', 'az' => 'çox'],
        'sie' => ['en' => 'she', 'es' => 'ella', 'fr' => 'elle', 'ja' => '彼女', 'ko' => '그녀', 'tr' => 'o', 'ru' => 'она', 'ar' => 'هي', 'az' => 'o qadın'],
        'sie ist' => ['en' => 'she is', 'es' => 'ella es', 'fr' => 'elle est', 'ja' => '彼女は', 'ko' => '그녀는', 'tr' => 'o', 'ru' => 'она', 'ar' => 'هي', 'az' => 'o qadın'],
        'sieben' => ['en' => 'seven', 'es' => 'siete', 'fr' => 'sept', 'ja' => '七', 'ko' => '일곱', 'tr' => 'yedi', 'ru' => 'семь', 'ar' => 'سبعة', 'az' => 'yeddi'],
        'sind' => ['en' => 'are', 'es' => 'son', 'fr' => 'sont', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'sin', 'ru' => 'есть', 'ar' => 'يكون', 'az' => 'olmaq'],
        'sprechen' => ['en' => 'speak', 'es' => 'hablar', 'fr' => 'parler', 'ja' => '話す', 'ko' => '말하다', 'tr' => 'konuş', 'ru' => 'говорю', 'ar' => 'أتكلم', 'az' => 'danışıram'],
        'sprich' => ['en' => 'speak', 'es' => 'habla', 'fr' => 'parle', 'ja' => '話す', 'ko' => '말하다', 'tr' => 'konuş', 'ru' => 'говорю', 'ar' => 'أتكلم', 'az' => 'danışıram'],
        'später' => ['en' => 'later', 'es' => 'más tarde', 'fr' => 'plus tard', 'ja' => '後で', 'ko' => '나중에', 'tr' => 'sonra', 'ru' => 'позже', 'ar' => 'لاحقا', 'az' => 'sonradan'],
        'stornieren' => ['en' => 'to cancel', 'es' => 'cancelar', 'fr' => 'annuler', 'ja' => 'キャンセルする', 'ko' => '취소하다', 'tr' => 'iptal etmek', 'ru' => 'отменить', 'ar' => 'الإلغاء', 'az' => 'ləğv etmək'],
        'suchen' => ['en' => 'to look for', 'es' => 'buscar', 'fr' => 'chercher', 'ja' => '探す', 'ko' => '찾다', 'tr' => 'aramak', 'ru' => 'искать', 'ar' => 'البحث', 'az' => 'axtarmaq'],
        'süß' => ['en' => 'sweet', 'es' => 'dulce', 'fr' => 'sucré', 'ja' => '甘い', 'ko' => '단', 'tr' => 'tatlı', 'ru' => 'сладкий', 'ar' => 'حلو', 'az' => 'şirin'],
        'süßer' => ['en' => 'sweet', 'es' => 'dulce', 'fr' => 'sucré', 'ja' => '甘い', 'ko' => '단', 'tr' => 'tatlı', 'ru' => 'сладкий', 'ar' => 'حلو', 'az' => 'şirin'],
        'süßes' => ['en' => 'sweet', 'es' => 'dulce', 'fr' => 'sucré', 'ja' => '甘い', 'ko' => '단', 'tr' => 'tatlı', 'ru' => 'сладкий', 'ar' => 'حلو', 'az' => 'şirin'],
        'tages' => ['en' => 'day', 'es' => 'día', 'fr' => 'jour', 'ja' => '日', 'ko' => '날', 'tr' => 'gün', 'ru' => 'день', 'ar' => 'يوم', 'az' => 'gün'],
        'teilen' => ['en' => 'to share', 'es' => 'compartir', 'fr' => 'partager', 'ja' => '分ける', 'ko' => '나누다', 'tr' => 'paylaşmak', 'ru' => 'разделить', 'ar' => 'المشاركة', 'az' => 'bölüşmək'],
        'teuer' => ['en' => 'expensive', 'es' => 'caro', 'fr' => 'cher', 'ja' => '高い', 'ko' => '비싼', 'tr' => 'pahalı', 'ru' => 'дорогой', 'ar' => 'غالي', 'az' => 'bahalı'],
        'tragen' => ['en' => 'to carry', 'es' => 'llevar', 'fr' => 'porter', 'ja' => '運ぶ', 'ko' => '나르다', 'tr' => 'taşımak', 'ru' => 'нести', 'ar' => 'الحمل', 'az' => 'daşımaq'],
        'trank' => ['en' => 'drank', 'es' => 'bebí', 'fr' => 'bu', 'ja' => '飲んだ', 'ko' => '마셨다', 'tr' => 'içti', 'ru' => 'пил', 'ar' => 'شرب', 'az' => 'içdi'],
        'traurig' => ['en' => 'sad', 'es' => 'triste', 'fr' => 'triste', 'ja' => '悲しい', 'ko' => '슬픈', 'tr' => 'üzgün', 'ru' => 'грустный', 'ar' => 'حزين', 'az' => 'kədərli'],
        'trinke' => ['en' => 'drink', 'es' => 'beber', 'fr' => 'boire', 'ja' => '飲む', 'ko' => '마시다', 'tr' => 'iç', 'ru' => 'напиток', 'ar' => 'مشروب', 'az' => 'içki'],
        'trinken' => ['en' => 'drink', 'es' => 'beber', 'fr' => 'boire', 'ja' => '飲む', 'ko' => '마시다', 'tr' => 'iç', 'ru' => 'напиток', 'ar' => 'مشروب', 'az' => 'içki'],
        'um' => ['en' => 'at', 'es' => 'a', 'fr' => 'à', 'ja' => 'に', 'ko' => '에', 'tr' => 'de', 'ru' => 'на', 'ar' => 'على', 'az' => 'yanında'],
        'und' => ['en' => 'and', 'es' => 'y', 'fr' => 'et', 'ja' => 'と', 'ko' => '그리고', 'tr' => 've', 'ru' => 'и', 'ar' => 'و', 'az' => 'və'],
        'uns' => ['en' => 'us', 'es' => 'nos', 'fr' => 'nous', 'ja' => '私たち', 'ko' => '우리', 'tr' => 'biz', 'ru' => 'нас', 'ar' => 'نا', 'az' => 'bizi'],
        'unter' => ['en' => 'under', 'es' => 'debajo', 'fr' => 'sous', 'ja' => 'の下に', 'ko' => '아래에', 'tr' => 'altında', 'ru' => 'под', 'ar' => 'تحت', 'az' => 'altında'],
        'vanilleeis' => ['en' => 'vanilla ice cream', 'es' => 'helado de vainilla', 'fr' => 'glace à la vanille', 'ja' => 'バニラアイス', 'ko' => '바닐라 아이스크림', 'tr' => 'vanilyalı dondurma', 'ru' => 'ванильное мороженое', 'ar' => 'آيس كريم فانيليا', 'az' => 'vanilli dondurma'],
        'vegetarisch' => ['en' => 'vegetarian', 'es' => 'vegetariano', 'fr' => 'végétarien', 'ja' => 'ベジタリアン', 'ko' => '채식주의자', 'tr' => 'vejetaryen', 'ru' => 'вегетарианец', 'ar' => 'نباتي', 'az' => 'vegetarian'],
        'vergleichen' => ['en' => 'to compare', 'es' => 'comparar', 'fr' => 'comparer', 'ja' => '比べる', 'ko' => '비교하다', 'tr' => 'karşılaştırmak', 'ru' => 'сравнить', 'ar' => 'المقارنة', 'az' => 'müqayisə etmək'],
        'vermeiden' => ['en' => 'to avoid', 'es' => 'evitar', 'fr' => 'éviter', 'ja' => '避ける', 'ko' => '피하다', 'tr' => 'kaçınmak', 'ru' => 'избегать', 'ar' => 'التجنب', 'az' => 'qaçınmaq'],
        'viel' => ['en' => 'much', 'es' => 'mucho', 'fr' => 'beaucoup', 'ja' => 'たくさん', 'ko' => '많이', 'tr' => 'çok', 'ru' => 'много', 'ar' => 'كثير', 'az' => 'çox'],
        'viele' => ['en' => 'many', 'es' => 'muchos', 'fr' => 'beaucoup', 'ja' => '多くの', 'ko' => '많은', 'tr' => 'çok', 'ru' => 'много', 'ar' => 'كثير', 'az' => 'çoxlu'],
        'vielleicht' => ['en' => 'maybe', 'es' => 'quizás', 'fr' => 'peut-être', 'ja' => 'たぶん', 'ko' => '아마도', 'tr' => 'belki', 'ru' => 'может быть', 'ar' => 'ربما', 'az' => 'bəlkə'],
        'vier' => ['en' => 'four', 'es' => 'cuatro', 'fr' => 'quatre', 'ja' => '四', 'ko' => '넷', 'tr' => 'dört', 'ru' => 'четыре', 'ar' => 'أربعة', 'az' => 'dörd'],
        'voll' => ['en' => 'full', 'es' => 'lleno', 'fr' => 'plein', 'ja' => 'いっぱい', 'ko' => '가득한', 'tr' => 'dolu', 'ru' => 'полный', 'ar' => 'ممتلئ', 'az' => 'dolu'],
        'voller' => ['en' => 'full', 'es' => 'lleno', 'fr' => 'plein', 'ja' => 'いっぱい', 'ko' => '가득한', 'tr' => 'dolu', 'ru' => 'полный', 'ar' => 'ممتلئ', 'az' => 'dolu'],
        'von' => ['en' => 'of', 'es' => 'de', 'fr' => 'de', 'ja' => 'の', 'ko' => '의', 'tr' => 'in', 'ru' => 'из', 'ar' => 'من', 'az' => 'ın'],
        'vor' => ['en' => 'before', 'es' => 'antes', 'fr' => 'avant', 'ja' => '前に', 'ko' => '전에', 'tr' => 'önce', 'ru' => 'до', 'ar' => 'قبل', 'az' => 'əvvəl'],
        'vorne' => ['en' => 'in front', 'es' => 'delante', 'fr' => 'devant', 'ja' => '前に', 'ko' => '앞에', 'tr' => 'önde', 'ru' => 'впереди', 'ar' => 'أمام', 'az' => 'qarşıda'],
        'wahr' => ['en' => 'true', 'es' => 'verdadero', 'fr' => 'vrai', 'ja' => '本当', 'ko' => '사실', 'tr' => 'doğru', 'ru' => 'правильно', 'ar' => 'صحيح', 'az' => 'düzgün'],
        'wann' => ['en' => 'when', 'es' => 'cuándo', 'fr' => 'quand', 'ja' => 'いつ', 'ko' => '언제', 'tr' => 'ne zaman', 'ru' => 'когда', 'ar' => 'متى', 'az' => 'nə vaxt'],
        'war' => ['en' => 'was', 'es' => 'era', 'fr' => 'était', 'ja' => 'だった', 'ko' => '였다', 'tr' => 'idi', 'ru' => 'был', 'ar' => 'كان', 'az' => 'idi'],
        'warm' => ['en' => 'warm', 'es' => 'cálido', 'fr' => 'doux', 'ja' => '暖かい', 'ko' => '따뜻한', 'tr' => 'sıcak', 'ru' => 'тёплый', 'ar' => 'دافئ', 'az' => 'isti'],
        'warme' => ['en' => 'warm', 'es' => 'cálido', 'fr' => 'doux', 'ja' => '暖かい', 'ko' => '따뜻한', 'tr' => 'sıcak', 'ru' => 'тёплый', 'ar' => 'دافئ', 'az' => 'isti'],
        'warte' => ['en' => 'wait', 'es' => 'esperar', 'fr' => 'attendre', 'ja' => '待つ', 'ko' => '기다리다', 'tr' => 'bekle', 'ru' => 'подожди', 'ar' => 'انتظر', 'az' => 'gözlə'],
        'warten' => ['en' => 'wait', 'es' => 'esperar', 'fr' => 'attendre', 'ja' => '待つ', 'ko' => '기다리다', 'tr' => 'bekle', 'ru' => 'подожди', 'ar' => 'انتظر', 'az' => 'gözlə'],
        'warum' => ['en' => 'why', 'es' => 'por qué', 'fr' => 'pourquoi', 'ja' => 'なぜ', 'ko' => '왜', 'tr' => 'neden', 'ru' => 'почему', 'ar' => 'لماذا', 'az' => 'niyə'],
        'weil' => ['en' => 'because', 'es' => 'porque', 'fr' => 'parce que', 'ja' => 'なぜなら', 'ko' => '왜냐하면', 'tr' => 'çünkü', 'ru' => 'потому что', 'ar' => 'لأن', 'az' => 'çünki'],
        'weit' => ['en' => 'far', 'es' => 'lejos', 'fr' => 'loin', 'ja' => '遠く', 'ko' => '멀리', 'tr' => 'uzak', 'ru' => 'далеко', 'ar' => 'بعيد', 'az' => 'uzaq'],
        'weiter' => ['en' => 'far', 'es' => 'lejos', 'fr' => 'loin', 'ja' => '遠く', 'ko' => '멀리', 'tr' => 'uzak', 'ru' => 'далеко', 'ar' => 'بعيد', 'az' => 'uzaq'],
        'weitergehen' => ['en' => 'continue', 'es' => 'continuar', 'fr' => 'continuer', 'ja' => '続ける', 'ko' => '계속하다', 'tr' => 'devam et', 'ru' => 'продолжай', 'ar' => 'تابع', 'az' => 'davam et'],
        'weiß' => ['en' => 'white', 'es' => 'blanco', 'fr' => 'blanc', 'ja' => '白', 'ko' => '하얀색', 'tr' => 'beyaz', 'ru' => 'белый', 'ar' => 'أبيض', 'az' => 'ağ'],
        'weißer' => ['en' => 'white', 'es' => 'blanco', 'fr' => 'blanc', 'ja' => '白', 'ko' => '하얀색', 'tr' => 'beyaz', 'ru' => 'белый', 'ar' => 'أبيض', 'az' => 'ağ'],
        'weißes' => ['en' => 'white', 'es' => 'blanco', 'fr' => 'blanc', 'ja' => '白', 'ko' => '하얀색', 'tr' => 'beyaz', 'ru' => 'белый', 'ar' => 'أبيض', 'az' => 'ağ'],
        'welcher' => ['en' => 'which', 'es' => 'cuál', 'fr' => 'quel', 'ja' => 'どれ', 'ko' => '어느', 'tr' => 'hangi', 'ru' => 'какой', 'ar' => 'أي', 'az' => 'hansı'],
        'weniger' => ['en' => 'less', 'es' => 'menos', 'fr' => 'moins', 'ja' => 'より少ない', 'ko' => '덜', 'tr' => 'daha az', 'ru' => 'меньше', 'ar' => 'أقل', 'az' => 'daha az'],
        'wer' => ['en' => 'who', 'es' => 'quién', 'fr' => 'qui', 'ja' => '誰', 'ko' => '누구', 'tr' => 'kim', 'ru' => 'кто', 'ar' => 'مَن', 'az' => 'kim'],
        'wie' => ['en' => 'like', 'es' => 'como', 'fr' => 'comme', 'ja' => 'のように', 'ko' => '처럼', 'tr' => 'gibi', 'ru' => 'нравится', 'ar' => 'يعجبني', 'az' => 'xoşuma gəlir'],
        'wie geht es dir' => ['en' => 'how are you', 'es' => 'cómo estás', 'fr' => 'comment ça va', 'ja' => 'お元気ですか', 'ko' => '어떻게 지내세요', 'tr' => 'nasılsın', 'ru' => 'как дела', 'ar' => 'كيف حالك', 'az' => 'necəsən'],
        'wie viele' => ['en' => 'how many', 'es' => 'cuántos', 'fr' => 'combien', 'ja' => 'いくつ', 'ko' => '몇 개', 'tr' => 'kaç', 'ru' => 'сколько', 'ar' => 'كم', 'az' => 'neçə'],
        'wiegen' => ['en' => 'to weigh', 'es' => 'pesar', 'fr' => 'peser', 'ja' => '量る', 'ko' => '무게를 재다', 'tr' => 'tartmak', 'ru' => 'взвесить', 'ar' => 'الوزن', 'az' => 'çəkmək'],
        'will' => ['en' => 'want', 'es' => 'quiero', 'fr' => 'veux', 'ja' => 'したい', 'ko' => '원하다', 'tr' => 'iste', 'ru' => 'хочу', 'ar' => 'أريد', 'az' => 'istəyirəm'],
        'willkommen' => ['en' => 'welcome', 'es' => 'bienvenido', 'fr' => 'bienvenue', 'ja' => 'ようこそ', 'ko' => '환영합니다', 'tr' => 'hoş geldin', 'ru' => 'добро пожаловать', 'ar' => 'أهلا وسهلا', 'az' => 'xoş gəlmisiniz'],
        'wirklich' => ['en' => 'really', 'es' => 'de verdad', 'fr' => 'vraiment', 'ja' => '本当に', 'ko' => '정말', 'tr' => 'gerçekten', 'ru' => 'действительно', 'ar' => 'حقا', 'az' => 'həqiqətən'],
        'wo' => ['en' => 'where', 'es' => 'dónde', 'fr' => 'où', 'ja' => 'どこ', 'ko' => '어디', 'tr' => 'nerede', 'ru' => 'где', 'ar' => 'أين', 'az' => 'harada'],
        'wo ist' => ['en' => 'where is', 'es' => 'dónde está', 'fr' => 'où est', 'ja' => 'どこですか', 'ko' => '어디입니까', 'tr' => 'nerede', 'ru' => 'где', 'ar' => 'أين', 'az' => 'harada'],
        'wohne' => ['en' => 'live', 'es' => 'vivo', 'fr' => 'habite', 'ja' => '住む', 'ko' => '살다', 'tr' => 'yaşa', 'ru' => 'живи', 'ar' => 'عش', 'az' => 'yaşa'],
        'wählen' => ['en' => 'to choose', 'es' => 'elegir', 'fr' => 'choisir', 'ja' => '選ぶ', 'ko' => '고르다', 'tr' => 'seçmek', 'ru' => 'выбрать', 'ar' => 'الاختيار', 'az' => 'seçmək'],
        'zehn' => ['en' => 'ten', 'es' => 'diez', 'fr' => 'dix', 'ja' => '十', 'ko' => '열', 'tr' => 'on', 'ru' => 'десять', 'ar' => 'عشرة', 'az' => 'on'],
        'zu' => ['en' => 'to', 'es' => 'a', 'fr' => 'à', 'ja' => 'へ', 'ko' => '로', 'tr' => 'e', 'ru' => 'в', 'ar' => 'إلى', 'az' => 'doğru'],
        'zu viel' => ['en' => 'too much', 'es' => 'demasiado', 'fr' => 'trop', 'ja' => 'すぎます', 'ko' => '너무', 'tr' => 'çok fazla', 'ru' => 'слишком много', 'ar' => 'كثير جدا', 'az' => 'çox artıq'],
        'zum' => ['en' => 'to the', 'es' => 'al', 'fr' => 'au', 'ja' => 'へ', 'ko' => '로', 'tr' => 'e', 'ru' => 'в', 'ar' => 'إلى', 'az' => 'doğru'],
        'zum Hieressen' => ['en' => 'eat in', 'es' => 'para tomar aquí', 'fr' => 'sur place', 'ja' => '店内で', 'ko' => '매장에서', 'tr' => 'burada ye', 'ru' => 'ем в', 'ar' => 'آكل في', 'az' => 'yeyirəm içində'],
        'zum Mitnehmen' => ['en' => 'takeaway', 'es' => 'para llevar', 'fr' => 'à emporter', 'ja' => '持ち帰り', 'ko' => '포장', 'tr' => 'paket', 'ru' => 'с собой', 'ar' => 'للخارج', 'az' => 'özümlə'],
        'zur' => ['en' => 'to the', 'es' => 'a la', 'fr' => 'à la', 'ja' => 'へ', 'ko' => '로', 'tr' => 'e', 'ru' => 'в', 'ar' => 'إلى', 'az' => 'doğru'],
        'zurück' => ['en' => 'back', 'es' => 'de vuelta', 'fr' => 'en retour', 'ja' => '戻って', 'ko' => '다시', 'tr' => 'geri', 'ru' => 'назад', 'ar' => 'خلف', 'az' => 'geri'],
        'zurückrufen' => ['en' => 'call back', 'es' => 'devolver la llamada', 'fr' => 'rappeler', 'ja' => '折り返す', 'ko' => '다시 전화하다', 'tr' => 'tekrar ara', 'ru' => 'перезвони', 'ar' => 'عاود الاتصال', 'az' => 'geri zəng et'],
        'zusammen' => ['en' => 'together', 'es' => 'juntos', 'fr' => 'ensemble', 'ja' => '一緒に', 'ko' => '함께', 'tr' => 'birlikte', 'ru' => 'вместе', 'ar' => 'معا', 'az' => 'birlikdə'],
        'zwei' => ['en' => 'two', 'es' => 'dos', 'fr' => 'deux', 'ja' => '二', 'ko' => '둘', 'tr' => 'iki', 'ru' => 'два', 'ar' => 'اثنان', 'az' => 'iki'],
        'zwei Bücher' => ['en' => 'two books', 'es' => 'dos libros', 'fr' => 'deux livres', 'ja' => '二冊の本', 'ko' => '책 두 권', 'tr' => 'iki kitap', 'ru' => 'два книги', 'ar' => 'اثنان كتب', 'az' => 'iki kitablar'],
        'überquere' => ['en' => 'cross', 'es' => 'cruzar', 'fr' => 'traverser', 'ja' => '渡る', 'ko' => '건너다', 'tr' => 'geç', 'ru' => 'перейди', 'ar' => 'اعبر', 'az' => 'keç'],
        'überqueren' => ['en' => 'cross', 'es' => 'cruzar', 'fr' => 'traverser', 'ja' => '渡る', 'ko' => '건너다', 'tr' => 'geç', 'ru' => 'перейди', 'ar' => 'اعبر', 'az' => 'keç'],
    ];

    /** Native languages a learner can take a German course in. */
    private const LANGS = ['en', 'es', 'fr', 'ja', 'ko'];

    /**
     * The ['i18n' => [...]] map for a German word, ready to store in exercise
     * data. Falls back to the word itself if it isn't in the dictionary yet.
     *
     * @return array{i18n: array<string, string>}
     */
    public static function hint(string $german): array
    {
        return ['i18n' => self::meanings($german)];
    }

    /**
     * @return array<string, string>
     */
    public static function meanings(string $german): array
    {
        $key = mb_strtolower(trim($german));

        foreach (self::WORDS as $word => $translations) {
            if (mb_strtolower($word) === $key) {
                return $translations;
            }
        }

        // Not in the dictionary: show the German word itself to every learner.
        return array_fill_keys(self::LANGS, $german);
    }

    /** Every German word the dictionary knows (used for wrong-answer options). */
    public static function all(): array
    {
        return array_keys(self::WORDS);
    }

    public static function knows(string $german): bool
    {
        $key = mb_strtolower(trim($german));

        foreach (array_keys(self::WORDS) as $word) {
            if (mb_strtolower($word) === $key) {
                return true;
            }
        }

        return false;
    }
}
