<?php

namespace Database\Seeders\Support;

/**
 * Japanese word => its meaning in every native language a Japanese course
 * supports (English, Spanish, German, French, Korean).
 *
 * Japanese is the LEARNING language here, so exercise content (words, phrases,
 * tiles) is authored in Japanese, and only the hints/prompts are shown in the
 * learner's own language. Nothing user-facing is hardcoded: seeders pull from
 * here and store the result as an ['i18n' => [...]] map, which
 * ExerciseContentService resolves per request.
 *
 * This mirrors EnglishVocabulary and the other course dictionaries exactly, only
 * the language roles are swapped. Add a word here once and every unit can use it.
 */
class JapaneseVocabulary
{
    private const WORDS = [
        'あなた' => ['en' => 'you', 'es' => 'tú', 'de' => 'du', 'fr' => 'tu', 'ko' => '당신'],
        'あなたの' => ['en' => 'your', 'es' => 'tu', 'de' => 'dein', 'fr' => 'ton', 'ko' => '당신의'],
        'あの' => ['en' => 'that', 'es' => 'ese', 'de' => 'jener', 'fr' => 'cette', 'ko' => '저'],
        'ありがとう' => ['en' => 'thank you', 'es' => 'gracias', 'de' => 'danke', 'fr' => 'merci', 'ko' => '감사합니다'],
        'あれらの' => ['en' => 'those', 'es' => 'esos', 'de' => 'jene', 'fr' => 'ces', 'ko' => '저것들'],
        'いいえ' => ['en' => 'no', 'es' => 'no', 'de' => 'nein', 'fr' => 'non', 'ko' => '아니요'],
        'いいよ' => ['en' => 'okay', 'es' => 'vale', 'de' => 'okay', 'fr' => 'd\'accord', 'ko' => '좋아요'],
        'いくつ' => ['en' => 'how many', 'es' => 'cuántos', 'de' => 'wie viele', 'fr' => 'combien', 'ko' => '몇 개'],
        'いちご' => ['en' => 'strawberry', 'es' => 'fresa', 'de' => 'Erdbeere', 'fr' => 'fraise', 'ko' => '딸기'],
        'いっぱい' => ['en' => 'full', 'es' => 'lleno', 'de' => 'voll', 'fr' => 'plein', 'ko' => '가득한'],
        'いつ' => ['en' => 'when', 'es' => 'cuándo', 'de' => 'wann', 'fr' => 'quand', 'ko' => '언제'],
        'おいしい' => ['en' => 'delicious', 'es' => 'delicioso', 'de' => 'köstlich', 'fr' => 'délicieux', 'ko' => '맛있는'],
        'おつり' => ['en' => 'change', 'es' => 'cambio', 'de' => 'Wechselgeld', 'fr' => 'monnaie', 'ko' => '거스름돈'],
        'お会計' => ['en' => 'the bill', 'es' => 'la cuenta', 'de' => 'die Rechnung', 'fr' => 'l\'addition', 'ko' => '계산서'],
        'お元気ですか' => ['en' => 'how are you', 'es' => 'cómo estás', 'de' => 'wie geht es dir', 'fr' => 'comment ça va', 'ko' => '어떻게 지내세요'],
        'お皿' => ['en' => 'plate', 'es' => 'plato', 'de' => 'Teller', 'fr' => 'assiette', 'ko' => '접시'],
        'お腹がすいた' => ['en' => 'hungry', 'es' => 'hambriento', 'de' => 'hungrig', 'fr' => 'affamé', 'ko' => '배고픈'],
        'お茶' => ['en' => 'tea', 'es' => 'té', 'de' => 'Tee', 'fr' => 'thé', 'ko' => '차'],
        'お金' => ['en' => 'money', 'es' => 'dinero', 'de' => 'Geld', 'fr' => 'argent', 'ko' => '돈'],
        'お願いします' => ['en' => 'please', 'es' => 'por favor', 'de' => 'bitte', 'fr' => 's\'il vous plaît', 'ko' => '부탁합니다'],
        'かかる' => ['en' => 'costs', 'es' => 'cuesta', 'de' => 'kostet', 'fr' => 'coûte', 'ko' => '입니다'],
        'かご' => ['en' => 'basket', 'es' => 'cesta', 'de' => 'Korb', 'fr' => 'panier', 'ko' => '바구니'],
        'から' => ['en' => 'from', 'es' => 'de', 'de' => 'von', 'fr' => 'de', 'ko' => '에서'],
        'かわいい' => ['en' => 'pretty', 'es' => 'bonito', 'de' => 'hübsch', 'fr' => 'joli', 'ko' => '예쁜'],
        'きれい' => ['en' => 'clean', 'es' => 'limpio', 'de' => 'sauber', 'fr' => 'propre', 'ko' => '깨끗한'],
        'ここ' => ['en' => 'here', 'es' => 'aquí', 'de' => 'hier', 'fr' => 'ici', 'ko' => '여기'],
        'こしょう' => ['en' => 'pepper', 'es' => 'pimienta', 'de' => 'Pfeffer', 'fr' => 'poivre', 'ko' => '후추'],
        'この' => ['en' => 'this', 'es' => 'este', 'de' => 'dieser', 'fr' => 'ce', 'ko' => '이'],
        'これが' => ['en' => 'here is', 'es' => 'aquí está', 'de' => 'hier ist', 'fr' => 'voici', 'ko' => '여기'],
        'これは' => ['en' => 'this is', 'es' => 'este es', 'de' => 'das ist', 'fr' => 'c\'est', 'ko' => '이분은'],
        'これらの' => ['en' => 'these', 'es' => 'estos', 'de' => 'diese', 'fr' => 'ces', 'ko' => '이것들'],
        'こんにちは' => ['en' => 'hello', 'es' => 'hola', 'de' => 'hallo', 'fr' => 'bonjour', 'ko' => '안녕하세요'],
        'ごめんなさい' => ['en' => 'sorry', 'es' => 'lo siento', 'de' => 'Entschuldigung', 'fr' => 'désolé', 'ko' => '죄송합니다'],
        'ご飯' => ['en' => 'rice', 'es' => 'arroz', 'de' => 'Reis', 'fr' => 'riz', 'ko' => '밥'],
        'さようなら' => ['en' => 'goodbye', 'es' => 'adiós', 'de' => 'auf Wiedersehen', 'fr' => 'au revoir', 'ko' => '안녕히 가세요'],
        'しかし' => ['en' => 'but', 'es' => 'pero', 'de' => 'aber', 'fr' => 'mais', 'ko' => '하지만'],
        'しょっぱい' => ['en' => 'salty', 'es' => 'salado', 'de' => 'salzig', 'fr' => 'salé', 'ko' => '짠'],
        'じゃがいも' => ['en' => 'potato', 'es' => 'patata', 'de' => 'Kartoffel', 'fr' => 'pomme de terre', 'ko' => '감자'],
        'すぐに' => ['en' => 'soon', 'es' => 'pronto', 'de' => 'bald', 'fr' => 'bientôt', 'ko' => '곧'],
        'すみません' => ['en' => 'excuse me', 'es' => 'disculpe', 'de' => 'entschuldigen Sie', 'fr' => 'excusez-moi', 'ko' => '실례합니다'],
        'その' => ['en' => 'the', 'es' => 'el', 'de' => 'der', 'fr' => 'le', 'ko' => '그'],
        'それ' => ['en' => 'it', 'es' => 'eso', 'de' => 'es', 'fr' => 'ce', 'ko' => '그것'],
        'それから' => ['en' => 'then', 'es' => 'entonces', 'de' => 'dann', 'fr' => 'ensuite', 'ko' => '그러면'],
        'それぞれの' => ['en' => 'each', 'es' => 'cada', 'de' => 'jeder', 'fr' => 'chaque', 'ko' => '각각의'],
        'たぶん' => ['en' => 'maybe', 'es' => 'quizás', 'de' => 'vielleicht', 'fr' => 'peut-être', 'ko' => '아마도'],
        'です' => ['en' => 'is', 'es' => 'es', 'de' => 'ist', 'fr' => 'est', 'ko' => '입니다'],
        'と' => ['en' => 'and', 'es' => 'y', 'de' => 'und', 'fr' => 'et', 'ko' => '그리고'],
        'とても' => ['en' => 'very', 'es' => 'muy', 'de' => 'sehr', 'fr' => 'très', 'ko' => '매우'],
        'どこ' => ['en' => 'where', 'es' => 'dónde', 'de' => 'wo', 'fr' => 'où', 'ko' => '어디'],
        'どこですか' => ['en' => 'where is', 'es' => 'dónde está', 'de' => 'wo ist', 'fr' => 'où est', 'ko' => '어디입니까'],
        'どれ' => ['en' => 'which', 'es' => 'cuál', 'de' => 'welcher', 'fr' => 'quel', 'ko' => '어느'],
        'なぜ' => ['en' => 'why', 'es' => 'por qué', 'de' => 'warum', 'fr' => 'pourquoi', 'ko' => '왜'],
        'なぜなら' => ['en' => 'because', 'es' => 'porque', 'de' => 'weil', 'fr' => 'parce que', 'ko' => '왜냐하면'],
        'にんじん' => ['en' => 'carrot', 'es' => 'zanahoria', 'de' => 'Karotte', 'fr' => 'carotte', 'ko' => '당근'],
        'の' => ['en' => 'of', 'es' => 'de', 'de' => 'von', 'fr' => 'de', 'ko' => '의'],
        'のどが渇いた' => ['en' => 'thirsty', 'es' => 'sediento', 'de' => 'durstig', 'fr' => 'assoiffé', 'ko' => '목마른'],
        'のように' => ['en' => 'like', 'es' => 'como', 'de' => 'wie', 'fr' => 'comme', 'ko' => '처럼'],
        'は' => ['en' => 'topic marker', 'es' => 'marca de tema', 'de' => 'Themenpartikel', 'fr' => 'marque de thème', 'ko' => '주제 조사'],
        'はい' => ['en' => 'yes', 'es' => 'sí', 'de' => 'ja', 'fr' => 'oui', 'ko' => '네'],
        'はかり' => ['en' => 'scales', 'es' => 'balanza', 'de' => 'Waage', 'fr' => 'balance', 'ko' => '저울'],
        'はじめまして' => ['en' => 'nice to meet you', 'es' => 'encantado', 'de' => 'freut mich', 'fr' => 'enchanté', 'ko' => '반갑습니다'],
        'ぶどう' => ['en' => 'grapes', 'es' => 'uvas', 'de' => 'Trauben', 'fr' => 'raisin', 'ko' => '포도'],
        'または' => ['en' => 'or', 'es' => 'o', 'de' => 'oder', 'fr' => 'ou', 'ko' => '또는'],
        'まっすぐ' => ['en' => 'straight', 'es' => 'recto', 'de' => 'geradeaus', 'fr' => 'tout droit', 'ko' => '똑바로'],
        'も' => ['en' => 'also', 'es' => 'también', 'de' => 'auch', 'fr' => 'aussi', 'ko' => '또한'],
        'もう' => ['en' => 'already', 'es' => 'ya', 'de' => 'schon', 'fr' => 'déjà', 'ko' => '이미'],
        'もう一つの' => ['en' => 'another', 'es' => 'otro', 'de' => 'noch ein', 'fr' => 'encore', 'ko' => '하나 더'],
        'もちろん' => ['en' => 'of course', 'es' => 'por supuesto', 'de' => 'natürlich', 'fr' => 'bien sûr', 'ko' => '물론'],
        'もっと' => ['en' => 'more', 'es' => 'más', 'de' => 'mehr', 'fr' => 'plus', 'ko' => '더'],
        'もっと悪い' => ['en' => 'worse', 'es' => 'peor', 'de' => 'schlechter', 'fr' => 'pire', 'ko' => '더 나쁜'],
        'もっと良い' => ['en' => 'better', 'es' => 'mejor', 'de' => 'besser', 'fr' => 'meilleur', 'ko' => '더 좋은'],
        'ゆっくり' => ['en' => 'slowly', 'es' => 'despacio', 'de' => 'langsam', 'fr' => 'lentement', 'ko' => '천천히'],
        'ようこそ' => ['en' => 'welcome', 'es' => 'bienvenido', 'de' => 'willkommen', 'fr' => 'bienvenue', 'ko' => '환영합니다'],
        'より' => ['en' => 'than', 'es' => 'que', 'de' => 'als', 'fr' => 'que', 'ko' => '보다'],
        'より少ない' => ['en' => 'less', 'es' => 'menos', 'de' => 'weniger', 'fr' => 'moins', 'ko' => '덜'],
        'りんご' => ['en' => 'apple', 'es' => 'manzana', 'de' => 'Apfel', 'fr' => 'pomme', 'ko' => '사과'],
        'を' => ['en' => 'object marker', 'es' => 'marca de objeto', 'de' => 'Objektpartikel', 'fr' => 'marque d\'objet', 'ko' => '목적격 조사'],
        'アイスクリーム' => ['en' => 'ice cream', 'es' => 'helado', 'de' => 'Eis', 'fr' => 'glace', 'ko' => '아이스크림'],
        'アレルギー' => ['en' => 'allergy', 'es' => 'alergia', 'de' => 'Allergie', 'fr' => 'allergie', 'ko' => '알레르기'],
        'アレルギーの' => ['en' => 'allergic', 'es' => 'alérgico', 'de' => 'allergisch', 'fr' => 'allergique', 'ko' => '알레르기가 있는'],
        'ウェイター' => ['en' => 'waiter', 'es' => 'camarero', 'de' => 'Kellner', 'fr' => 'serveur', 'ko' => '웨이터'],
        'オレンジ' => ['en' => 'orange', 'es' => 'naranja', 'de' => 'Orange', 'fr' => 'orange', 'ko' => '오렌지'],
        'カレンダー' => ['en' => 'calendar', 'es' => 'calendario', 'de' => 'Kalender', 'fr' => 'calendrier', 'ko' => '달력'],
        'カート' => ['en' => 'trolley', 'es' => 'carrito', 'de' => 'Einkaufswagen', 'fr' => 'chariot', 'ko' => '카트'],
        'カード' => ['en' => 'card', 'es' => 'tarjeta', 'de' => 'Karte', 'fr' => 'carte', 'ko' => '카드'],
        'キャンセルする' => ['en' => 'to cancel', 'es' => 'cancelar', 'de' => 'stornieren', 'fr' => 'annuler', 'ko' => '취소하다'],
        'キロ' => ['en' => 'kilo', 'es' => 'kilo', 'de' => 'Kilo', 'fr' => 'kilo', 'ko' => '킬로'],
        'クリーム' => ['en' => 'cream', 'es' => 'nata', 'de' => 'Sahne', 'fr' => 'crème', 'ko' => '크림'],
        'グラス' => ['en' => 'glass', 'es' => 'vaso', 'de' => 'Glas', 'fr' => 'verre', 'ko' => '유리잔'],
        'グラム' => ['en' => 'gram', 'es' => 'gramo', 'de' => 'Gramm', 'fr' => 'gramme', 'ko' => '그램'],
        'グルテン' => ['en' => 'gluten', 'es' => 'gluten', 'de' => 'Gluten', 'fr' => 'gluten', 'ko' => '글루텐'],
        'ケーキ' => ['en' => 'cake', 'es' => 'pastel', 'de' => 'Kuchen', 'fr' => 'gâteau', 'ko' => '케이크'],
        'コーヒー' => ['en' => 'coffee', 'es' => 'café', 'de' => 'Kaffee', 'fr' => 'café', 'ko' => '커피'],
        'サラダ' => ['en' => 'salad', 'es' => 'ensalada', 'de' => 'Salat', 'fr' => 'salade', 'ko' => '샐러드'],
        'サンドイッチ' => ['en' => 'sandwich', 'es' => 'sándwich', 'de' => 'Sandwich', 'fr' => 'sandwich', 'ko' => '샌드위치'],
        'ジュース' => ['en' => 'juice', 'es' => 'zumo', 'de' => 'Saft', 'fr' => 'jus', 'ko' => '주스'],
        'スプーン' => ['en' => 'spoon', 'es' => 'cuchara', 'de' => 'Löffel', 'fr' => 'cuillère', 'ko' => '숟가락'],
        'スーパー' => ['en' => 'supermarket', 'es' => 'supermercado', 'de' => 'Supermarkt', 'fr' => 'supermarché', 'ko' => '슈퍼마켓'],
        'スープ' => ['en' => 'soup', 'es' => 'sopa', 'de' => 'Suppe', 'fr' => 'soupe', 'ko' => '수프'],
        'タルト' => ['en' => 'tart', 'es' => 'tarta', 'de' => 'Torte', 'fr' => 'tarte', 'ko' => '타르트'],
        'チップ' => ['en' => 'tip', 'es' => 'propina', 'de' => 'Trinkgeld', 'fr' => 'pourboire', 'ko' => '팁'],
        'チョコレート' => ['en' => 'chocolate', 'es' => 'chocolate', 'de' => 'Schokolade', 'fr' => 'chocolat', 'ko' => '초콜릿'],
        'チーズ' => ['en' => 'cheese', 'es' => 'queso', 'de' => 'Käse', 'fr' => 'fromage', 'ko' => '치즈'],
        'テーブル' => ['en' => 'table', 'es' => 'mesa', 'de' => 'Tisch', 'fr' => 'table', 'ko' => '탁자'],
        'デザート' => ['en' => 'dessert', 'es' => 'postre', 'de' => 'Nachtisch', 'fr' => 'dessert', 'ko' => '디저트'],
        'トマト' => ['en' => 'tomato', 'es' => 'tomate', 'de' => 'Tomate', 'fr' => 'tomate', 'ko' => '토마토'],
        'ドル' => ['en' => 'dollars', 'es' => 'dólares', 'de' => 'Dollar', 'fr' => 'dollars', 'ko' => '달러'],
        'ナイフ' => ['en' => 'knife', 'es' => 'cuchillo', 'de' => 'Messer', 'fr' => 'couteau', 'ko' => '나이프'],
        'ナッツ' => ['en' => 'nuts', 'es' => 'nueces', 'de' => 'Nüsse', 'fr' => 'noix', 'ko' => '견과류'],
        'ナプキン' => ['en' => 'napkin', 'es' => 'servilleta', 'de' => 'Serviette', 'fr' => 'serviette', 'ko' => '냅킨'],
        'ハンバーガー' => ['en' => 'burger', 'es' => 'hamburguesa', 'de' => 'Burger', 'fr' => 'hamburger', 'ko' => '햄버거'],
        'バター' => ['en' => 'butter', 'es' => 'mantequilla', 'de' => 'Butter', 'fr' => 'beurre', 'ko' => '버터'],
        'バナナ' => ['en' => 'banana', 'es' => 'plátano', 'de' => 'Banane', 'fr' => 'banane', 'ko' => '바나나'],
        'バニラ' => ['en' => 'vanilla', 'es' => 'vainilla', 'de' => 'Vanille', 'fr' => 'vanille', 'ko' => '바닐라'],
        'パン' => ['en' => 'bread', 'es' => 'pan', 'de' => 'Brot', 'fr' => 'pain', 'ko' => '빵'],
        'パン屋' => ['en' => 'bakery', 'es' => 'panadería', 'de' => 'Bäckerei', 'fr' => 'boulangerie', 'ko' => '빵집'],
        'ビール' => ['en' => 'beer', 'es' => 'cerveza', 'de' => 'Bier', 'fr' => 'bière', 'ko' => '맥주'],
        'フォーク' => ['en' => 'fork', 'es' => 'tenedor', 'de' => 'Gabel', 'fr' => 'fourchette', 'ko' => '포크'],
        'フライドポテト' => ['en' => 'fries', 'es' => 'patatas fritas', 'de' => 'Pommes', 'fr' => 'frites', 'ko' => '감자튀김'],
        'ベジタリアン' => ['en' => 'vegetarian', 'es' => 'vegetariano', 'de' => 'vegetarisch', 'fr' => 'végétarien', 'ko' => '채식주의자'],
        'ペン' => ['en' => 'pen', 'es' => 'bolígrafo', 'de' => 'Kugelschreiber', 'fr' => 'stylo', 'ko' => '펜'],
        'ボトル' => ['en' => 'bottle', 'es' => 'botella', 'de' => 'Flasche', 'fr' => 'bouteille', 'ko' => '병'],
        'マダム' => ['en' => 'madam', 'es' => 'señora', 'de' => 'gnädige Frau', 'fr' => 'madame', 'ko' => '부인'],
        'ムッシュ' => ['en' => 'sir', 'es' => 'señor', 'de' => 'mein Herr', 'fr' => 'monsieur', 'ko' => '선생님'],
        'メッセージ' => ['en' => 'message', 'es' => 'mensaje', 'de' => 'Nachricht', 'fr' => 'message', 'ko' => '메시지'],
        'メニュー' => ['en' => 'menu', 'es' => 'menú', 'de' => 'Menü', 'fr' => 'menu', 'ko' => '메뉴'],
        'リスト' => ['en' => 'list', 'es' => 'lista', 'de' => 'Liste', 'fr' => 'liste', 'ko' => '목록'],
        'リットル' => ['en' => 'litre', 'es' => 'litro', 'de' => 'Liter', 'fr' => 'litre', 'ko' => '리터'],
        'レシート' => ['en' => 'receipt', 'es' => 'recibo', 'de' => 'Quittung', 'fr' => 'reçu', 'ko' => '영수증'],
        'レジ' => ['en' => 'checkout', 'es' => 'caja', 'de' => 'Kasse', 'fr' => 'caisse', 'ko' => '계산대'],
        'レジ係' => ['en' => 'cashier', 'es' => 'cajero', 'de' => 'Kassierer', 'fr' => 'caissier', 'ko' => '계산원'],
        'レストラン' => ['en' => 'restaurant', 'es' => 'restaurante', 'de' => 'Restaurant', 'fr' => 'restaurant', 'ko' => '식당'],
        'ワイン' => ['en' => 'wine', 'es' => 'vino', 'de' => 'Wein', 'fr' => 'vin', 'ko' => '와인'],
        '一' => ['en' => 'one', 'es' => 'uno', 'de' => 'eins', 'fr' => 'un', 'ko' => '하나'],
        '一つの' => ['en' => 'a', 'es' => 'un', 'de' => 'ein', 'fr' => 'un', 'ko' => '하나의'],
        '一切れ' => ['en' => 'slice', 'es' => 'trozo', 'de' => 'Stück', 'fr' => 'part', 'ko' => '한 조각'],
        '一緒に' => ['en' => 'together', 'es' => 'juntos', 'de' => 'zusammen', 'fr' => 'ensemble', 'ko' => '함께'],
        '七' => ['en' => 'seven', 'es' => 'siete', 'de' => 'sieben', 'fr' => 'sept', 'ko' => '일곱'],
        '三' => ['en' => 'three', 'es' => 'tres', 'de' => 'drei', 'fr' => 'trois', 'ko' => '셋'],
        '九' => ['en' => 'nine', 'es' => 'nueve', 'de' => 'neun', 'fr' => 'neuf', 'ko' => '아홉'],
        '予約' => ['en' => 'booking', 'es' => 'reserva', 'de' => 'Reservierung', 'fr' => 'réservation', 'ko' => '예약'],
        '予約する' => ['en' => 'to book', 'es' => 'reservar', 'de' => 'reservieren', 'fr' => 'réserver', 'ko' => '예약하다'],
        '二' => ['en' => 'two', 'es' => 'dos', 'de' => 'zwei', 'fr' => 'deux', 'ko' => '둘'],
        '二冊の本' => ['en' => 'two books', 'es' => 'dos libros', 'de' => 'zwei Bücher', 'fr' => 'deux livres', 'ko' => '책 두 권'],
        '五' => ['en' => 'five', 'es' => 'cinco', 'de' => 'fünf', 'fr' => 'cinq', 'ko' => '다섯'],
        '人' => ['en' => 'people', 'es' => 'personas', 'de' => 'Personen', 'fr' => 'personnes', 'ko' => '명'],
        '今' => ['en' => 'now', 'es' => 'ahora', 'de' => 'jetzt', 'fr' => 'maintenant', 'ko' => '지금'],
        '今夜' => ['en' => 'tonight', 'es' => 'esta noche', 'de' => 'heute Abend', 'fr' => 'ce soir', 'ko' => '오늘 밤'],
        '今日' => ['en' => 'today', 'es' => 'hoy', 'de' => 'heute', 'fr' => 'aujourd\'hui', 'ko' => '오늘'],
        '値段' => ['en' => 'price', 'es' => 'precio', 'de' => 'Preis', 'fr' => 'prix', 'ko' => '가격'],
        '偽' => ['en' => 'false', 'es' => 'falso', 'de' => 'falsch', 'fr' => 'faux', 'ko' => '거짓'],
        '元気' => ['en' => 'well', 'es' => 'bien', 'de' => 'gut', 'fr' => 'bien', 'ko' => '잘'],
        '兄弟' => ['en' => 'brother', 'es' => 'hermano', 'de' => 'Bruder', 'fr' => 'frère', 'ko' => '형제'],
        '先生' => ['en' => 'teacher', 'es' => 'profesor', 'de' => 'Lehrer', 'fr' => 'professeur', 'ko' => '선생님'],
        '入れる' => ['en' => 'to put', 'es' => 'poner', 'de' => 'legen', 'fr' => 'mettre', 'ko' => '넣다'],
        '八' => ['en' => 'eight', 'es' => 'ocho', 'de' => 'acht', 'fr' => 'huit', 'ko' => '여덟'],
        '公園' => ['en' => 'park', 'es' => 'parque', 'de' => 'Park', 'fr' => 'parc', 'ko' => '공원'],
        '六' => ['en' => 'six', 'es' => 'seis', 'de' => 'sechs', 'fr' => 'six', 'ko' => '여섯'],
        '冬' => ['en' => 'winter', 'es' => 'invierno', 'de' => 'Winter', 'fr' => 'hiver', 'ko' => '겨울'],
        '冷たい' => ['en' => 'cold', 'es' => 'frío', 'de' => 'kalt', 'fr' => 'froid', 'ko' => '차가운'],
        '分' => ['en' => 'minutes', 'es' => 'minutos', 'de' => 'Minuten', 'fr' => 'minutes', 'ko' => '분'],
        '分ける' => ['en' => 'to share', 'es' => 'compartir', 'de' => 'teilen', 'fr' => 'partager', 'ko' => '나누다'],
        '列' => ['en' => 'queue', 'es' => 'cola', 'de' => 'Schlange', 'fr' => 'file', 'ko' => '줄'],
        '別々に' => ['en' => 'separately', 'es' => 'por separado', 'de' => 'getrennt', 'fr' => 'séparément', 'ko' => '따로'],
        '前に' => ['en' => 'before', 'es' => 'antes', 'de' => 'vor', 'fr' => 'avant', 'ko' => '전에'],
        '前菜' => ['en' => 'starter', 'es' => 'entrante', 'de' => 'Vorspeise', 'fr' => 'entrée', 'ko' => '전채'],
        '割引' => ['en' => 'discount', 'es' => 'descuento', 'de' => 'Rabatt', 'fr' => 'réduction', 'ko' => '할인'],
        '北' => ['en' => 'north', 'es' => 'norte', 'de' => 'Norden', 'fr' => 'nord', 'ko' => '북쪽'],
        '医者' => ['en' => 'doctor', 'es' => 'médico', 'de' => 'Arzt', 'fr' => 'médecin', 'ko' => '의사'],
        '十' => ['en' => 'ten', 'es' => 'diez', 'de' => 'zehn', 'fr' => 'dix', 'ko' => '열'],
        '十分に' => ['en' => 'enough', 'es' => 'bastante', 'de' => 'genug', 'fr' => 'assez', 'ko' => '충분히'],
        '南' => ['en' => 'south', 'es' => 'sur', 'de' => 'Süden', 'fr' => 'sud', 'ko' => '남쪽'],
        '卵' => ['en' => 'egg', 'es' => 'huevo', 'de' => 'Ei', 'fr' => 'œuf', 'ko' => '계란'],
        '厨房' => ['en' => 'kitchen', 'es' => 'cocina', 'de' => 'Küche', 'fr' => 'cuisine', 'ko' => '주방'],
        '友達' => ['en' => 'friend', 'es' => 'amigo', 'de' => 'Freund', 'fr' => 'ami', 'ko' => '친구'],
        '古い' => ['en' => 'old', 'es' => 'viejo', 'de' => 'alt', 'fr' => 'vieux', 'ko' => '오래된'],
        '右' => ['en' => 'right', 'es' => 'derecha', 'de' => 'rechts', 'fr' => 'droite', 'ko' => '오른쪽'],
        '合計' => ['en' => 'total', 'es' => 'total', 'de' => 'Gesamt', 'fr' => 'total', 'ko' => '총액'],
        '同じ' => ['en' => 'same', 'es' => 'mismo', 'de' => 'gleich', 'fr' => 'même', 'ko' => '같은'],
        '同じくらい' => ['en' => 'as much', 'es' => 'tanto', 'de' => 'genauso viel', 'fr' => 'autant', 'ko' => '그만큼'],
        '名前' => ['en' => 'name', 'es' => 'nombre', 'de' => 'Name', 'fr' => 'nom', 'ko' => '이름'],
        '含む' => ['en' => 'contains', 'es' => 'contiene', 'de' => 'enthält', 'fr' => 'contient', 'ko' => '들어있다'],
        '味' => ['en' => 'taste', 'es' => 'sabor', 'de' => 'Geschmack', 'fr' => 'goût', 'ko' => '맛'],
        '商品' => ['en' => 'product', 'es' => 'producto', 'de' => 'Produkt', 'fr' => 'produit', 'ko' => '상품'],
        '問題' => ['en' => 'problem', 'es' => 'problema', 'de' => 'Problem', 'fr' => 'problème', 'ko' => '문제'],
        '四' => ['en' => 'four', 'es' => 'cuatro', 'de' => 'vier', 'fr' => 'quatre', 'ko' => '넷'],
        '塩' => ['en' => 'salt', 'es' => 'sal', 'de' => 'Salz', 'fr' => 'sel', 'ko' => '소금'],
        '売り場' => ['en' => 'aisle', 'es' => 'pasillo', 'de' => 'Regal', 'fr' => 'rayon', 'ko' => '진열대'],
        '夏' => ['en' => 'summer', 'es' => 'verano', 'de' => 'Sommer', 'fr' => 'été', 'ko' => '여름'],
        '夕方' => ['en' => 'evening', 'es' => 'tarde', 'de' => 'Abend', 'fr' => 'soir', 'ko' => '저녁'],
        '夜' => ['en' => 'night', 'es' => 'noche', 'de' => 'Nacht', 'fr' => 'nuit', 'ko' => '밤'],
        '大きい' => ['en' => 'big', 'es' => 'grande', 'de' => 'groß', 'fr' => 'grand', 'ko' => '큰'],
        '天気' => ['en' => 'weather', 'es' => 'tiempo', 'de' => 'Wetter', 'fr' => 'temps', 'ko' => '날씨'],
        '太陽' => ['en' => 'sun', 'es' => 'sol', 'de' => 'Sonne', 'fr' => 'soleil', 'ko' => '해'],
        '姉妹' => ['en' => 'sister', 'es' => 'hermana', 'de' => 'Schwester', 'fr' => 'sœur', 'ko' => '자매'],
        '嬉しい' => ['en' => 'glad', 'es' => 'contento', 'de' => 'froh', 'fr' => 'content', 'ko' => '기쁜'],
        '子供' => ['en' => 'child', 'es' => 'niño', 'de' => 'Kind', 'fr' => 'enfant', 'ko' => '아이'],
        '季節' => ['en' => 'season', 'es' => 'estación', 'de' => 'Jahreszeit', 'fr' => 'saison', 'ko' => '계절'],
        '学校' => ['en' => 'school', 'es' => 'escuela', 'de' => 'Schule', 'fr' => 'école', 'ko' => '학교'],
        '安い' => ['en' => 'cheap', 'es' => 'barato', 'de' => 'billig', 'fr' => 'bon marché', 'ko' => '싼'],
        '完璧' => ['en' => 'perfect', 'es' => 'perfecto', 'de' => 'perfekt', 'fr' => 'parfait', 'ko' => '완벽한'],
        '家' => ['en' => 'house', 'es' => 'casa', 'de' => 'Haus', 'fr' => 'maison', 'ko' => '집'],
        '小さい' => ['en' => 'small', 'es' => 'pequeño', 'de' => 'klein', 'fr' => 'petit', 'ko' => '작은'],
        '少し' => ['en' => 'a little', 'es' => 'un poco', 'de' => 'ein bisschen', 'fr' => 'un peu', 'ko' => '조금'],
        '少しの' => ['en' => 'some', 'es' => 'algo de', 'de' => 'etwas', 'fr' => 'du', 'ko' => '약간의'],
        '左' => ['en' => 'left', 'es' => 'izquierda', 'de' => 'links', 'fr' => 'gauche', 'ko' => '왼쪽'],
        '席' => ['en' => 'seat', 'es' => 'sitio', 'de' => 'Platz', 'fr' => 'place', 'ko' => '자리'],
        '年齢' => ['en' => 'age', 'es' => 'edad', 'de' => 'Alter', 'fr' => 'âge', 'ko' => '나이'],
        '幸せ' => ['en' => 'happy', 'es' => 'feliz', 'de' => 'glücklich', 'fr' => 'heureux', 'ko' => '행복한'],
        '店' => ['en' => 'shop', 'es' => 'tienda', 'de' => 'Geschäft', 'fr' => 'magasin', 'ko' => '가게'],
        '店内で' => ['en' => 'eat in', 'es' => 'para tomar aquí', 'de' => 'zum Hieressen', 'fr' => 'sur place', 'ko' => '매장에서'],
        '彼は' => ['en' => 'he is', 'es' => 'él es', 'de' => 'er ist', 'fr' => 'il est', 'ko' => '그는'],
        '彼女は' => ['en' => 'she is', 'es' => 'ella es', 'de' => 'sie ist', 'fr' => 'elle est', 'ko' => '그녀는'],
        '待つ' => ['en' => 'wait', 'es' => 'esperar', 'de' => 'warten', 'fr' => 'attendre', 'ko' => '기다리다'],
        '後で' => ['en' => 'later', 'es' => 'más tarde', 'de' => 'später', 'fr' => 'plus tard', 'ko' => '나중에'],
        '後に' => ['en' => 'after', 'es' => 'después', 'de' => 'nach', 'fr' => 'après', 'ko' => '후에'],
        '後ろに' => ['en' => 'behind', 'es' => 'detrás', 'de' => 'hinten', 'fr' => 'derrière', 'ko' => '뒤에'],
        '忙しい' => ['en' => 'busy', 'es' => 'ocupado', 'de' => 'beschäftigt', 'fr' => 'occupé', 'ko' => '바쁜'],
        '悲しい' => ['en' => 'sad', 'es' => 'triste', 'de' => 'traurig', 'fr' => 'triste', 'ko' => '슬픈'],
        '払う' => ['en' => 'pay', 'es' => 'pagar', 'de' => 'bezahlen', 'fr' => 'payer', 'ko' => '지불하다'],
        '折り返す' => ['en' => 'call back', 'es' => 'devolver la llamada', 'de' => 'zurückrufen', 'fr' => 'rappeler', 'ko' => '다시 전화하다'],
        '持ち帰り' => ['en' => 'takeaway', 'es' => 'para llevar', 'de' => 'zum Mitnehmen', 'fr' => 'à emporter', 'ko' => '포장'],
        '持ってきてください' => ['en' => 'bring me', 'es' => 'tráigame', 'de' => 'bringen Sie mir', 'fr' => 'apportez-moi', 'ko' => '가져다주세요'],
        '持ってくる' => ['en' => 'to bring', 'es' => 'traer', 'de' => 'bringen', 'fr' => 'apporter', 'ko' => '가져오다'],
        '探す' => ['en' => 'to look for', 'es' => 'buscar', 'de' => 'suchen', 'fr' => 'chercher', 'ko' => '찾다'],
        '料理' => ['en' => 'dish', 'es' => 'plato', 'de' => 'Gericht', 'fr' => 'plat', 'ko' => '요리'],
        '新しい' => ['en' => 'new', 'es' => 'nuevo', 'de' => 'neu', 'fr' => 'nouveau', 'ko' => '새로운'],
        '新鮮' => ['en' => 'fresh', 'es' => 'fresco', 'de' => 'frisch', 'fr' => 'frais', 'ko' => '신선한'],
        '日' => ['en' => 'day', 'es' => 'día', 'de' => 'Tag', 'fr' => 'jour', 'ko' => '날'],
        '明日' => ['en' => 'tomorrow', 'es' => 'mañana', 'de' => 'morgen', 'fr' => 'demain', 'ko' => '내일'],
        '映画' => ['en' => 'film', 'es' => 'película', 'de' => 'Film', 'fr' => 'film', 'ko' => '영화'],
        '春' => ['en' => 'spring', 'es' => 'primavera', 'de' => 'Frühling', 'fr' => 'printemps', 'ko' => '봄'],
        '昨日' => ['en' => 'yesterday', 'es' => 'ayer', 'de' => 'gestern', 'fr' => 'hier', 'ko' => '어제'],
        '時' => ['en' => 'o\'clock', 'es' => 'en punto', 'de' => 'Uhr', 'fr' => 'heures', 'ko' => '시'],
        '時計' => ['en' => 'clock', 'es' => 'reloj', 'de' => 'Uhr', 'fr' => 'horloge', 'ko' => '시계'],
        '時間' => ['en' => 'hour', 'es' => 'hora', 'de' => 'Stunde', 'fr' => 'heure', 'ko' => '시간'],
        '暇' => ['en' => 'free', 'es' => 'libre', 'de' => 'frei', 'fr' => 'libre', 'ko' => '한가한'],
        '暖かい' => ['en' => 'warm', 'es' => 'cálido', 'de' => 'warm', 'fr' => 'doux', 'ko' => '따뜻한'],
        '曲がる' => ['en' => 'turn', 'es' => 'girar', 'de' => 'abbiegen', 'fr' => 'tourner', 'ko' => '돌다'],
        '月曜日' => ['en' => 'Monday', 'es' => 'lunes', 'de' => 'Montag', 'fr' => 'lundi', 'ko' => '월요일'],
        '朝' => ['en' => 'morning', 'es' => 'mañana', 'de' => 'Morgen', 'fr' => 'matin', 'ko' => '아침'],
        '本' => ['en' => 'book', 'es' => 'libro', 'de' => 'Buch', 'fr' => 'livre', 'ko' => '책'],
        '本当' => ['en' => 'true', 'es' => 'verdadero', 'de' => 'wahr', 'fr' => 'vrai', 'ko' => '사실'],
        '本当に' => ['en' => 'really', 'es' => 'de verdad', 'de' => 'wirklich', 'fr' => 'vraiment', 'ko' => '정말'],
        '材料' => ['en' => 'ingredients', 'es' => 'ingredientes', 'de' => 'Zutaten', 'fr' => 'ingrédients', 'ko' => '재료'],
        '村' => ['en' => 'village', 'es' => 'pueblo', 'de' => 'Dorf', 'fr' => 'village', 'ko' => '마을'],
        '来る' => ['en' => 'come', 'es' => 'venir', 'de' => 'kommen', 'fr' => 'venir', 'ko' => '오다'],
        '果物' => ['en' => 'fruit', 'es' => 'fruta', 'de' => 'Obst', 'fr' => 'fruit', 'ko' => '과일'],
        '椅子' => ['en' => 'chair', 'es' => 'silla', 'de' => 'Stuhl', 'fr' => 'chaise', 'ko' => '의자'],
        '次の' => ['en' => 'next', 'es' => 'próximo', 'de' => 'nächste', 'fr' => 'prochain', 'ko' => '다음'],
        '正午' => ['en' => 'noon', 'es' => 'mediodía', 'de' => 'Mittag', 'fr' => 'midi', 'ko' => '정오'],
        '歩く' => ['en' => 'walk', 'es' => 'caminar', 'de' => 'gehen', 'fr' => 'marcher', 'ko' => '걷다'],
        '歳' => ['en' => 'years old', 'es' => 'años', 'de' => 'Jahre alt', 'fr' => 'ans', 'ko' => '살'],
        '母' => ['en' => 'mother', 'es' => 'madre', 'de' => 'Mutter', 'fr' => 'mère', 'ko' => '어머니'],
        '比べる' => ['en' => 'to compare', 'es' => 'comparar', 'de' => 'vergleichen', 'fr' => 'comparer', 'ko' => '비교하다'],
        '水' => ['en' => 'water', 'es' => 'agua', 'de' => 'Wasser', 'fr' => 'eau', 'ko' => '물'],
        '氷' => ['en' => 'ice', 'es' => 'hielo', 'de' => 'Eiswürfel', 'fr' => 'glaçons', 'ko' => '얼음'],
        '汚い' => ['en' => 'dirty', 'es' => 'sucio', 'de' => 'schmutzig', 'fr' => 'sale', 'ko' => '더러운'],
        '注文' => ['en' => 'order', 'es' => 'pedido', 'de' => 'Bestellung', 'fr' => 'commande', 'ko' => '주문'],
        '注文する' => ['en' => 'to order', 'es' => 'pedir', 'de' => 'bestellen', 'fr' => 'commander', 'ko' => '주문하다'],
        '渡る' => ['en' => 'cross', 'es' => 'cruzar', 'de' => 'überqueren', 'fr' => 'traverser', 'ko' => '건너다'],
        '準備ができた' => ['en' => 'ready', 'es' => 'listo', 'de' => 'bereit', 'fr' => 'prêt', 'ko' => '준비된'],
        '火曜日' => ['en' => 'Tuesday', 'es' => 'martes', 'de' => 'Dienstag', 'fr' => 'mardi', 'ko' => '화요일'],
        '熱い' => ['en' => 'hot', 'es' => 'caliente', 'de' => 'heiß', 'fr' => 'chaud', 'ko' => '뜨거운'],
        '父' => ['en' => 'father', 'es' => 'padre', 'de' => 'Vater', 'fr' => 'père', 'ko' => '아버지'],
        '牛乳' => ['en' => 'milk', 'es' => 'leche', 'de' => 'Milch', 'fr' => 'lait', 'ko' => '우유'],
        '特に' => ['en' => 'especially', 'es' => 'sobre todo', 'de' => 'besonders', 'fr' => 'surtout', 'ko' => '특히'],
        '犬' => ['en' => 'dog', 'es' => 'perro', 'de' => 'Hund', 'fr' => 'chien', 'ko' => '개'],
        '猫' => ['en' => 'cat', 'es' => 'gato', 'de' => 'Katze', 'fr' => 'chat', 'ko' => '고양이'],
        '玉ねぎ' => ['en' => 'onion', 'es' => 'cebolla', 'de' => 'Zwiebel', 'fr' => 'oignon', 'ko' => '양파'],
        '現金で' => ['en' => 'cash', 'es' => 'en efectivo', 'de' => 'in bar', 'fr' => 'en espèces', 'ko' => '현금으로'],
        '甘い' => ['en' => 'sweet', 'es' => 'dulce', 'de' => 'süß', 'fr' => 'sucré', 'ko' => '단'],
        '町' => ['en' => 'town', 'es' => 'ciudad', 'de' => 'Stadt', 'fr' => 'ville', 'ko' => '도시'],
        '疲れた' => ['en' => 'tired', 'es' => 'cansado', 'de' => 'müde', 'fr' => 'fatigué', 'ko' => '피곤한'],
        '病気' => ['en' => 'sick', 'es' => 'enfermo', 'de' => 'krank', 'fr' => 'malade', 'ko' => '아픈'],
        '白' => ['en' => 'white', 'es' => 'blanco', 'de' => 'weiß', 'fr' => 'blanc', 'ko' => '하얀색'],
        '眠る' => ['en' => 'sleep', 'es' => 'dormir', 'de' => 'schlafen', 'fr' => 'dormir', 'ko' => '자다'],
        '砂糖' => ['en' => 'sugar', 'es' => 'azúcar', 'de' => 'Zucker', 'fr' => 'sucre', 'ko' => '설탕'],
        '確認する' => ['en' => 'to confirm', 'es' => 'confirmar', 'de' => 'bestätigen', 'fr' => 'confirmer', 'ko' => '확인하다'],
        '私' => ['en' => 'I', 'es' => 'yo', 'de' => 'ich', 'fr' => 'je', 'ko' => '나'],
        '私が払う' => ['en' => 'I pay', 'es' => 'pago', 'de' => 'ich bezahle', 'fr' => 'je paie', 'ko' => '제가 냅니다'],
        '私の' => ['en' => 'my', 'es' => 'mi', 'de' => 'mein', 'fr' => 'mon', 'ko' => '나의'],
        '私はできる' => ['en' => 'I can', 'es' => 'puedo', 'de' => 'ich kann', 'fr' => 'je peux', 'ko' => '나는 할 수 있다'],
        '私は住んでいる' => ['en' => 'I live', 'es' => 'vivo', 'de' => 'ich wohne', 'fr' => 'j\'habite', 'ko' => '나는 삽니다'],
        '私は信じる' => ['en' => 'I believe', 'es' => 'creo que', 'de' => 'ich glaube', 'fr' => 'je crois', 'ko' => '나는 믿는다'],
        '私は好む' => ['en' => 'I prefer', 'es' => 'prefiero', 'de' => 'ich bevorzuge', 'fr' => 'je préfère', 'ko' => '나는 선호한다'],
        '私は思う' => ['en' => 'I think', 'es' => 'creo', 'de' => 'ich denke', 'fr' => 'je pense', 'ko' => '나는 생각한다'],
        '私は感じる' => ['en' => 'I feel', 'es' => 'me siento', 'de' => 'ich fühle mich', 'fr' => 'je me sens', 'ko' => '나는 느낍니다'],
        '私は持っている' => ['en' => 'I have', 'es' => 'tengo', 'de' => 'ich habe', 'fr' => 'j\'ai', 'ko' => '나는 가지고 있다'],
        '私は行く' => ['en' => 'I am going', 'es' => 'voy', 'de' => 'ich gehe', 'fr' => 'je vais', 'ko' => '나는 갈 것이다'],
        '私は見た' => ['en' => 'I saw', 'es' => 'vi', 'de' => 'ich sah', 'fr' => 'j\'ai vu', 'ko' => '나는 보았다'],
        '私は食べた' => ['en' => 'I ate', 'es' => 'comí', 'de' => 'ich aß', 'fr' => 'j\'ai mangé', 'ko' => '나는 먹었다'],
        '私は飲んだ' => ['en' => 'I drank', 'es' => 'bebí', 'de' => 'ich trank', 'fr' => 'j\'ai bu', 'ko' => '나는 마셨다'],
        'ほしいです' => ['en' => 'want', 'es' => 'quiero', 'de' => 'möchte', 'fr' => 'veux', 'ko' => '원합니다'],
        'たいです' => ['en' => 'want to', 'es' => 'quiero', 'de' => 'möchte', 'fr' => 'veux', 'ko' => '하고 싶습니다'],
        'にします' => ['en' => 'will have', 'es' => 'tomo', 'de' => 'nehme', 'fr' => 'prends', 'ko' => '로 하겠습니다'],
        '秋' => ['en' => 'autumn', 'es' => 'otoño', 'de' => 'Herbst', 'fr' => 'automne', 'ko' => '가을'],
        '空' => ['en' => 'sky', 'es' => 'cielo', 'de' => 'Himmel', 'fr' => 'ciel', 'ko' => '하늘'],
        '箱' => ['en' => 'box', 'es' => 'caja', 'de' => 'Schachtel', 'fr' => 'boîte', 'ko' => '상자'],
        '簡単' => ['en' => 'easy', 'es' => 'fácil', 'de' => 'einfach', 'fr' => 'facile', 'ko' => '쉬운'],
        '素晴らしい' => ['en' => 'excellent', 'es' => 'excelente', 'de' => 'ausgezeichnet', 'fr' => 'excellent', 'ko' => '훌륭한'],
        '続ける' => ['en' => 'continue', 'es' => 'continuar', 'de' => 'weitergehen', 'fr' => 'continuer', 'ko' => '계속하다'],
        '緑' => ['en' => 'green', 'es' => 'verde', 'de' => 'grün', 'fr' => 'vert', 'ko' => '초록색'],
        '美しい' => ['en' => 'beautiful', 'es' => 'hermoso', 'de' => 'schön', 'fr' => 'beau', 'ko' => '아름다운'],
        '肉' => ['en' => 'meat', 'es' => 'carne', 'de' => 'Fleisch', 'fr' => 'viande', 'ko' => '고기'],
        '良い' => ['en' => 'good', 'es' => 'bueno', 'de' => 'gut', 'fr' => 'bon', 'ko' => '좋은'],
        '落ち着いた' => ['en' => 'calm', 'es' => 'tranquilo', 'de' => 'ruhig', 'fr' => 'calme', 'ko' => '차분한'],
        '行きましょう' => ['en' => 'let\'s go', 'es' => 'vamos', 'de' => 'lass uns gehen', 'fr' => 'allons-y', 'ko' => '갑시다'],
        '行く' => ['en' => 'go', 'es' => 'ir', 'de' => 'gehen', 'fr' => 'aller', 'ko' => '가다'],
        '袋' => ['en' => 'bag', 'es' => 'bolsa', 'de' => 'Tüte', 'fr' => 'sac', 'ko' => '봉투'],
        '見つける' => ['en' => 'to find', 'es' => 'encontrar', 'de' => 'finden', 'fr' => 'trouver', 'ko' => '발견하다'],
        '見る' => ['en' => 'watch', 'es' => 'mirar', 'de' => 'schauen', 'fr' => 'regarder', 'ko' => '보다'],
        '話す' => ['en' => 'speak', 'es' => 'hablar', 'de' => 'sprechen', 'fr' => 'parler', 'ko' => '말하다'],
        '読む' => ['en' => 'read', 'es' => 'leer', 'de' => 'lesen', 'fr' => 'lire', 'ko' => '읽다'],
        '誰' => ['en' => 'who', 'es' => 'quién', 'de' => 'wer', 'fr' => 'qui', 'ko' => '누구'],
        '買う' => ['en' => 'to buy', 'es' => 'comprar', 'de' => 'kaufen', 'fr' => 'acheter', 'ko' => '사다'],
        '赤' => ['en' => 'red', 'es' => 'rojo', 'de' => 'rot', 'fr' => 'rouge', 'ko' => '빨간색'],
        '軽い' => ['en' => 'light', 'es' => 'ligero', 'de' => 'leicht', 'fr' => 'léger', 'ko' => '가벼운'],
        '辛い' => ['en' => 'spicy', 'es' => 'picante', 'de' => 'scharf', 'fr' => 'épicé', 'ko' => '매운'],
        '近く' => ['en' => 'near', 'es' => 'cerca', 'de' => 'nah', 'fr' => 'près', 'ko' => '가까이'],
        '通り' => ['en' => 'street', 'es' => 'calle', 'de' => 'Straße', 'fr' => 'rue', 'ko' => '거리'],
        '速い' => ['en' => 'fast', 'es' => 'rápido', 'de' => 'schnell', 'fr' => 'rapide', 'ko' => '빠른'],
        '週' => ['en' => 'week', 'es' => 'semana', 'de' => 'Woche', 'fr' => 'semaine', 'ko' => '주'],
        '運ぶ' => ['en' => 'to carry', 'es' => 'llevar', 'de' => 'tragen', 'fr' => 'porter', 'ko' => '나르다'],
        '遠く' => ['en' => 'far', 'es' => 'lejos', 'de' => 'weit', 'fr' => 'loin', 'ko' => '멀리'],
        '選ぶ' => ['en' => 'to choose', 'es' => 'elegir', 'de' => 'wählen', 'fr' => 'choisir', 'ko' => '고르다'],
        '避ける' => ['en' => 'to avoid', 'es' => 'evitar', 'de' => 'vermeiden', 'fr' => 'éviter', 'ko' => '피하다'],
        '都市' => ['en' => 'city', 'es' => 'ciudad', 'de' => 'Stadt', 'fr' => 'ville', 'ko' => '도시'],
        '重い' => ['en' => 'heavy', 'es' => 'pesado', 'de' => 'schwer', 'fr' => 'lourd', 'ko' => '무거운'],
        '野菜' => ['en' => 'vegetables', 'es' => 'verduras', 'de' => 'Gemüse', 'fr' => 'légumes', 'ko' => '채소'],
        '量る' => ['en' => 'to weigh', 'es' => 'pesar', 'de' => 'wiegen', 'fr' => 'peser', 'ko' => '무게를 재다'],
        '閉じた' => ['en' => 'closed', 'es' => 'cerrado', 'de' => 'geschlossen', 'fr' => 'fermé', 'ko' => '닫힌'],
        '開いた' => ['en' => 'open', 'es' => 'abierto', 'de' => 'offen', 'fr' => 'ouvert', 'ko' => '열린'],
        '隣人' => ['en' => 'neighbour', 'es' => 'vecino', 'de' => 'Nachbar', 'fr' => 'voisin', 'ko' => '이웃'],
        '難しい' => ['en' => 'hard', 'es' => 'difícil', 'de' => 'schwer', 'fr' => 'difficile', 'ko' => '어려운'],
        '雨' => ['en' => 'rain', 'es' => 'lluvia', 'de' => 'Regen', 'fr' => 'pluie', 'ko' => '비'],
        '雪' => ['en' => 'snow', 'es' => 'nieve', 'de' => 'Schnee', 'fr' => 'neige', 'ko' => '눈'],
        '雲' => ['en' => 'cloud', 'es' => 'nube', 'de' => 'Wolke', 'fr' => 'nuage', 'ko' => '구름'],
        '電話' => ['en' => 'phone', 'es' => 'teléfono', 'de' => 'Telefon', 'fr' => 'téléphone', 'ko' => '전화'],
        '電話する' => ['en' => 'call', 'es' => 'llamar', 'de' => 'anrufen', 'fr' => 'appeler', 'ko' => '전화하다'],
        '青' => ['en' => 'blue', 'es' => 'azul', 'de' => 'blau', 'fr' => 'bleu', 'ko' => '파란색'],
        '風' => ['en' => 'wind', 'es' => 'viento', 'de' => 'Wind', 'fr' => 'vent', 'ko' => '바람'],
        '食べる' => ['en' => 'eat', 'es' => 'comer', 'de' => 'essen', 'fr' => 'manger', 'ko' => '먹다'],
        '食事制限' => ['en' => 'diet', 'es' => 'dieta', 'de' => 'Diät', 'fr' => 'régime', 'ko' => '식단'],
        '飲み物' => ['en' => 'a drink', 'es' => 'una bebida', 'de' => 'ein Getränk', 'fr' => 'une boisson', 'ko' => '음료'],
        '飲む' => ['en' => 'drink', 'es' => 'beber', 'de' => 'trinken', 'fr' => 'boire', 'ko' => '마시다'],
        '駅' => ['en' => 'station', 'es' => 'estación', 'de' => 'Bahnhof', 'fr' => 'gare', 'ko' => '역'],
        '高い' => ['en' => 'expensive', 'es' => 'caro', 'de' => 'teuer', 'fr' => 'cher', 'ko' => '비싼'],
        '魚' => ['en' => 'fish', 'es' => 'pescado', 'de' => 'Fisch', 'fr' => 'poisson', 'ko' => '생선'],
        '鶏肉' => ['en' => 'chicken', 'es' => 'pollo', 'de' => 'Hähnchen', 'fr' => 'poulet', 'ko' => '닭고기'],
        '黄色' => ['en' => 'yellow', 'es' => 'amarillo', 'de' => 'gelb', 'fr' => 'jaune', 'ko' => '노란색'],
        '黒' => ['en' => 'black', 'es' => 'negro', 'de' => 'schwarz', 'fr' => 'noir', 'ko' => '검은색'],
        // ---- Particles and postpositions ----------------------------------
        // These attach AFTER the word they mark. They used to be stored with a
        // leading ～ to show a learner where the noun goes, but the seeders
        // then used them as literal tiles, so learners were asked to place a
        // tile reading "～の上に". The placeholder job belongs in the hint.
        'が' => ['en' => 'subject marker', 'es' => 'marca de sujeto', 'de' => 'Subjektpartikel', 'fr' => 'marque de sujet', 'ko' => '주격 조사'],
        'に' => ['en' => 'at / to', 'es' => 'en / a', 'de' => 'an / zu', 'fr' => 'à', 'ko' => '에'],
        'で' => ['en' => 'at (where it happens)', 'es' => 'en', 'de' => 'an', 'fr' => 'à', 'ko' => '에서'],
        'へ' => ['en' => 'towards', 'es' => 'hacia', 'de' => 'nach', 'fr' => 'vers', 'ko' => '로'],
        'か' => ['en' => 'question marker', 'es' => 'marca de pregunta', 'de' => 'Fragepartikel', 'fr' => 'marque de question', 'ko' => '의문 조사'],
        'の上に' => ['en' => 'on top of', 'es' => 'encima de', 'de' => 'auf', 'fr' => 'sur', 'ko' => '위에'],
        'の下に' => ['en' => 'underneath', 'es' => 'debajo de', 'de' => 'unter', 'fr' => 'sous', 'ko' => '아래에'],
        'の中に' => ['en' => 'inside', 'es' => 'dentro de', 'de' => 'in', 'fr' => 'dans', 'ko' => '안에'],
        'の前に' => ['en' => 'in front of', 'es' => 'delante de', 'de' => 'vor', 'fr' => 'devant', 'ko' => '앞에'],
        'の後ろに' => ['en' => 'behind', 'es' => 'detrás de', 'de' => 'hinter', 'fr' => 'derrière', 'ko' => '뒤에'],
        'のために' => ['en' => 'for', 'es' => 'para', 'de' => 'für', 'fr' => 'pour', 'ko' => '을 위해'],
        'なし' => ['en' => 'without', 'es' => 'sin', 'de' => 'ohne', 'fr' => 'sans', 'ko' => '없이'],
        'と一緒に' => ['en' => 'together with', 'es' => 'junto con', 'de' => 'zusammen mit', 'fr' => 'avec', 'ko' => '와 함께'],

        // ---- Verbs and copula, stored inflected ----------------------------
        // A tile must be a form the learner would actually write. The old
        // entries ("私は～です") bundled a subject, a particle and a copula
        // into one tile that could not be placed anywhere.
        'でした' => ['en' => 'was', 'es' => 'era', 'de' => 'war', 'fr' => 'était', 'ko' => '였습니다'],
        'ください' => ['en' => 'please give me', 'es' => 'deme', 'de' => 'geben Sie mir', 'fr' => 'donnez-moi', 'ko' => '주세요'],
        'います' => ['en' => 'there is (living thing)', 'es' => 'hay', 'de' => 'ist da', 'fr' => 'il y a', 'ko' => '있습니다'],
        'あります' => ['en' => 'there is (object)', 'es' => 'hay', 'de' => 'ist da', 'fr' => 'il y a', 'ko' => '있습니다'],
        'ました' => ['en' => 'did (past)', 'es' => 'hizo', 'de' => 'tat', 'fr' => 'a fait', 'ko' => '했습니다'],
        '必要です' => ['en' => 'is needed', 'es' => 'es necesario', 'de' => 'wird gebraucht', 'fr' => 'est nécessaire', 'ko' => '필요합니다'],
        'できますか' => ['en' => 'could you', 'es' => 'podría', 'de' => 'könnten Sie', 'fr' => 'pourriez-vous', 'ko' => '해 주시겠어요'],
        'すぎます' => ['en' => 'too (excessively)', 'es' => 'demasiado', 'de' => 'zu sehr', 'fr' => 'trop', 'ko' => '너무'],

        // ---- Adjectives in the form that can modify a noun ------------------
        // A bare colour noun cannot: 赤 本 is not "a red book".
        '赤い' => ['en' => 'red', 'es' => 'rojo', 'de' => 'rot', 'fr' => 'rouge', 'ko' => '빨간'],
        '青い' => ['en' => 'blue', 'es' => 'azul', 'de' => 'blau', 'fr' => 'bleu', 'ko' => '파란'],
        '白い' => ['en' => 'white', 'es' => 'blanco', 'de' => 'weiß', 'fr' => 'blanc', 'ko' => '하얀'],
        '黒い' => ['en' => 'black', 'es' => 'negro', 'de' => 'schwarz', 'fr' => 'noir', 'ko' => '검은'],
        '黄色い' => ['en' => 'yellow', 'es' => 'amarillo', 'de' => 'gelb', 'fr' => 'jaune', 'ko' => '노란'],
        '緑の' => ['en' => 'green', 'es' => 'verde', 'de' => 'grün', 'fr' => 'vert', 'ko' => '초록'],
        '簡単な' => ['en' => 'easy', 'es' => 'fácil', 'de' => 'einfach', 'fr' => 'facile', 'ko' => '쉬운'],
        '新鮮な' => ['en' => 'fresh', 'es' => 'fresco', 'de' => 'frisch', 'fr' => 'frais', 'ko' => '신선한'],
        'きれいな' => ['en' => 'clean', 'es' => 'limpio', 'de' => 'sauber', 'fr' => 'propre', 'ko' => '깨끗한'],
        '完璧な' => ['en' => 'perfect', 'es' => 'perfecto', 'de' => 'perfekt', 'fr' => 'parfait', 'ko' => '완벽한'],
        '硬い' => ['en' => 'hard to the touch', 'es' => 'duro', 'de' => 'hart', 'fr' => 'dur', 'ko' => '딱딱한'],

        // ---- Counters --------------------------------------------------------
        // Japanese counts with a counter matched to the shape of the thing.
        // 一 本 does not mean "one book"; 一本 counts long thin objects.
        '一冊' => ['en' => 'one (book)', 'es' => 'un (libro)', 'de' => 'ein (Buch)', 'fr' => 'un (livre)', 'ko' => '한 권'],
        '二冊' => ['en' => 'two (books)', 'es' => 'dos (libros)', 'de' => 'zwei (Bücher)', 'fr' => 'deux (livres)', 'ko' => '두 권'],
        '三冊' => ['en' => 'three (books)', 'es' => 'tres (libros)', 'de' => 'drei (Bücher)', 'fr' => 'trois (livres)', 'ko' => '세 권'],
        '一本' => ['en' => 'one (long object)', 'es' => 'uno (alargado)', 'de' => 'ein (längliches)', 'fr' => 'un (long)', 'ko' => '한 자루'],
        '二本' => ['en' => 'two (long objects)', 'es' => 'dos (alargados)', 'de' => 'zwei (längliche)', 'fr' => 'deux (longs)', 'ko' => '두 자루'],
        '十本' => ['en' => 'ten (long objects)', 'es' => 'diez (alargados)', 'de' => 'zehn (längliche)', 'fr' => 'dix (longs)', 'ko' => '열 자루'],
        '一匹' => ['en' => 'one (animal)', 'es' => 'un (animal)', 'de' => 'ein (Tier)', 'fr' => 'un (animal)', 'ko' => '한 마리'],
        '二匹' => ['en' => 'two (animals)', 'es' => 'dos (animales)', 'de' => 'zwei (Tiere)', 'fr' => 'deux (animaux)', 'ko' => '두 마리'],
        '二人' => ['en' => 'two people', 'es' => 'dos personas', 'de' => 'zwei Personen', 'fr' => 'deux personnes', 'ko' => '두 명'],
        '一時間' => ['en' => 'one hour', 'es' => 'una hora', 'de' => 'eine Stunde', 'fr' => 'une heure', 'ko' => '한 시간'],
        '五分' => ['en' => 'five minutes', 'es' => 'cinco minutos', 'de' => 'fünf Minuten', 'fr' => 'cinq minutes', 'ko' => '오 분'],
        '十歳' => ['en' => 'ten years old', 'es' => 'diez años', 'de' => 'zehn Jahre alt', 'fr' => 'dix ans', 'ko' => '열 살'],
        '上' => ['en' => 'top', 'es' => 'parte superior', 'de' => 'Oberseite', 'fr' => 'dessus', 'ko' => '위'],
        '中' => ['en' => 'inside', 'es' => 'interior', 'de' => 'Inneres', 'fr' => 'intérieur', 'ko' => '안'],
        '下' => ['en' => 'underside', 'es' => 'parte inferior', 'de' => 'Unterseite', 'fr' => 'dessous', 'ko' => '아래'],
        '前' => ['en' => 'front', 'es' => 'delante', 'de' => 'Vorderseite', 'fr' => 'devant', 'ko' => '앞'],
        '後' => ['en' => 'after', 'es' => 'después', 'de' => 'danach', 'fr' => 'après', 'ko' => '후'],
        '後ろ' => ['en' => 'behind', 'es' => 'detrás', 'de' => 'hinten', 'fr' => 'derrière', 'ko' => '뒤'],
        '方' => ['en' => 'side / one of two', 'es' => 'lado', 'de' => 'Seite', 'fr' => 'côté', 'ko' => '쪽'],
        'ため' => ['en' => 'sake', 'es' => 'causa', 'de' => 'wegen', 'fr' => 'cause', 'ko' => '위함'],
        'クロワッサン' => ['en' => 'croissant', 'es' => 'cruasán', 'de' => 'Croissant', 'fr' => 'croissant', 'ko' => '크루아상'],
        'エクレア' => ['en' => 'eclair', 'es' => 'eclair', 'de' => 'Eclair', 'fr' => 'éclair', 'ko' => '에클레르'],
        'ユーロ' => ['en' => 'euro', 'es' => 'euro', 'de' => 'Euro', 'fr' => 'euro', 'ko' => '유로'],
        '無料' => ['en' => 'free of charge', 'es' => 'gratis', 'de' => 'kostenlos', 'fr' => 'gratuit', 'ko' => '무료'],
        '準備' => ['en' => 'preparation', 'es' => 'preparación', 'de' => 'Vorbereitung', 'fr' => 'préparation', 'ko' => '준비'],
        '冊' => ['en' => 'counter for books', 'es' => 'contador de libros', 'de' => 'Zähleinheit Bücher', 'fr' => 'compteur livres', 'ko' => '권'],
        '杯' => ['en' => 'counter for cupfuls', 'es' => 'contador de tazas', 'de' => 'Zähleinheit Tassen', 'fr' => 'compteur tasses', 'ko' => '잔'],
        '月' => ['en' => 'month', 'es' => 'mes', 'de' => 'Monat', 'fr' => 'mois', 'ko' => '월'],
        'いる' => ['en' => 'to exist (living)', 'es' => 'estar', 'de' => 'da sein', 'fr' => 'être', 'ko' => '있다'],
        'いります' => ['en' => 'is needed', 'es' => 'se necesita', 'de' => 'wird gebraucht', 'fr' => 'est nécessaire', 'ko' => '필요합니다'],
        'いりません' => ['en' => 'is not needed', 'es' => 'no se necesita', 'de' => 'wird nicht gebraucht', 'fr' => 'pas nécessaire', 'ko' => '필요 없습니다'],
        '入れた' => ['en' => 'put in (past)', 'es' => 'metido', 'de' => 'hineingetan', 'fr' => 'mis', 'ko' => '넣은'],
        '入り' => ['en' => 'containing', 'es' => 'con', 'de' => 'mit', 'fr' => 'avec', 'ko' => '들어간'],
        '付き' => ['en' => 'served with', 'es' => 'con', 'de' => 'mit', 'fr' => 'avec', 'ko' => '포함'],
        '飼う' => ['en' => 'to keep (a pet)', 'es' => 'tener', 'de' => 'halten', 'fr' => 'avoir', 'ko' => '기르다'],
        '飼って' => ['en' => 'keeping', 'es' => 'teniendo', 'de' => 'haltend', 'fr' => 'ayant', 'ko' => '기르고'],
        '飼っています' => ['en' => 'keeps (a pet)', 'es' => 'tiene', 'de' => 'hält', 'fr' => 'a', 'ko' => '기릅니다'],
        '思う' => ['en' => 'to think', 'es' => 'pensar', 'de' => 'denken', 'fr' => 'penser', 'ko' => '생각하다'],
        '信じる' => ['en' => 'to believe', 'es' => 'creer', 'de' => 'glauben', 'fr' => 'croire', 'ko' => '믿다'],
        '好む' => ['en' => 'to prefer', 'es' => 'preferir', 'de' => 'bevorzugen', 'fr' => 'préférer', 'ko' => '선호하다'],
        '取る' => ['en' => 'to take', 'es' => 'tomar', 'de' => 'nehmen', 'fr' => 'prendre', 'ko' => '가지다'],
        '与える' => ['en' => 'to give', 'es' => 'dar', 'de' => 'geben', 'fr' => 'donner', 'ko' => '주다'],
        '尋ねる' => ['en' => 'to ask', 'es' => 'preguntar', 'de' => 'fragen', 'fr' => 'demander', 'ko' => '묻다'],
        '寝る' => ['en' => 'to go to bed', 'es' => 'acostarse', 'de' => 'schlafen gehen', 'fr' => 'se coucher', 'ko' => '자다'],
        '食べて' => ['en' => 'eating', 'es' => 'comiendo', 'de' => 'essend', 'fr' => 'mangeant', 'ko' => '먹고'],
        '食べた' => ['en' => 'ate', 'es' => 'comió', 'de' => 'aß', 'fr' => 'a mangé', 'ko' => '먹었다'],
        '食べすぎる' => ['en' => 'to eat too much', 'es' => 'comer demasiado', 'de' => 'zu viel essen', 'fr' => 'trop manger', 'ko' => '과식하다'],
        '飲んで' => ['en' => 'drinking', 'es' => 'bebiendo', 'de' => 'trinkend', 'fr' => 'buvant', 'ko' => '마시고'],
        '飲んだ' => ['en' => 'drank', 'es' => 'bebió', 'de' => 'trank', 'fr' => 'a bu', 'ko' => '마셨다'],
        '飲み' => ['en' => 'drinking', 'es' => 'bebida', 'de' => 'Trinken', 'fr' => 'boisson', 'ko' => '마시기'],
        '歩いて' => ['en' => 'walking', 'es' => 'caminando', 'de' => 'gehend', 'fr' => 'marchant', 'ko' => '걷고'],
        '行って' => ['en' => 'going', 'es' => 'yendo', 'de' => 'gehend', 'fr' => 'allant', 'ko' => '가고'],
        '行きたい' => ['en' => 'want to go', 'es' => 'quiero ir', 'de' => 'möchte gehen', 'fr' => 'veux aller', 'ko' => '가고 싶다'],
        '来て' => ['en' => 'coming', 'es' => 'viniendo', 'de' => 'kommend', 'fr' => 'venant', 'ko' => '오고'],
        '眠って' => ['en' => 'sleeping', 'es' => 'durmiendo', 'de' => 'schlafend', 'fr' => 'dormant', 'ko' => '자고'],
        '開いて' => ['en' => 'opening', 'es' => 'abriendo', 'de' => 'öffnend', 'fr' => 'ouvrant', 'ko' => '열고'],
        '開いています' => ['en' => 'is open', 'es' => 'está abierto', 'de' => 'ist geöffnet', 'fr' => 'est ouvert', 'ko' => '열려 있습니다'],
        '閉まって' => ['en' => 'closing', 'es' => 'cerrando', 'de' => 'schließend', 'fr' => 'fermant', 'ko' => '닫고'],
        '閉まっています' => ['en' => 'is closed', 'es' => 'está cerrado', 'de' => 'ist geschlossen', 'fr' => 'est fermé', 'ko' => '닫혀 있습니다'],
        '閉じて' => ['en' => 'closing', 'es' => 'cerrando', 'de' => 'schließend', 'fr' => 'fermant', 'ko' => '닫고'],
        '閉じています' => ['en' => 'is closed', 'es' => 'está cerrado', 'de' => 'ist geschlossen', 'fr' => 'est fermé', 'ko' => '닫혀 있습니다'],
        '住んで' => ['en' => 'living', 'es' => 'viviendo', 'de' => 'wohnend', 'fr' => 'habitant', 'ko' => '살고'],
        '住んでいます' => ['en' => 'lives', 'es' => 'vive', 'de' => 'wohnt', 'fr' => 'habite', 'ko' => '삽니다'],
        '持ってきて' => ['en' => 'bringing', 'es' => 'trayendo', 'de' => 'bringend', 'fr' => 'apportant', 'ko' => '가져오고'],
        '見つけて' => ['en' => 'finding', 'es' => 'encontrando', 'de' => 'findend', 'fr' => 'trouvant', 'ko' => '찾고'],
        '見た' => ['en' => 'saw', 'es' => 'vio', 'de' => 'sah', 'fr' => 'a vu', 'ko' => '보았다'],
        '払い' => ['en' => 'payment', 'es' => 'pago', 'de' => 'Zahlung', 'fr' => 'paiement', 'ko' => '지불'],
        '払えます' => ['en' => 'can pay', 'es' => 'puede pagar', 'de' => 'kann zahlen', 'fr' => 'peut payer', 'ko' => '낼 수 있습니다'],
        'もらえます' => ['en' => 'could I have', 'es' => 'me da', 'de' => 'bekomme ich', 'fr' => 'puis-je avoir', 'ko' => '받을 수 있습니다'],
        'なり' => ['en' => 'becoming', 'es' => 'volviéndose', 'de' => 'werdend', 'fr' => 'devenant', 'ko' => '되고'],
        'して' => ['en' => 'doing', 'es' => 'haciendo', 'de' => 'machend', 'fr' => 'faisant', 'ko' => '하고'],
        'だった' => ['en' => 'was', 'es' => 'era', 'de' => 'war', 'fr' => 'était', 'ko' => '였다'],
        'よく' => ['en' => 'well', 'es' => 'bien', 'de' => 'gut', 'fr' => 'bien', 'ko' => '잘'],
        '速く' => ['en' => 'quickly', 'es' => 'rápido', 'de' => 'schnell', 'fr' => 'vite', 'ko' => '빨리'],
        '少なく' => ['en' => 'fewer', 'es' => 'menos', 'de' => 'weniger', 'fr' => 'moins', 'ko' => '적게'],
        'たくさん' => ['en' => 'a lot', 'es' => 'mucho', 'de' => 'viel', 'fr' => 'beaucoup', 'ko' => '많이'],
        'また' => ['en' => 'again', 'es' => 'otra vez', 'de' => 'wieder', 'fr' => 'encore', 'ko' => '또'],
        'どう' => ['en' => 'how', 'es' => 'cómo', 'de' => 'wie', 'fr' => 'comment', 'ko' => '어떻게'],
        '遠い' => ['en' => 'far', 'es' => 'lejos', 'de' => 'weit', 'fr' => 'loin', 'ko' => '먼'],
        '近い' => ['en' => 'near', 'es' => 'cerca', 'de' => 'nah', 'fr' => 'proche', 'ko' => '가까운'],
        '悪い' => ['en' => 'bad', 'es' => 'malo', 'de' => 'schlecht', 'fr' => 'mauvais', 'ko' => '나쁜'],
        '寒い' => ['en' => 'cold (weather)', 'es' => 'frío', 'de' => 'kalt', 'fr' => 'froid', 'ko' => '추운'],
        '多すぎる' => ['en' => 'too many', 'es' => 'demasiados', 'de' => 'zu viele', 'fr' => 'trop', 'ko' => '너무 많다'],
        '美しくて' => ['en' => 'beautiful and', 'es' => 'hermoso y', 'de' => 'schön und', 'fr' => 'beau et', 'ko' => '아름답고'],
        '良くて' => ['en' => 'good and', 'es' => 'bueno y', 'de' => 'gut und', 'fr' => 'bon et', 'ko' => '좋고'],
        '疲れて' => ['en' => 'tired', 'es' => 'cansado', 'de' => 'müde', 'fr' => 'fatigué', 'ko' => '피곤하고'],
        '満足' => ['en' => 'satisfied', 'es' => 'satisfecho', 'de' => 'zufrieden', 'fr' => 'satisfait', 'ko' => '만족'],
        '高くない' => ['en' => 'not expensive', 'es' => 'no caro', 'de' => 'nicht teuer', 'fr' => 'pas cher', 'ko' => '비싸지 않은'],
        '落ち着いて' => ['en' => 'calmly', 'es' => 'con calma', 'de' => 'ruhig', 'fr' => 'calmement', 'ko' => '차분하게'],
        '感じる' => ['en' => 'to feel', 'es' => 'sentir', 'de' => 'fühlen', 'fr' => 'sentir', 'ko' => '느끼다'],
        'ほしい' => ['en' => 'want', 'es' => 'querer', 'de' => 'wollen', 'fr' => 'vouloir', 'ko' => '원하다'],
        '行ける' => ['en' => 'can go', 'es' => 'puede ir', 'de' => 'kann gehen', 'fr' => 'peut aller', 'ko' => '갈 수 있다'],
        '渡って' => ['en' => 'crossing', 'es' => 'cruzando', 'de' => 'überquerend', 'fr' => 'traversant', 'ko' => '건너서'],
        '選び' => ['en' => 'choosing', 'es' => 'eligiendo', 'de' => 'wählend', 'fr' => 'choisissant', 'ko' => '고르기'],
        '選べます' => ['en' => 'can choose', 'es' => 'puede elegir', 'de' => 'kann wählen', 'fr' => 'peut choisir', 'ko' => '고를 수 있습니다'],
        '確認し' => ['en' => 'confirming', 'es' => 'confirmando', 'de' => 'bestätigend', 'fr' => 'confirmant', 'ko' => '확인하고'],
        '避け' => ['en' => 'avoiding', 'es' => 'evitando', 'de' => 'vermeidend', 'fr' => 'évitant', 'ko' => '피하고'],
        '渇いて' => ['en' => 'thirsty', 'es' => 'sediento', 'de' => 'durstig', 'fr' => 'assoiffé', 'ko' => '목말라'],
        '代金' => ['en' => 'charge', 'es' => 'importe', 'de' => 'Betrag', 'fr' => 'montant', 'ko' => '대금'],
        '持って' => ['en' => 'holding', 'es' => 'llevando', 'de' => 'haltend', 'fr' => 'tenant', 'ko' => '들고'],
        'そこ' => ['en' => 'there', 'es' => 'allí', 'de' => 'dort', 'fr' => 'là', 'ko' => '거기'],
        '間' => ['en' => 'interval', 'es' => 'intervalo', 'de' => 'Zeitraum', 'fr' => 'intervalle', 'ko' => '동안'],
        '昼' => ['en' => 'midday', 'es' => 'mediodía', 'de' => 'Mittag', 'fr' => 'midi', 'ko' => '낮'],
        '晩' => ['en' => 'evening', 'es' => 'noche', 'de' => 'Abend', 'fr' => 'soir', 'ko' => '저녁'],
        '年' => ['en' => 'year', 'es' => 'año', 'de' => 'Jahr', 'fr' => 'an', 'ko' => '년'],
        '歩き' => ['en' => 'walking', 'es' => 'caminando', 'de' => 'gehend', 'fr' => 'marchant', 'ko' => '걷기'],
        'しばしば' => ['en' => 'often', 'es' => 'a menudo', 'de' => 'oft', 'fr' => 'souvent', 'ko' => '자주'],
        '寝て' => ['en' => 'sleeping', 'es' => 'durmiendo', 'de' => 'schlafend', 'fr' => 'dormant', 'ko' => '자고'],
        'すぎる' => ['en' => 'too much', 'es' => 'demasiado', 'de' => 'zu sehr', 'fr' => 'trop', 'ko' => '너무'],
        'すぎて' => ['en' => 'too much and', 'es' => 'demasiado y', 'de' => 'zu sehr und', 'fr' => 'trop et', 'ko' => '너무해서'],
        '話' => ['en' => 'talk', 'es' => 'charla', 'de' => 'Gespräch', 'fr' => 'discussion', 'ko' => '이야기'],
        '複数' => ['en' => 'several', 'es' => 'varios', 'de' => 'mehrere', 'fr' => 'plusieurs', 'ko' => '여러'],
        '何匹' => ['en' => 'how many (animals)', 'es' => 'cuántos', 'de' => 'wie viele', 'fr' => 'combien', 'ko' => '몇 마리'],
        '何' => ['en' => 'what', 'es' => 'qué', 'de' => 'was', 'fr' => 'quoi', 'ko' => '무엇'],
        '自由' => ['en' => 'free', 'es' => 'libre', 'de' => 'frei', 'fr' => 'libre', 'ko' => '자유'],
        '重要' => ['en' => 'important', 'es' => 'importante', 'de' => 'wichtig', 'fr' => 'important', 'ko' => '중요'],
        'さん' => ['en' => 'Mr / Ms', 'es' => 'señor', 'de' => 'Herr / Frau', 'fr' => 'monsieur', 'ko' => '씨'],
        'ような' => ['en' => 'like', 'es' => 'como', 'de' => 'wie', 'fr' => 'comme', 'ko' => '같은'],
        '来' => ['en' => 'come', 'es' => 'venir', 'de' => 'kommen', 'fr' => 'venir', 'ko' => '오다'],
        'きて' => ['en' => 'coming', 'es' => 'viniendo', 'de' => 'kommend', 'fr' => 'venant', 'ko' => '와서'],
        'ありません' => ['en' => 'there is not', 'es' => 'no hay', 'de' => 'gibt es nicht', 'fr' => 'il n\'y a pas', 'ko' => '없습니다'],
        '曲がって' => ['en' => 'turning', 'es' => 'girando', 'de' => 'abbiegend', 'fr' => 'tournant', 'ko' => '돌아서'],
        '一緒' => ['en' => 'together', 'es' => 'juntos', 'de' => 'zusammen', 'fr' => 'ensemble', 'ko' => '함께'],
        '払います' => ['en' => 'pay', 'es' => 'pago', 'de' => 'zahle', 'fr' => 'paie', 'ko' => '냅니다'],
        'いました' => ['en' => 'was there', 'es' => 'estaba', 'de' => 'war da', 'fr' => 'était', 'ko' => '있었습니다'],
        'その時' => ['en' => 'at that time', 'es' => 'entonces', 'de' => 'damals', 'fr' => 'alors', 'ko' => '그때'],
        '予約し' => ['en' => 'reserving', 'es' => 'reservando', 'de' => 'reservierend', 'fr' => 'réservant', 'ko' => '예약하고'],
        '注文し' => ['en' => 'ordering', 'es' => 'pidiendo', 'de' => 'bestellend', 'fr' => 'commandant', 'ko' => '주문하고'],
        '十分な' => ['en' => 'enough', 'es' => 'suficiente', 'de' => 'genug', 'fr' => 'assez de', 'ko' => '충분한'],
        'いくら' => ['en' => 'how much', 'es' => 'cuánto', 'de' => 'wie viel', 'fr' => 'combien', 'ko' => '얼마'],
        '良かった' => ['en' => 'was good', 'es' => 'fue bueno', 'de' => 'war gut', 'fr' => 'était bon', 'ko' => '좋았다'],
        '甘すぎる' => ['en' => 'too sweet', 'es' => 'demasiado dulce', 'de' => 'zu süß', 'fr' => 'trop sucré', 'ko' => '너무 달다'],
        'しょっぱすぎる' => ['en' => 'too salty', 'es' => 'demasiado salado', 'de' => 'zu salzig', 'fr' => 'trop salé', 'ko' => '너무 짜다'],
        'だ' => ['en' => 'is (plain)', 'es' => 'es', 'de' => 'ist', 'fr' => 'est', 'ko' => '이다'],
        '思います' => ['en' => 'I think', 'es' => 'creo', 'de' => 'ich denke', 'fr' => 'je pense', 'ko' => '생각합니다'],
        '匹' => ['en' => 'counter for animals', 'es' => 'contador de animales', 'de' => 'Zähleinheit Tiere', 'fr' => 'compteur animaux', 'ko' => '마리'],
        '個' => ['en' => 'counter for items', 'es' => 'contador de cosas', 'de' => 'Zähleinheit Stücke', 'fr' => 'compteur objets', 'ko' => '개'],
        'どの' => ['en' => 'which', 'es' => 'qué', 'de' => 'welcher', 'fr' => 'quel', 'ko' => '어느'],
        'いた' => ['en' => 'was there', 'es' => 'estaba', 'de' => 'war da', 'fr' => 'était', 'ko' => '있었다'],
        'まで' => ['en' => 'as far as', 'es' => 'hasta', 'de' => 'bis', 'fr' => 'jusqu\'à', 'ko' => '까지'],
        'それぞれ' => ['en' => 'each', 'es' => 'cada', 'de' => 'jeder', 'fr' => 'chaque', 'ko' => '각각'],
        '空いて' => ['en' => 'vacant', 'es' => 'libre', 'de' => 'frei', 'fr' => 'libre', 'ko' => '비어'],
        '空いています' => ['en' => 'is free', 'es' => 'está libre', 'de' => 'ist frei', 'fr' => 'est libre', 'ko' => '비어 있습니다'],
        '渇いています' => ['en' => 'am thirsty', 'es' => 'tengo sed', 'de' => 'bin durstig', 'fr' => 'ai soif', 'ko' => '목마릅니다'],
        '甘すぎます' => ['en' => 'is too sweet', 'es' => 'es demasiado dulce', 'de' => 'ist zu süß', 'fr' => 'est trop sucré', 'ko' => '너무 답니다'],
        'しょっぱすぎます' => ['en' => 'is too salty', 'es' => 'es demasiado salado', 'de' => 'ist zu salzig', 'fr' => 'est trop salé', 'ko' => '너무 짭니다'],
        '暑い' => ['en' => 'hot (weather)', 'es' => 'caluroso', 'de' => 'heiß', 'fr' => 'chaud', 'ko' => '더운'],
        '暑くて' => ['en' => 'hot and', 'es' => 'caluroso y', 'de' => 'heiß und', 'fr' => 'chaud et', 'ko' => '덥고'],
        '長い' => ['en' => 'long', 'es' => 'largo', 'de' => 'lang', 'fr' => 'long', 'ko' => '긴'],
        'よい' => ['en' => 'good', 'es' => 'bueno', 'de' => 'gut', 'fr' => 'bon', 'ko' => '좋은'],
        '母さん' => ['en' => 'mum', 'es' => 'mamá', 'de' => 'Mama', 'fr' => 'maman', 'ko' => '엄마'],
        'もしもし' => ['en' => 'hello (on the phone)', 'es' => 'diga', 'de' => 'hallo', 'fr' => 'allô', 'ko' => '여보세요'],
        '渡す' => ['en' => 'to hand over', 'es' => 'entregar', 'de' => 'übergeben', 'fr' => 'remettre', 'ko' => '건네다'],
        '払って' => ['en' => 'paying', 'es' => 'pagando', 'de' => 'zahlend', 'fr' => 'payant', 'ko' => '내고'],
        '米' => ['en' => 'rice (uncooked)', 'es' => 'arroz', 'de' => 'Reis', 'fr' => 'riz', 'ko' => '쌀'],
        '読んで' => ['en' => 'reading', 'es' => 'leyendo', 'de' => 'lesend', 'fr' => 'lisant', 'ko' => '읽고'],
        '行きます' => ['en' => 'go', 'es' => 'voy', 'de' => 'gehe', 'fr' => 'vais', 'ko' => '갑니다'],
        '面' => ['en' => 'side', 'es' => 'lado', 'de' => 'Seite', 'fr' => 'côté', 'ko' => '면'],
        '表' => ['en' => 'table / chart', 'es' => 'tabla', 'de' => 'Tabelle', 'fr' => 'tableau', 'ko' => '표'],
        'テーブルクロス' => ['en' => 'tablecloth', 'es' => 'mantel', 'de' => 'Tischdecke', 'fr' => 'nappe', 'ko' => '식탁보'],
        '高' => ['en' => 'high', 'es' => 'alto', 'de' => 'hoch', 'fr' => 'haut', 'ko' => '높은'],
        'できる' => ['en' => 'can do', 'es' => 'poder', 'de' => 'können', 'fr' => 'pouvoir', 'ko' => '할 수 있다'],
        'いくつか' => ['en' => 'a few', 'es' => 'algunos', 'de' => 'einige', 'fr' => 'quelques', 'ko' => '몇몇'],
        'のどが' => ['en' => 'throat', 'es' => 'garganta', 'de' => 'Hals', 'fr' => 'gorge', 'ko' => '목이'],
        'もう一つ' => ['en' => 'one more', 'es' => 'uno más', 'de' => 'noch eins', 'fr' => 'un de plus', 'ko' => '하나 더'],
        'あり' => ['en' => 'there is', 'es' => 'hay', 'de' => 'gibt es', 'fr' => 'il y a', 'ko' => '있고'],
        '食べたい' => ['en' => 'want to eat', 'es' => 'quiero comer', 'de' => 'möchte essen', 'fr' => 'veux manger', 'ko' => '먹고 싶다'],
        '近くて' => ['en' => 'near and', 'es' => 'cerca y', 'de' => 'nah und', 'fr' => 'proche et', 'ko' => '가깝고'],
        '時々' => ['en' => 'sometimes', 'es' => 'a veces', 'de' => 'manchmal', 'fr' => 'parfois', 'ko' => '가끔'],
        'わかりました' => ['en' => 'understood', 'es' => 'entendido', 'de' => 'verstanden', 'fr' => 'compris', 'ko' => '알겠습니다'],
        '満足して' => ['en' => 'satisfied and', 'es' => 'satisfecho y', 'de' => 'zufrieden und', 'fr' => 'satisfait et', 'ko' => '만족하고'],
        'いて' => ['en' => 'being', 'es' => 'estando', 'de' => 'seiend', 'fr' => 'étant', 'ko' => '있고'],
        'よかった' => ['en' => 'was good', 'es' => 'fue bueno', 'de' => 'war gut', 'fr' => 'était bon', 'ko' => '좋았다'],
        'すでに' => ['en' => 'already', 'es' => 'ya', 'de' => 'schon', 'fr' => 'déjà', 'ko' => '이미'],
        'こと' => ['en' => 'thing / act', 'es' => 'cosa', 'de' => 'Sache', 'fr' => 'chose', 'ko' => '것'],
        'ができる' => ['en' => 'can', 'es' => 'puede', 'de' => 'kann', 'fr' => 'peut', 'ko' => '할 수 있다'],
        'かかりますか' => ['en' => 'does it cost', 'es' => 'cuesta', 'de' => 'kostet es', 'fr' => 'coûte', 'ko' => '듭니까'],
        'かかります' => ['en' => 'costs', 'es' => 'cuesta', 'de' => 'kostet', 'fr' => 'coûte', 'ko' => '듭니다'],
        '探しています' => ['en' => 'am looking for', 'es' => 'busco', 'de' => 'suche', 'fr' => 'cherche', 'ko' => '찾고 있습니다'],
        'そして' => ['en' => 'and then', 'es' => 'y luego', 'de' => 'und dann', 'fr' => 'et puis', 'ko' => '그리고'],
    ];

    /** Native languages a learner can take a Japanese course in. */
    private const LANGS = ['en', 'es', 'de', 'fr', 'ko'];

    /**
     * The ['i18n' => [...]] map for a Japanese word, ready to store in exercise
     * data. Falls back to the word itself if it isn't in the dictionary yet.
     *
     * @return array{i18n: array<string, string>}
     */
    public static function hint(string $japanese): array
    {
        return ['i18n' => self::meanings($japanese)];
    }

    /**
     * @return array<string, string>
     */
    public static function meanings(string $japanese): array
    {
        $key = trim($japanese);

        foreach (self::WORDS as $word => $translations) {
            if ($word === $key) {
                return $translations;
            }
        }

        // Not in the dictionary: show the Japanese word itself to every learner.
        return array_fill_keys(self::LANGS, $japanese);
    }

    /** Every Japanese word the dictionary knows (used for wrong-answer options). */
    public static function all(): array
    {
        return array_keys(self::WORDS);
    }

    public static function knows(string $japanese): bool
    {
        $key = trim($japanese);

        foreach (array_keys(self::WORDS) as $word) {
            if ($word === $key) {
                return true;
            }
        }

        return false;
    }
}
