<?php

namespace Database\Seeders\Support;

/**
 * Korean word => its meaning in every native language a Korean course supports
 * (English, Spanish, German, French, Japanese).
 *
 * Korean is the LEARNING language here, so exercise content (words, phrases,
 * tiles) is authored in Korean, and only the hints/prompts are shown in the
 * learner's own language. Translations are the authoritative ones already used
 * by the other five course seeders (their `ko` fields), so the courses stay in
 * lockstep. Covers Chapter 1 (Beginner); grows as later chapters are added.
 */
class KoreanVocabulary
{
    private const WORDS = [
        // ---- Position words and verb endings, without the placeholder tilde --
        // These were stored as "~위에" so a learner could see where the noun
        // goes. The seeders then used them as literal tiles, so learners were
        // asked to place a tile reading "~위에". Case particles are gone from
        // this list entirely: Korean joins them to the noun with no space, so
        // they belong on the word tile (고양이가), not on a tile of their own.
        // meanings() strips a trailing particle to find the base noun.
        '위에' => ['en' => 'on top of', 'es' => 'encima de', 'de' => 'auf', 'fr' => 'sur', 'ja' => 'の上に'],
        '아래에' => ['en' => 'underneath', 'es' => 'debajo de', 'de' => 'unter', 'fr' => 'sous', 'ja' => 'の下に'],
        '안에' => ['en' => 'inside', 'es' => 'dentro de', 'de' => 'in', 'fr' => 'dans', 'ja' => 'の中に'],
        '없이' => ['en' => 'without', 'es' => 'sin', 'de' => 'ohne', 'fr' => 'sans', 'ja' => 'なし'],
        '와 함께' => ['en' => 'together with', 'es' => 'junto con', 'de' => 'zusammen mit', 'fr' => 'avec', 'ja' => 'と一緒に'],
        '위해' => ['en' => 'for the sake of', 'es' => 'para', 'de' => 'für', 'fr' => 'pour', 'ja' => 'のために'],
        '주세요' => ['en' => 'please give me', 'es' => 'deme', 'de' => 'geben Sie mir', 'fr' => 'donnez-moi', 'ja' => 'ください'],
        '필요합니다' => ['en' => 'is needed', 'es' => 'es necesario', 'de' => 'wird gebraucht', 'fr' => 'est nécessaire', 'ja' => '必要です'],
        '주시겠어요' => ['en' => 'could you', 'es' => 'podría', 'de' => 'könnten Sie', 'fr' => 'pourriez-vous', 'ja' => 'できますか'],
        '있습니다' => ['en' => 'there is', 'es' => 'hay', 'de' => 'ist da', 'fr' => 'il y a', 'ja' => 'あります'],
        '없습니다' => ['en' => 'there is not', 'es' => 'no hay', 'de' => 'ist nicht da', 'fr' => 'il n\'y a pas', 'ja' => 'ありません'],
        '였습니다' => ['en' => 'was', 'es' => 'era', 'de' => 'war', 'fr' => 'était', 'ja' => 'でした'],
        '하겠습니다' => ['en' => 'will have', 'es' => 'tomo', 'de' => 'nehme', 'fr' => 'prends', 'ja' => 'にします'],
        '싶습니다' => ['en' => 'want to', 'es' => 'quiero', 'de' => 'möchte', 'fr' => 'veux', 'ja' => 'たいです'],
        '가게' => ['en' => 'shop', 'es' => 'tienda', 'de' => 'Geschäft', 'fr' => 'magasin', 'ja' => '店'],
        '가격' => ['en' => 'price', 'es' => 'precio', 'de' => 'Preis', 'fr' => 'prix', 'ja' => '値段'],
        '가까이' => ['en' => 'near', 'es' => 'cerca', 'de' => 'nah', 'fr' => 'près', 'ja' => '近く'],
        '가다' => ['en' => 'go', 'es' => 'ir', 'de' => 'gehen', 'fr' => 'aller', 'ja' => '行く'],
        '가득한' => ['en' => 'full', 'es' => 'lleno', 'de' => 'voll', 'fr' => 'plein', 'ja' => 'いっぱい'],
        '가벼운' => ['en' => 'light', 'es' => 'ligero', 'de' => 'leicht', 'fr' => 'léger', 'ja' => '軽い'],
        '가을' => ['en' => 'autumn', 'es' => 'otoño', 'de' => 'Herbst', 'fr' => 'automne', 'ja' => '秋'],
        '가을과' => ['en' => 'autumn and', 'es' => 'otoño y', 'de' => 'Herbst und', 'fr' => 'automne et', 'ja' => '秋と'],
        '가져다주세요' => ['en' => 'bring me', 'es' => 'tráigame', 'de' => 'bringen Sie mir', 'fr' => 'apportez-moi', 'ja' => '持ってきてください'],
        '가져오다' => ['en' => 'to bring', 'es' => 'traer', 'de' => 'bringen', 'fr' => 'apporter', 'ja' => '持ってくる'],
        '각각의' => ['en' => 'each', 'es' => 'cada', 'de' => 'jeder', 'fr' => 'chaque', 'ja' => 'それぞれの'],
        '감사합니다' => ['en' => 'thank you', 'es' => 'gracias', 'de' => 'danke', 'fr' => 'merci', 'ja' => 'ありがとう'],
        '감자' => ['en' => 'potato', 'es' => 'patata', 'de' => 'Kartoffel', 'fr' => 'pomme de terre', 'ja' => 'じゃがいも'],
        '감자튀김' => ['en' => 'fries', 'es' => 'patatas fritas', 'de' => 'Pommes', 'fr' => 'frites', 'ja' => 'フライドポテト'],
        '갑시다' => ['en' => 'let\'s go', 'es' => 'vamos', 'de' => 'lass uns gehen', 'fr' => 'allons-y', 'ja' => '行きましょう'],
        '같은' => ['en' => 'same', 'es' => 'mismo', 'de' => 'gleich', 'fr' => 'même', 'ja' => '同じ'],
        '개' => ['en' => 'dog', 'es' => 'perro', 'de' => 'Hund', 'fr' => 'chien', 'ja' => '犬'],
        '개들' => ['en' => 'dogs', 'es' => 'perros', 'de' => 'Hunde', 'fr' => 'chiens', 'ja' => '犬'],
        '개와' => ['en' => 'dog and', 'es' => 'perro y', 'de' => 'Hund und', 'fr' => 'chien et', 'ja' => '犬と'],
        '거리' => ['en' => 'street', 'es' => 'calle', 'de' => 'Straße', 'fr' => 'rue', 'ja' => '通り'],
        '거스름돈' => ['en' => 'change', 'es' => 'cambio', 'de' => 'Wechselgeld', 'fr' => 'monnaie', 'ja' => 'おつり'],
        '거짓' => ['en' => 'false', 'es' => 'falso', 'de' => 'falsch', 'fr' => 'faux', 'ja' => '偽'],
        '건너다' => ['en' => 'cross', 'es' => 'cruzar', 'de' => 'überqueren', 'fr' => 'traverser', 'ja' => '渡る'],
        '걷다' => ['en' => 'walk', 'es' => 'caminar', 'de' => 'gehen', 'fr' => 'marcher', 'ja' => '歩く'],
        '검은색' => ['en' => 'black', 'es' => 'negro', 'de' => 'schwarz', 'fr' => 'noir', 'ja' => '黒'],
        '겨울' => ['en' => 'winter', 'es' => 'invierno', 'de' => 'Winter', 'fr' => 'hiver', 'ja' => '冬'],
        '견과류' => ['en' => 'nuts', 'es' => 'nueces', 'de' => 'Nüsse', 'fr' => 'noix', 'ja' => 'ナッツ'],
        '계란' => ['en' => 'egg', 'es' => 'huevo', 'de' => 'Ei', 'fr' => 'œuf', 'ja' => '卵'],
        '계산대' => ['en' => 'checkout', 'es' => 'caja', 'de' => 'Kasse', 'fr' => 'caisse', 'ja' => 'レジ'],
        '계산서' => ['en' => 'the bill', 'es' => 'la cuenta', 'de' => 'die Rechnung', 'fr' => 'l\'addition', 'ja' => 'お会計'],
        '계산원' => ['en' => 'cashier', 'es' => 'cajero', 'de' => 'Kassierer', 'fr' => 'caissier', 'ja' => 'レジ係'],
        '계속하다' => ['en' => 'continue', 'es' => 'continuar', 'de' => 'weitergehen', 'fr' => 'continuer', 'ja' => '続ける'],
        '계절' => ['en' => 'season', 'es' => 'estación', 'de' => 'Jahreszeit', 'fr' => 'saison', 'ja' => '季節'],
        '고기' => ['en' => 'meat', 'es' => 'carne', 'de' => 'Fleisch', 'fr' => 'viande', 'ja' => '肉'],
        '고르다' => ['en' => 'to choose', 'es' => 'elegir', 'de' => 'wählen', 'fr' => 'choisir', 'ja' => '選ぶ'],
        '고양이' => ['en' => 'cat', 'es' => 'gato', 'de' => 'Katze', 'fr' => 'chat', 'ja' => '猫'],
        '고양이들' => ['en' => 'cats', 'es' => 'gatos', 'de' => 'Katzen', 'fr' => 'chats', 'ja' => '猫'],
        '고양이와' => ['en' => 'cat and', 'es' => 'gato y', 'de' => 'Katze und', 'fr' => 'chat et', 'ja' => '猫と'],
        '곧' => ['en' => 'soon', 'es' => 'pronto', 'de' => 'bald', 'fr' => 'bientôt', 'ja' => 'すぐに'],
        '공원' => ['en' => 'park', 'es' => 'parque', 'de' => 'Park', 'fr' => 'parc', 'ja' => '公園'],
        '과일' => ['en' => 'fruit', 'es' => 'fruta', 'de' => 'Obst', 'fr' => 'fruit', 'ja' => '果物'],
        '그' => ['en' => 'the', 'es' => 'el', 'de' => 'der', 'fr' => 'le', 'ja' => 'その'],
        '그것' => ['en' => 'it', 'es' => 'eso', 'de' => 'es', 'fr' => 'ce', 'ja' => 'それ'],
        '그녀는' => ['en' => 'she is', 'es' => 'ella es', 'de' => 'sie ist', 'fr' => 'elle est', 'ja' => '彼女は'],
        '그는' => ['en' => 'he is', 'es' => 'él es', 'de' => 'er ist', 'fr' => 'il est', 'ja' => '彼は'],
        '그램' => ['en' => 'gram', 'es' => 'gramo', 'de' => 'Gramm', 'fr' => 'gramme', 'ja' => 'グラム'],
        '그러면' => ['en' => 'then', 'es' => 'entonces', 'de' => 'dann', 'fr' => 'ensuite', 'ja' => 'それから'],
        '그리고' => ['en' => 'and', 'es' => 'y', 'de' => 'und', 'fr' => 'et', 'ja' => 'と'],
        '그만큼' => ['en' => 'as much', 'es' => 'tanto', 'de' => 'genauso viel', 'fr' => 'autant', 'ja' => '同じくらい'],
        '글루텐' => ['en' => 'gluten', 'es' => 'gluten', 'de' => 'Gluten', 'fr' => 'gluten', 'ja' => 'グルテン'],
        '기다리다' => ['en' => 'wait', 'es' => 'esperar', 'de' => 'warten', 'fr' => 'attendre', 'ja' => '待つ'],
        '기쁜' => ['en' => 'glad', 'es' => 'contento', 'de' => 'froh', 'fr' => 'content', 'ja' => '嬉しい'],
        '깨끗한' => ['en' => 'clean', 'es' => 'limpio', 'de' => 'sauber', 'fr' => 'propre', 'ja' => 'きれい'],
        '나' => ['en' => 'I', 'es' => 'yo', 'de' => 'ich', 'fr' => 'je', 'ja' => '私'],
        '나누다' => ['en' => 'to share', 'es' => 'compartir', 'de' => 'teilen', 'fr' => 'partager', 'ja' => '分ける'],
        '나는 가지고 있다' => ['en' => 'I have', 'es' => 'tengo', 'de' => 'ich habe', 'fr' => 'j\'ai', 'ja' => '私は持っている'],
        '나는 갈 것이다' => ['en' => 'I am going', 'es' => 'voy', 'de' => 'ich gehe', 'fr' => 'je vais', 'ja' => '私は行く'],
        '나는 느낍니다' => ['en' => 'I feel', 'es' => 'me siento', 'de' => 'ich fühle mich', 'fr' => 'je me sens', 'ja' => '私は感じる'],
        '나는 마셨다' => ['en' => 'I drank', 'es' => 'bebí', 'de' => 'ich trank', 'fr' => 'j\'ai bu', 'ja' => '私は飲んだ'],
        '나는 먹었다' => ['en' => 'I ate', 'es' => 'comí', 'de' => 'ich aß', 'fr' => 'j\'ai mangé', 'ja' => '私は食べた'],
        '나는 믿는다' => ['en' => 'I believe', 'es' => 'creo que', 'de' => 'ich glaube', 'fr' => 'je crois', 'ja' => '私は信じる'],
        '나는 보았다' => ['en' => 'I saw', 'es' => 'vi', 'de' => 'ich sah', 'fr' => 'j\'ai vu', 'ja' => '私は見た'],
        '나는 삽니다' => ['en' => 'I live', 'es' => 'vivo', 'de' => 'ich wohne', 'fr' => 'j\'habite', 'ja' => '私は住んでいる'],
        '나는 생각한다' => ['en' => 'I think', 'es' => 'creo', 'de' => 'ich denke', 'fr' => 'je pense', 'ja' => '私は思う'],
        '나는 선호한다' => ['en' => 'I prefer', 'es' => 'prefiero', 'de' => 'ich bevorzuge', 'fr' => 'je préfère', 'ja' => '私は好む'],
        '원합니다' => ['en' => 'want', 'es' => 'quiero', 'de' => 'möchte', 'fr' => 'veux', 'ja' => 'ほしいです'],
        '나는 할 수 있다' => ['en' => 'I can', 'es' => 'puedo', 'de' => 'ich kann', 'fr' => 'je peux', 'ja' => '私はできる'],
        '나르다' => ['en' => 'to carry', 'es' => 'llevar', 'de' => 'tragen', 'fr' => 'porter', 'ja' => '運ぶ'],
        '나의' => ['en' => 'my', 'es' => 'mi', 'de' => 'mein', 'fr' => 'mon', 'ja' => '私の'],
        '나이' => ['en' => 'age', 'es' => 'edad', 'de' => 'Alter', 'fr' => 'âge', 'ja' => '年齢'],
        '나이프' => ['en' => 'knife', 'es' => 'cuchillo', 'de' => 'Messer', 'fr' => 'couteau', 'ja' => 'ナイフ'],
        '나중에' => ['en' => 'later', 'es' => 'más tarde', 'de' => 'später', 'fr' => 'plus tard', 'ja' => '後で'],
        '날' => ['en' => 'day', 'es' => 'día', 'de' => 'Tag', 'fr' => 'jour', 'ja' => '日'],
        '날씨' => ['en' => 'weather', 'es' => 'tiempo', 'de' => 'Wetter', 'fr' => 'temps', 'ja' => '天気'],
        '남쪽' => ['en' => 'south', 'es' => 'sur', 'de' => 'Süden', 'fr' => 'sud', 'ja' => '南'],
        '내일' => ['en' => 'tomorrow', 'es' => 'mañana', 'de' => 'morgen', 'fr' => 'demain', 'ja' => '明日'],
        '냅킨' => ['en' => 'napkin', 'es' => 'servilleta', 'de' => 'Serviette', 'fr' => 'serviette', 'ja' => 'ナプキン'],
        '너무' => ['en' => 'too much', 'es' => 'demasiado', 'de' => 'zu viel', 'fr' => 'trop', 'ja' => 'すぎます'],
        '넣다' => ['en' => 'to put', 'es' => 'poner', 'de' => 'legen', 'fr' => 'mettre', 'ja' => '入れる'],
        '네' => ['en' => 'yes', 'es' => 'sí', 'de' => 'ja', 'fr' => 'oui', 'ja' => 'はい'],
        '노란색' => ['en' => 'yellow', 'es' => 'amarillo', 'de' => 'gelb', 'fr' => 'jaune', 'ja' => '黄色'],
        '누구' => ['en' => 'who', 'es' => 'quién', 'de' => 'wer', 'fr' => 'qui', 'ja' => '誰'],
        '눈' => ['en' => 'snow', 'es' => 'nieve', 'de' => 'Schnee', 'fr' => 'neige', 'ja' => '雪'],
        '다섯' => ['en' => 'five', 'es' => 'cinco', 'de' => 'fünf', 'fr' => 'cinq', 'ja' => '五'],
        '다시 전화하다' => ['en' => 'call back', 'es' => 'devolver la llamada', 'de' => 'zurückrufen', 'fr' => 'rappeler', 'ja' => '折り返す'],
        '다음' => ['en' => 'next', 'es' => 'próximo', 'de' => 'nächste', 'fr' => 'prochain', 'ja' => '次の'],
        '단' => ['en' => 'sweet', 'es' => 'dulce', 'de' => 'süß', 'fr' => 'sucré', 'ja' => '甘い'],
        '닫힌' => ['en' => 'closed', 'es' => 'cerrado', 'de' => 'geschlossen', 'fr' => 'fermé', 'ja' => '閉じた'],
        '달러' => ['en' => 'dollars', 'es' => 'dólares', 'de' => 'Dollar', 'fr' => 'dollars', 'ja' => 'ドル'],
        '달력' => ['en' => 'calendar', 'es' => 'calendario', 'de' => 'Kalender', 'fr' => 'calendrier', 'ja' => 'カレンダー'],
        '닭고기' => ['en' => 'chicken', 'es' => 'pollo', 'de' => 'Hähnchen', 'fr' => 'poulet', 'ja' => '鶏肉'],
        '당근' => ['en' => 'carrot', 'es' => 'zanahoria', 'de' => 'Karotte', 'fr' => 'carotte', 'ja' => 'にんじん'],
        '당신의' => ['en' => 'your', 'es' => 'tu', 'de' => 'dein', 'fr' => 'ton', 'ja' => 'あなたの'],
        '더' => ['en' => 'more', 'es' => 'más', 'de' => 'mehr', 'fr' => 'plus', 'ja' => 'もっと'],
        '더 나쁜' => ['en' => 'worse', 'es' => 'peor', 'de' => 'schlechter', 'fr' => 'pire', 'ja' => 'もっと悪い'],
        '더 좋은' => ['en' => 'better', 'es' => 'mejor', 'de' => 'besser', 'fr' => 'meilleur', 'ja' => 'もっと良い'],
        '더러운' => ['en' => 'dirty', 'es' => 'sucio', 'de' => 'schmutzig', 'fr' => 'sale', 'ja' => '汚い'],
        '덜' => ['en' => 'less', 'es' => 'menos', 'de' => 'weniger', 'fr' => 'moins', 'ja' => 'より少ない'],
        '도시' => ['en' => 'town', 'es' => 'ciudad', 'de' => 'Stadt', 'fr' => 'ville', 'ja' => '町'],
        '돈' => ['en' => 'money', 'es' => 'dinero', 'de' => 'Geld', 'fr' => 'argent', 'ja' => 'お金'],
        '돌다' => ['en' => 'turn', 'es' => 'girar', 'de' => 'abbiegen', 'fr' => 'tourner', 'ja' => '曲がる'],
        '둘' => ['en' => 'two', 'es' => 'dos', 'de' => 'zwei', 'fr' => 'deux', 'ja' => '二'],
        '뒤에' => ['en' => 'behind', 'es' => 'detrás', 'de' => 'hinten', 'fr' => 'derrière', 'ja' => '後ろに'],
        '들어있다' => ['en' => 'contains', 'es' => 'contiene', 'de' => 'enthält', 'fr' => 'contient', 'ja' => '含む'],
        '디저트' => ['en' => 'dessert', 'es' => 'postre', 'de' => 'Nachtisch', 'fr' => 'dessert', 'ja' => 'デザート'],
        '따뜻한' => ['en' => 'warm', 'es' => 'cálido', 'de' => 'warm', 'fr' => 'doux', 'ja' => '暖かい'],
        '따로' => ['en' => 'separately', 'es' => 'por separado', 'de' => 'getrennt', 'fr' => 'séparément', 'ja' => '別々に'],
        '딸기' => ['en' => 'strawberry', 'es' => 'fresa', 'de' => 'Erdbeere', 'fr' => 'fraise', 'ja' => 'いちご'],
        '또는' => ['en' => 'or', 'es' => 'o', 'de' => 'oder', 'fr' => 'ou', 'ja' => 'または'],
        '또한' => ['en' => 'also', 'es' => 'también', 'de' => 'auch', 'fr' => 'aussi', 'ja' => 'も'],
        '똑바로' => ['en' => 'straight', 'es' => 'recto', 'de' => 'geradeaus', 'fr' => 'tout droit', 'ja' => 'まっすぐ'],
        '뜨거운' => ['en' => 'hot', 'es' => 'caliente', 'de' => 'heiß', 'fr' => 'chaud', 'ja' => '熱い'],
        '리터' => ['en' => 'litre', 'es' => 'litro', 'de' => 'Liter', 'fr' => 'litre', 'ja' => 'リットル'],
        '마시다' => ['en' => 'drink', 'es' => 'beber', 'de' => 'trinken', 'fr' => 'boire', 'ja' => '飲む'],
        '마을' => ['en' => 'village', 'es' => 'pueblo', 'de' => 'Dorf', 'fr' => 'village', 'ja' => '村'],
        '말하다' => ['en' => 'speak', 'es' => 'hablar', 'de' => 'sprechen', 'fr' => 'parler', 'ja' => '話す'],
        '맛' => ['en' => 'taste', 'es' => 'sabor', 'de' => 'Geschmack', 'fr' => 'goût', 'ja' => '味'],
        '맛있는' => ['en' => 'delicious', 'es' => 'delicioso', 'de' => 'köstlich', 'fr' => 'délicieux', 'ja' => 'おいしい'],
        '매우' => ['en' => 'very', 'es' => 'muy', 'de' => 'sehr', 'fr' => 'très', 'ja' => 'とても'],
        '매운' => ['en' => 'spicy', 'es' => 'picante', 'de' => 'scharf', 'fr' => 'épicé', 'ja' => '辛い'],
        '매장에서' => ['en' => 'eat in', 'es' => 'para tomar aquí', 'de' => 'zum Hieressen', 'fr' => 'sur place', 'ja' => '店内で'],
        '맥주' => ['en' => 'beer', 'es' => 'cerveza', 'de' => 'Bier', 'fr' => 'bière', 'ja' => 'ビール'],
        '먹다' => ['en' => 'eat', 'es' => 'comer', 'de' => 'essen', 'fr' => 'manger', 'ja' => '食べる'],
        '멀리' => ['en' => 'far', 'es' => 'lejos', 'de' => 'weit', 'fr' => 'loin', 'ja' => '遠く'],
        '메뉴' => ['en' => 'menu', 'es' => 'menú', 'de' => 'Menü', 'fr' => 'menu', 'ja' => 'メニュー'],
        '메뉴와' => ['en' => 'menu and', 'es' => 'menú y', 'de' => 'Menü und', 'fr' => 'menu et', 'ja' => 'メニューと'],
        '메시지' => ['en' => 'message', 'es' => 'mensaje', 'de' => 'Nachricht', 'fr' => 'message', 'ja' => 'メッセージ'],
        '명' => ['en' => 'people', 'es' => 'personas', 'de' => 'Personen', 'fr' => 'personnes', 'ja' => '人'],
        '몇 개' => ['en' => 'how many', 'es' => 'cuántos', 'de' => 'wie viele', 'fr' => 'combien', 'ja' => 'いくつ'],
        '목록' => ['en' => 'list', 'es' => 'lista', 'de' => 'Liste', 'fr' => 'liste', 'ja' => 'リスト'],
        '목마른' => ['en' => 'thirsty', 'es' => 'sediento', 'de' => 'durstig', 'fr' => 'assoiffé', 'ja' => 'のどが渇いた'],
        '무거운' => ['en' => 'heavy', 'es' => 'pesado', 'de' => 'schwer', 'fr' => 'lourd', 'ja' => '重い'],
        '무게를 재다' => ['en' => 'to weigh', 'es' => 'pesar', 'de' => 'wiegen', 'fr' => 'peser', 'ja' => '量る'],
        '문제' => ['en' => 'problem', 'es' => 'problema', 'de' => 'Problem', 'fr' => 'problème', 'ja' => '問題'],
        '물' => ['en' => 'water', 'es' => 'agua', 'de' => 'Wasser', 'fr' => 'eau', 'ja' => '水'],
        '물론' => ['en' => 'of course', 'es' => 'por supuesto', 'de' => 'natürlich', 'fr' => 'bien sûr', 'ja' => 'もちろん'],
        '바구니' => ['en' => 'basket', 'es' => 'cesta', 'de' => 'Korb', 'fr' => 'panier', 'ja' => 'かご'],
        '바나나' => ['en' => 'banana', 'es' => 'plátano', 'de' => 'Banane', 'fr' => 'banane', 'ja' => 'バナナ'],
        '바닐라' => ['en' => 'vanilla', 'es' => 'vainilla', 'de' => 'Vanille', 'fr' => 'vanille', 'ja' => 'バニラ'],
        '바람' => ['en' => 'wind', 'es' => 'viento', 'de' => 'Wind', 'fr' => 'vent', 'ja' => '風'],
        '바쁜' => ['en' => 'busy', 'es' => 'ocupado', 'de' => 'beschäftigt', 'fr' => 'occupé', 'ja' => '忙しい'],
        '반갑습니다' => ['en' => 'nice to meet you', 'es' => 'encantado', 'de' => 'freut mich', 'fr' => 'enchanté', 'ja' => 'はじめまして'],
        '발견하다' => ['en' => 'to find', 'es' => 'encontrar', 'de' => 'finden', 'fr' => 'trouver', 'ja' => '見つける'],
        '밤' => ['en' => 'night', 'es' => 'noche', 'de' => 'Nacht', 'fr' => 'nuit', 'ja' => '夜'],
        '밥' => ['en' => 'rice', 'es' => 'arroz', 'de' => 'Reis', 'fr' => 'riz', 'ja' => 'ご飯'],
        '버터' => ['en' => 'butter', 'es' => 'mantequilla', 'de' => 'Butter', 'fr' => 'beurre', 'ja' => 'バター'],
        '병' => ['en' => 'bottle', 'es' => 'botella', 'de' => 'Flasche', 'fr' => 'bouteille', 'ja' => 'ボトル'],
        '보다' => ['en' => 'watch', 'es' => 'mirar', 'de' => 'schauen', 'fr' => 'regarder', 'ja' => '見る'],
        '봄' => ['en' => 'spring', 'es' => 'primavera', 'de' => 'Frühling', 'fr' => 'printemps', 'ja' => '春'],
        '봄과' => ['en' => 'spring and', 'es' => 'primavera y', 'de' => 'Frühling und', 'fr' => 'printemps et', 'ja' => '春と'],
        '봉투' => ['en' => 'bag', 'es' => 'bolsa', 'de' => 'Tüte', 'fr' => 'sac', 'ja' => '袋'],
        '부탁합니다' => ['en' => 'please', 'es' => 'por favor', 'de' => 'bitte', 'fr' => 's\'il vous plaît', 'ja' => 'お願いします'],
        '북쪽' => ['en' => 'north', 'es' => 'norte', 'de' => 'Norden', 'fr' => 'nord', 'ja' => '北'],
        '분' => ['en' => 'minutes', 'es' => 'minutos', 'de' => 'Minuten', 'fr' => 'minutes', 'ja' => '分'],
        '비' => ['en' => 'rain', 'es' => 'lluvia', 'de' => 'Regen', 'fr' => 'pluie', 'ja' => '雨'],
        '비교하다' => ['en' => 'to compare', 'es' => 'comparar', 'de' => 'vergleichen', 'fr' => 'comparer', 'ja' => '比べる'],
        '비싼' => ['en' => 'expensive', 'es' => 'caro', 'de' => 'teuer', 'fr' => 'cher', 'ja' => '高い'],
        '비와' => ['en' => 'rain and', 'es' => 'lluvia y', 'de' => 'Regen und', 'fr' => 'pluie et', 'ja' => '雨と'],
        '빈' => ['en' => 'empty', 'es' => 'vacío', 'de' => 'leer', 'fr' => 'vide', 'ja' => '空'],
        '빠른' => ['en' => 'fast', 'es' => 'rápido', 'de' => 'schnell', 'fr' => 'rapide', 'ja' => '速い'],
        '빨간색' => ['en' => 'red', 'es' => 'rojo', 'de' => 'rot', 'fr' => 'rouge', 'ja' => '赤'],
        '빵' => ['en' => 'bread', 'es' => 'pan', 'de' => 'Brot', 'fr' => 'pain', 'ja' => 'パン'],
        '빵과' => ['en' => 'bread and', 'es' => 'pan y', 'de' => 'Brot und', 'fr' => 'pain et', 'ja' => 'パンと'],
        '빵집' => ['en' => 'bakery', 'es' => 'panadería', 'de' => 'Bäckerei', 'fr' => 'boulangerie', 'ja' => 'パン屋'],
        '사과' => ['en' => 'apple', 'es' => 'manzana', 'de' => 'Apfel', 'fr' => 'pomme', 'ja' => 'りんご'],
        '사과와' => ['en' => 'apple and', 'es' => 'manzana y', 'de' => 'Apfel und', 'fr' => 'pomme et', 'ja' => 'りんごと'],
        '사다' => ['en' => 'to buy', 'es' => 'comprar', 'de' => 'kaufen', 'fr' => 'acheter', 'ja' => '買う'],
        '사실' => ['en' => 'true', 'es' => 'verdadero', 'de' => 'wahr', 'fr' => 'vrai', 'ja' => '本当'],
        '살' => ['en' => 'years old', 'es' => 'años', 'de' => 'Jahre alt', 'fr' => 'ans', 'ja' => '歳'],
        '삼' => ['en' => 'three', 'es' => 'tres', 'de' => 'drei', 'fr' => 'trois', 'ja' => '三'],
        '상자' => ['en' => 'box', 'es' => 'caja', 'de' => 'Schachtel', 'fr' => 'boîte', 'ja' => '箱'],
        '상품' => ['en' => 'product', 'es' => 'producto', 'de' => 'Produkt', 'fr' => 'produit', 'ja' => '商品'],
        '새로운' => ['en' => 'new', 'es' => 'nuevo', 'de' => 'neu', 'fr' => 'nouveau', 'ja' => '新しい'],
        '샌드위치' => ['en' => 'sandwich', 'es' => 'sándwich', 'de' => 'Sandwich', 'fr' => 'sandwich', 'ja' => 'サンドイッチ'],
        '샐러드' => ['en' => 'salad', 'es' => 'ensalada', 'de' => 'Salat', 'fr' => 'salade', 'ja' => 'サラダ'],
        '생선' => ['en' => 'fish', 'es' => 'pescado', 'de' => 'Fisch', 'fr' => 'poisson', 'ja' => '魚'],
        '선생님' => ['en' => 'sir', 'es' => 'señor', 'de' => 'mein Herr', 'fr' => 'monsieur', 'ja' => 'ムッシュ'],
        '선생님과' => ['en' => 'sir and', 'es' => 'señor y', 'de' => 'mein Herr und', 'fr' => 'monsieur et', 'ja' => 'ムッシュと'],
        '선생님입니다' => ['en' => 'is a teacher', 'es' => 'es profesor', 'de' => 'ist Lehrer', 'fr' => 'est professeur', 'ja' => '先生です'],
        '설탕' => ['en' => 'sugar', 'es' => 'azúcar', 'de' => 'Zucker', 'fr' => 'sucre', 'ja' => '砂糖'],
        '셋' => ['en' => 'three', 'es' => 'tres', 'de' => 'drei', 'fr' => 'trois', 'ja' => '三'],
        '소금' => ['en' => 'salt', 'es' => 'sal', 'de' => 'Salz', 'fr' => 'sel', 'ja' => '塩'],
        '수프' => ['en' => 'soup', 'es' => 'sopa', 'de' => 'Suppe', 'fr' => 'soupe', 'ja' => 'スープ'],
        '숟가락' => ['en' => 'spoon', 'es' => 'cuchara', 'de' => 'Löffel', 'fr' => 'cuillère', 'ja' => 'スプーン'],
        '쉬운' => ['en' => 'easy', 'es' => 'fácil', 'de' => 'einfach', 'fr' => 'facile', 'ja' => '簡単'],
        '슈퍼마켓' => ['en' => 'supermarket', 'es' => 'supermercado', 'de' => 'Supermarkt', 'fr' => 'supermarché', 'ja' => 'スーパー'],
        '슬픈' => ['en' => 'sad', 'es' => 'triste', 'de' => 'traurig', 'fr' => 'triste', 'ja' => '悲しい'],
        '시' => ['en' => 'o\'clock', 'es' => 'en punto', 'de' => 'Uhr', 'fr' => 'heures', 'ja' => '時'],
        '시간' => ['en' => 'hour', 'es' => 'hora', 'de' => 'Stunde', 'fr' => 'heure', 'ja' => '時間'],
        '시계' => ['en' => 'clock', 'es' => 'reloj', 'de' => 'Uhr', 'fr' => 'horloge', 'ja' => '時計'],
        '시계와' => ['en' => 'clock and', 'es' => 'reloj y', 'de' => 'Uhr und', 'fr' => 'horloge et', 'ja' => '時計と'],
        '식단' => ['en' => 'diet', 'es' => 'dieta', 'de' => 'Diät', 'fr' => 'régime', 'ja' => '食事制限'],
        '식당' => ['en' => 'restaurant', 'es' => 'restaurante', 'de' => 'Restaurant', 'fr' => 'restaurant', 'ja' => 'レストラン'],
        '신선한' => ['en' => 'fresh', 'es' => 'fresco', 'de' => 'frisch', 'fr' => 'frais', 'ja' => '新鮮'],
        '실례합니다' => ['en' => 'excuse me', 'es' => 'disculpe', 'de' => 'entschuldigen Sie', 'fr' => 'excusez-moi', 'ja' => 'すみません'],
        '싼' => ['en' => 'cheap', 'es' => 'barato', 'de' => 'billig', 'fr' => 'bon marché', 'ja' => '安い'],
        '아니요' => ['en' => 'no', 'es' => 'no', 'de' => 'nein', 'fr' => 'non', 'ja' => 'いいえ'],
        '아름다운' => ['en' => 'beautiful', 'es' => 'hermoso', 'de' => 'schön', 'fr' => 'beau', 'ja' => '美しい'],
        '아마도' => ['en' => 'maybe', 'es' => 'quizás', 'de' => 'vielleicht', 'fr' => 'peut-être', 'ja' => 'たぶん'],
        '아버지' => ['en' => 'father', 'es' => 'padre', 'de' => 'Vater', 'fr' => 'père', 'ja' => '父'],
        '아이' => ['en' => 'child', 'es' => 'niño', 'de' => 'Kind', 'fr' => 'enfant', 'ja' => '子供'],
        '아이스크림' => ['en' => 'ice cream', 'es' => 'helado', 'de' => 'Eis', 'fr' => 'glace', 'ja' => 'アイスクリーム'],
        '아침' => ['en' => 'morning', 'es' => 'mañana', 'de' => 'Morgen', 'fr' => 'matin', 'ja' => '朝'],
        '아픈' => ['en' => 'sick', 'es' => 'enfermo', 'de' => 'krank', 'fr' => 'malade', 'ja' => '病気'],
        '안녕하세요' => ['en' => 'hello', 'es' => 'hola', 'de' => 'hallo', 'fr' => 'bonjour', 'ja' => 'こんにちは'],
        '알레르기' => ['en' => 'allergy', 'es' => 'alergia', 'de' => 'Allergie', 'fr' => 'allergie', 'ja' => 'アレルギー'],
        '알레르기가 있는' => ['en' => 'allergic', 'es' => 'alérgico', 'de' => 'allergisch', 'fr' => 'allergique', 'ja' => 'アレルギーの'],
        '앞에' => ['en' => 'in front', 'es' => 'delante', 'de' => 'vorne', 'fr' => 'devant', 'ja' => '前に'],
        '약간의' => ['en' => 'some', 'es' => 'algo de', 'de' => 'etwas', 'fr' => 'du', 'ja' => '少しの'],
        '양파' => ['en' => 'onion', 'es' => 'cebolla', 'de' => 'Zwiebel', 'fr' => 'oignon', 'ja' => '玉ねぎ'],
        '어느' => ['en' => 'which', 'es' => 'cuál', 'de' => 'welcher', 'fr' => 'quel', 'ja' => 'どれ'],
        '어디' => ['en' => 'where', 'es' => 'dónde', 'de' => 'wo', 'fr' => 'où', 'ja' => 'どこ'],
        '어디입니까' => ['en' => 'where is', 'es' => 'dónde está', 'de' => 'wo ist', 'fr' => 'où est', 'ja' => 'どこですか'],
        '어떻게 지내세요' => ['en' => 'how are you', 'es' => 'cómo estás', 'de' => 'wie geht es dir', 'fr' => 'comment ça va', 'ja' => 'お元気ですか'],
        '어려운' => ['en' => 'hard', 'es' => 'difícil', 'de' => 'schwer', 'fr' => 'difficile', 'ja' => '難しい'],
        '어머니' => ['en' => 'mother', 'es' => 'madre', 'de' => 'Mutter', 'fr' => 'mère', 'ja' => '母'],
        '어머니는' => ['en' => 'mother', 'es' => 'madre', 'de' => 'Mutter', 'fr' => 'mère', 'ja' => '母'],
        '어머니와' => ['en' => 'mother and', 'es' => 'madre y', 'de' => 'Mutter und', 'fr' => 'mère et', 'ja' => '母と'],
        '어제' => ['en' => 'yesterday', 'es' => 'ayer', 'de' => 'gestern', 'fr' => 'hier', 'ja' => '昨日'],
        '언제' => ['en' => 'when', 'es' => 'cuándo', 'de' => 'wann', 'fr' => 'quand', 'ja' => 'いつ'],
        '얼음' => ['en' => 'ice', 'es' => 'hielo', 'de' => 'Eiswürfel', 'fr' => 'glaçons', 'ja' => '氷'],
        '에서' => ['en' => 'from', 'es' => 'de', 'de' => 'von', 'fr' => 'de', 'ja' => 'から'],
        '여기' => ['en' => 'here is', 'es' => 'aquí está', 'de' => 'hier ist', 'fr' => 'voici', 'ja' => 'これが'],
        '여덟' => ['en' => 'eight', 'es' => 'ocho', 'de' => 'acht', 'fr' => 'huit', 'ja' => '八'],
        '여름' => ['en' => 'summer', 'es' => 'verano', 'de' => 'Sommer', 'fr' => 'été', 'ja' => '夏'],
        '역' => ['en' => 'station', 'es' => 'estación', 'de' => 'Bahnhof', 'fr' => 'gare', 'ja' => '駅'],
        '열' => ['en' => 'ten', 'es' => 'diez', 'de' => 'zehn', 'fr' => 'dix', 'ja' => '十'],
        '열린' => ['en' => 'open', 'es' => 'abierto', 'de' => 'offen', 'fr' => 'ouvert', 'ja' => '開いた'],
        '영수증' => ['en' => 'receipt', 'es' => 'recibo', 'de' => 'Quittung', 'fr' => 'reçu', 'ja' => 'レシート'],
        '영화' => ['en' => 'film', 'es' => 'película', 'de' => 'Film', 'fr' => 'film', 'ja' => '映画'],
        '예쁜' => ['en' => 'pretty', 'es' => 'bonito', 'de' => 'hübsch', 'fr' => 'joli', 'ja' => 'かわいい'],
        '예약' => ['en' => 'booking', 'es' => 'reserva', 'de' => 'Reservierung', 'fr' => 'réservation', 'ja' => '予約'],
        '예약하다' => ['en' => 'to book', 'es' => 'reservar', 'de' => 'reservieren', 'fr' => 'réserver', 'ja' => '予約する'],
        '오늘' => ['en' => 'today', 'es' => 'hoy', 'de' => 'heute', 'fr' => 'aujourd\'hui', 'ja' => '今日'],
        '오늘 밤' => ['en' => 'tonight', 'es' => 'esta noche', 'de' => 'heute Abend', 'fr' => 'ce soir', 'ja' => '今夜'],
        '오늘과' => ['en' => 'today and', 'es' => 'hoy y', 'de' => 'heute und', 'fr' => 'aujourd\'hui et', 'ja' => '今日と'],
        '오다' => ['en' => 'come', 'es' => 'venir', 'de' => 'kommen', 'fr' => 'venir', 'ja' => '来る'],
        '오렌지' => ['en' => 'orange', 'es' => 'naranja', 'de' => 'Orange', 'fr' => 'orange', 'ja' => 'オレンジ'],
        '오른쪽' => ['en' => 'right', 'es' => 'derecha', 'de' => 'rechts', 'fr' => 'droite', 'ja' => '右'],
        '와인' => ['en' => 'wine', 'es' => 'vino', 'de' => 'Wein', 'fr' => 'vin', 'ja' => 'ワイン'],
        '완벽한' => ['en' => 'perfect', 'es' => 'perfecto', 'de' => 'perfekt', 'fr' => 'parfait', 'ja' => '完璧'],
        '왜' => ['en' => 'why', 'es' => 'por qué', 'de' => 'warum', 'fr' => 'pourquoi', 'ja' => 'なぜ'],
        '왜냐하면' => ['en' => 'because', 'es' => 'porque', 'de' => 'weil', 'fr' => 'parce que', 'ja' => 'なぜなら'],
        '왼쪽' => ['en' => 'left', 'es' => 'izquierda', 'de' => 'links', 'fr' => 'gauche', 'ja' => '左'],
        '요리' => ['en' => 'dish', 'es' => 'plato', 'de' => 'Gericht', 'fr' => 'plat', 'ja' => '料理'],
        '우유' => ['en' => 'milk', 'es' => 'leche', 'de' => 'Milch', 'fr' => 'lait', 'ja' => '牛乳'],
        '월요일' => ['en' => 'Monday', 'es' => 'lunes', 'de' => 'Montag', 'fr' => 'lundi', 'ja' => '月曜日'],
        '웨이터' => ['en' => 'waiter', 'es' => 'camarero', 'de' => 'Kellner', 'fr' => 'serveur', 'ja' => 'ウェイター'],
        '유리잔' => ['en' => 'glass', 'es' => 'vaso', 'de' => 'Glas', 'fr' => 'verre', 'ja' => 'グラス'],
        '음료' => ['en' => 'a drink', 'es' => 'una bebida', 'de' => 'ein Getränk', 'fr' => 'une boisson', 'ja' => '飲み物'],
        '의' => ['en' => 'of', 'es' => 'de', 'de' => 'von', 'fr' => 'de', 'ja' => 'の'],
        '의사' => ['en' => 'doctor', 'es' => 'médico', 'de' => 'Arzt', 'fr' => 'médecin', 'ja' => '医者'],
        '의사는' => ['en' => 'doctor', 'es' => 'médico', 'de' => 'Arzt', 'fr' => 'médecin', 'ja' => '医者'],
        '의자' => ['en' => 'chair', 'es' => 'silla', 'de' => 'Stuhl', 'fr' => 'chaise', 'ja' => '椅子'],
        '이' => ['en' => 'this', 'es' => 'este', 'de' => 'dieser', 'fr' => 'ce', 'ja' => 'この'],
        '이것들' => ['en' => 'these', 'es' => 'estos', 'de' => 'diese', 'fr' => 'ces', 'ja' => 'これらの'],
        '이름' => ['en' => 'name', 'es' => 'nombre', 'de' => 'Name', 'fr' => 'nom', 'ja' => '名前'],
        '이미' => ['en' => 'already', 'es' => 'ya', 'de' => 'schon', 'fr' => 'déjà', 'ja' => 'もう'],
        '이분은' => ['en' => 'this is', 'es' => 'este es', 'de' => 'das ist', 'fr' => 'c\'est', 'ja' => 'これは'],
        '이웃' => ['en' => 'neighbour', 'es' => 'vecino', 'de' => 'Nachbar', 'fr' => 'voisin', 'ja' => '隣人'],
        '읽다' => ['en' => 'read', 'es' => 'leer', 'de' => 'lesen', 'fr' => 'lire', 'ja' => '読む'],
        '입니다' => ['en' => 'is', 'es' => 'es', 'de' => 'ist', 'fr' => 'est', 'ja' => 'です'],
        '자다' => ['en' => 'sleep', 'es' => 'dormir', 'de' => 'schlafen', 'fr' => 'dormir', 'ja' => '眠る'],
        '자리' => ['en' => 'seat', 'es' => 'sitio', 'de' => 'Platz', 'fr' => 'place', 'ja' => '席'],
        '자매' => ['en' => 'sister', 'es' => 'hermana', 'de' => 'Schwester', 'fr' => 'sœur', 'ja' => '姉妹'],
        '자매는' => ['en' => 'sister', 'es' => 'hermana', 'de' => 'Schwester', 'fr' => 'sœur', 'ja' => '姉妹'],
        '자매와' => ['en' => 'sister and', 'es' => 'hermana y', 'de' => 'Schwester und', 'fr' => 'sœur et', 'ja' => '姉妹と'],
        '작은' => ['en' => 'small', 'es' => 'pequeño', 'de' => 'klein', 'fr' => 'petit', 'ja' => '小さい'],
        '잘' => ['en' => 'well', 'es' => 'bien', 'de' => 'gut', 'fr' => 'bien', 'ja' => '元気'],
        '재료' => ['en' => 'ingredients', 'es' => 'ingredientes', 'de' => 'Zutaten', 'fr' => 'ingrédients', 'ja' => '材料'],
        '저' => ['en' => 'me', 'es' => 'me', 'de' => 'mich', 'fr' => 'moi', 'ja' => '私'],
        '저것들' => ['en' => 'those', 'es' => 'esos', 'de' => 'jene', 'fr' => 'ces', 'ja' => 'あれらの'],
        '저녁' => ['en' => 'evening', 'es' => 'tarde', 'de' => 'Abend', 'fr' => 'soir', 'ja' => '夕方'],
        '저울' => ['en' => 'scales', 'es' => 'balanza', 'de' => 'Waage', 'fr' => 'balance', 'ja' => 'はかり'],
        '전에' => ['en' => 'before', 'es' => 'antes', 'de' => 'vor', 'fr' => 'avant', 'ja' => '前に'],
        '전채' => ['en' => 'starter', 'es' => 'entrante', 'de' => 'Vorspeise', 'fr' => 'entrée', 'ja' => '前菜'],
        '전화' => ['en' => 'phone', 'es' => 'teléfono', 'de' => 'Telefon', 'fr' => 'téléphone', 'ja' => '電話'],
        '전화하다' => ['en' => 'call', 'es' => 'llamar', 'de' => 'anrufen', 'fr' => 'appeler', 'ja' => '電話する'],
        '접시' => ['en' => 'plate', 'es' => 'plato', 'de' => 'Teller', 'fr' => 'assiette', 'ja' => 'お皿'],
        '정말' => ['en' => 'really', 'es' => 'de verdad', 'de' => 'wirklich', 'fr' => 'vraiment', 'ja' => '本当に'],
        '정오' => ['en' => 'noon', 'es' => 'mediodía', 'de' => 'Mittag', 'fr' => 'midi', 'ja' => '正午'],
        '제가 냅니다' => ['en' => 'I pay', 'es' => 'pago', 'de' => 'ich bezahle', 'fr' => 'je paie', 'ja' => '私が払う'],
        '조금' => ['en' => 'a little', 'es' => 'un poco', 'de' => 'ein bisschen', 'fr' => 'un peu', 'ja' => '少し'],
        '좋아요' => ['en' => 'okay', 'es' => 'vale', 'de' => 'okay', 'fr' => 'd\'accord', 'ja' => 'いいよ'],
        '좋은' => ['en' => 'good', 'es' => 'bueno', 'de' => 'gut', 'fr' => 'bon', 'ja' => '良い'],
        '죄송합니다' => ['en' => 'sorry', 'es' => 'lo siento', 'de' => 'Entschuldigung', 'fr' => 'désolé', 'ja' => 'ごめんなさい'],
        '주' => ['en' => 'week', 'es' => 'semana', 'de' => 'Woche', 'fr' => 'semaine', 'ja' => '週'],
        '주문' => ['en' => 'order', 'es' => 'pedido', 'de' => 'Bestellung', 'fr' => 'commande', 'ja' => '注文'],
        '주문하다' => ['en' => 'to order', 'es' => 'pedir', 'de' => 'bestellen', 'fr' => 'commander', 'ja' => '注文する'],
        '주방' => ['en' => 'kitchen', 'es' => 'cocina', 'de' => 'Küche', 'fr' => 'cuisine', 'ja' => '厨房'],
        '주스' => ['en' => 'juice', 'es' => 'zumo', 'de' => 'Saft', 'fr' => 'jus', 'ja' => 'ジュース'],
        '준비된' => ['en' => 'ready', 'es' => 'listo', 'de' => 'bereit', 'fr' => 'prêt', 'ja' => '準備ができた'],
        '줄' => ['en' => 'queue', 'es' => 'cola', 'de' => 'Schlange', 'fr' => 'file', 'ja' => '列'],
        '지금' => ['en' => 'now', 'es' => 'ahora', 'de' => 'jetzt', 'fr' => 'maintenant', 'ja' => '今'],
        '지불하다' => ['en' => 'pay', 'es' => 'pagar', 'de' => 'bezahlen', 'fr' => 'payer', 'ja' => '払う'],
        '진열대' => ['en' => 'aisle', 'es' => 'pasillo', 'de' => 'Regal', 'fr' => 'rayon', 'ja' => '売り場'],
        '집' => ['en' => 'house', 'es' => 'casa', 'de' => 'Haus', 'fr' => 'maison', 'ja' => '家'],
        '집과' => ['en' => 'house and', 'es' => 'casa y', 'de' => 'Haus und', 'fr' => 'maison et', 'ja' => '家と'],
        '짠' => ['en' => 'salty', 'es' => 'salado', 'de' => 'salzig', 'fr' => 'salé', 'ja' => 'しょっぱい'],
        '차' => ['en' => 'tea', 'es' => 'té', 'de' => 'Tee', 'fr' => 'thé', 'ja' => 'お茶'],
        '차가운' => ['en' => 'cold', 'es' => 'frío', 'de' => 'kalt', 'fr' => 'froid', 'ja' => '冷たい'],
        '차분한' => ['en' => 'calm', 'es' => 'tranquilo', 'de' => 'ruhig', 'fr' => 'calme', 'ja' => '落ち着いた'],
        '찾다' => ['en' => 'to look for', 'es' => 'buscar', 'de' => 'suchen', 'fr' => 'chercher', 'ja' => '探す'],
        '채소' => ['en' => 'vegetables', 'es' => 'verduras', 'de' => 'Gemüse', 'fr' => 'légumes', 'ja' => '野菜'],
        '채식주의자' => ['en' => 'vegetarian', 'es' => 'vegetariano', 'de' => 'vegetarisch', 'fr' => 'végétarien', 'ja' => 'ベジタリアン'],
        '책' => ['en' => 'book', 'es' => 'libro', 'de' => 'Buch', 'fr' => 'livre', 'ja' => '本'],
        '책과' => ['en' => 'book and', 'es' => 'libro y', 'de' => 'Buch und', 'fr' => 'livre et', 'ja' => '本と'],
        '책들' => ['en' => 'books', 'es' => 'libros', 'de' => 'Bücher', 'fr' => 'livres', 'ja' => '本'],
        '처럼' => ['en' => 'like', 'es' => 'como', 'de' => 'wie', 'fr' => 'comme', 'ja' => 'のように'],
        '천천히' => ['en' => 'slowly', 'es' => 'despacio', 'de' => 'langsam', 'fr' => 'lentement', 'ja' => 'ゆっくり'],
        '초록색' => ['en' => 'green', 'es' => 'verde', 'de' => 'grün', 'fr' => 'vert', 'ja' => '緑'],
        '초콜릿' => ['en' => 'chocolate', 'es' => 'chocolate', 'de' => 'Schokolade', 'fr' => 'chocolat', 'ja' => 'チョコレート'],
        '총액' => ['en' => 'total', 'es' => 'total', 'de' => 'Gesamt', 'fr' => 'total', 'ja' => '合計'],
        '충분히' => ['en' => 'enough', 'es' => 'bastante', 'de' => 'genug', 'fr' => 'assez', 'ja' => '十分に'],
        '취소하다' => ['en' => 'to cancel', 'es' => 'cancelar', 'de' => 'stornieren', 'fr' => 'annuler', 'ja' => 'キャンセルする'],
        '치즈' => ['en' => 'cheese', 'es' => 'queso', 'de' => 'Käse', 'fr' => 'fromage', 'ja' => 'チーズ'],
        '친구' => ['en' => 'friend', 'es' => 'amigo', 'de' => 'Freund', 'fr' => 'ami', 'ja' => '友達'],
        '친구는' => ['en' => 'friend', 'es' => 'amigo', 'de' => 'Freund', 'fr' => 'ami', 'ja' => '友達'],
        '친구와' => ['en' => 'friend and', 'es' => 'amigo y', 'de' => 'Freund und', 'fr' => 'ami et', 'ja' => '友達と'],
        '카드' => ['en' => 'card', 'es' => 'tarjeta', 'de' => 'Karte', 'fr' => 'carte', 'ja' => 'カード'],
        '카트' => ['en' => 'trolley', 'es' => 'carrito', 'de' => 'Einkaufswagen', 'fr' => 'chariot', 'ja' => 'カート'],
        '커피' => ['en' => 'coffee', 'es' => 'café', 'de' => 'Kaffee', 'fr' => 'café', 'ja' => 'コーヒー'],
        '커피와' => ['en' => 'coffee and', 'es' => 'café y', 'de' => 'Kaffee und', 'fr' => 'café et', 'ja' => 'コーヒーと'],
        '케이크' => ['en' => 'cake', 'es' => 'pastel', 'de' => 'Kuchen', 'fr' => 'gâteau', 'ja' => 'ケーキ'],
        '크림' => ['en' => 'cream', 'es' => 'nata', 'de' => 'Sahne', 'fr' => 'crème', 'ja' => 'クリーム'],
        '큰' => ['en' => 'big', 'es' => 'grande', 'de' => 'groß', 'fr' => 'grand', 'ja' => '大きい'],
        '킬로' => ['en' => 'kilo', 'es' => 'kilo', 'de' => 'Kilo', 'fr' => 'kilo', 'ja' => 'キロ'],
        '타르트' => ['en' => 'tart', 'es' => 'tarta', 'de' => 'Torte', 'fr' => 'tarte', 'ja' => 'タルト'],
        '탁자' => ['en' => 'table', 'es' => 'mesa', 'de' => 'Tisch', 'fr' => 'table', 'ja' => 'テーブル'],
        '탁자와' => ['en' => 'table and', 'es' => 'mesa y', 'de' => 'Tisch und', 'fr' => 'table et', 'ja' => 'テーブルと'],
        '토마토' => ['en' => 'tomato', 'es' => 'tomate', 'de' => 'Tomate', 'fr' => 'tomate', 'ja' => 'トマト'],
        '특히' => ['en' => 'especially', 'es' => 'sobre todo', 'de' => 'besonders', 'fr' => 'surtout', 'ja' => '特に'],
        '팁' => ['en' => 'tip', 'es' => 'propina', 'de' => 'Trinkgeld', 'fr' => 'pourboire', 'ja' => 'チップ'],
        '파란색' => ['en' => 'blue', 'es' => 'azul', 'de' => 'blau', 'fr' => 'bleu', 'ja' => '青'],
        '펜' => ['en' => 'pen', 'es' => 'bolígrafo', 'de' => 'Kugelschreiber', 'fr' => 'stylo', 'ja' => 'ペン'],
        '포도' => ['en' => 'grapes', 'es' => 'uvas', 'de' => 'Trauben', 'fr' => 'raisin', 'ja' => 'ぶどう'],
        '포장' => ['en' => 'takeaway', 'es' => 'para llevar', 'de' => 'zum Mitnehmen', 'fr' => 'à emporter', 'ja' => '持ち帰り'],
        '포크' => ['en' => 'fork', 'es' => 'tenedor', 'de' => 'Gabel', 'fr' => 'fourchette', 'ja' => 'フォーク'],
        '피곤한' => ['en' => 'tired', 'es' => 'cansado', 'de' => 'müde', 'fr' => 'fatigué', 'ja' => '疲れた'],
        '피하다' => ['en' => 'to avoid', 'es' => 'evitar', 'de' => 'vermeiden', 'fr' => 'éviter', 'ja' => '避ける'],
        '하나' => ['en' => 'one', 'es' => 'uno', 'de' => 'eins', 'fr' => 'un', 'ja' => '一'],
        '하나 더' => ['en' => 'another', 'es' => 'otro', 'de' => 'noch ein', 'fr' => 'encore', 'ja' => 'もう一つの'],
        '하나의' => ['en' => 'a', 'es' => 'un', 'de' => 'ein', 'fr' => 'un', 'ja' => '一つの'],
        '하늘' => ['en' => 'sky', 'es' => 'cielo', 'de' => 'Himmel', 'fr' => 'ciel', 'ja' => '空'],
        '하얀색' => ['en' => 'white', 'es' => 'blanco', 'de' => 'weiß', 'fr' => 'blanc', 'ja' => '白'],
        '학교' => ['en' => 'school', 'es' => 'escuela', 'de' => 'Schule', 'fr' => 'école', 'ja' => '学校'],
        '학교와' => ['en' => 'school and', 'es' => 'escuela y', 'de' => 'Schule und', 'fr' => 'école et', 'ja' => '学校と'],
        '한 조각' => ['en' => 'slice', 'es' => 'trozo', 'de' => 'Stück', 'fr' => 'part', 'ja' => '一切れ'],
        '한가한' => ['en' => 'free', 'es' => 'libre', 'de' => 'frei', 'fr' => 'libre', 'ja' => '暇'],
        '할인' => ['en' => 'discount', 'es' => 'descuento', 'de' => 'Rabatt', 'fr' => 'réduction', 'ja' => '割引'],
        '함께' => ['en' => 'together', 'es' => 'juntos', 'de' => 'zusammen', 'fr' => 'ensemble', 'ja' => '一緒に'],
        '해' => ['en' => 'sun', 'es' => 'sol', 'de' => 'Sonne', 'fr' => 'soleil', 'ja' => '太陽'],
        '해와' => ['en' => 'sun and', 'es' => 'sol y', 'de' => 'Sonne und', 'fr' => 'soleil et', 'ja' => '太陽と'],
        '햄버거' => ['en' => 'burger', 'es' => 'hamburguesa', 'de' => 'Burger', 'fr' => 'hamburger', 'ja' => 'ハンバーガー'],
        '행복한' => ['en' => 'happy', 'es' => 'feliz', 'de' => 'glücklich', 'fr' => 'heureux', 'ja' => '幸せ'],
        '현금으로' => ['en' => 'cash', 'es' => 'en efectivo', 'de' => 'in bar', 'fr' => 'en espèces', 'ja' => '現金で'],
        '형제' => ['en' => 'brother', 'es' => 'hermano', 'de' => 'Bruder', 'fr' => 'frère', 'ja' => '兄弟'],
        '형제는' => ['en' => 'brother', 'es' => 'hermano', 'de' => 'Bruder', 'fr' => 'frère', 'ja' => '兄弟'],
        '형제와' => ['en' => 'brother and', 'es' => 'hermano y', 'de' => 'Bruder und', 'fr' => 'frère et', 'ja' => '兄弟と'],
        '화요일' => ['en' => 'Tuesday', 'es' => 'martes', 'de' => 'Dienstag', 'fr' => 'mardi', 'ja' => '火曜日'],
        '확인하다' => ['en' => 'to confirm', 'es' => 'confirmar', 'de' => 'bestätigen', 'fr' => 'confirmer', 'ja' => '確認する'],
        '환영합니다' => ['en' => 'welcome', 'es' => 'bienvenido', 'de' => 'willkommen', 'fr' => 'bienvenue', 'ja' => 'ようこそ'],
        '후에' => ['en' => 'after', 'es' => 'después', 'de' => 'nach', 'fr' => 'après', 'ja' => '後に'],
        '훌륭한' => ['en' => 'excellent', 'es' => 'excelente', 'de' => 'ausgezeichnet', 'fr' => 'excellent', 'ja' => '素晴らしい'],
        '크루아상' => ['en' => 'croissant', 'es' => 'cruasán', 'de' => 'Croissant', 'fr' => 'croissant', 'ja' => 'クロワッサン'],
        '에클레어' => ['en' => 'eclair', 'es' => 'eclair', 'de' => 'Eclair', 'fr' => 'éclair', 'ja' => 'エクレア'],
        '유로' => ['en' => 'euro', 'es' => 'euro', 'de' => 'Euro', 'fr' => 'euro', 'ja' => 'ユーロ'],
        '태양' => ['en' => 'sun', 'es' => 'sol', 'de' => 'Sonne', 'fr' => 'soleil', 'ja' => '太陽'],
        '테이블' => ['en' => 'table', 'es' => 'mesa', 'de' => 'Tisch', 'fr' => 'table', 'ja' => 'テーブル'],
        '구름' => ['en' => 'cloud', 'es' => 'nube', 'de' => 'Wolke', 'fr' => 'nuage', 'ja' => '雲'],
        '메뉴판' => ['en' => 'menu card', 'es' => 'carta', 'de' => 'Speisekarte', 'fr' => 'carte', 'ja' => 'メニュー'],
        '식탁보' => ['en' => 'tablecloth', 'es' => 'mantel', 'de' => 'Tischdecke', 'fr' => 'nappe', 'ja' => 'テーブルクロス'],
        '어린이' => ['en' => 'child', 'es' => 'niño', 'de' => 'Kind', 'fr' => 'enfant', 'ja' => '子供'],
        '부인' => ['en' => 'madam', 'es' => 'señora', 'de' => 'Frau', 'fr' => 'madame', 'ja' => '奥様'],
        '일주일' => ['en' => 'one week', 'es' => 'una semana', 'de' => 'eine Woche', 'fr' => 'une semaine', 'ja' => '一週間'],
        '낮' => ['en' => 'daytime', 'es' => 'día', 'de' => 'Tag', 'fr' => 'journée', 'ja' => '昼'],
        '일' => ['en' => 'day / work', 'es' => 'día', 'de' => 'Tag', 'fr' => 'jour', 'ja' => '日'],
        '달' => ['en' => 'month', 'es' => 'mes', 'de' => 'Monat', 'fr' => 'mois', 'ja' => '月'],
        '년' => ['en' => 'year', 'es' => 'año', 'de' => 'Jahr', 'fr' => 'an', 'ja' => '年'],
        '수' => ['en' => 'possibility', 'es' => 'posibilidad', 'de' => 'Möglichkeit', 'fr' => 'possibilité', 'ja' => 'こと'],
        '레드' => ['en' => 'red (wine)', 'es' => 'tinto', 'de' => 'rot', 'fr' => 'rouge', 'ja' => '赤'],
        '위' => ['en' => 'top', 'es' => 'encima', 'de' => 'Oberseite', 'fr' => 'dessus', 'ja' => '上'],
        '안' => ['en' => 'inside', 'es' => 'dentro', 'de' => 'Inneres', 'fr' => 'intérieur', 'ja' => '中'],
        '앞' => ['en' => 'front', 'es' => 'delante', 'de' => 'Vorderseite', 'fr' => 'devant', 'ja' => '前'],
        '뒤' => ['en' => 'back', 'es' => 'detrás', 'de' => 'Rückseite', 'fr' => 'derrière', 'ja' => '後ろ'],
        '아래' => ['en' => 'below', 'es' => 'debajo', 'de' => 'Unterseite', 'fr' => 'dessous', 'ja' => '下'],
        '한' => ['en' => 'one', 'es' => 'un', 'de' => 'ein', 'fr' => 'un', 'ja' => '一'],
        '두' => ['en' => 'two', 'es' => 'dos', 'de' => 'zwei', 'fr' => 'deux', 'ja' => '二'],
        '세' => ['en' => 'three', 'es' => 'tres', 'de' => 'drei', 'fr' => 'trois', 'ja' => '三'],
        '오' => ['en' => 'five', 'es' => 'cinco', 'de' => 'fünf', 'fr' => 'cinq', 'ja' => '五'],
        '십' => ['en' => 'ten', 'es' => 'diez', 'de' => 'zehn', 'fr' => 'dix', 'ja' => '十'],
        '여섯' => ['en' => 'six', 'es' => 'seis', 'de' => 'sechs', 'fr' => 'six', 'ja' => '六'],
        '일곱' => ['en' => 'seven', 'es' => 'siete', 'de' => 'sieben', 'fr' => 'sept', 'ja' => '七'],
        '아홉' => ['en' => 'nine', 'es' => 'nueve', 'de' => 'neun', 'fr' => 'neuf', 'ja' => '九'],
        '권' => ['en' => 'counter for books', 'es' => 'contador de libros', 'de' => 'Zähleinheit Bücher', 'fr' => 'compteur livres', 'ja' => '冊'],
        '잔' => ['en' => 'counter for glasses', 'es' => 'contador de vasos', 'de' => 'Zähleinheit Gläser', 'fr' => 'compteur verres', 'ja' => '杯'],
        '마리' => ['en' => 'counter for animals', 'es' => 'contador de animales', 'de' => 'Zähleinheit Tiere', 'fr' => 'compteur animaux', 'ja' => '匹'],
        '조각' => ['en' => 'slice', 'es' => 'trozo', 'de' => 'Stück', 'fr' => 'morceau', 'ja' => '一切れ'],
        '제' => ['en' => 'my (polite)', 'es' => 'mi', 'de' => 'mein', 'fr' => 'mon', 'ja' => '私の'],
        '몇' => ['en' => 'how many', 'es' => 'cuántos', 'de' => 'wie viele', 'fr' => 'combien', 'ja' => 'いくつ'],
        '몇몇' => ['en' => 'a few', 'es' => 'algunos', 'de' => 'einige', 'fr' => 'quelques', 'ja' => 'いくつかの'],
        '많은' => ['en' => 'many', 'es' => 'muchos', 'de' => 'viele', 'fr' => 'beaucoup de', 'ja' => '多くの'],
        '많이' => ['en' => 'a lot', 'es' => 'mucho', 'de' => 'viel', 'fr' => 'beaucoup', 'ja' => 'たくさん'],
        '적게' => ['en' => 'less', 'es' => 'menos', 'de' => 'weniger', 'fr' => 'moins', 'ja' => '少なく'],
        '충분한' => ['en' => 'enough', 'es' => 'suficiente', 'de' => 'genug', 'fr' => 'assez de', 'ja' => '十分な'],
        '꽤' => ['en' => 'quite', 'es' => 'bastante', 'de' => 'ziemlich', 'fr' => 'assez', 'ja' => 'かなり'],
        '어떤' => ['en' => 'which', 'es' => 'cuál', 'de' => 'welche', 'fr' => 'quel', 'ja' => 'どの'],
        '새' => ['en' => 'new', 'es' => 'nuevo', 'de' => 'neu', 'fr' => 'nouveau', 'ja' => '新しい'],
        '든' => ['en' => 'any', 'es' => 'cualquiera', 'de' => 'irgendein', 'fr' => 'quelconque', 'ja' => 'でも'],
        '빨간' => ['en' => 'red', 'es' => 'rojo', 'de' => 'rot', 'fr' => 'rouge', 'ja' => '赤い'],
        '파란' => ['en' => 'blue', 'es' => 'azul', 'de' => 'blau', 'fr' => 'bleu', 'ja' => '青い'],
        '초록' => ['en' => 'green', 'es' => 'verde', 'de' => 'grün', 'fr' => 'vert', 'ja' => '緑の'],
        '노란' => ['en' => 'yellow', 'es' => 'amarillo', 'de' => 'gelb', 'fr' => 'jaune', 'ja' => '黄色い'],
        '검은' => ['en' => 'black', 'es' => 'negro', 'de' => 'schwarz', 'fr' => 'noir', 'ja' => '黒い'],
        '하얀' => ['en' => 'white', 'es' => 'blanco', 'de' => 'weiß', 'fr' => 'blanc', 'ja' => '白い'],
        '좋습니다' => ['en' => 'is good', 'es' => 'es bueno', 'de' => 'ist gut', 'fr' => 'est bon', 'ja' => '良いです'],
        '좋다' => ['en' => 'is good', 'es' => 'es bueno', 'de' => 'ist gut', 'fr' => 'est bon', 'ja' => '良い'],
        '좋았다' => ['en' => 'was good', 'es' => 'fue bueno', 'de' => 'war gut', 'fr' => 'était bon', 'ja' => '良かった'],
        '좋고' => ['en' => 'good and', 'es' => 'bueno y', 'de' => 'gut und', 'fr' => 'bon et', 'ja' => '良くて'],
        '좋거나' => ['en' => 'good or', 'es' => 'bueno o', 'de' => 'gut oder', 'fr' => 'bon ou', 'ja' => '良いか'],
        '나쁘다' => ['en' => 'is bad', 'es' => 'es malo', 'de' => 'ist schlecht', 'fr' => 'est mauvais', 'ja' => '悪い'],
        '나쁜' => ['en' => 'bad', 'es' => 'malo', 'de' => 'schlecht', 'fr' => 'mauvais', 'ja' => '悪い'],
        '비쌉니다' => ['en' => 'is expensive', 'es' => 'es caro', 'de' => 'ist teuer', 'fr' => 'est cher', 'ja' => '高いです'],
        '비싸거나' => ['en' => 'expensive or', 'es' => 'caro o', 'de' => 'teuer oder', 'fr' => 'cher ou', 'ja' => '高いか'],
        '쌉니다' => ['en' => 'is cheap', 'es' => 'es barato', 'de' => 'ist billig', 'fr' => 'est bon marché', 'ja' => '安いです'],
        '짭니다' => ['en' => 'is salty', 'es' => 'es salado', 'de' => 'ist salzig', 'fr' => 'est salé', 'ja' => 'しょっぱいです'],
        '멉니다' => ['en' => 'is far', 'es' => 'está lejos', 'de' => 'ist weit', 'fr' => 'est loin', 'ja' => '遠いです'],
        '멀다' => ['en' => 'is far', 'es' => 'está lejos', 'de' => 'ist weit', 'fr' => 'est loin', 'ja' => '遠い'],
        '가깝습니다' => ['en' => 'is near', 'es' => 'está cerca', 'de' => 'ist nah', 'fr' => 'est proche', 'ja' => '近いです'],
        '가깝다' => ['en' => 'is near', 'es' => 'está cerca', 'de' => 'ist nah', 'fr' => 'est proche', 'ja' => '近い'],
        '가깝고' => ['en' => 'near and', 'es' => 'cerca y', 'de' => 'nah und', 'fr' => 'proche et', 'ja' => '近くて'],
        '가깝거나' => ['en' => 'near or', 'es' => 'cerca o', 'de' => 'nah oder', 'fr' => 'proche ou', 'ja' => '近いか'],
        '완벽합니다' => ['en' => 'is perfect', 'es' => 'es perfecto', 'de' => 'ist perfekt', 'fr' => 'est parfait', 'ja' => '完璧です'],
        '맛있습니다' => ['en' => 'is delicious', 'es' => 'está delicioso', 'de' => 'ist köstlich', 'fr' => 'est délicieux', 'ja' => 'おいしいです'],
        '훌륭합니다' => ['en' => 'is excellent', 'es' => 'es excelente', 'de' => 'ist ausgezeichnet', 'fr' => 'est excellent', 'ja' => '素晴らしいです'],
        '맵습니다' => ['en' => 'is spicy', 'es' => 'está picante', 'de' => 'ist scharf', 'fr' => 'est épicé', 'ja' => '辛いです'],
        '차갑습니다' => ['en' => 'is cold', 'es' => 'está frío', 'de' => 'ist kalt', 'fr' => 'est froid', 'ja' => '冷たいです'],
        '뜨겁습니다' => ['en' => 'is hot', 'es' => 'está caliente', 'de' => 'ist heiß', 'fr' => 'est chaud', 'ja' => '熱いです'],
        '깨끗합니다' => ['en' => 'is clean', 'es' => 'está limpio', 'de' => 'ist sauber', 'fr' => 'est propre', 'ja' => 'きれいです'],
        '따뜻합니다' => ['en' => 'is warm', 'es' => 'es cálido', 'de' => 'ist warm', 'fr' => 'est chaud', 'ja' => '暖かいです'],
        '춥습니다' => ['en' => 'is cold', 'es' => 'hace frío', 'de' => 'ist kalt', 'fr' => 'fait froid', 'ja' => '寒いです'],
        '피곤합니다' => ['en' => 'am tired', 'es' => 'estoy cansado', 'de' => 'bin müde', 'fr' => 'suis fatigué', 'ja' => '疲れています'],
        '기쁩니다' => ['en' => 'am glad', 'es' => 'estoy contento', 'de' => 'bin froh', 'fr' => 'suis content', 'ja' => '嬉しいです'],
        '바쁩니다' => ['en' => 'is busy', 'es' => 'está ocupado', 'de' => 'ist beschäftigt', 'fr' => 'est occupé', 'ja' => '忙しいです'],
        '슬픕니다' => ['en' => 'is sad', 'es' => 'está triste', 'de' => 'ist traurig', 'fr' => 'est triste', 'ja' => '悲しいです'],
        '아픕니다' => ['en' => 'is sick', 'es' => 'está enfermo', 'de' => 'ist krank', 'fr' => 'est malade', 'ja' => '病気です'],
        '행복합니다' => ['en' => 'is happy', 'es' => 'está feliz', 'de' => 'ist glücklich', 'fr' => 'est heureux', 'ja' => '幸せです'],
        '차분합니다' => ['en' => 'is calm', 'es' => 'está tranquilo', 'de' => 'ist ruhig', 'fr' => 'est calme', 'ja' => '落ち着いています'],
        '한가합니다' => ['en' => 'is free', 'es' => 'está libre', 'de' => 'ist frei', 'fr' => 'est libre', 'ja' => '暇です'],
        '자유롭습니다' => ['en' => 'is free', 'es' => 'es libre', 'de' => 'ist frei', 'fr' => 'est libre', 'ja' => '自由です'],
        '미안합니다' => ['en' => 'am sorry', 'es' => 'lo siento', 'de' => 'tut mir leid', 'fr' => 'désolé', 'ja' => 'ごめんなさい'],
        '중요합니다' => ['en' => 'is important', 'es' => 'es importante', 'de' => 'ist wichtig', 'fr' => 'est important', 'ja' => '重要です'],
        '만족합니다' => ['en' => 'is satisfied', 'es' => 'está satisfecho', 'de' => 'ist zufrieden', 'fr' => 'est satisfait', 'ja' => '満足しています'],
        '만족하고' => ['en' => 'satisfied and', 'es' => 'satisfecho y', 'de' => 'zufrieden und', 'fr' => 'satisfait et', 'ja' => '満足して'],
        '만족했다' => ['en' => 'was satisfied', 'es' => 'estuvo satisfecho', 'de' => 'war zufrieden', 'fr' => 'était satisfait', 'ja' => '満足した'],
        '가득합니다' => ['en' => 'is full', 'es' => 'está lleno', 'de' => 'ist voll', 'fr' => 'est plein', 'ja' => 'いっぱいです'],
        '비었습니다' => ['en' => 'is empty', 'es' => 'está vacío', 'de' => 'ist leer', 'fr' => 'est vide', 'ja' => '空です'],
        '비어' => ['en' => 'empty', 'es' => 'vacío', 'de' => 'leer', 'fr' => 'vide', 'ja' => '空いて'],
        '무겁습니다' => ['en' => 'is heavy', 'es' => 'está pesado', 'de' => 'ist schwer', 'fr' => 'est lourd', 'ja' => '重いです'],
        '가볍습니다' => ['en' => 'is light', 'es' => 'es ligero', 'de' => 'ist leicht', 'fr' => 'est léger', 'ja' => '軽いです'],
        '단단한' => ['en' => 'hard', 'es' => 'duro', 'de' => 'hart', 'fr' => 'dur', 'ja' => '硬い'],
        '쉽다' => ['en' => 'is easy', 'es' => 'es fácil', 'de' => 'ist einfach', 'fr' => 'est facile', 'ja' => '簡単'],
        '쉽거나' => ['en' => 'easy or', 'es' => 'fácil o', 'de' => 'einfach oder', 'fr' => 'facile ou', 'ja' => '簡単か'],
        '어렵다' => ['en' => 'is hard', 'es' => 'es difícil', 'de' => 'ist schwer', 'fr' => 'est difficile', 'ja' => '難しい'],
        '흥미로운' => ['en' => 'interesting', 'es' => 'interesante', 'de' => 'interessant', 'fr' => 'intéressant', 'ja' => '面白い'],
        '오래된' => ['en' => 'old', 'es' => 'viejo', 'de' => 'alt', 'fr' => 'vieux', 'ja' => '古い'],
        '아름답고' => ['en' => 'beautiful and', 'es' => 'hermoso y', 'de' => 'schön und', 'fr' => 'beau et', 'ja' => '美しくて'],
        '없는' => ['en' => 'without', 'es' => 'sin', 'de' => 'ohne', 'fr' => 'sans', 'ja' => 'ない'],
        '준비되었습니다' => ['en' => 'is ready', 'es' => 'está listo', 'de' => 'ist fertig', 'fr' => 'est prêt', 'ja' => '準備ができました'],
        '준비됐습니다' => ['en' => 'is ready', 'es' => 'está listo', 'de' => 'ist fertig', 'fr' => 'est prêt', 'ja' => '準備ができました'],
        '닫혔습니다' => ['en' => 'is closed', 'es' => 'está cerrado', 'de' => 'ist geschlossen', 'fr' => 'est fermé', 'ja' => '閉まっています'],
        '열려' => ['en' => 'open', 'es' => 'abierto', 'de' => 'offen', 'fr' => 'ouvert', 'ja' => '開いて'],
        '열렸거나' => ['en' => 'open or', 'es' => 'abierto o', 'de' => 'offen oder', 'fr' => 'ouvert ou', 'ja' => '開いているか'],
        '들어있습니다' => ['en' => 'contains', 'es' => 'contiene', 'de' => 'enthält', 'fr' => 'contient', 'ja' => '入っています'],
        '깁니다' => ['en' => 'is long', 'es' => 'es largo', 'de' => 'ist lang', 'fr' => 'est long', 'ja' => '長いです'],
        '답니다' => ['en' => 'is sweet', 'es' => 'es dulce', 'de' => 'ist süß', 'fr' => 'est sucré', 'ja' => '甘いです'],
        '간다' => ['en' => 'goes', 'es' => 'va', 'de' => 'geht', 'fr' => 'va', 'ja' => '行く'],
        '가고' => ['en' => 'going', 'es' => 'yendo', 'de' => 'gehend', 'fr' => 'allant', 'ja' => '行って'],
        '갈' => ['en' => 'to go', 'es' => 'ir', 'de' => 'gehen', 'fr' => 'aller', 'ja' => '行く'],
        '올' => ['en' => 'to come', 'es' => 'venir', 'de' => 'kommen', 'fr' => 'venir', 'ja' => '来る'],
        '있다' => ['en' => 'there is', 'es' => 'hay', 'de' => 'gibt es', 'fr' => 'il y a', 'ja' => 'いる'],
        '있고' => ['en' => 'there is and', 'es' => 'hay y', 'de' => 'gibt es und', 'fr' => 'il y a et', 'ja' => 'いて'],
        '있었다' => ['en' => 'there was', 'es' => 'había', 'de' => 'gab es', 'fr' => 'il y avait', 'ja' => 'いた'],
        '있나요' => ['en' => 'is there', 'es' => 'hay', 'de' => 'gibt es', 'fr' => 'y a-t-il', 'ja' => 'いますか'],
        '있습니까' => ['en' => 'is there', 'es' => 'hay', 'de' => 'gibt es', 'fr' => 'y a-t-il', 'ja' => 'ありますか'],
        '있으면' => ['en' => 'if there is', 'es' => 'si hay', 'de' => 'wenn es gibt', 'fr' => 's\'il y a', 'ja' => 'あれば'],
        '생각한다' => ['en' => 'thinks', 'es' => 'piensa', 'de' => 'denkt', 'fr' => 'pense', 'ja' => '思う'],
        '믿는다' => ['en' => 'believes', 'es' => 'cree', 'de' => 'glaubt', 'fr' => 'croit', 'ja' => '信じる'],
        '선호한다' => ['en' => 'prefers', 'es' => 'prefiere', 'de' => 'bevorzugt', 'fr' => 'préfère', 'ja' => '好む'],
        '선호하다' => ['en' => 'to prefer', 'es' => 'preferir', 'de' => 'bevorzugen', 'fr' => 'préférer', 'ja' => '好む'],
        '먹는다' => ['en' => 'eats', 'es' => 'come', 'de' => 'isst', 'fr' => 'mange', 'ja' => '食べる'],
        '먹었다' => ['en' => 'ate', 'es' => 'comió', 'de' => 'aß', 'fr' => 'a mangé', 'ja' => '食べた'],
        '먹고' => ['en' => 'eating', 'es' => 'comiendo', 'de' => 'essend', 'fr' => 'mangeant', 'ja' => '食べて'],
        '마신다' => ['en' => 'drinks', 'es' => 'bebe', 'de' => 'trinkt', 'fr' => 'boit', 'ja' => '飲む'],
        '마셨다' => ['en' => 'drank', 'es' => 'bebió', 'de' => 'trank', 'fr' => 'a bu', 'ja' => '飲んだ'],
        '마시고' => ['en' => 'drinking', 'es' => 'bebiendo', 'de' => 'trinkend', 'fr' => 'buvant', 'ja' => '飲んで'],
        '걷는다' => ['en' => 'walks', 'es' => 'camina', 'de' => 'geht', 'fr' => 'marche', 'ja' => '歩く'],
        '걷고' => ['en' => 'walking', 'es' => 'caminando', 'de' => 'gehend', 'fr' => 'marchant', 'ja' => '歩いて'],
        '잔다' => ['en' => 'sleeps', 'es' => 'duerme', 'de' => 'schläft', 'fr' => 'dort', 'ja' => '眠る'],
        '자고' => ['en' => 'sleeping', 'es' => 'durmiendo', 'de' => 'schlafend', 'fr' => 'dormant', 'ja' => '眠って'],
        '읽는다' => ['en' => 'reads', 'es' => 'lee', 'de' => 'liest', 'fr' => 'lit', 'ja' => '読む'],
        '삽니다' => ['en' => 'lives', 'es' => 'vive', 'de' => 'wohnt', 'fr' => 'habite', 'ja' => '住んでいます'],
        '보았다' => ['en' => 'saw', 'es' => 'vio', 'de' => 'sah', 'fr' => 'a vu', 'ja' => '見た'],
        '키웁니다' => ['en' => 'keeps (a pet)', 'es' => 'tiene', 'de' => 'hält', 'fr' => 'a', 'ja' => '飼っています'],
        '느낍니다' => ['en' => 'feels', 'es' => 'siente', 'de' => 'fühlt', 'fr' => 'sent', 'ja' => '感じます'],
        '지냅니다' => ['en' => 'gets along', 'es' => 'está', 'de' => 'geht es', 'fr' => 'va', 'ja' => '過ごしています'],
        '지내요' => ['en' => 'get along', 'es' => 'estoy', 'de' => 'geht es', 'fr' => 'va', 'ja' => '過ごします'],
        '지내세요' => ['en' => 'how are you', 'es' => 'cómo está', 'de' => 'wie geht es', 'fr' => 'comment allez-vous', 'ja' => 'お元気ですか'],
        '냅니다' => ['en' => 'pays', 'es' => 'paga', 'de' => 'zahlt', 'fr' => 'paie', 'ja' => '払います'],
        '낼' => ['en' => 'to pay', 'es' => 'pagar', 'de' => 'zahlen', 'fr' => 'payer', 'ja' => '払う'],
        '지불하고' => ['en' => 'paying', 'es' => 'pagando', 'de' => 'zahlend', 'fr' => 'payant', 'ja' => '払って'],
        '주다' => ['en' => 'to give', 'es' => 'dar', 'de' => 'geben', 'fr' => 'donner', 'ja' => '与える'],
        '받다' => ['en' => 'to receive', 'es' => 'recibir', 'de' => 'bekommen', 'fr' => 'recevoir', 'ja' => '受け取る'],
        '묻다' => ['en' => 'to ask', 'es' => 'preguntar', 'de' => 'fragen', 'fr' => 'demander', 'ja' => '尋ねる'],
        '재다' => ['en' => 'to weigh', 'es' => 'pesar', 'de' => 'wiegen', 'fr' => 'peser', 'ja' => '量る'],
        '찾을' => ['en' => 'to find', 'es' => 'encontrar', 'de' => 'finden', 'fr' => 'trouver', 'ja' => '見つける'],
        '찾고' => ['en' => 'finding', 'es' => 'encontrando', 'de' => 'findend', 'fr' => 'trouvant', 'ja' => '探して'],
        '가져올' => ['en' => 'to bring', 'es' => 'traer', 'de' => 'bringen', 'fr' => 'apporter', 'ja' => '持ってくる'],
        '고르고' => ['en' => 'choosing', 'es' => 'eligiendo', 'de' => 'wählend', 'fr' => 'choisissant', 'ja' => '選んで'],
        '고를' => ['en' => 'to choose', 'es' => 'elegir', 'de' => 'wählen', 'fr' => 'choisir', 'ja' => '選ぶ'],
        '계산하고' => ['en' => 'paying up', 'es' => 'pagando', 'de' => 'abrechnend', 'fr' => 'réglant', 'ja' => '計算して'],
        '계산해' => ['en' => 'pay up', 'es' => 'paga', 'de' => 'rechne ab', 'fr' => 'règle', 'ja' => '計算して'],
        '예약하고' => ['en' => 'booking', 'es' => 'reservando', 'de' => 'reservierend', 'fr' => 'réservant', 'ja' => '予約して'],
        '확인하고' => ['en' => 'confirming', 'es' => 'confirmando', 'de' => 'bestätigend', 'fr' => 'confirmant', 'ja' => '確認して'],
        '주문하고' => ['en' => 'ordering', 'es' => 'pidiendo', 'de' => 'bestellend', 'fr' => 'commandant', 'ja' => '注文して'],
        '피하고' => ['en' => 'avoiding', 'es' => 'evitando', 'de' => 'vermeidend', 'fr' => 'évitant', 'ja' => '避けて'],
        '건너서' => ['en' => 'crossing', 'es' => 'cruzando', 'de' => 'überquerend', 'fr' => 'traversant', 'ja' => '渡って'],
        '돌아서' => ['en' => 'turning', 'es' => 'girando', 'de' => 'abbiegend', 'fr' => 'tournant', 'ja' => '曲がって'],
        '전화하고' => ['en' => 'calling', 'es' => 'llamando', 'de' => 'anrufend', 'fr' => 'appelant', 'ja' => '電話して'],
        '전화해' => ['en' => 'call', 'es' => 'llama', 'de' => 'ruf an', 'fr' => 'appelle', 'ja' => '電話して'],
        '만나요' => ['en' => 'nice to meet you', 'es' => 'encantado', 'de' => 'freut mich', 'fr' => 'enchanté', 'ja' => 'はじめまして'],
        '알겠습니다' => ['en' => 'understood', 'es' => 'entendido', 'de' => 'verstanden', 'fr' => 'compris', 'ja' => 'わかりました'],
        '원한다' => ['en' => 'wants', 'es' => 'quiere', 'de' => 'will', 'fr' => 'veut', 'ja' => 'ほしい'],
        '원하다' => ['en' => 'to want', 'es' => 'querer', 'de' => 'wollen', 'fr' => 'vouloir', 'ja' => 'ほしい'],
        '싶다' => ['en' => 'want to', 'es' => 'quiero', 'de' => 'möchte', 'fr' => 'veux', 'ja' => 'たい'],
        '싶어요' => ['en' => 'want to', 'es' => 'quiero', 'de' => 'möchte', 'fr' => 'veux', 'ja' => 'たいです'],
        '넣은' => ['en' => 'put in', 'es' => 'con', 'de' => 'mit', 'fr' => 'avec', 'ja' => '入れた'],
        '사기' => ['en' => 'buying', 'es' => 'comprar', 'de' => 'kaufen', 'fr' => 'acheter', 'ja' => '買うこと'],
        '가기를' => ['en' => 'going', 'es' => 'ir', 'de' => 'gehen', 'fr' => 'aller', 'ja' => '行くこと'],
        '여나요' => ['en' => 'does it open', 'es' => 'abre', 'de' => 'öffnet', 'fr' => 'ouvre', 'ja' => '開きますか'],
        '어떻게' => ['en' => 'how', 'es' => 'cómo', 'de' => 'wie', 'fr' => 'comment', 'ja' => 'どう'],
        '누가' => ['en' => 'who', 'es' => 'quién', 'de' => 'wer', 'fr' => 'qui', 'ja' => '誰が'],
        '얼마나' => ['en' => 'how much', 'es' => 'cuánto', 'de' => 'wie viel', 'fr' => 'combien', 'ja' => 'どのくらい'],
        '얼마입니까' => ['en' => 'how much is it', 'es' => 'cuánto es', 'de' => 'wie viel kostet', 'fr' => 'combien coûte', 'ja' => 'いくらですか'],
        '여보세요' => ['en' => 'hello (on the phone)', 'es' => 'diga', 'de' => 'hallo', 'fr' => 'allô', 'ja' => 'もしもし'],
        '같이' => ['en' => 'together', 'es' => 'juntos', 'de' => 'zusammen', 'fr' => 'ensemble', 'ja' => '一緒に'],
        '다시' => ['en' => 'again', 'es' => 'otra vez', 'de' => 'wieder', 'fr' => 'encore', 'ja' => 'また'],
        '빨리' => ['en' => 'quickly', 'es' => 'rápido', 'de' => 'schnell', 'fr' => 'vite', 'ja' => '速く'],
        '바른' => ['en' => 'right', 'es' => 'correcto', 'de' => 'richtig', 'fr' => 'correct', 'ja' => '正しい'],
        '직진' => ['en' => 'straight ahead', 'es' => 'recto', 'de' => 'geradeaus', 'fr' => 'tout droit', 'ja' => 'まっすぐ'],
        '자주' => ['en' => 'often', 'es' => 'a menudo', 'de' => 'oft', 'fr' => 'souvent', 'ja' => 'しばしば'],
        '항상' => ['en' => 'always', 'es' => 'siempre', 'de' => 'immer', 'fr' => 'toujours', 'ja' => 'いつも'],
        '가끔' => ['en' => 'sometimes', 'es' => 'a veces', 'de' => 'manchmal', 'fr' => 'parfois', 'ja' => '時々'],
        '여기서' => ['en' => 'here', 'es' => 'aquí', 'de' => 'hier', 'fr' => 'ici', 'ja' => 'ここで'],
        '앞에서' => ['en' => 'in front of', 'es' => 'delante de', 'de' => 'vor', 'fr' => 'devant', 'ja' => '前で'],
        '위에서' => ['en' => 'on top of', 'es' => 'encima de', 'de' => 'auf', 'fr' => 'sur', 'ja' => '上で'],
        '거기에' => ['en' => 'there', 'es' => 'allí', 'de' => 'dort', 'fr' => 'là', 'ja' => 'そこに'],
        '위의' => ['en' => 'on top of', 'es' => 'encima de', 'de' => 'auf', 'fr' => 'sur', 'ja' => 'の上の'],
        '안의' => ['en' => 'inside of', 'es' => 'dentro de', 'de' => 'in', 'fr' => 'dans', 'ja' => 'の中の'],
        '아래의' => ['en' => 'under', 'es' => 'debajo de', 'de' => 'unter', 'fr' => 'sous', 'ja' => 'の下の'],
        '뒤의' => ['en' => 'behind', 'es' => 'detrás de', 'de' => 'hinter', 'fr' => 'derrière', 'ja' => 'の後ろの'],
        '위한' => ['en' => 'for', 'es' => 'para', 'de' => 'für', 'fr' => 'pour', 'ja' => 'のための'],
        '때문에' => ['en' => 'because of', 'es' => 'porque', 'de' => 'weil', 'fr' => 'parce que', 'ja' => 'なぜなら'],
        '그다음에' => ['en' => 'then', 'es' => 'entonces', 'de' => 'dann', 'fr' => 'ensuite', 'ja' => 'それから'],
        '그때' => ['en' => 'at that time', 'es' => 'entonces', 'de' => 'damals', 'fr' => 'alors', 'ja' => 'その時'],
        '행복하게' => ['en' => 'happily', 'es' => 'felizmente', 'de' => 'glücklich', 'fr' => 'heureusement', 'ja' => '幸せに'],
        '차분하게' => ['en' => 'calmly', 'es' => 'con calma', 'de' => 'ruhig', 'fr' => 'calmement', 'ja' => '落ち着いて'],
        '사실이다' => ['en' => 'is true', 'es' => 'es verdad', 'de' => 'ist wahr', 'fr' => 'est vrai', 'ja' => '本当だ'],
        '거짓이다' => ['en' => 'is false', 'es' => 'es falso', 'de' => 'ist falsch', 'fr' => 'est faux', 'ja' => '偽だ'],
        '좋다고' => ['en' => 'that it is good', 'es' => 'que es bueno', 'de' => 'dass es gut ist', 'fr' => 'que c\'est bon', 'ja' => '良いと'],
        '네라고' => ['en' => 'saying yes', 'es' => 'que sí', 'de' => 'dass ja', 'fr' => 'que oui', 'ja' => 'はいと'],
        '책처럼' => ['en' => 'like a book', 'es' => 'como un libro', 'de' => 'wie ein Buch', 'fr' => 'comme un livre', 'ja' => '本のように'],
        '커피만큼' => ['en' => 'as much as coffee', 'es' => 'tanto como el café', 'de' => 'so viel wie Kaffee', 'fr' => 'autant que le café', 'ja' => 'コーヒーと同じくらい'],
        '개보다' => ['en' => 'than a dog', 'es' => 'que un perro', 'de' => 'als ein Hund', 'fr' => 'qu\'un chien', 'ja' => '犬より'],
        '목이' => ['en' => 'throat', 'es' => 'garganta', 'de' => 'Hals', 'fr' => 'gorge', 'ja' => 'のどが'],
        '마릅니다' => ['en' => 'is dry / thirsty', 'es' => 'tengo sed', 'de' => 'bin durstig', 'fr' => 'ai soif', 'ja' => '渇いています'],
        '무게를' => ['en' => 'the weight', 'es' => 'el peso', 'de' => 'das Gewicht', 'fr' => 'le poids', 'ja' => '重さを'],
        '값을' => ['en' => 'the price', 'es' => 'el precio', 'de' => 'den Preis', 'fr' => 'le prix', 'ja' => '値段を'],
        '이것은' => ['en' => 'this is', 'es' => 'esto es', 'de' => 'das ist', 'fr' => 'c\'est', 'ja' => 'これは'],
        '이것이' => ['en' => 'this', 'es' => 'esto', 'de' => 'dies', 'fr' => 'ceci', 'ja' => 'これが'],
        '하루' => ['en' => 'a day', 'es' => 'un día', 'de' => 'ein Tag', 'fr' => 'un jour', 'ja' => '一日'],
        '당신' => ['en' => 'you', 'es' => 'tú', 'de' => 'du', 'fr' => 'tu', 'ja' => 'あなた'],
        '진실' => ['en' => 'truth', 'es' => 'verdad', 'de' => 'Wahrheit', 'fr' => 'vérité', 'ja' => '本当'],
        '무료' => ['en' => 'free of charge', 'es' => 'gratis', 'de' => 'kostenlos', 'fr' => 'gratuit', 'ja' => '無料'],
        '집에서였다' => ['en' => 'was at home', 'es' => 'estaba en casa', 'de' => 'war zu Hause', 'fr' => 'était à la maison', 'ja' => '家でした'],
        '말하고' => ['en' => 'speaking', 'es' => 'hablando', 'de' => 'sprechend', 'fr' => 'parlant', 'ja' => '話して'],
        '그러고' => ['en' => 'and then', 'es' => 'y luego', 'de' => 'und dann', 'fr' => 'et puis', 'ja' => 'そして'],
        '나서' => ['en' => 'after that', 'es' => 'después', 'de' => 'danach', 'fr' => 'ensuite', 'ja' => 'それから'],
        '진실이라고' => ['en' => 'that it is true', 'es' => 'que es verdad', 'de' => 'dass es wahr ist', 'fr' => 'que c\'est vrai', 'ja' => '本当だと'],
        '잡다' => ['en' => 'to hold', 'es' => 'sujetar', 'de' => 'halten', 'fr' => 'tenir', 'ja' => '掴む'],
        '사세요' => ['en' => 'to buy', 'es' => 'comprar', 'de' => 'kaufen', 'fr' => 'acheter', 'ja' => '買う'],
        '드세요' => ['en' => 'eat', 'es' => 'comer', 'de' => 'essen', 'fr' => 'manger', 'ja' => '食べる'],
        '가세요' => ['en' => 'go', 'es' => 'ir', 'de' => 'gehen', 'fr' => 'aller', 'ja' => '行く'],
        '오세요' => ['en' => 'come', 'es' => 'venir', 'de' => 'kommen', 'fr' => 'venir', 'ja' => '来る'],
        '마시세요' => ['en' => 'drink', 'es' => 'beber', 'de' => 'trinken', 'fr' => 'boire', 'ja' => '飲む'],
        '주무세요' => ['en' => 'sleep', 'es' => 'dormir', 'de' => 'schlafen', 'fr' => 'dormir', 'ja' => '眠る'],
        '읽으세요' => ['en' => 'read', 'es' => 'leer', 'de' => 'lesen', 'fr' => 'lire', 'ja' => '読む'],
        '걸으세요' => ['en' => 'walk', 'es' => 'caminar', 'de' => 'gehen', 'fr' => 'marcher', 'ja' => '歩く'],
        '말하세요' => ['en' => 'speak', 'es' => 'hablar', 'de' => 'sprechen', 'fr' => 'parler', 'ja' => '話す'],
        '기다리세요' => ['en' => 'wait', 'es' => 'esperar', 'de' => 'warten', 'fr' => 'attendre', 'ja' => '待つ'],
        '전화하세요' => ['en' => 'call', 'es' => 'llamar', 'de' => 'anrufen', 'fr' => 'appeler', 'ja' => '電話する'],
        '다시 전화하세요' => ['en' => 'call back', 'es' => 'devolver la llamada', 'de' => 'zurückrufen', 'fr' => 'rappeler', 'ja' => '折り返す'],
        '찾으세요' => ['en' => 'to look for', 'es' => 'buscar', 'de' => 'suchen', 'fr' => 'chercher', 'ja' => '探す'],
        '넣으세요' => ['en' => 'to put', 'es' => 'poner', 'de' => 'legen', 'fr' => 'mettre', 'ja' => '入れる'],
        '고르세요' => ['en' => 'to choose', 'es' => 'elegir', 'de' => 'wählen', 'fr' => 'choisir', 'ja' => '選ぶ'],
        '비교하세요' => ['en' => 'to compare', 'es' => 'comparar', 'de' => 'vergleichen', 'fr' => 'comparer', 'ja' => '比べる'],
        '나르세요' => ['en' => 'to carry', 'es' => 'llevar', 'de' => 'tragen', 'fr' => 'porter', 'ja' => '運ぶ'],
        '피하세요' => ['en' => 'to avoid', 'es' => 'evitar', 'de' => 'vermeiden', 'fr' => 'éviter', 'ja' => '避ける'],
        '건너세요' => ['en' => 'cross', 'es' => 'cruzar', 'de' => 'überqueren', 'fr' => 'traverser', 'ja' => '渡る'],
        '계속하세요' => ['en' => 'continue', 'es' => 'continuar', 'de' => 'weitergehen', 'fr' => 'continuer', 'ja' => '続ける'],
        '도세요' => ['en' => 'turn', 'es' => 'girar', 'de' => 'abbiegen', 'fr' => 'tourner', 'ja' => '曲がる'],
        '보세요' => ['en' => 'watch', 'es' => 'mirar', 'de' => 'schauen', 'fr' => 'regarder', 'ja' => '見る'],
        '나누세요' => ['en' => 'to share', 'es' => 'compartir', 'de' => 'teilen', 'fr' => 'partager', 'ja' => '分ける'],
        '지불하세요' => ['en' => 'pay', 'es' => 'pagar', 'de' => 'bezahlen', 'fr' => 'payer', 'ja' => '払う'],
        '발견하세요' => ['en' => 'to find', 'es' => 'encontrar', 'de' => 'finden', 'fr' => 'trouver', 'ja' => '見つける'],
        '가져오세요' => ['en' => 'to bring', 'es' => 'traer', 'de' => 'bringen', 'fr' => 'apporter', 'ja' => '持ってくる'],
        '예약하세요' => ['en' => 'to book', 'es' => 'reservar', 'de' => 'reservieren', 'fr' => 'réserver', 'ja' => '予約する'],
        '확인하세요' => ['en' => 'to confirm', 'es' => 'confirmar', 'de' => 'bestätigen', 'fr' => 'confirmer', 'ja' => '確認する'],
        '주문하세요' => ['en' => 'to order', 'es' => 'pedir', 'de' => 'bestellen', 'fr' => 'commander', 'ja' => '注文する'],
        '재세요' => ['en' => 'to weigh', 'es' => 'pesar', 'de' => 'wiegen', 'fr' => 'peser', 'ja' => '量る'],
        '잡으세요' => ['en' => 'to hold', 'es' => 'sujetar', 'de' => 'halten', 'fr' => 'tenir', 'ja' => '掴む'],
        '물으세요' => ['en' => 'to ask', 'es' => 'preguntar', 'de' => 'fragen', 'fr' => 'demander', 'ja' => '尋ねる'],
        '받으세요' => ['en' => 'to receive', 'es' => 'recibir', 'de' => 'bekommen', 'fr' => 'recevoir', 'ja' => '受け取る'],
        '무게를 재세요' => ['en' => 'to weigh', 'es' => 'pesar', 'de' => 'wiegen', 'fr' => 'peser', 'ja' => '量る'],
    ];

    private const LANGS = ['en', 'es', 'de', 'fr', 'ja'];

    /**
     * @return array{i18n: array<string, string>}
     */
    public static function hint(string $korean): array
    {
        return ['i18n' => self::meanings($korean)];
    }

    /**
     * Case particles, longest first so 에서 is tried before 에.
     *
     * Korean writes a particle joined to its noun with no space, so a word
     * tile has to carry its own particle to be spelled correctly. Rather than
     * store 고양이, 고양이가, 고양이를 and 고양이에게 as four dictionary
     * entries, a tile that isn't found is looked up again with its particle
     * stripped, and inherits the base noun's meaning.
     */
    /**
     * The copula glued onto a noun to make a sentence: 형제 -> 형제입니다.
     * Tried before the particles, longest first, so 입니다 is not mistaken for
     * a stray 다.
     */
    private const COPULAS = [
        '이라고', '입니까', '입니다', '이었습니다', '였습니다', '이었다', '이에요', '예요',
        '이고', '이다',
    ];

    private const PARTICLES = [
        '에서는', '으로는', '에게서', '이라고', '에서', '에게', '으로', '까지', '부터', '이나',
        '은', '는', '이', '가', '을', '를', '에', '와', '과', '로', '의', '도', '만', '나',
    ];

    /**
     * @return array<string, string>
     */
    public static function meanings(string $korean): array
    {
        $key = trim($korean);

        foreach (self::WORDS as $word => $translations) {
            if ($word === $key) {
                return $translations;
            }
        }

        // Not a dictionary headword. Try again without a trailing particle or
        // copula, so 고양이가 and 형제입니다 both resolve to their noun. Only
        // strip when something is left: a bare particle is not a word and
        // should fall through.
        foreach (array_merge(self::COPULAS, self::PARTICLES) as $suffix) {
            if (! str_ends_with($key, $suffix)) {
                continue;
            }

            $stem = mb_substr($key, 0, mb_strlen($key) - mb_strlen($suffix));

            if ($stem === '') {
                continue;
            }

            foreach (self::WORDS as $word => $translations) {
                if ($word === $stem) {
                    return $translations;
                }
            }
        }

        return array_fill_keys(self::LANGS, $korean);
    }

    /** Every Korean word the dictionary knows (used for wrong-answer options). */
    public static function all(): array
    {
        return array_keys(self::WORDS);
    }

    public static function knows(string $korean): bool
    {
        $key = trim($korean);

        foreach (array_keys(self::WORDS) as $word) {
            if ($word === $key) {
                return true;
            }
        }

        return false;
    }
}
