<?php

namespace Database\Seeders\Support;

/**
 * Spanish word => its meaning in every native language a Spanish course supports
 * (English, German, French, Japanese, Korean).
 *
 * Spanish is the LEARNING language here, so exercise content (words, phrases,
 * tiles) is authored in Spanish, and only the hints/prompts are shown in the
 * learner's own language. Nothing user-facing is hardcoded: seeders pull from
 * here and store the result as an ['i18n' => [...]] map, which
 * ExerciseContentService resolves per request.
 *
 * This mirrors EnglishVocabulary and the other course dictionaries exactly, only
 * the language roles are swapped. Add a word here once and every unit can use it.
 */
class SpanishVocabulary
{
    private const WORDS = [
        'a' => ['en' => 'to', 'de' => 'zu', 'fr' => 'à', 'ja' => 'へ', 'ko' => '로', 'tr' => 'e', 'ru' => 'в', 'ar' => 'إلى', 'az' => 'doğru'],
        'abierta' => ['en' => 'open', 'de' => 'offen', 'fr' => 'ouvert', 'ja' => '開いた', 'ko' => '열린', 'tr' => 'açık', 'ru' => 'открыто', 'ar' => 'مفتوح', 'az' => 'açıq'],
        'abierto' => ['en' => 'open', 'de' => 'offen', 'fr' => 'ouvert', 'ja' => '開いた', 'ko' => '열린', 'tr' => 'açık', 'ru' => 'открыто', 'ar' => 'مفتوح', 'az' => 'açıq'],
        'adiós' => ['en' => 'goodbye', 'de' => 'auf Wiedersehen', 'fr' => 'au revoir', 'ja' => 'さようなら', 'ko' => '안녕히 가세요', 'tr' => 'hoşça kal', 'ru' => 'до свидания', 'ar' => 'مع السلامة', 'az' => 'sağ ol'],
        'agua' => ['en' => 'water', 'de' => 'Wasser', 'fr' => 'eau', 'ja' => '水', 'ko' => '물', 'tr' => 'su', 'ru' => 'вода', 'ar' => 'ماء', 'az' => 'su'],
        'ahora' => ['en' => 'now', 'de' => 'jetzt', 'fr' => 'maintenant', 'ja' => '今', 'ko' => '지금', 'tr' => 'şimdi', 'ru' => 'сейчас', 'ar' => 'الآن', 'az' => 'indi'],
        'al' => ['en' => 'to the', 'de' => 'zum', 'fr' => 'au', 'ja' => 'へ', 'ko' => '로', 'tr' => 'e', 'ru' => 'в', 'ar' => 'إلى', 'az' => 'doğru'],
        'alergia' => ['en' => 'allergy', 'de' => 'Allergie', 'fr' => 'allergie', 'ja' => 'アレルギー', 'ko' => '알레르기', 'tr' => 'alerji', 'ru' => 'аллергия', 'ar' => 'حساسية', 'az' => 'allergiya'],
        'algo' => ['en' => 'some', 'de' => 'etwas', 'fr' => 'du', 'ja' => 'いくつかの', 'ko' => '약간의', 'tr' => 'biraz', 'ru' => 'немного', 'ar' => 'بعض', 'az' => 'bir az'],
        'algo de' => ['en' => 'some', 'de' => 'etwas', 'fr' => 'du', 'ja' => '少しの', 'ko' => '약간의', 'tr' => 'biraz', 'ru' => 'немного', 'ar' => 'بعض', 'az' => 'bir az'],
        'alérgico' => ['en' => 'allergic', 'de' => 'allergisch', 'fr' => 'allergique', 'ja' => 'アレルギーの', 'ko' => '알레르기가 있는', 'tr' => 'alerjik', 'ru' => 'аллергия', 'ar' => 'حساسية', 'az' => 'allergiya'],
        'amarillo' => ['en' => 'yellow', 'de' => 'gelb', 'fr' => 'jaune', 'ja' => '黄色', 'ko' => '노란색', 'tr' => 'sarı', 'ru' => 'жёлтый', 'ar' => 'أصفر', 'az' => 'sarı'],
        'amigo' => ['en' => 'friend', 'de' => 'Freund', 'fr' => 'ami', 'ja' => '友達', 'ko' => '친구', 'tr' => 'arkadaş', 'ru' => 'друг', 'ar' => 'صديق', 'az' => 'dost'],
        'antes' => ['en' => 'before', 'de' => 'vor', 'fr' => 'avant', 'ja' => '前に', 'ko' => '전에', 'tr' => 'önce', 'ru' => 'до', 'ar' => 'قبل', 'az' => 'əvvəl'],
        'aquí' => ['en' => 'here', 'de' => 'hier', 'fr' => 'ici', 'ja' => 'ここ', 'ko' => '여기', 'tr' => 'burada', 'ru' => 'здесь', 'ar' => 'هنا', 'az' => 'burada'],
        'aquí está' => ['en' => 'here is', 'de' => 'hier ist', 'fr' => 'voici', 'ja' => 'これが', 'ko' => '여기', 'tr' => 'işte', 'ru' => 'здесь', 'ar' => 'هنا', 'az' => 'burada'],
        'arroz' => ['en' => 'rice', 'de' => 'Reis', 'fr' => 'riz', 'ja' => 'ご飯', 'ko' => '밥', 'tr' => 'pirinç', 'ru' => 'рис', 'ar' => 'أرز', 'az' => 'düyü'],
        'ayer' => ['en' => 'yesterday', 'de' => 'gestern', 'fr' => 'hier', 'ja' => '昨日', 'ko' => '어제', 'tr' => 'dün', 'ru' => 'вчера', 'ar' => 'أمس', 'az' => 'dünən'],
        'azul' => ['en' => 'blue', 'de' => 'blau', 'fr' => 'bleu', 'ja' => '青', 'ko' => '파란색', 'tr' => 'mavi', 'ru' => 'синий', 'ar' => 'أزرق', 'az' => 'mavi'],
        'azúcar' => ['en' => 'sugar', 'de' => 'Zucker', 'fr' => 'sucre', 'ja' => '砂糖', 'ko' => '설탕', 'tr' => 'şeker', 'ru' => 'сахар', 'ar' => 'سكر', 'az' => 'şəkər'],
        'años' => ['en' => 'years old', 'de' => 'Jahre alt', 'fr' => 'ans', 'ja' => '歳', 'ko' => '살', 'tr' => 'yaşında', 'ru' => 'лет старый', 'ar' => 'سنوات قديم', 'az' => 'yaşında köhnə'],
        'balanza' => ['en' => 'scales', 'de' => 'Waage', 'fr' => 'balance', 'ja' => 'はかり', 'ko' => '저울', 'tr' => 'terazi', 'ru' => 'весы', 'ar' => 'ميزان', 'az' => 'tərəzi'],
        'barata' => ['en' => 'cheap', 'de' => 'billig', 'fr' => 'bon marché', 'ja' => '安い', 'ko' => '싼', 'tr' => 'ucuz', 'ru' => 'дешёвый', 'ar' => 'رخيص', 'az' => 'ucuz'],
        'barato' => ['en' => 'cheap', 'de' => 'billig', 'fr' => 'bon marché', 'ja' => '安い', 'ko' => '싼', 'tr' => 'ucuz', 'ru' => 'дешёвый', 'ar' => 'رخيص', 'az' => 'ucuz'],
        'bastante' => ['en' => 'enough', 'de' => 'genug', 'fr' => 'assez', 'ja' => '十分に', 'ko' => '충분히', 'tr' => 'yeterli', 'ru' => 'достаточно', 'ar' => 'كفى', 'az' => 'kifayət'],
        'bastantes' => ['en' => 'enough', 'de' => 'genug', 'fr' => 'assez', 'ja' => '十分に', 'ko' => '충분히', 'tr' => 'yeterli', 'ru' => 'достаточно', 'ar' => 'كفى', 'az' => 'kifayət'],
        'beber' => ['en' => 'drink', 'de' => 'trinken', 'fr' => 'boire', 'ja' => '飲む', 'ko' => '마시다', 'tr' => 'iç', 'ru' => 'напиток', 'ar' => 'مشروب', 'az' => 'içki'],
        'bebida' => ['en' => 'drink', 'de' => 'Getränk', 'fr' => 'boisson', 'ja' => '飲み物', 'ko' => '음료', 'tr' => 'iç', 'ru' => 'напиток', 'ar' => 'مشروب', 'az' => 'içki'],
        'bebo' => ['en' => 'drink', 'de' => 'trinke', 'fr' => 'bois', 'ja' => '飲む', 'ko' => '마시다', 'tr' => 'iç', 'ru' => 'напиток', 'ar' => 'مشروب', 'az' => 'içki'],
        'bebí' => ['en' => 'I drank', 'de' => 'ich trank', 'fr' => 'j\'ai bu', 'ja' => '私は飲んだ', 'ko' => '나는 마셨다', 'tr' => 'içtim', 'ru' => 'я пил', 'ar' => 'شربت', 'az' => 'içdim'],
        'bien' => ['en' => 'well', 'de' => 'gut', 'fr' => 'bien', 'ja' => '元気', 'ko' => '잘', 'tr' => 'iyi', 'ru' => 'хорошо', 'ar' => 'بخير', 'az' => 'yaxşıyam'],
        'bienvenido' => ['en' => 'welcome', 'de' => 'willkommen', 'fr' => 'bienvenue', 'ja' => 'ようこそ', 'ko' => '환영합니다', 'tr' => 'hoş geldin', 'ru' => 'добро пожаловать', 'ar' => 'أهلا وسهلا', 'az' => 'xoş gəlmisiniz'],
        'blanco' => ['en' => 'white', 'de' => 'weiß', 'fr' => 'blanc', 'ja' => '白', 'ko' => '하얀색', 'tr' => 'beyaz', 'ru' => 'белый', 'ar' => 'أبيض', 'az' => 'ağ'],
        'bolsa' => ['en' => 'bag', 'de' => 'Tüte', 'fr' => 'sac', 'ja' => '袋', 'ko' => '봉투', 'tr' => 'poşet', 'ru' => 'пакет', 'ar' => 'كيس', 'az' => 'torba'],
        'bolígrafo' => ['en' => 'pen', 'de' => 'Kugelschreiber', 'fr' => 'stylo', 'ja' => 'ペン', 'ko' => '펜', 'tr' => 'kalem', 'ru' => 'ручка', 'ar' => 'قلم', 'az' => 'qələm'],
        'bolígrafos' => ['en' => 'pens', 'de' => 'Kugelschreiber', 'fr' => 'stylos', 'ja' => 'ペン', 'ko' => '펜들', 'tr' => 'kalemler', 'ru' => 'ручки', 'ar' => 'أقلام', 'az' => 'qələmlər'],
        'bonito' => ['en' => 'pretty', 'de' => 'hübsch', 'fr' => 'joli', 'ja' => 'かわいい', 'ko' => '예쁜', 'tr' => 'güzel', 'ru' => 'красивый', 'ar' => 'جميل', 'az' => 'gözəl'],
        'botella' => ['en' => 'bottle', 'de' => 'Flasche', 'fr' => 'bouteille', 'ja' => 'ボトル', 'ko' => '병', 'tr' => 'şişe', 'ru' => 'бутылка', 'ar' => 'زجاجة', 'az' => 'şüşə'],
        'botellas' => ['en' => 'bottle', 'de' => 'Flasche', 'fr' => 'bouteille', 'ja' => 'ボトル', 'ko' => '병', 'tr' => 'şişe', 'ru' => 'бутылка', 'ar' => 'زجاجة', 'az' => 'şüşə'],
        'buen' => ['en' => 'good', 'de' => 'gut', 'fr' => 'bon', 'ja' => '良い', 'ko' => '좋은', 'tr' => 'iyi', 'ru' => 'хороший', 'ar' => 'جيد', 'az' => 'yaxşı'],
        'buena' => ['en' => 'good', 'de' => 'gut', 'fr' => 'bon', 'ja' => '良い', 'ko' => '좋은', 'tr' => 'iyi', 'ru' => 'хороший', 'ar' => 'جيد', 'az' => 'yaxşı'],
        'bueno' => ['en' => 'good', 'de' => 'gut', 'fr' => 'bon', 'ja' => '良い', 'ko' => '좋은', 'tr' => 'iyi', 'ru' => 'хороший', 'ar' => 'جيد', 'az' => 'yaxşı'],
        'buscar' => ['en' => 'to look for', 'de' => 'suchen', 'fr' => 'chercher', 'ja' => '探す', 'ko' => '찾다', 'tr' => 'aramak', 'ru' => 'искать', 'ar' => 'البحث', 'az' => 'axtarmaq'],
        'cada' => ['en' => 'each', 'de' => 'jeder', 'fr' => 'chaque', 'ja' => 'それぞれの', 'ko' => '각각의', 'tr' => 'her', 'ru' => 'каждый', 'ar' => 'كل', 'az' => 'hər biri'],
        'café' => ['en' => 'coffee', 'de' => 'Kaffee', 'fr' => 'café', 'ja' => 'コーヒー', 'ko' => '커피', 'tr' => 'kahve', 'ru' => 'кофе', 'ar' => 'قهوة', 'az' => 'qəhvə'],
        'caja' => ['en' => 'checkout', 'de' => 'Kasse', 'fr' => 'caisse', 'ja' => 'レジ', 'ko' => '계산대', 'tr' => 'kasa', 'ru' => 'касса', 'ar' => 'صندوق الدفع', 'az' => 'kassa'],
        'cajero' => ['en' => 'cashier', 'de' => 'Kassierer', 'fr' => 'caissier', 'ja' => 'レジ係', 'ko' => '계산원', 'tr' => 'kasiyer', 'ru' => 'кассир', 'ar' => 'أمين الصندوق', 'az' => 'kassir'],
        'calendario' => ['en' => 'calendar', 'de' => 'Kalender', 'fr' => 'calendrier', 'ja' => 'カレンダー', 'ko' => '달력', 'tr' => 'takvim', 'ru' => 'календарь', 'ar' => 'تقويم', 'az' => 'təqvim'],
        'caliente' => ['en' => 'hot', 'de' => 'heiß', 'fr' => 'chaud', 'ja' => '熱い', 'ko' => '뜨거운', 'tr' => 'sıcak', 'ru' => 'горячий', 'ar' => 'ساخن', 'az' => 'isti'],
        'calle' => ['en' => 'street', 'de' => 'Straße', 'fr' => 'rue', 'ja' => '通り', 'ko' => '거리', 'tr' => 'cadde', 'ru' => 'улица', 'ar' => 'شارع', 'az' => 'küçə'],
        'camarero' => ['en' => 'waiter', 'de' => 'Kellner', 'fr' => 'serveur', 'ja' => 'ウェイター', 'ko' => '웨이터', 'tr' => 'garson', 'ru' => 'официант', 'ar' => 'نادل', 'az' => 'ofisiant'],
        'cambio' => ['en' => 'change', 'de' => 'Wechselgeld', 'fr' => 'monnaie', 'ja' => 'おつり', 'ko' => '거스름돈', 'tr' => 'para üstü', 'ru' => 'сдача', 'ar' => 'الباقي', 'az' => 'qalıq'],
        'camina' => ['en' => 'walk', 'de' => 'geht', 'fr' => 'marche', 'ja' => '歩く', 'ko' => '걷다', 'tr' => 'yürü', 'ru' => 'гуляю', 'ar' => 'أتمشى', 'az' => 'gəzirəm'],
        'caminar' => ['en' => 'walk', 'de' => 'gehen', 'fr' => 'marcher', 'ja' => '歩く', 'ko' => '걷다', 'tr' => 'yürü', 'ru' => 'гуляю', 'ar' => 'أتمشى', 'az' => 'gəzirəm'],
        'camino' => ['en' => 'walk', 'de' => 'gehe', 'fr' => 'marche', 'ja' => '歩く', 'ko' => '걷다', 'tr' => 'yürü', 'ru' => 'гуляю', 'ar' => 'أتمشى', 'az' => 'gəzirəm'],
        'cancelar' => ['en' => 'to cancel', 'de' => 'stornieren', 'fr' => 'annuler', 'ja' => 'キャンセルする', 'ko' => '취소하다', 'tr' => 'iptal etmek', 'ru' => 'отменить', 'ar' => 'الإلغاء', 'az' => 'ləğv etmək'],
        'cansado' => ['en' => 'tired', 'de' => 'müde', 'fr' => 'fatigué', 'ja' => '疲れた', 'ko' => '피곤한', 'tr' => 'yorgun', 'ru' => 'усталый', 'ar' => 'متعب', 'az' => 'yorğun'],
        'carne' => ['en' => 'meat', 'de' => 'Fleisch', 'fr' => 'viande', 'ja' => '肉', 'ko' => '고기', 'tr' => 'et', 'ru' => 'мясо', 'ar' => 'لحم', 'az' => 'ət'],
        'caro' => ['en' => 'expensive', 'de' => 'teuer', 'fr' => 'cher', 'ja' => '高い', 'ko' => '비싼', 'tr' => 'pahalı', 'ru' => 'дорогой', 'ar' => 'غالي', 'az' => 'bahalı'],
        'carrito' => ['en' => 'trolley', 'de' => 'Einkaufswagen', 'fr' => 'chariot', 'ja' => 'カート', 'ko' => '카트', 'tr' => 'araba', 'ru' => 'тележка', 'ar' => 'عربة', 'az' => 'araba'],
        'casa' => ['en' => 'house', 'de' => 'Haus', 'fr' => 'maison', 'ja' => '家', 'ko' => '집', 'tr' => 'ev', 'ru' => 'дом', 'ar' => 'بيت', 'az' => 'ev'],
        'cebolla' => ['en' => 'onion', 'de' => 'Zwiebel', 'fr' => 'oignon', 'ja' => '玉ねぎ', 'ko' => '양파', 'tr' => 'soğan', 'ru' => 'лук', 'ar' => 'بصل', 'az' => 'soğan'],
        'cerca' => ['en' => 'near', 'de' => 'nah', 'fr' => 'près', 'ja' => '近く', 'ko' => '가까이', 'tr' => 'yakın', 'ru' => 'близко', 'ar' => 'قريب', 'az' => 'yaxın'],
        'cerrada' => ['en' => 'closed', 'de' => 'geschlossen', 'fr' => 'fermé', 'ja' => '閉じた', 'ko' => '닫힌', 'tr' => 'kapalı', 'ru' => 'закрыто', 'ar' => 'مغلق', 'az' => 'bağlı'],
        'cerrado' => ['en' => 'closed', 'de' => 'geschlossen', 'fr' => 'fermé', 'ja' => '閉じた', 'ko' => '닫힌', 'tr' => 'kapalı', 'ru' => 'закрыто', 'ar' => 'مغلق', 'az' => 'bağlı'],
        'cerveza' => ['en' => 'beer', 'de' => 'Bier', 'fr' => 'bière', 'ja' => 'ビール', 'ko' => '맥주', 'tr' => 'bira', 'ru' => 'пиво', 'ar' => 'بيرة', 'az' => 'pivə'],
        'cesta' => ['en' => 'basket', 'de' => 'Korb', 'fr' => 'panier', 'ja' => 'かご', 'ko' => '바구니', 'tr' => 'sepet', 'ru' => 'корзина', 'ar' => 'سلة', 'az' => 'səbət'],
        'chocolate' => ['en' => 'chocolate', 'de' => 'Schokolade', 'fr' => 'chocolat', 'ja' => 'チョコレート', 'ko' => '초콜릿', 'tr' => 'çikolata', 'ru' => 'шоколад', 'ar' => 'شوكولاتة', 'az' => 'şokolad'],
        'cielo' => ['en' => 'sky', 'de' => 'Himmel', 'fr' => 'ciel', 'ja' => '空', 'ko' => '하늘', 'tr' => 'gökyüzü', 'ru' => 'небо', 'ar' => 'سماء', 'az' => 'göy'],
        'cinco' => ['en' => 'five', 'de' => 'fünf', 'fr' => 'cinq', 'ja' => '五', 'ko' => '다섯', 'tr' => 'beş', 'ru' => 'пять', 'ar' => 'خمسة', 'az' => 'beş'],
        'ciudad' => ['en' => 'town', 'de' => 'Stadt', 'fr' => 'ville', 'ja' => '町', 'ko' => '도시', 'tr' => 'şehir', 'ru' => 'город', 'ar' => 'بلدة', 'az' => 'qəsəbə'],
        'cocina' => ['en' => 'kitchen', 'de' => 'Küche', 'fr' => 'cuisine', 'ja' => '厨房', 'ko' => '주방', 'tr' => 'mutfak', 'ru' => 'кухня', 'ar' => 'مطبخ', 'az' => 'mətbəx'],
        'cola' => ['en' => 'queue', 'de' => 'Schlange', 'fr' => 'file', 'ja' => '列', 'ko' => '줄', 'tr' => 'sıra', 'ru' => 'очередь', 'ar' => 'طابور', 'az' => 'növbə'],
        'come' => ['en' => 'eat', 'de' => 'isst', 'fr' => 'mange', 'ja' => '食べる', 'ko' => '먹다', 'tr' => 'ye', 'ru' => 'ем', 'ar' => 'آكل', 'az' => 'yeyirəm'],
        'comer' => ['en' => 'eat', 'de' => 'essen', 'fr' => 'manger', 'ja' => '食べる', 'ko' => '먹다', 'tr' => 'ye', 'ru' => 'ем', 'ar' => 'آكل', 'az' => 'yeyirəm'],
        'como' => ['en' => 'like', 'de' => 'wie', 'fr' => 'comme', 'ja' => 'のように', 'ko' => '처럼', 'tr' => 'gibi', 'ru' => 'нравится', 'ar' => 'يعجبني', 'az' => 'xoşuma gəlir'],
        'comparar' => ['en' => 'to compare', 'de' => 'vergleichen', 'fr' => 'comparer', 'ja' => '比べる', 'ko' => '비교하다', 'tr' => 'karşılaştırmak', 'ru' => 'сравнить', 'ar' => 'المقارنة', 'az' => 'müqayisə etmək'],
        'compartir' => ['en' => 'to share', 'de' => 'teilen', 'fr' => 'partager', 'ja' => '分ける', 'ko' => '나누다', 'tr' => 'paylaşmak', 'ru' => 'разделить', 'ar' => 'المشاركة', 'az' => 'bölüşmək'],
        'comprar' => ['en' => 'to buy', 'de' => 'kaufen', 'fr' => 'acheter', 'ja' => '買う', 'ko' => '사다', 'tr' => 'almak', 'ru' => 'купить', 'ar' => 'الشراء', 'az' => 'almaq'],
        'comí' => ['en' => 'I ate', 'de' => 'ich aß', 'fr' => 'j\'ai mangé', 'ja' => '私は食べた', 'ko' => '나는 먹었다', 'tr' => 'yedim', 'ru' => 'я ел', 'ar' => 'أكلت', 'az' => 'yedim'],
        'con' => ['en' => 'with', 'de' => 'mit', 'fr' => 'avec', 'ja' => 'と一緒に', 'ko' => '와 함께', 'tr' => 'ile', 'ru' => 'с', 'ar' => 'مع', 'az' => 'ilə'],
        'confirmar' => ['en' => 'to confirm', 'de' => 'bestätigen', 'fr' => 'confirmer', 'ja' => '確認する', 'ko' => '확인하다', 'tr' => 'onaylamak', 'ru' => 'подтвердить', 'ar' => 'التأكيد', 'az' => 'təsdiqləmək'],
        'contenta' => ['en' => 'glad', 'de' => 'froh', 'fr' => 'content', 'ja' => '嬉しい', 'ko' => '기쁜', 'tr' => 'memnun', 'ru' => 'рада', 'ar' => 'سعيد', 'az' => 'şad'],
        'contento' => ['en' => 'glad', 'de' => 'froh', 'fr' => 'content', 'ja' => '嬉しい', 'ko' => '기쁜', 'tr' => 'memnun', 'ru' => 'рада', 'ar' => 'سعيد', 'az' => 'şad'],
        'contiene' => ['en' => 'contains', 'de' => 'enthält', 'fr' => 'contient', 'ja' => '含む', 'ko' => '들어있다', 'tr' => 'içerir', 'ru' => 'содержит', 'ar' => 'يحتوي', 'az' => 'tərkibində var'],
        'continuar' => ['en' => 'continue', 'de' => 'weitergehen', 'fr' => 'continuer', 'ja' => '続ける', 'ko' => '계속하다', 'tr' => 'devam et', 'ru' => 'продолжай', 'ar' => 'تابع', 'az' => 'davam et'],
        'continúa' => ['en' => 'continue', 'de' => 'weitergehen', 'fr' => 'continue', 'ja' => '続ける', 'ko' => '계속하다', 'tr' => 'devam et', 'ru' => 'продолжай', 'ar' => 'تابع', 'az' => 'davam et'],
        'creo' => ['en' => 'I think', 'de' => 'ich denke', 'fr' => 'je pense', 'ja' => '私は思う', 'ko' => '나는 생각한다', 'tr' => 'düşünüyorum', 'ru' => 'я думаю', 'ar' => 'أفكر', 'az' => 'düşünürəm'],
        'creo que' => ['en' => 'I believe', 'de' => 'ich glaube', 'fr' => 'je crois', 'ja' => '私は信じる', 'ko' => '나는 믿는다', 'tr' => 'bence', 'ru' => 'я думаю', 'ar' => 'أعتقد', 'az' => 'inanıram'],
        'cruza' => ['en' => 'cross', 'de' => 'überqueren', 'fr' => 'traverse', 'ja' => '渡る', 'ko' => '건너다', 'tr' => 'geç', 'ru' => 'перейди', 'ar' => 'اعبر', 'az' => 'keç'],
        'cruzar' => ['en' => 'cross', 'de' => 'überqueren', 'fr' => 'traverser', 'ja' => '渡る', 'ko' => '건너다', 'tr' => 'geç', 'ru' => 'перейди', 'ar' => 'اعبر', 'az' => 'keç'],
        'cuatro' => ['en' => 'four', 'de' => 'vier', 'fr' => 'quatre', 'ja' => '四', 'ko' => '넷', 'tr' => 'dört', 'ru' => 'четыре', 'ar' => 'أربعة', 'az' => 'dörd'],
        'cuchara' => ['en' => 'spoon', 'de' => 'Löffel', 'fr' => 'cuillère', 'ja' => 'スプーン', 'ko' => '숟가락', 'tr' => 'kaşık', 'ru' => 'ложка', 'ar' => 'ملعقة', 'az' => 'qaşıq'],
        'cuchillo' => ['en' => 'knife', 'de' => 'Messer', 'fr' => 'couteau', 'ja' => 'ナイフ', 'ko' => '나이프', 'tr' => 'bıçak', 'ru' => 'нож', 'ar' => 'سكين', 'az' => 'bıçaq'],
        'cuenta' => ['en' => 'bill', 'de' => 'Rechnung', 'fr' => 'addition', 'ja' => '会計', 'ko' => '계산서', 'tr' => 'hesap', 'ru' => 'счёт', 'ar' => 'الحساب', 'az' => 'hesab'],
        'cuesta' => ['en' => 'costs', 'de' => 'kostet', 'fr' => 'coûte', 'ja' => 'かかる', 'ko' => '입니다', 'tr' => 'tutar', 'ru' => 'стоит', 'ar' => 'يكلف', 'az' => 'qiyməti'],
        'cuál' => ['en' => 'which', 'de' => 'welcher', 'fr' => 'quel', 'ja' => 'どれ', 'ko' => '어느', 'tr' => 'hangi', 'ru' => 'какой', 'ar' => 'أي', 'az' => 'hansı'],
        'cuándo' => ['en' => 'when', 'de' => 'wann', 'fr' => 'quand', 'ja' => 'いつ', 'ko' => '언제', 'tr' => 'ne zaman', 'ru' => 'когда', 'ar' => 'متى', 'az' => 'nə vaxt'],
        'cuánto' => ['en' => 'how much', 'de' => 'wie viel', 'fr' => 'combien', 'ja' => 'いくら', 'ko' => '얼마', 'tr' => 'kaç para', 'ru' => 'сколько', 'ar' => 'كم', 'az' => 'neçəyə'],
        'cuántos' => ['en' => 'how many', 'de' => 'wie viele', 'fr' => 'combien', 'ja' => 'いくつ', 'ko' => '몇 개', 'tr' => 'kaç', 'ru' => 'сколько', 'ar' => 'كم', 'az' => 'neçə'],
        'cálido' => ['en' => 'warm', 'de' => 'warm', 'fr' => 'doux', 'ja' => '暖かい', 'ko' => '따뜻한', 'tr' => 'sıcak', 'ru' => 'тёплый', 'ar' => 'دافئ', 'az' => 'isti'],
        'cómo' => ['en' => 'how', 'de' => 'wie', 'fr' => 'comment', 'ja' => 'どう', 'ko' => '어떻게', 'tr' => 'nasıl', 'ru' => 'как', 'ar' => 'كيف', 'az' => 'necə'],
        'cómo estás' => ['en' => 'how are you', 'de' => 'wie geht es dir', 'fr' => 'comment ça va', 'ja' => 'お元気ですか', 'ko' => '어떻게 지내세요', 'tr' => 'nasılsın', 'ru' => 'как дела', 'ar' => 'كيف حالك', 'az' => 'necəsən'],
        'de' => ['en' => 'of', 'de' => 'von', 'fr' => 'de', 'ja' => 'の', 'ko' => '의', 'tr' => 'in', 'ru' => 'из', 'ar' => 'من', 'az' => 'ın'],
        'de verdad' => ['en' => 'really', 'de' => 'wirklich', 'fr' => 'vraiment', 'ja' => '本当に', 'ko' => '정말', 'tr' => 'gerçekten', 'ru' => 'действительно', 'ar' => 'حقا', 'az' => 'həqiqətən'],
        'debajo' => ['en' => 'under', 'de' => 'unter', 'fr' => 'sous', 'ja' => 'の下に', 'ko' => '아래에', 'tr' => 'altında', 'ru' => 'под', 'ar' => 'تحت', 'az' => 'altında'],
        'del' => ['en' => 'of the', 'de' => 'vom', 'fr' => 'du', 'ja' => 'の', 'ko' => '의', 'tr' => 'in', 'ru' => 'из', 'ar' => 'من', 'az' => 'ın'],
        'delante' => ['en' => 'in front', 'de' => 'vorne', 'fr' => 'devant', 'ja' => '前に', 'ko' => '앞에', 'tr' => 'önde', 'ru' => 'впереди', 'ar' => 'أمام', 'az' => 'qarşıda'],
        'delicioso' => ['en' => 'delicious', 'de' => 'köstlich', 'fr' => 'délicieux', 'ja' => 'おいしい', 'ko' => '맛있는', 'tr' => 'lezzetli', 'ru' => 'вкусный', 'ar' => 'لذيذ', 'az' => 'dadlı'],
        'demasiado' => ['en' => 'too much', 'de' => 'zu viel', 'fr' => 'trop', 'ja' => 'すぎます', 'ko' => '너무', 'tr' => 'çok fazla', 'ru' => 'слишком много', 'ar' => 'كثير جدا', 'az' => 'çox artıq'],
        'deme' => ['en' => 'give me', 'de' => 'geben Sie mir', 'fr' => 'donnez-moi', 'ja' => 'ください', 'ko' => '주세요', 'tr' => 'bana ver', 'ru' => 'дайте мне', 'ar' => 'أعطني', 'az' => 'mənə ver'],
        'derecha' => ['en' => 'right', 'de' => 'rechts', 'fr' => 'droite', 'ja' => '右', 'ko' => '오른쪽', 'tr' => 'sağ', 'ru' => 'правый', 'ar' => 'يمين', 'az' => 'sağ'],
        'descuento' => ['en' => 'discount', 'de' => 'Rabatt', 'fr' => 'réduction', 'ja' => '割引', 'ko' => '할인', 'tr' => 'indirim', 'ru' => 'скидка', 'ar' => 'خصم', 'az' => 'endirim'],
        'despacio' => ['en' => 'slowly', 'de' => 'langsam', 'fr' => 'lentement', 'ja' => 'ゆっくり', 'ko' => '천천히', 'tr' => 'yavaş', 'ru' => 'медленно', 'ar' => 'ببطء', 'az' => 'yavaş'],
        'después' => ['en' => 'after', 'de' => 'nach', 'fr' => 'après', 'ja' => '後に', 'ko' => '후에', 'tr' => 'sonra', 'ru' => 'после', 'ar' => 'بعد', 'az' => 'sonra'],
        'detrás' => ['en' => 'behind', 'de' => 'hinten', 'fr' => 'derrière', 'ja' => '後ろに', 'ko' => '뒤에', 'tr' => 'arkasında', 'ru' => 'сзади', 'ar' => 'خلف', 'az' => 'arxada'],
        'devolver la llamada' => ['en' => 'call back', 'de' => 'zurückrufen', 'fr' => 'rappeler', 'ja' => '折り返す', 'ko' => '다시 전화하다', 'tr' => 'tekrar ara', 'ru' => 'перезвони', 'ar' => 'عاود الاتصال', 'az' => 'geri zəng et'],
        'devuelve' => ['en' => 'return', 'de' => 'zurückrufen', 'fr' => 'rappelle', 'ja' => '折り返す', 'ko' => '돌려주다', 'tr' => 'geri dön', 'ru' => 'вернуться', 'ar' => 'يعود', 'az' => 'qayıt'],
        'dieta' => ['en' => 'diet', 'de' => 'Diät', 'fr' => 'régime', 'ja' => '食事制限', 'ko' => '식단', 'tr' => 'beslenme', 'ru' => 'диета', 'ar' => 'حمية', 'az' => 'pəhriz'],
        'diez' => ['en' => 'ten', 'de' => 'zehn', 'fr' => 'dix', 'ja' => '十', 'ko' => '열', 'tr' => 'on', 'ru' => 'десять', 'ar' => 'عشرة', 'az' => 'on'],
        'difícil' => ['en' => 'hard', 'de' => 'schwer', 'fr' => 'difficile', 'ja' => '難しい', 'ko' => '어려운', 'tr' => 'zor', 'ru' => 'трудно', 'ar' => 'صعب', 'az' => 'çətin'],
        'dinero' => ['en' => 'money', 'de' => 'Geld', 'fr' => 'argent', 'ja' => 'お金', 'ko' => '돈', 'tr' => 'para', 'ru' => 'деньги', 'ar' => 'نقود', 'az' => 'pul'],
        'disculpe' => ['en' => 'excuse me', 'de' => 'entschuldigen Sie', 'fr' => 'excusez-moi', 'ja' => 'すみません', 'ko' => '실례합니다', 'tr' => 'affedersiniz', 'ru' => 'извините', 'ar' => 'عفوا', 'az' => 'bağışlayın'],
        'dormir' => ['en' => 'sleep', 'de' => 'schlafen', 'fr' => 'dormir', 'ja' => '眠る', 'ko' => '자다', 'tr' => 'uyu', 'ru' => 'сплю', 'ar' => 'أنام', 'az' => 'yatıram'],
        'dos' => ['en' => 'two', 'de' => 'zwei', 'fr' => 'deux', 'ja' => '二', 'ko' => '둘', 'tr' => 'iki', 'ru' => 'два', 'ar' => 'اثنان', 'az' => 'iki'],
        'dos libros' => ['en' => 'two books', 'de' => 'zwei Bücher', 'fr' => 'deux livres', 'ja' => '二冊の本', 'ko' => '책 두 권', 'tr' => 'iki kitap', 'ru' => 'два книги', 'ar' => 'اثنان كتب', 'az' => 'iki kitablar'],
        'duerme' => ['en' => 'sleep', 'de' => 'schläft', 'fr' => 'dort', 'ja' => '眠る', 'ko' => '자다', 'tr' => 'uyu', 'ru' => 'сплю', 'ar' => 'أنام', 'az' => 'yatıram'],
        'duermo' => ['en' => 'sleep', 'de' => 'schlafe', 'fr' => 'dors', 'ja' => '眠る', 'ko' => '자다', 'tr' => 'uyu', 'ru' => 'сплю', 'ar' => 'أنام', 'az' => 'yatıram'],
        'dulce' => ['en' => 'sweet', 'de' => 'süß', 'fr' => 'sucré', 'ja' => '甘い', 'ko' => '단', 'tr' => 'tatlı', 'ru' => 'сладкий', 'ar' => 'حلو', 'az' => 'şirin'],
        'dura' => ['en' => 'hard', 'de' => 'hart', 'fr' => 'dur', 'ja' => '硬い', 'ko' => '단단한', 'tr' => 'zor', 'ru' => 'трудно', 'ar' => 'صعب', 'az' => 'çətin'],
        'día' => ['en' => 'day', 'de' => 'Tag', 'fr' => 'jour', 'ja' => '日', 'ko' => '날', 'tr' => 'gün', 'ru' => 'день', 'ar' => 'يوم', 'az' => 'gün'],
        'dólares' => ['en' => 'dollars', 'de' => 'Dollar', 'fr' => 'dollars', 'ja' => 'ドル', 'ko' => '달러', 'tr' => 'dolar', 'ru' => 'долларов', 'ar' => 'دولارات', 'az' => 'dollar'],
        'dónde' => ['en' => 'where', 'de' => 'wo', 'fr' => 'où', 'ja' => 'どこ', 'ko' => '어디', 'tr' => 'nerede', 'ru' => 'где', 'ar' => 'أين', 'az' => 'harada'],
        'dónde está' => ['en' => 'where is', 'de' => 'wo ist', 'fr' => 'où est', 'ja' => 'どこですか', 'ko' => '어디입니까', 'tr' => 'nerede', 'ru' => 'где', 'ar' => 'أين', 'az' => 'harada'],
        'e' => ['en' => 'and', 'de' => 'und', 'fr' => 'et', 'ja' => 'と', 'ko' => '그리고', 'tr' => 've', 'ru' => 'и', 'ar' => 'و', 'az' => 'və'],
        'edad' => ['en' => 'age', 'de' => 'Alter', 'fr' => 'âge', 'ja' => '年齢', 'ko' => '나이', 'tr' => 'yaş', 'ru' => 'возраст', 'ar' => 'عمر', 'az' => 'yaş'],
        'efectivo' => ['en' => 'cash', 'de' => 'bar', 'fr' => 'espèces', 'ja' => '現金', 'ko' => '현금', 'tr' => 'nakit', 'ru' => 'наличные', 'ar' => 'كاش', 'az' => 'nağd'],
        'el' => ['en' => 'the', 'de' => 'der', 'fr' => 'le', 'ja' => 'その', 'ko' => '그', 'tr' => 'o', 'ru' => 'этот', 'ar' => 'هذا', 'az' => 'həmin'],
        'elegir' => ['en' => 'to choose', 'de' => 'wählen', 'fr' => 'choisir', 'ja' => '選ぶ', 'ko' => '고르다', 'tr' => 'seçmek', 'ru' => 'выбрать', 'ar' => 'الاختيار', 'az' => 'seçmək'],
        'ella' => ['en' => 'she', 'de' => 'sie', 'fr' => 'elle', 'ja' => '彼女', 'ko' => '그녀', 'tr' => 'o', 'ru' => 'она', 'ar' => 'هي', 'az' => 'o qadın'],
        'ella es' => ['en' => 'she is', 'de' => 'sie ist', 'fr' => 'elle est', 'ja' => '彼女は', 'ko' => '그녀는', 'tr' => 'o', 'ru' => 'она', 'ar' => 'هي', 'az' => 'o qadın'],
        'en' => ['en' => 'in', 'de' => 'in', 'fr' => 'dans', 'ja' => 'の中に', 'ko' => '안에', 'tr' => 'içinde', 'ru' => 'в', 'ar' => 'في', 'az' => 'içində'],
        'en efectivo' => ['en' => 'cash', 'de' => 'in bar', 'fr' => 'en espèces', 'ja' => '現金で', 'ko' => '현금으로', 'tr' => 'nakit', 'ru' => 'наличные', 'ar' => 'كاش', 'az' => 'nağd'],
        'en punto' => ['en' => 'o\'clock', 'de' => 'Uhr', 'fr' => 'heures', 'ja' => '時', 'ko' => '시', 'tr' => 'saat', 'ru' => 'часов', 'ar' => 'الساعة', 'az' => 'saat'],
        'encantado' => ['en' => 'nice to meet you', 'de' => 'freut mich', 'fr' => 'enchanté', 'ja' => 'はじめまして', 'ko' => '반갑습니다', 'tr' => 'memnun oldum', 'ru' => 'приятно познакомиться', 'ar' => 'تشرفنا', 'az' => 'tanış olmağa şadam'],
        'encontrar' => ['en' => 'to find', 'de' => 'finden', 'fr' => 'trouver', 'ja' => '見つける', 'ko' => '발견하다', 'tr' => 'bulmak', 'ru' => 'найти', 'ar' => 'العثور', 'az' => 'tapmaq'],
        'enfermo' => ['en' => 'sick', 'de' => 'krank', 'fr' => 'malade', 'ja' => '病気', 'ko' => '아픈', 'tr' => 'hasta', 'ru' => 'больной', 'ar' => 'مريض', 'az' => 'xəstə'],
        'ensalada' => ['en' => 'salad', 'de' => 'Salat', 'fr' => 'salade', 'ja' => 'サラダ', 'ko' => '샐러드', 'tr' => 'salata', 'ru' => 'салат', 'ar' => 'سلطة', 'az' => 'salat'],
        'entonces' => ['en' => 'then', 'de' => 'dann', 'fr' => 'ensuite', 'ja' => 'それから', 'ko' => '그러면', 'tr' => 'sonra', 'ru' => 'потом', 'ar' => 'ثم', 'az' => 'sonra'],
        'entrante' => ['en' => 'starter', 'de' => 'Vorspeise', 'fr' => 'entrée', 'ja' => '前菜', 'ko' => '전채', 'tr' => 'başlangıç', 'ru' => 'закуска', 'ar' => 'مقبلات', 'az' => 'qəlyanaltı'],
        'eres' => ['en' => 'you are', 'de' => 'du bist', 'fr' => 'tu es', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'sensin', 'ru' => 'ты', 'ar' => 'أنت', 'az' => 'sən'],
        'es' => ['en' => 'is', 'de' => 'ist', 'fr' => 'est', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'dır', 'ru' => 'есть', 'ar' => 'يكون', 'az' => 'olmaq'],
        'esa' => ['en' => 'it', 'de' => 'es', 'fr' => 'ce', 'ja' => 'それ', 'ko' => '그것', 'tr' => 'o', 'ru' => 'оно', 'ar' => 'هو', 'az' => 'o'],
        'escuela' => ['en' => 'school', 'de' => 'Schule', 'fr' => 'école', 'ja' => '学校', 'ko' => '학교', 'tr' => 'okul', 'ru' => 'школа', 'ar' => 'مدرسة', 'az' => 'məktəb'],
        'ese' => ['en' => 'that', 'de' => 'jener', 'fr' => 'cette', 'ja' => 'あの', 'ko' => '저', 'tr' => 'o', 'ru' => 'тот', 'ar' => 'ذلك', 'az' => 'o'],
        'eso' => ['en' => 'it', 'de' => 'es', 'fr' => 'ce', 'ja' => 'それ', 'ko' => '그것', 'tr' => 'o', 'ru' => 'оно', 'ar' => 'هو', 'az' => 'o'],
        'esos' => ['en' => 'those', 'de' => 'jene', 'fr' => 'ces', 'ja' => 'あれらの', 'ko' => '저것들', 'tr' => 'onlar', 'ru' => 'те', 'ar' => 'تلك', 'az' => 'onlar'],
        'espera' => ['en' => 'wait', 'de' => 'wartet', 'fr' => 'attends', 'ja' => '待つ', 'ko' => '기다리다', 'tr' => 'bekle', 'ru' => 'подожди', 'ar' => 'انتظر', 'az' => 'gözlə'],
        'esperar' => ['en' => 'wait', 'de' => 'warten', 'fr' => 'attendre', 'ja' => '待つ', 'ko' => '기다리다', 'tr' => 'bekle', 'ru' => 'подожди', 'ar' => 'انتظر', 'az' => 'gözlə'],
        'esta' => ['en' => 'this', 'de' => 'diese', 'fr' => 'cette', 'ja' => 'この', 'ko' => '이', 'tr' => 'bu', 'ru' => 'это', 'ar' => 'هذا', 'az' => 'bu'],
        'esta noche' => ['en' => 'tonight', 'de' => 'heute Abend', 'fr' => 'ce soir', 'ja' => '今夜', 'ko' => '오늘 밤', 'tr' => 'bu akşam', 'ru' => 'сегодня вечером', 'ar' => 'الليلة', 'az' => 'bu axşam'],
        'estaba' => ['en' => 'I was', 'de' => 'ich war', 'fr' => 'j\'étais', 'ja' => 'でした', 'ko' => '였습니다', 'tr' => 'idim', 'ru' => 'я был', 'ar' => 'كنت', 'az' => 'idim'],
        'estación' => ['en' => 'station', 'de' => 'Bahnhof', 'fr' => 'gare', 'ja' => '駅', 'ko' => '역', 'tr' => 'istasyon', 'ru' => 'станция', 'ar' => 'محطة', 'az' => 'stansiya'],
        'este' => ['en' => 'this', 'de' => 'dieser', 'fr' => 'ce', 'ja' => 'この', 'ko' => '이', 'tr' => 'bu', 'ru' => 'это', 'ar' => 'هذا', 'az' => 'bu'],
        'este es' => ['en' => 'this is', 'de' => 'das ist', 'fr' => 'c\'est', 'ja' => 'これは', 'ko' => '이분은', 'tr' => 'bu', 'ru' => 'это', 'ar' => 'هذا', 'az' => 'bu'],
        'estos' => ['en' => 'these', 'de' => 'diese', 'fr' => 'ces', 'ja' => 'これらの', 'ko' => '이것들', 'tr' => 'bunlar', 'ru' => 'эти', 'ar' => 'هذه', 'az' => 'bunlar'],
        'estoy' => ['en' => 'am', 'de' => 'bin', 'fr' => 'suis', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'im', 'ru' => 'есть', 'ar' => 'يكون', 'az' => 'olmaq'],
        'está' => ['en' => 'is', 'de' => 'ist', 'fr' => 'est', 'ja' => 'です', 'ko' => '있다', 'tr' => 'dır', 'ru' => 'есть', 'ar' => 'يكون', 'az' => 'olmaq'],
        'estás' => ['en' => 'are', 'de' => 'bist', 'fr' => 'es', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'sin', 'ru' => 'есть', 'ar' => 'يكون', 'az' => 'olmaq'],
        'evitar' => ['en' => 'to avoid', 'de' => 'vermeiden', 'fr' => 'éviter', 'ja' => '避ける', 'ko' => '피하다', 'tr' => 'kaçınmak', 'ru' => 'избегать', 'ar' => 'التجنب', 'az' => 'qaçınmaq'],
        'excelente' => ['en' => 'excellent', 'de' => 'ausgezeichnet', 'fr' => 'excellent', 'ja' => '素晴らしい', 'ko' => '훌륭한', 'tr' => 'mükemmel', 'ru' => 'отлично', 'ar' => 'ممتاز', 'az' => 'əla'],
        'falso' => ['en' => 'false', 'de' => 'falsch', 'fr' => 'faux', 'ja' => '偽', 'ko' => '거짓', 'tr' => 'yanlış', 'ru' => 'неверно', 'ar' => 'خطأ', 'az' => 'səhv'],
        'favor' => ['en' => 'please', 'de' => 'bitte', 'fr' => 'plaît', 'ja' => 'お願い', 'ko' => '부탁', 'tr' => 'lütfen', 'ru' => 'пожалуйста', 'ar' => 'من فضلك', 'az' => 'zəhmət olmasa'],
        'feliz' => ['en' => 'happy', 'de' => 'glücklich', 'fr' => 'heureux', 'ja' => '幸せ', 'ko' => '행복한', 'tr' => 'mutlu', 'ru' => 'счастливый', 'ar' => 'فرح', 'az' => 'xoşbəxt'],
        'fresa' => ['en' => 'strawberry', 'de' => 'Erdbeere', 'fr' => 'fraise', 'ja' => 'いちご', 'ko' => '딸기', 'tr' => 'çilek', 'ru' => 'клубничный', 'ar' => 'فراولة', 'az' => 'çiyələk'],
        'fresca' => ['en' => 'fresh', 'de' => 'frisch', 'fr' => 'frais', 'ja' => '新鮮', 'ko' => '신선한', 'tr' => 'taze', 'ru' => 'свежий', 'ar' => 'طازج', 'az' => 'təzə'],
        'fresco' => ['en' => 'fresh', 'de' => 'frisch', 'fr' => 'frais', 'ja' => '新鮮', 'ko' => '신선한', 'tr' => 'taze', 'ru' => 'свежий', 'ar' => 'طازج', 'az' => 'təzə'],
        'fritas' => ['en' => 'fried', 'de' => 'Pommes', 'fr' => 'frites', 'ja' => 'フライド', 'ko' => '튀김', 'tr' => 'kızarmış', 'ru' => 'жареный', 'ar' => 'مقلي', 'az' => 'qızardılmış'],
        'fruta' => ['en' => 'fruit', 'de' => 'Obst', 'fr' => 'fruit', 'ja' => '果物', 'ko' => '과일', 'tr' => 'meyve', 'ru' => 'фрукт', 'ar' => 'فاكهة', 'az' => 'meyvə'],
        'frutas' => ['en' => 'fruits', 'de' => 'Früchte', 'fr' => 'fruits', 'ja' => '果物', 'ko' => '과일', 'tr' => 'meyveler', 'ru' => 'фрукты', 'ar' => 'فواكه', 'az' => 'meyvələr'],
        'fría' => ['en' => 'cold', 'de' => 'kalt', 'fr' => 'froid', 'ja' => '冷たい', 'ko' => '차가운', 'tr' => 'soğuk', 'ru' => 'холодный', 'ar' => 'بارد', 'az' => 'soyuq'],
        'frío' => ['en' => 'cold', 'de' => 'kalt', 'fr' => 'froid', 'ja' => '冷たい', 'ko' => '차가운', 'tr' => 'soğuk', 'ru' => 'холодный', 'ar' => 'بارد', 'az' => 'soyuq'],
        'fue' => ['en' => 'it was', 'de' => 'es war', 'fr' => 'c\'était', 'ja' => 'でした', 'ko' => '였습니다', 'tr' => 'idi', 'ru' => 'было', 'ar' => 'كان', 'az' => 'idi'],
        'fácil' => ['en' => 'easy', 'de' => 'einfach', 'fr' => 'facile', 'ja' => '簡単', 'ko' => '쉬운', 'tr' => 'kolay', 'ru' => 'легко', 'ar' => 'سهل', 'az' => 'asan'],
        'gato' => ['en' => 'cat', 'de' => 'Katze', 'fr' => 'chat', 'ja' => '猫', 'ko' => '고양이', 'tr' => 'kedi', 'ru' => 'кот', 'ar' => 'قط', 'az' => 'pişik'],
        'gatos' => ['en' => 'cats', 'de' => 'Katzen', 'fr' => 'chats', 'ja' => '猫', 'ko' => '고양이들', 'tr' => 'kediler', 'ru' => 'коты', 'ar' => 'قطط', 'az' => 'pişiklər'],
        'gira' => ['en' => 'turn', 'de' => 'abbiegen', 'fr' => 'tourne', 'ja' => '曲がる', 'ko' => '돌다', 'tr' => 'dön', 'ru' => 'поворот', 'ar' => 'منعطف', 'az' => 'dönüş'],
        'girar' => ['en' => 'turn', 'de' => 'abbiegen', 'fr' => 'tourner', 'ja' => '曲がる', 'ko' => '돌다', 'tr' => 'dön', 'ru' => 'поворот', 'ar' => 'منعطف', 'az' => 'dönüş'],
        'gluten' => ['en' => 'gluten', 'de' => 'Gluten', 'fr' => 'gluten', 'ja' => 'グルテン', 'ko' => '글루텐', 'tr' => 'gluten', 'ru' => 'глютен', 'ar' => 'غلوتين', 'az' => 'qlüten'],
        'gracias' => ['en' => 'thank you', 'de' => 'danke', 'fr' => 'merci', 'ja' => 'ありがとう', 'ko' => '감사합니다', 'tr' => 'teşekkürler', 'ru' => 'спасибо', 'ar' => 'شكرا', 'az' => 'təşəkkür'],
        'gramo' => ['en' => 'gram', 'de' => 'Gramm', 'fr' => 'gramme', 'ja' => 'グラム', 'ko' => '그램', 'tr' => 'gram', 'ru' => 'грамм', 'ar' => 'غرام', 'az' => 'qram'],
        'grande' => ['en' => 'big', 'de' => 'groß', 'fr' => 'grand', 'ja' => '大きい', 'ko' => '큰', 'tr' => 'büyük', 'ru' => 'большой', 'ar' => 'كبير', 'az' => 'böyük'],
        'habla' => ['en' => 'speak', 'de' => 'spricht', 'fr' => 'parle', 'ja' => '話す', 'ko' => '말하다', 'tr' => 'konuş', 'ru' => 'говорю', 'ar' => 'أتكلم', 'az' => 'danışıram'],
        'hablar' => ['en' => 'speak', 'de' => 'sprechen', 'fr' => 'parler', 'ja' => '話す', 'ko' => '말하다', 'tr' => 'konuş', 'ru' => 'говорю', 'ar' => 'أتكلم', 'az' => 'danışıram'],
        'hambriento' => ['en' => 'hungry', 'de' => 'hungrig', 'fr' => 'affamé', 'ja' => 'お腹がすいた', 'ko' => '배고픈', 'tr' => 'aç', 'ru' => 'голодный', 'ar' => 'جائع', 'az' => 'ac'],
        'hamburguesa' => ['en' => 'burger', 'de' => 'Burger', 'fr' => 'hamburger', 'ja' => 'ハンバーガー', 'ko' => '햄버거', 'tr' => 'hamburger', 'ru' => 'бургер', 'ar' => 'برجر', 'az' => 'burger'],
        'helado' => ['en' => 'ice cream', 'de' => 'Eis', 'fr' => 'glace', 'ja' => 'アイスクリーム', 'ko' => '아이스크림', 'tr' => 'dondurma', 'ru' => 'мороженое', 'ar' => 'آيس كريم', 'az' => 'dondurma'],
        'hermana' => ['en' => 'sister', 'de' => 'Schwester', 'fr' => 'sœur', 'ja' => '姉妹', 'ko' => '자매', 'tr' => 'kız kardeş', 'ru' => 'сестра', 'ar' => 'أخت', 'az' => 'bacı'],
        'hermano' => ['en' => 'brother', 'de' => 'Bruder', 'fr' => 'frère', 'ja' => '兄弟', 'ko' => '형제', 'tr' => 'erkek kardeş', 'ru' => 'брат', 'ar' => 'أخ', 'az' => 'qardaş'],
        'hermosa' => ['en' => 'beautiful', 'de' => 'schön', 'fr' => 'beau', 'ja' => '美しい', 'ko' => '아름다운', 'tr' => 'güzel', 'ru' => 'красивый', 'ar' => 'جميل', 'az' => 'gözəl'],
        'hermoso' => ['en' => 'beautiful', 'de' => 'schön', 'fr' => 'beau', 'ja' => '美しい', 'ko' => '아름다운', 'tr' => 'güzel', 'ru' => 'красивый', 'ar' => 'جميل', 'az' => 'gözəl'],
        'hielo' => ['en' => 'ice', 'de' => 'Eiswürfel', 'fr' => 'glaçons', 'ja' => '氷', 'ko' => '얼음', 'tr' => 'buz', 'ru' => 'лёд', 'ar' => 'الثلج', 'az' => 'buz'],
        'hola' => ['en' => 'hello', 'de' => 'hallo', 'fr' => 'bonjour', 'ja' => 'こんにちは', 'ko' => '안녕하세요', 'tr' => 'merhaba', 'ru' => 'привет', 'ar' => 'مرحبا', 'az' => 'salam'],
        'hora' => ['en' => 'hour', 'de' => 'Stunde', 'fr' => 'heure', 'ja' => '時間', 'ko' => '시간', 'tr' => 'saat', 'ru' => 'час', 'ar' => 'ساعة', 'az' => 'saat'],
        'hoy' => ['en' => 'today', 'de' => 'heute', 'fr' => 'aujourd\'hui', 'ja' => '今日', 'ko' => '오늘', 'tr' => 'bugün', 'ru' => 'сегодня', 'ar' => 'اليوم', 'az' => 'bu gün'],
        'huevo' => ['en' => 'egg', 'de' => 'Ei', 'fr' => 'œuf', 'ja' => '卵', 'ko' => '계란', 'tr' => 'yumurta', 'ru' => 'яйцо', 'ar' => 'بيضة', 'az' => 'yumurta'],
        'huevos' => ['en' => 'eggs', 'de' => 'Eier', 'fr' => 'œufs', 'ja' => '卵', 'ko' => '계란', 'tr' => 'yumurta', 'ru' => 'яйца', 'ar' => 'بيض', 'az' => 'yumurtalar'],
        'ingredientes' => ['en' => 'ingredients', 'de' => 'Zutaten', 'fr' => 'ingrédients', 'ja' => '材料', 'ko' => '재료', 'tr' => 'içindekiler', 'ru' => 'ингредиенты', 'ar' => 'مكونات', 'az' => 'tərkib'],
        'invierno' => ['en' => 'winter', 'de' => 'Winter', 'fr' => 'hiver', 'ja' => '冬', 'ko' => '겨울', 'tr' => 'kış', 'ru' => 'зима', 'ar' => 'شتاء', 'az' => 'qış'],
        'ir' => ['en' => 'go', 'de' => 'gehen', 'fr' => 'aller', 'ja' => '行く', 'ko' => '가다', 'tr' => 'git', 'ru' => 'иду', 'ar' => 'أذهب', 'az' => 'gedirəm'],
        'izquierda' => ['en' => 'left', 'de' => 'links', 'fr' => 'gauche', 'ja' => '左', 'ko' => '왼쪽', 'tr' => 'sol', 'ru' => 'левый', 'ar' => 'يسار', 'az' => 'sol'],
        'juntos' => ['en' => 'together', 'de' => 'zusammen', 'fr' => 'ensemble', 'ja' => '一緒に', 'ko' => '함께', 'tr' => 'birlikte', 'ru' => 'вместе', 'ar' => 'معا', 'az' => 'birlikdə'],
        'kilo' => ['en' => 'kilo', 'de' => 'Kilo', 'fr' => 'kilo', 'ja' => 'キロ', 'ko' => '킬로', 'tr' => 'kilo', 'ru' => 'кило', 'ar' => 'كيلو', 'az' => 'kilo'],
        'la' => ['en' => 'the', 'de' => 'die', 'fr' => 'la', 'ja' => 'その', 'ko' => '그', 'tr' => 'o', 'ru' => 'этот', 'ar' => 'هذا', 'az' => 'həmin'],
        'la cuenta' => ['en' => 'the bill', 'de' => 'die Rechnung', 'fr' => 'l\'addition', 'ja' => 'お会計', 'ko' => '계산서', 'tr' => 'hesap', 'ru' => 'счёт', 'ar' => 'الحساب', 'az' => 'hesab'],
        'las' => ['en' => 'the', 'de' => 'die', 'fr' => 'les', 'ja' => 'その', 'ko' => '그', 'tr' => 'o', 'ru' => 'этот', 'ar' => 'هذا', 'az' => 'həmin'],
        'leche' => ['en' => 'milk', 'de' => 'Milch', 'fr' => 'lait', 'ja' => '牛乳', 'ko' => '우유', 'tr' => 'süt', 'ru' => 'молоко', 'ar' => 'حليب', 'az' => 'süd'],
        'leer' => ['en' => 'read', 'de' => 'lesen', 'fr' => 'lire', 'ja' => '読む', 'ko' => '읽다', 'tr' => 'oku', 'ru' => 'читаю', 'ar' => 'أقرأ', 'az' => 'oxuyuram'],
        'lejos' => ['en' => 'far', 'de' => 'weit', 'fr' => 'loin', 'ja' => '遠く', 'ko' => '멀리', 'tr' => 'uzak', 'ru' => 'далеко', 'ar' => 'بعيد', 'az' => 'uzaq'],
        'leo' => ['en' => 'read', 'de' => 'lese', 'fr' => 'lis', 'ja' => '読む', 'ko' => '읽다', 'tr' => 'oku', 'ru' => 'читаю', 'ar' => 'أقرأ', 'az' => 'oxuyuram'],
        'libre' => ['en' => 'free', 'de' => 'frei', 'fr' => 'libre', 'ja' => '暇', 'ko' => '한가한', 'tr' => 'boş', 'ru' => 'бесплатно', 'ar' => 'مجاني', 'az' => 'pulsuz'],
        'libro' => ['en' => 'book', 'de' => 'Buch', 'fr' => 'livre', 'ja' => '本', 'ko' => '책', 'tr' => 'kitap', 'ru' => 'книга', 'ar' => 'كتاب', 'az' => 'kitab'],
        'libros' => ['en' => 'books', 'de' => 'Bücher', 'fr' => 'livres', 'ja' => '本', 'ko' => '책들', 'tr' => 'kitaplar', 'ru' => 'книги', 'ar' => 'كتب', 'az' => 'kitablar'],
        'ligeras' => ['en' => 'light', 'de' => 'leicht', 'fr' => 'léger', 'ja' => '軽い', 'ko' => '가벼운', 'tr' => 'hafif', 'ru' => 'лёгкий', 'ar' => 'خفيف', 'az' => 'yüngül'],
        'ligero' => ['en' => 'light', 'de' => 'leicht', 'fr' => 'léger', 'ja' => '軽い', 'ko' => '가벼운', 'tr' => 'hafif', 'ru' => 'лёгкий', 'ar' => 'خفيف', 'az' => 'yüngül'],
        'limpio' => ['en' => 'clean', 'de' => 'sauber', 'fr' => 'propre', 'ja' => 'きれい', 'ko' => '깨끗한', 'tr' => 'temiz', 'ru' => 'чистый', 'ar' => 'نظيف', 'az' => 'təmiz'],
        'lista' => ['en' => 'list', 'de' => 'Liste', 'fr' => 'liste', 'ja' => 'リスト', 'ko' => '목록', 'tr' => 'liste', 'ru' => 'список', 'ar' => 'قائمة', 'az' => 'siyahı'],
        'listo' => ['en' => 'ready', 'de' => 'bereit', 'fr' => 'prêt', 'ja' => '準備ができた', 'ko' => '준비된', 'tr' => 'hazır', 'ru' => 'готов', 'ar' => 'جاهز', 'az' => 'hazır'],
        'litro' => ['en' => 'litre', 'de' => 'Liter', 'fr' => 'litre', 'ja' => 'リットル', 'ko' => '리터', 'tr' => 'litre', 'ru' => 'литр', 'ar' => 'لتر', 'az' => 'litr'],
        'litros' => ['en' => 'litre', 'de' => 'Liter', 'fr' => 'litre', 'ja' => 'リットル', 'ko' => '리터', 'tr' => 'litre', 'ru' => 'литр', 'ar' => 'لتر', 'az' => 'litr'],
        'llama' => ['en' => 'call', 'de' => 'ruft', 'fr' => 'appelle', 'ja' => '電話する', 'ko' => '전화하다', 'tr' => 'ara', 'ru' => 'позвони', 'ar' => 'اتصل', 'az' => 'zəng et'],
        'llamada' => ['en' => 'call', 'de' => 'Anruf', 'fr' => 'appel', 'ja' => '電話', 'ko' => '전화', 'tr' => 'ara', 'ru' => 'позвони', 'ar' => 'اتصل', 'az' => 'zəng et'],
        'llamar' => ['en' => 'call', 'de' => 'anrufen', 'fr' => 'appeler', 'ja' => '電話する', 'ko' => '전화하다', 'tr' => 'ara', 'ru' => 'позвони', 'ar' => 'اتصل', 'az' => 'zəng et'],
        'lleno' => ['en' => 'full', 'de' => 'voll', 'fr' => 'plein', 'ja' => 'いっぱい', 'ko' => '가득한', 'tr' => 'dolu', 'ru' => 'полный', 'ar' => 'ممتلئ', 'az' => 'dolu'],
        'llevar' => ['en' => 'to carry', 'de' => 'tragen', 'fr' => 'porter', 'ja' => '運ぶ', 'ko' => '나르다', 'tr' => 'taşımak', 'ru' => 'нести', 'ar' => 'الحمل', 'az' => 'daşımaq'],
        'lluvia' => ['en' => 'rain', 'de' => 'Regen', 'fr' => 'pluie', 'ja' => '雨', 'ko' => '비', 'tr' => 'yağmur', 'ru' => 'дождь', 'ar' => 'مطر', 'az' => 'yağış'],
        'llámame' => ['en' => 'call me', 'de' => 'ruf mich an', 'fr' => 'appelle-moi', 'ja' => '電話して', 'ko' => '전화해', 'tr' => 'beni ara', 'ru' => 'позвони мне', 'ar' => 'اتصل بي', 'az' => 'mənə zəng et'],
        'lo' => ['en' => 'it', 'de' => 'es', 'fr' => 'le', 'ja' => 'それ', 'ko' => '그것', 'tr' => 'o', 'ru' => 'оно', 'ar' => 'هو', 'az' => 'o'],
        'lo siento' => ['en' => 'sorry', 'de' => 'Entschuldigung', 'fr' => 'désolé', 'ja' => 'ごめんなさい', 'ko' => '죄송합니다', 'tr' => 'üzgünüm', 'ru' => 'извините', 'ar' => 'آسف', 'az' => 'bağışlayın'],
        'los' => ['en' => 'the', 'de' => 'die', 'fr' => 'les', 'ja' => 'その', 'ko' => '그', 'tr' => 'o', 'ru' => 'этот', 'ar' => 'هذا', 'az' => 'həmin'],
        'lunes' => ['en' => 'Monday', 'de' => 'Montag', 'fr' => 'lundi', 'ja' => '月曜日', 'ko' => '월요일', 'tr' => 'pazartesi', 'ru' => 'понедельник', 'ar' => 'الاثنين', 'az' => 'bazar ertəsi'],
        'madre' => ['en' => 'mother', 'de' => 'Mutter', 'fr' => 'mère', 'ja' => '母', 'ko' => '어머니', 'tr' => 'anne', 'ru' => 'мама', 'ar' => 'أم', 'az' => 'ana'],
        'mantequilla' => ['en' => 'butter', 'de' => 'Butter', 'fr' => 'beurre', 'ja' => 'バター', 'ko' => '버터', 'tr' => 'tereyağı', 'ru' => 'масло', 'ar' => 'زبدة', 'az' => 'kərə yağı'],
        'manzana' => ['en' => 'apple', 'de' => 'Apfel', 'fr' => 'pomme', 'ja' => 'りんご', 'ko' => '사과', 'tr' => 'elma', 'ru' => 'яблоко', 'ar' => 'تفاحة', 'az' => 'alma'],
        'martes' => ['en' => 'Tuesday', 'de' => 'Dienstag', 'fr' => 'mardi', 'ja' => '火曜日', 'ko' => '화요일', 'tr' => 'salı', 'ru' => 'вторник', 'ar' => 'الثلاثاء', 'az' => 'çərşənbə axşamı'],
        'mañana' => ['en' => 'morning', 'de' => 'Morgen', 'fr' => 'matin', 'ja' => '朝', 'ko' => '아침', 'tr' => 'sabah', 'ru' => 'утро', 'ar' => 'صباح', 'az' => 'səhər'],
        'me' => ['en' => 'me', 'de' => 'mich', 'fr' => 'moi', 'ja' => '私', 'ko' => '저', 'tr' => 'ben', 'ru' => 'меня', 'ar' => 'لي', 'az' => 'mənə'],
        'me siento' => ['en' => 'I feel', 'de' => 'ich fühle mich', 'fr' => 'je me sens', 'ja' => '私は感じる', 'ko' => '나는 느낍니다', 'tr' => 'hissediyorum', 'ru' => 'я чувствую', 'ar' => 'أشعر', 'az' => 'hiss edirəm'],
        'mediodía' => ['en' => 'noon', 'de' => 'Mittag', 'fr' => 'midi', 'ja' => '正午', 'ko' => '정오', 'tr' => 'öğlen', 'ru' => 'полдень', 'ar' => 'ظهرا', 'az' => 'günorta'],
        'mejor' => ['en' => 'better', 'de' => 'besser', 'fr' => 'meilleur', 'ja' => 'もっと良い', 'ko' => '더 좋은', 'tr' => 'daha iyi', 'ru' => 'лучше', 'ar' => 'أحسن', 'az' => 'daha yaxşı'],
        'menos' => ['en' => 'less', 'de' => 'weniger', 'fr' => 'moins', 'ja' => 'より少ない', 'ko' => '덜', 'tr' => 'daha az', 'ru' => 'меньше', 'ar' => 'أقل', 'az' => 'daha az'],
        'mensaje' => ['en' => 'message', 'de' => 'Nachricht', 'fr' => 'message', 'ja' => 'メッセージ', 'ko' => '메시지', 'tr' => 'mesaj', 'ru' => 'сообщение', 'ar' => 'رسالة', 'az' => 'mesaj'],
        'menú' => ['en' => 'menu', 'de' => 'Menü', 'fr' => 'menu', 'ja' => 'メニュー', 'ko' => '메뉴', 'tr' => 'menü', 'ru' => 'меню', 'ar' => 'قائمة الطعام', 'az' => 'menyu'],
        'mesa' => ['en' => 'table', 'de' => 'Tisch', 'fr' => 'table', 'ja' => 'テーブル', 'ko' => '탁자', 'tr' => 'masa', 'ru' => 'стол', 'ar' => 'طاولة', 'az' => 'masa'],
        'mi' => ['en' => 'my', 'de' => 'mein', 'fr' => 'mon', 'ja' => '私の', 'ko' => '나의', 'tr' => 'benim', 'ru' => 'мой', 'ar' => 'خاصتي', 'az' => 'mənim'],
        'minutos' => ['en' => 'minutes', 'de' => 'Minuten', 'fr' => 'minutes', 'ja' => '分', 'ko' => '분', 'tr' => 'dakika', 'ru' => 'минут', 'ar' => 'دقائق', 'az' => 'dəqiqə'],
        'mirar' => ['en' => 'watch', 'de' => 'schauen', 'fr' => 'regarder', 'ja' => '見る', 'ko' => '보다', 'tr' => 'izle', 'ru' => 'смотри', 'ar' => 'شاهد', 'az' => 'izlə'],
        'mismo' => ['en' => 'same', 'de' => 'gleich', 'fr' => 'même', 'ja' => '同じ', 'ko' => '같은', 'tr' => 'aynı', 'ru' => 'такой же', 'ar' => 'نفسه', 'az' => 'eyni'],
        'muy' => ['en' => 'very', 'de' => 'sehr', 'fr' => 'très', 'ja' => 'とても', 'ko' => '매우', 'tr' => 'çok', 'ru' => 'очень', 'ar' => 'جدا', 'az' => 'çox'],
        'más' => ['en' => 'more', 'de' => 'mehr', 'fr' => 'plus', 'ja' => 'もっと', 'ko' => '더', 'tr' => 'daha çok', 'ru' => 'больше', 'ar' => 'أكثر', 'az' => 'daha'],
        'más tarde' => ['en' => 'later', 'de' => 'später', 'fr' => 'plus tard', 'ja' => '後で', 'ko' => '나중에', 'tr' => 'sonra', 'ru' => 'позже', 'ar' => 'لاحقا', 'az' => 'sonradan'],
        'médico' => ['en' => 'doctor', 'de' => 'Arzt', 'fr' => 'médecin', 'ja' => '医者', 'ko' => '의사', 'tr' => 'doktor', 'ru' => 'врач', 'ar' => 'طبيب', 'az' => 'həkim'],
        'mí' => ['en' => 'me', 'de' => 'mich', 'fr' => 'moi', 'ja' => '私', 'ko' => '저', 'tr' => 'ben', 'ru' => 'меня', 'ar' => 'لي', 'az' => 'mənə'],
        'naranja' => ['en' => 'orange', 'de' => 'Orange', 'fr' => 'orange', 'ja' => 'オレンジ', 'ko' => '오렌지', 'tr' => 'portakal', 'ru' => 'апельсин', 'ar' => 'برتقالة', 'az' => 'portağal'],
        'nata' => ['en' => 'cream', 'de' => 'Sahne', 'fr' => 'crème', 'ja' => 'クリーム', 'ko' => '크림', 'tr' => 'krema', 'ru' => 'сливки', 'ar' => 'كريمة', 'az' => 'qaymaq'],
        'necesito' => ['en' => 'I need', 'de' => 'ich brauche', 'fr' => 'j\'ai besoin', 'ja' => '必要です', 'ko' => '필요합니다', 'tr' => 'ihtiyacım var', 'ru' => 'мне нужно', 'ar' => 'أحتاج', 'az' => 'lazımdır'],
        'negro' => ['en' => 'black', 'de' => 'schwarz', 'fr' => 'noir', 'ja' => '黒', 'ko' => '검은색', 'tr' => 'siyah', 'ru' => 'чёрный', 'ar' => 'أسود', 'az' => 'qara'],
        'nieve' => ['en' => 'snow', 'de' => 'Schnee', 'fr' => 'neige', 'ja' => '雪', 'ko' => '눈', 'tr' => 'kar', 'ru' => 'снег', 'ar' => 'ثلج', 'az' => 'qar'],
        'niño' => ['en' => 'child', 'de' => 'Kind', 'fr' => 'enfant', 'ja' => '子供', 'ko' => '아이', 'tr' => 'çocuk', 'ru' => 'ребёнок', 'ar' => 'طفل', 'az' => 'uşaq'],
        'no' => ['en' => 'no', 'de' => 'nein', 'fr' => 'non', 'ja' => 'いいえ', 'ko' => '아니요', 'tr' => 'hayır', 'ru' => 'нет', 'ar' => 'لا', 'az' => 'xeyr'],
        'noche' => ['en' => 'night', 'de' => 'Nacht', 'fr' => 'nuit', 'ja' => '夜', 'ko' => '밤', 'tr' => 'gece', 'ru' => 'ночь', 'ar' => 'ليل', 'az' => 'gecə'],
        'nombre' => ['en' => 'name', 'de' => 'Name', 'fr' => 'nom', 'ja' => '名前', 'ko' => '이름', 'tr' => 'ad', 'ru' => 'имя', 'ar' => 'اسم', 'az' => 'ad'],
        'norte' => ['en' => 'north', 'de' => 'Norden', 'fr' => 'nord', 'ja' => '北', 'ko' => '북쪽', 'tr' => 'kuzey', 'ru' => 'север', 'ar' => 'شمال', 'az' => 'şimal'],
        'nube' => ['en' => 'cloud', 'de' => 'Wolke', 'fr' => 'nuage', 'ja' => '雲', 'ko' => '구름', 'tr' => 'bulut', 'ru' => 'облако', 'ar' => 'سحابة', 'az' => 'bulud'],
        'nueces' => ['en' => 'nuts', 'de' => 'Nüsse', 'fr' => 'noix', 'ja' => 'ナッツ', 'ko' => '견과류', 'tr' => 'fındık', 'ru' => 'орехи', 'ar' => 'مكسرات', 'az' => 'qoz'],
        'nueva' => ['en' => 'new', 'de' => 'neu', 'fr' => 'nouveau', 'ja' => '新しい', 'ko' => '새로운', 'tr' => 'yeni', 'ru' => 'новый', 'ar' => 'جديد', 'az' => 'yeni'],
        'nueve' => ['en' => 'nine', 'de' => 'neun', 'fr' => 'neuf', 'ja' => '九', 'ko' => '아홉', 'tr' => 'dokuz', 'ru' => 'девять', 'ar' => 'تسعة', 'az' => 'doqquz'],
        'nuevo' => ['en' => 'new', 'de' => 'neu', 'fr' => 'nouveau', 'ja' => '新しい', 'ko' => '새로운', 'tr' => 'yeni', 'ru' => 'новый', 'ar' => 'جديد', 'az' => 'yeni'],
        'o' => ['en' => 'or', 'de' => 'oder', 'fr' => 'ou', 'ja' => 'または', 'ko' => '또는', 'tr' => 'veya', 'ru' => 'или', 'ar' => 'أو', 'az' => 'və ya'],
        'ocho' => ['en' => 'eight', 'de' => 'acht', 'fr' => 'huit', 'ja' => '八', 'ko' => '여덟', 'tr' => 'sekiz', 'ru' => 'восемь', 'ar' => 'ثمانية', 'az' => 'səkkiz'],
        'ocupada' => ['en' => 'busy', 'de' => 'beschäftigt', 'fr' => 'occupé', 'ja' => '忙しい', 'ko' => '바쁜', 'tr' => 'meşgul', 'ru' => 'занят', 'ar' => 'مشغول', 'az' => 'məşğul'],
        'ocupado' => ['en' => 'busy', 'de' => 'beschäftigt', 'fr' => 'occupé', 'ja' => '忙しい', 'ko' => '바쁜', 'tr' => 'meşgul', 'ru' => 'занят', 'ar' => 'مشغول', 'az' => 'məşğul'],
        'otoño' => ['en' => 'autumn', 'de' => 'Herbst', 'fr' => 'automne', 'ja' => '秋', 'ko' => '가을', 'tr' => 'sonbahar', 'ru' => 'осень', 'ar' => 'خريف', 'az' => 'payız'],
        'otro' => ['en' => 'another', 'de' => 'noch ein', 'fr' => 'encore', 'ja' => 'もう一つの', 'ko' => '하나 더', 'tr' => 'başka', 'ru' => 'другой', 'ar' => 'آخر', 'az' => 'başqa'],
        'padre' => ['en' => 'father', 'de' => 'Vater', 'fr' => 'père', 'ja' => '父', 'ko' => '아버지', 'tr' => 'baba', 'ru' => 'папа', 'ar' => 'أب', 'az' => 'ata'],
        'pagar' => ['en' => 'pay', 'de' => 'bezahlen', 'fr' => 'payer', 'ja' => '払う', 'ko' => '지불하다', 'tr' => 'öde', 'ru' => 'плати', 'ar' => 'ادفع', 'az' => 'ödə'],
        'pago' => ['en' => 'I pay', 'de' => 'ich bezahle', 'fr' => 'je paie', 'ja' => '私が払う', 'ko' => '제가 냅니다', 'tr' => 'ödüyorum', 'ru' => 'я плачу', 'ar' => 'أدفع', 'az' => 'ödəyirəm'],
        'pan' => ['en' => 'bread', 'de' => 'Brot', 'fr' => 'pain', 'ja' => 'パン', 'ko' => '빵', 'tr' => 'ekmek', 'ru' => 'хлеб', 'ar' => 'خبز', 'az' => 'çörək'],
        'panadería' => ['en' => 'bakery', 'de' => 'Bäckerei', 'fr' => 'boulangerie', 'ja' => 'パン屋', 'ko' => '빵집', 'tr' => 'fırın', 'ru' => 'пекарня', 'ar' => 'مخبز', 'az' => 'çörəkxana'],
        'para' => ['en' => 'for', 'de' => 'für', 'fr' => 'pour', 'ja' => 'のために', 'ko' => '위해', 'tr' => 'için', 'ru' => 'для', 'ar' => 'لأجل', 'az' => 'üçün'],
        'para llevar' => ['en' => 'takeaway', 'de' => 'zum Mitnehmen', 'fr' => 'à emporter', 'ja' => '持ち帰り', 'ko' => '포장', 'tr' => 'paket', 'ru' => 'с собой', 'ar' => 'للخارج', 'az' => 'özümlə'],
        'para tomar aquí' => ['en' => 'eat in', 'de' => 'zum Hieressen', 'fr' => 'sur place', 'ja' => '店内で', 'ko' => '매장에서', 'tr' => 'burada ye', 'ru' => 'ем в', 'ar' => 'آكل في', 'az' => 'yeyirəm içində'],
        'parque' => ['en' => 'park', 'de' => 'Park', 'fr' => 'parc', 'ja' => '公園', 'ko' => '공원', 'tr' => 'park', 'ru' => 'парк', 'ar' => 'حديقة', 'az' => 'park'],
        'pasillo' => ['en' => 'aisle', 'de' => 'Regal', 'fr' => 'rayon', 'ja' => '売り場', 'ko' => '진열대', 'tr' => 'reyon', 'ru' => 'отдел', 'ar' => 'قسم', 'az' => 'şöbə'],
        'pastel' => ['en' => 'cake', 'de' => 'Kuchen', 'fr' => 'gâteau', 'ja' => 'ケーキ', 'ko' => '케이크', 'tr' => 'pasta', 'ru' => 'торт', 'ar' => 'كعكة', 'az' => 'tort'],
        'patata' => ['en' => 'potato', 'de' => 'Kartoffel', 'fr' => 'pomme de terre', 'ja' => 'じゃがいも', 'ko' => '감자', 'tr' => 'patates', 'ru' => 'картофель', 'ar' => 'بطاطا', 'az' => 'kartof'],
        'patatas' => ['en' => 'potato', 'de' => 'Kartoffel', 'fr' => 'pomme de terre', 'ja' => 'じゃがいも', 'ko' => '감자', 'tr' => 'patates', 'ru' => 'картофель', 'ar' => 'بطاطا', 'az' => 'kartof'],
        'patatas fritas' => ['en' => 'fries', 'de' => 'Pommes', 'fr' => 'frites', 'ja' => 'フライドポテト', 'ko' => '감자튀김', 'tr' => 'patates kızartması', 'ru' => 'картошка фри', 'ar' => 'بطاطا مقلية', 'az' => 'kartof fri'],
        'pedido' => ['en' => 'order', 'de' => 'Bestellung', 'fr' => 'commande', 'ja' => '注文', 'ko' => '주문', 'tr' => 'sipariş', 'ru' => 'заказ', 'ar' => 'طلب', 'az' => 'sifariş'],
        'pedir' => ['en' => 'to order', 'de' => 'bestellen', 'fr' => 'commander', 'ja' => '注文する', 'ko' => '주문하다', 'tr' => 'sipariş vermek', 'ru' => 'заказать', 'ar' => 'الطلب', 'az' => 'sifariş vermək'],
        'película' => ['en' => 'film', 'de' => 'Film', 'fr' => 'film', 'ja' => '映画', 'ko' => '영화', 'tr' => 'film', 'ru' => 'фильм', 'ar' => 'فيلم', 'az' => 'film'],
        'peor' => ['en' => 'worse', 'de' => 'schlechter', 'fr' => 'pire', 'ja' => 'もっと悪い', 'ko' => '더 나쁜', 'tr' => 'daha kötü', 'ru' => 'хуже', 'ar' => 'أسوأ', 'az' => 'daha pis'],
        'pequeña' => ['en' => 'small', 'de' => 'klein', 'fr' => 'petit', 'ja' => '小さい', 'ko' => '작은', 'tr' => 'küçük', 'ru' => 'маленький', 'ar' => 'صغير', 'az' => 'kiçik'],
        'pequeño' => ['en' => 'small', 'de' => 'klein', 'fr' => 'petit', 'ja' => '小さい', 'ko' => '작은', 'tr' => 'küçük', 'ru' => 'маленький', 'ar' => 'صغير', 'az' => 'kiçik'],
        'perfecto' => ['en' => 'perfect', 'de' => 'perfekt', 'fr' => 'parfait', 'ja' => '完璧', 'ko' => '완벽한', 'tr' => 'mükemmel', 'ru' => 'идеально', 'ar' => 'مثالي', 'az' => 'mükəmməl'],
        'pero' => ['en' => 'but', 'de' => 'aber', 'fr' => 'mais', 'ja' => 'しかし', 'ko' => '하지만', 'tr' => 'ama', 'ru' => 'но', 'ar' => 'لكن', 'az' => 'amma'],
        'perro' => ['en' => 'dog', 'de' => 'Hund', 'fr' => 'chien', 'ja' => '犬', 'ko' => '개', 'tr' => 'köpek', 'ru' => 'собака', 'ar' => 'كلب', 'az' => 'it'],
        'perros' => ['en' => 'dogs', 'de' => 'Hunde', 'fr' => 'chiens', 'ja' => '犬', 'ko' => '개들', 'tr' => 'köpekler', 'ru' => 'собаки', 'ar' => 'كلاب', 'az' => 'itlər'],
        'personas' => ['en' => 'people', 'de' => 'Personen', 'fr' => 'personnes', 'ja' => '人', 'ko' => '명', 'tr' => 'kişi', 'ru' => 'люди', 'ar' => 'ناس', 'az' => 'insanlar'],
        'pesada' => ['en' => 'heavy', 'de' => 'schwer', 'fr' => 'lourd', 'ja' => '重い', 'ko' => '무거운', 'tr' => 'ağır', 'ru' => 'тяжёлый', 'ar' => 'ثقيل', 'az' => 'ağır'],
        'pesado' => ['en' => 'heavy', 'de' => 'schwer', 'fr' => 'lourd', 'ja' => '重い', 'ko' => '무거운', 'tr' => 'ağır', 'ru' => 'тяжёлый', 'ar' => 'ثقيل', 'az' => 'ağır'],
        'pesar' => ['en' => 'to weigh', 'de' => 'wiegen', 'fr' => 'peser', 'ja' => '量る', 'ko' => '무게를 재다', 'tr' => 'tartmak', 'ru' => 'взвесить', 'ar' => 'الوزن', 'az' => 'çəkmək'],
        'pescado' => ['en' => 'fish', 'de' => 'Fisch', 'fr' => 'poisson', 'ja' => '魚', 'ko' => '생선', 'tr' => 'balık', 'ru' => 'рыба', 'ar' => 'سمك', 'az' => 'balıq'],
        'picante' => ['en' => 'spicy', 'de' => 'scharf', 'fr' => 'épicé', 'ja' => '辛い', 'ko' => '매운', 'tr' => 'acılı', 'ru' => 'острый', 'ar' => 'حار', 'az' => 'acılı'],
        'pimienta' => ['en' => 'pepper', 'de' => 'Pfeffer', 'fr' => 'poivre', 'ja' => 'こしょう', 'ko' => '후추', 'tr' => 'biber', 'ru' => 'перец', 'ar' => 'فلفل', 'az' => 'bibər'],
        'plato' => ['en' => 'plate', 'de' => 'Teller', 'fr' => 'assiette', 'ja' => 'お皿', 'ko' => '접시', 'tr' => 'tabak', 'ru' => 'тарелка', 'ar' => 'صحن', 'az' => 'boşqab'],
        'plátano' => ['en' => 'banana', 'de' => 'Banane', 'fr' => 'banane', 'ja' => 'バナナ', 'ko' => '바나나', 'tr' => 'muz', 'ru' => 'банан', 'ar' => 'موزة', 'az' => 'banan'],
        'poco' => ['en' => 'little', 'de' => 'wenig', 'fr' => 'peu', 'ja' => '少し', 'ko' => '조금', 'tr' => 'küçük', 'ru' => 'мало', 'ar' => 'قليل', 'az' => 'az'],
        'pollo' => ['en' => 'chicken', 'de' => 'Hähnchen', 'fr' => 'poulet', 'ja' => '鶏肉', 'ko' => '닭고기', 'tr' => 'tavuk', 'ru' => 'курица', 'ar' => 'دجاج', 'az' => 'toyuq'],
        'poner' => ['en' => 'to put', 'de' => 'legen', 'fr' => 'mettre', 'ja' => '入れる', 'ko' => '넣다', 'tr' => 'koymak', 'ru' => 'положить', 'ar' => 'وضع', 'az' => 'qoymaq'],
        'por' => ['en' => 'for', 'de' => 'für', 'fr' => 'pour', 'ja' => 'のために', 'ko' => '위해', 'tr' => 'için', 'ru' => 'для', 'ar' => 'لأجل', 'az' => 'üçün'],
        'por favor' => ['en' => 'please', 'de' => 'bitte', 'fr' => 's\'il vous plaît', 'ja' => 'お願いします', 'ko' => '부탁합니다', 'tr' => 'lütfen', 'ru' => 'пожалуйста', 'ar' => 'من فضلك', 'az' => 'zəhmət olmasa'],
        'por qué' => ['en' => 'why', 'de' => 'warum', 'fr' => 'pourquoi', 'ja' => 'なぜ', 'ko' => '왜', 'tr' => 'neden', 'ru' => 'почему', 'ar' => 'لماذا', 'az' => 'niyə'],
        'por separado' => ['en' => 'separately', 'de' => 'getrennt', 'fr' => 'séparément', 'ja' => '別々に', 'ko' => '따로', 'tr' => 'ayrı', 'ru' => 'отдельно', 'ar' => 'منفصل', 'az' => 'ayrıca'],
        'por supuesto' => ['en' => 'of course', 'de' => 'natürlich', 'fr' => 'bien sûr', 'ja' => 'もちろん', 'ko' => '물론', 'tr' => 'elbette', 'ru' => 'конечно', 'ar' => 'بالطبع', 'az' => 'əlbəttə'],
        'porque' => ['en' => 'because', 'de' => 'weil', 'fr' => 'parce que', 'ja' => 'なぜなら', 'ko' => '왜냐하면', 'tr' => 'çünkü', 'ru' => 'потому что', 'ar' => 'لأن', 'az' => 'çünki'],
        'postre' => ['en' => 'dessert', 'de' => 'Nachtisch', 'fr' => 'dessert', 'ja' => 'デザート', 'ko' => '디저트', 'tr' => 'tatlı', 'ru' => 'десерт', 'ar' => 'حلوى', 'az' => 'şirniyyat'],
        'precio' => ['en' => 'price', 'de' => 'Preis', 'fr' => 'prix', 'ja' => '値段', 'ko' => '가격', 'tr' => 'fiyat', 'ru' => 'цена', 'ar' => 'سعر', 'az' => 'qiymət'],
        'precios' => ['en' => 'prices', 'de' => 'Preise', 'fr' => 'prix', 'ja' => '値段', 'ko' => '가격', 'tr' => 'fiyatlar', 'ru' => 'цены', 'ar' => 'أسعار', 'az' => 'qiymətlər'],
        'prefiero' => ['en' => 'I prefer', 'de' => 'ich bevorzuge', 'fr' => 'je préfère', 'ja' => '私は好む', 'ko' => '나는 선호한다', 'tr' => 'tercih ederim', 'ru' => 'я предпочитаю', 'ar' => 'أفضل', 'az' => 'üstünlük verirəm'],
        'primavera' => ['en' => 'spring', 'de' => 'Frühling', 'fr' => 'printemps', 'ja' => '春', 'ko' => '봄', 'tr' => 'ilkbahar', 'ru' => 'весна', 'ar' => 'ربيع', 'az' => 'yaz'],
        'problema' => ['en' => 'problem', 'de' => 'Problem', 'fr' => 'problème', 'ja' => '問題', 'ko' => '문제', 'tr' => 'sorun', 'ru' => 'проблема', 'ar' => 'مشكلة', 'az' => 'problem'],
        'producto' => ['en' => 'product', 'de' => 'Produkt', 'fr' => 'produit', 'ja' => '商品', 'ko' => '상품', 'tr' => 'ürün', 'ru' => 'продукт', 'ar' => 'منتج', 'az' => 'məhsul'],
        'profesor' => ['en' => 'teacher', 'de' => 'Lehrer', 'fr' => 'professeur', 'ja' => '先生', 'ko' => '선생님', 'tr' => 'öğretmen', 'ru' => 'учитель', 'ar' => 'معلم', 'az' => 'müəllim'],
        'pronto' => ['en' => 'soon', 'de' => 'bald', 'fr' => 'bientôt', 'ja' => 'すぐに', 'ko' => '곧', 'tr' => 'yakında', 'ru' => 'скоро', 'ar' => 'قريبا', 'az' => 'tezliklə'],
        'propina' => ['en' => 'tip', 'de' => 'Trinkgeld', 'fr' => 'pourboire', 'ja' => 'チップ', 'ko' => '팁', 'tr' => 'bahşiş', 'ru' => 'чаевые', 'ar' => 'بقشيش', 'az' => 'çaypulu'],
        'próxima' => ['en' => 'next', 'de' => 'nächste', 'fr' => 'prochain', 'ja' => '次の', 'ko' => '다음', 'tr' => 'sonraki', 'ru' => 'следующий', 'ar' => 'التالي', 'az' => 'növbəti'],
        'próximo' => ['en' => 'next', 'de' => 'nächste', 'fr' => 'prochain', 'ja' => '次の', 'ko' => '다음', 'tr' => 'sonraki', 'ru' => 'следующий', 'ar' => 'التالي', 'az' => 'növbəti'],
        'pueblo' => ['en' => 'village', 'de' => 'Dorf', 'fr' => 'village', 'ja' => '村', 'ko' => '마을', 'tr' => 'köy', 'ru' => 'деревня', 'ar' => 'قرية', 'az' => 'kənd'],
        'puede' => ['en' => 'can', 'de' => 'können', 'fr' => 'pouvez', 'ja' => 'できる', 'ko' => '할 수 있다', 'tr' => 'yapabilir', 'ru' => 'могу', 'ar' => 'أستطيع', 'az' => 'bacarıram'],
        'puede usted' => ['en' => 'can you', 'de' => 'können Sie', 'fr' => 'pouvez-vous', 'ja' => 'できますか', 'ko' => '주시겠어요', 'tr' => 'yapabilir misiniz', 'ru' => 'могу ты', 'ar' => 'أستطيع أنت', 'az' => 'bacarıram sən'],
        'puedo' => ['en' => 'I can', 'de' => 'ich kann', 'fr' => 'je peux', 'ja' => '私はできる', 'ko' => '나는 할 수 있다', 'tr' => 'yapabilirim', 'ru' => 'я могу', 'ar' => 'أنا أستطيع', 'az' => 'mən bacarıram'],
        'punto' => ['en' => 'o\'clock', 'de' => 'Uhr', 'fr' => 'heures', 'ja' => '時', 'ko' => '시', 'tr' => 'saat', 'ru' => 'часов', 'ar' => 'الساعة', 'az' => 'saat'],
        'que' => ['en' => 'than', 'de' => 'als', 'fr' => 'que', 'ja' => 'より', 'ko' => '보다', 'tr' => 'den', 'ru' => 'чем', 'ar' => 'من', 'az' => 'dan'],
        'queso' => ['en' => 'cheese', 'de' => 'Käse', 'fr' => 'fromage', 'ja' => 'チーズ', 'ko' => '치즈', 'tr' => 'peynir', 'ru' => 'сыр', 'ar' => 'جبن', 'az' => 'pendir'],
        'quiero' => ['en' => 'I want', 'de' => 'ich will', 'fr' => 'je veux', 'ja' => 'たいです', 'ko' => '나는 원한다', 'tr' => 'istiyorum', 'ru' => 'я хочу', 'ar' => 'أريد', 'az' => 'istəyirəm'],
        'quisiera' => ['en' => 'I would like', 'de' => 'ich möchte', 'fr' => 'je voudrais', 'ja' => 'ください', 'ko' => '주세요', 'tr' => 'istiyorum', 'ru' => 'я хочу', 'ar' => 'أريد', 'az' => 'istəyirəm'],
        'quizás' => ['en' => 'maybe', 'de' => 'vielleicht', 'fr' => 'peut-être', 'ja' => 'たぶん', 'ko' => '아마도', 'tr' => 'belki', 'ru' => 'может быть', 'ar' => 'ربما', 'az' => 'bəlkə'],
        'quién' => ['en' => 'who', 'de' => 'wer', 'fr' => 'qui', 'ja' => '誰', 'ko' => '누구', 'tr' => 'kim', 'ru' => 'кто', 'ar' => 'مَن', 'az' => 'kim'],
        'qué' => ['en' => 'what', 'de' => 'was', 'fr' => 'quoi', 'ja' => '何', 'ko' => '무엇', 'tr' => 'ne', 'ru' => 'что', 'ar' => 'ماذا', 'az' => 'nə'],
        'recibo' => ['en' => 'receipt', 'de' => 'Quittung', 'fr' => 'reçu', 'ja' => 'レシート', 'ko' => '영수증', 'tr' => 'fiş', 'ru' => 'чек', 'ar' => 'إيصال', 'az' => 'qəbz'],
        'recto' => ['en' => 'straight', 'de' => 'geradeaus', 'fr' => 'tout droit', 'ja' => 'まっすぐ', 'ko' => '똑바로', 'tr' => 'düz', 'ru' => 'прямо', 'ar' => 'مباشرة', 'az' => 'düz'],
        'reloj' => ['en' => 'clock', 'de' => 'Uhr', 'fr' => 'horloge', 'ja' => '時計', 'ko' => '시계', 'tr' => 'saat', 'ru' => 'часы', 'ar' => 'ساعة', 'az' => 'saat'],
        'reserva' => ['en' => 'booking', 'de' => 'Reservierung', 'fr' => 'réservation', 'ja' => '予約', 'ko' => '예약', 'tr' => 'rezervasyon', 'ru' => 'бронь', 'ar' => 'حجز', 'az' => 'rezervasiya'],
        'reservar' => ['en' => 'to book', 'de' => 'reservieren', 'fr' => 'réserver', 'ja' => '予約する', 'ko' => '예약하다', 'tr' => 'ayırtmak', 'ru' => 'в книга', 'ar' => 'إلى كتاب', 'az' => 'kitab'],
        'restaurante' => ['en' => 'restaurant', 'de' => 'Restaurant', 'fr' => 'restaurant', 'ja' => 'レストラン', 'ko' => '식당', 'tr' => 'restoran', 'ru' => 'ресторан', 'ar' => 'مطعم', 'az' => 'restoran'],
        'rojo' => ['en' => 'red', 'de' => 'rot', 'fr' => 'rouge', 'ja' => '赤', 'ko' => '빨간색', 'tr' => 'kırmızı', 'ru' => 'красный', 'ar' => 'أحمر', 'az' => 'qırmızı'],
        'rápida' => ['en' => 'fast', 'de' => 'schnell', 'fr' => 'rapide', 'ja' => '速い', 'ko' => '빠른', 'tr' => 'hızlı', 'ru' => 'быстро', 'ar' => 'بسرعة', 'az' => 'sürətli'],
        'rápido' => ['en' => 'fast', 'de' => 'schnell', 'fr' => 'rapide', 'ja' => '速い', 'ko' => '빠른', 'tr' => 'hızlı', 'ru' => 'быстро', 'ar' => 'بسرعة', 'az' => 'sürətli'],
        'sabor' => ['en' => 'taste', 'de' => 'Geschmack', 'fr' => 'goût', 'ja' => '味', 'ko' => '맛', 'tr' => 'tat', 'ru' => 'вкус', 'ar' => 'مذاق', 'az' => 'dad'],
        'sal' => ['en' => 'salt', 'de' => 'Salz', 'fr' => 'sel', 'ja' => '塩', 'ko' => '소금', 'tr' => 'tuz', 'ru' => 'соль', 'ar' => 'ملح', 'az' => 'duz'],
        'salado' => ['en' => 'salty', 'de' => 'salzig', 'fr' => 'salé', 'ja' => 'しょっぱい', 'ko' => '짠', 'tr' => 'tuzlu', 'ru' => 'солёный', 'ar' => 'مالح', 'az' => 'duzlu'],
        'sed' => ['en' => 'thirsty', 'de' => 'durstig', 'fr' => 'soif', 'ja' => 'のどが渇いた', 'ko' => '목마른', 'tr' => 'susamış', 'ru' => 'хочу пить', 'ar' => 'عطشان', 'az' => 'susuz'],
        'sediento' => ['en' => 'thirsty', 'de' => 'durstig', 'fr' => 'assoiffé', 'ja' => 'のどが渇いた', 'ko' => '목마른', 'tr' => 'susamış', 'ru' => 'хочу пить', 'ar' => 'عطشان', 'az' => 'susuz'],
        'seis' => ['en' => 'six', 'de' => 'sechs', 'fr' => 'six', 'ja' => '六', 'ko' => '여섯', 'tr' => 'altı', 'ru' => 'шесть', 'ar' => 'ستة', 'az' => 'altı'],
        'semana' => ['en' => 'week', 'de' => 'Woche', 'fr' => 'semaine', 'ja' => '週', 'ko' => '주', 'tr' => 'hafta', 'ru' => 'неделя', 'ar' => 'أسبوع', 'az' => 'həftə'],
        'separado' => ['en' => 'separately', 'de' => 'getrennt', 'fr' => 'séparément', 'ja' => '別々', 'ko' => '따로', 'tr' => 'ayrı', 'ru' => 'отдельно', 'ar' => 'منفصل', 'az' => 'ayrıca'],
        'servilleta' => ['en' => 'napkin', 'de' => 'Serviette', 'fr' => 'serviette', 'ja' => 'ナプキン', 'ko' => '냅킨', 'tr' => 'peçete', 'ru' => 'салфетка', 'ar' => 'منديل', 'az' => 'salfet'],
        'señor' => ['en' => 'sir', 'de' => 'mein Herr', 'fr' => 'monsieur', 'ja' => 'ムッシュ', 'ko' => '선생님', 'tr' => 'beyefendi', 'ru' => 'господин', 'ar' => 'سيدي', 'az' => 'cənab'],
        'señora' => ['en' => 'madam', 'de' => 'gnädige Frau', 'fr' => 'madame', 'ja' => 'マダム', 'ko' => '부인', 'tr' => 'hanımefendi', 'ru' => 'госпожа', 'ar' => 'سيدتي', 'az' => 'xanım'],
        'siento' => ['en' => 'feel', 'de' => 'fühle', 'fr' => 'sens', 'ja' => '感じる', 'ko' => '느끼다', 'tr' => 'hisset', 'ru' => 'чувствую', 'ar' => 'أشعر', 'az' => 'hiss edirəm'],
        'siete' => ['en' => 'seven', 'de' => 'sieben', 'fr' => 'sept', 'ja' => '七', 'ko' => '일곱', 'tr' => 'yedi', 'ru' => 'семь', 'ar' => 'سبعة', 'az' => 'yeddi'],
        'silla' => ['en' => 'chair', 'de' => 'Stuhl', 'fr' => 'chaise', 'ja' => '椅子', 'ko' => '의자', 'tr' => 'sandalye', 'ru' => 'стул', 'ar' => 'كرسي', 'az' => 'stul'],
        'sin' => ['en' => 'without', 'de' => 'ohne', 'fr' => 'sans', 'ja' => 'なし', 'ko' => '없이', 'tr' => 'sız', 'ru' => 'без', 'ar' => 'بدون', 'az' => 'olmadan'],
        'sitio' => ['en' => 'seat', 'de' => 'Platz', 'fr' => 'place', 'ja' => '席', 'ko' => '자리', 'tr' => 'koltuk', 'ru' => 'место', 'ar' => 'مقعد', 'az' => 'yer'],
        'sobre' => ['en' => 'on', 'de' => 'auf', 'fr' => 'sur', 'ja' => 'の上に', 'ko' => '위에', 'tr' => 'üzerinde', 'ru' => 'на', 'ar' => 'على', 'az' => 'üzərində'],
        'sobre todo' => ['en' => 'especially', 'de' => 'besonders', 'fr' => 'surtout', 'ja' => '特に', 'ko' => '특히', 'tr' => 'özellikle', 'ru' => 'особенно', 'ar' => 'خاصة', 'az' => 'xüsusilə'],
        'sol' => ['en' => 'sun', 'de' => 'Sonne', 'fr' => 'soleil', 'ja' => '太陽', 'ko' => '해', 'tr' => 'güneş', 'ru' => 'солнце', 'ar' => 'شمس', 'az' => 'günəş'],
        'son' => ['en' => 'are', 'de' => 'sind', 'fr' => 'sont', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'sin', 'ru' => 'есть', 'ar' => 'يكون', 'az' => 'olmaq'],
        'sopa' => ['en' => 'soup', 'de' => 'Suppe', 'fr' => 'soupe', 'ja' => 'スープ', 'ko' => '수프', 'tr' => 'çorba', 'ru' => 'суп', 'ar' => 'حساء', 'az' => 'şorba'],
        'soy' => ['en' => 'I am', 'de' => 'ich bin', 'fr' => 'je suis', 'ja' => 'です', 'ko' => '입니다', 'tr' => 'ben', 'ru' => 'я', 'ar' => 'أنا', 'az' => 'mən'],
        'sucio' => ['en' => 'dirty', 'de' => 'schmutzig', 'fr' => 'sale', 'ja' => '汚い', 'ko' => '더러운', 'tr' => 'kirli', 'ru' => 'грязный', 'ar' => 'متسخ', 'az' => 'çirkli'],
        'supermercado' => ['en' => 'supermarket', 'de' => 'Supermarkt', 'fr' => 'supermarché', 'ja' => 'スーパー', 'ko' => '슈퍼마켓', 'tr' => 'market', 'ru' => 'супермаркет', 'ar' => 'سوبرماركت', 'az' => 'supermarket'],
        'supuesto' => ['en' => 'course', 'de' => 'natürlich', 'fr' => 'sûr', 'ja' => 'もちろん', 'ko' => '물론', 'tr' => 'yemek', 'ru' => 'блюдо', 'ar' => 'طبق', 'az' => 'yemək'],
        'sur' => ['en' => 'south', 'de' => 'Süden', 'fr' => 'sud', 'ja' => '南', 'ko' => '남쪽', 'tr' => 'güney', 'ru' => 'юг', 'ar' => 'جنوب', 'az' => 'cənub'],
        'sándwich' => ['en' => 'sandwich', 'de' => 'Sandwich', 'fr' => 'sandwich', 'ja' => 'サンドイッチ', 'ko' => '샌드위치', 'tr' => 'sandviç', 'ru' => 'сэндвич', 'ar' => 'شطيرة', 'az' => 'sendviç'],
        'sí' => ['en' => 'yes', 'de' => 'ja', 'fr' => 'oui', 'ja' => 'はい', 'ko' => '네', 'tr' => 'evet', 'ru' => 'да', 'ar' => 'نعم', 'az' => 'bəli'],
        'también' => ['en' => 'also', 'de' => 'auch', 'fr' => 'aussi', 'ja' => 'も', 'ko' => '또한', 'tr' => 'de', 'ru' => 'тоже', 'ar' => 'أيضا', 'az' => 'həmçinin'],
        'tanto' => ['en' => 'as much', 'de' => 'genauso viel', 'fr' => 'autant', 'ja' => '同じくらい', 'ko' => '그만큼', 'tr' => 'bu kadar', 'ru' => 'столько же', 'ar' => 'بقدر', 'az' => 'qədər'],
        'tarde' => ['en' => 'evening', 'de' => 'Abend', 'fr' => 'soir', 'ja' => '夕方', 'ko' => '저녁', 'tr' => 'akşam', 'ru' => 'вечер', 'ar' => 'مساء', 'az' => 'axşam'],
        'tarjeta' => ['en' => 'card', 'de' => 'Karte', 'fr' => 'carte', 'ja' => 'カード', 'ko' => '카드', 'tr' => 'kart', 'ru' => 'карта', 'ar' => 'بطاقة', 'az' => 'kart'],
        'tarta' => ['en' => 'tart', 'de' => 'Torte', 'fr' => 'tarte', 'ja' => 'タルト', 'ko' => '타르트', 'tr' => 'turta', 'ru' => 'тарт', 'ar' => 'فطيرة', 'az' => 'tart'],
        'teléfono' => ['en' => 'phone', 'de' => 'Telefon', 'fr' => 'téléphone', 'ja' => '電話', 'ko' => '전화', 'tr' => 'telefon', 'ru' => 'телефон', 'ar' => 'هاتف', 'az' => 'telefon'],
        'tenedor' => ['en' => 'fork', 'de' => 'Gabel', 'fr' => 'fourchette', 'ja' => 'フォーク', 'ko' => '포크', 'tr' => 'çatal', 'ru' => 'вилка', 'ar' => 'شوكة', 'az' => 'çəngəl'],
        'tengo' => ['en' => 'I have', 'de' => 'ich habe', 'fr' => 'j\'ai', 'ja' => '私は持っている', 'ko' => '나는 가지고 있다', 'tr' => 'var', 'ru' => 'у меня', 'ar' => 'عندي', 'az' => 'məndə var'],
        'tiempo' => ['en' => 'weather', 'de' => 'Wetter', 'fr' => 'temps', 'ja' => '天気', 'ko' => '날씨', 'tr' => 'hava', 'ru' => 'погода', 'ar' => 'طقس', 'az' => 'hava'],
        'tienda' => ['en' => 'shop', 'de' => 'Geschäft', 'fr' => 'magasin', 'ja' => '店', 'ko' => '가게', 'tr' => 'dükkan', 'ru' => 'магазин', 'ar' => 'متجر', 'az' => 'mağaza'],
        'todo' => ['en' => 'all', 'de' => 'alles', 'fr' => 'tout', 'ja' => 'すべて', 'ko' => '모든', 'tr' => 'hepsi', 'ru' => 'все', 'ar' => 'كل', 'az' => 'hamısı'],
        'tomar' => ['en' => 'have', 'de' => 'nehmen', 'fr' => 'prendre', 'ja' => '食べる', 'ko' => '먹다', 'tr' => 'sahip ol', 'ru' => 'есть', 'ar' => 'عند', 'az' => 'var'],
        'tomate' => ['en' => 'tomato', 'de' => 'Tomate', 'fr' => 'tomate', 'ja' => 'トマト', 'ko' => '토마토', 'tr' => 'domates', 'ru' => 'помидор', 'ar' => 'طماطم', 'az' => 'pomidor'],
        'tomo' => ['en' => 'I\'ll have', 'de' => 'ich nehme', 'fr' => 'je prends', 'ja' => 'にします', 'ko' => '하겠습니다', 'tr' => 'alayım', 'ru' => 'я возьму', 'ar' => 'سآخذ', 'az' => 'götürəcəyəm'],
        'total' => ['en' => 'total', 'de' => 'Gesamt', 'fr' => 'total', 'ja' => '合計', 'ko' => '총액', 'tr' => 'toplam', 'ru' => 'итого', 'ar' => 'المجموع', 'az' => 'cəmi'],
        'traer' => ['en' => 'to bring', 'de' => 'bringen', 'fr' => 'apporter', 'ja' => '持ってくる', 'ko' => '가져오다', 'tr' => 'getirmek', 'ru' => 'принести', 'ar' => 'الإحضار', 'az' => 'gətirmək'],
        'tranquila' => ['en' => 'calm', 'de' => 'ruhig', 'fr' => 'calme', 'ja' => '落ち着いた', 'ko' => '차분한', 'tr' => 'sakin', 'ru' => 'спокойный', 'ar' => 'هادئ', 'az' => 'sakit'],
        'tranquilo' => ['en' => 'calm', 'de' => 'ruhig', 'fr' => 'calme', 'ja' => '落ち着いた', 'ko' => '차분한', 'tr' => 'sakin', 'ru' => 'спокойный', 'ar' => 'هادئ', 'az' => 'sakit'],
        'tres' => ['en' => 'three', 'de' => 'drei', 'fr' => 'trois', 'ja' => '三', 'ko' => '셋', 'tr' => 'üç', 'ru' => 'три', 'ar' => 'ثلاثة', 'az' => 'üç'],
        'triste' => ['en' => 'sad', 'de' => 'traurig', 'fr' => 'triste', 'ja' => '悲しい', 'ko' => '슬픈', 'tr' => 'üzgün', 'ru' => 'грустный', 'ar' => 'حزين', 'az' => 'kədərli'],
        'trozo' => ['en' => 'slice', 'de' => 'Stück', 'fr' => 'part', 'ja' => '一切れ', 'ko' => '한 조각', 'tr' => 'dilim', 'ru' => 'кусок', 'ar' => 'شريحة', 'az' => 'dilim'],
        'tráigame' => ['en' => 'bring me', 'de' => 'bringen Sie mir', 'fr' => 'apportez-moi', 'ja' => '持ってきてください', 'ko' => '가져다주세요', 'tr' => 'bana getirin', 'ru' => 'принесите мне', 'ar' => 'أحضر لي', 'az' => 'mənə gətir'],
        'tu' => ['en' => 'your', 'de' => 'dein', 'fr' => 'ton', 'ja' => 'あなたの', 'ko' => '당신의', 'tr' => 'senin', 'ru' => 'твой', 'ar' => 'خاصتك', 'az' => 'sənin'],
        'té' => ['en' => 'tea', 'de' => 'Tee', 'fr' => 'thé', 'ja' => 'お茶', 'ko' => '차', 'tr' => 'çay', 'ru' => 'чай', 'ar' => 'شاي', 'az' => 'çay'],
        'tú' => ['en' => 'you', 'de' => 'du', 'fr' => 'tu', 'ja' => 'あなた', 'ko' => '당신', 'tr' => 'sen', 'ru' => 'ты', 'ar' => 'أنت', 'az' => 'sən'],
        'un' => ['en' => 'a', 'de' => 'ein', 'fr' => 'un', 'ja' => '一つの', 'ko' => '하나의', 'tr' => 'bir', 'ru' => 'один', 'ar' => 'واحد', 'az' => 'bir'],
        'un poco' => ['en' => 'a little', 'de' => 'ein bisschen', 'fr' => 'un peu', 'ja' => '少し', 'ko' => '조금', 'tr' => 'biraz', 'ru' => 'немного', 'ar' => 'قليل', 'az' => 'az'],
        'una' => ['en' => 'a', 'de' => 'eine', 'fr' => 'une', 'ja' => '一つの', 'ko' => '하나의', 'tr' => 'bir', 'ru' => 'один', 'ar' => 'واحد', 'az' => 'bir'],
        'una bebida' => ['en' => 'a drink', 'de' => 'ein Getränk', 'fr' => 'une boisson', 'ja' => '飲み物', 'ko' => '음료', 'tr' => 'bir içecek', 'ru' => 'напиток', 'ar' => 'مشروب', 'az' => 'içki'],
        'uno' => ['en' => 'one', 'de' => 'eins', 'fr' => 'un', 'ja' => '一', 'ko' => '하나', 'tr' => 'bir', 'ru' => 'один', 'ar' => 'واحد', 'az' => 'bir'],
        'unos' => ['en' => 'one', 'de' => 'eins', 'fr' => 'un', 'ja' => '一', 'ko' => '하나', 'tr' => 'bir', 'ru' => 'один', 'ar' => 'واحد', 'az' => 'bir'],
        'uvas' => ['en' => 'grapes', 'de' => 'Trauben', 'fr' => 'raisin', 'ja' => 'ぶどう', 'ko' => '포도', 'tr' => 'üzüm', 'ru' => 'виноград', 'ar' => 'عنب', 'az' => 'üzüm'],
        'vacía' => ['en' => 'empty', 'de' => 'leer', 'fr' => 'vide', 'ja' => '空', 'ko' => '빈', 'tr' => 'boş', 'ru' => 'пустой', 'ar' => 'فارغ', 'az' => 'boş'],
        'vacío' => ['en' => 'empty', 'de' => 'leer', 'fr' => 'vide', 'ja' => '空', 'ko' => '빈', 'tr' => 'boş', 'ru' => 'пустой', 'ar' => 'فارغ', 'az' => 'boş'],
        'vainilla' => ['en' => 'vanilla', 'de' => 'Vanille', 'fr' => 'vanille', 'ja' => 'バニラ', 'ko' => '바닐라', 'tr' => 'vanilya', 'ru' => 'ванильный', 'ar' => 'فانيليا', 'az' => 'vanil'],
        'vale' => ['en' => 'okay', 'de' => 'okay', 'fr' => 'd\'accord', 'ja' => 'いいよ', 'ko' => '좋아요', 'tr' => 'tamam', 'ru' => 'хорошо', 'ar' => 'حسنا', 'az' => 'yaxşı'],
        'vamos' => ['en' => 'let\'s go', 'de' => 'lass uns gehen', 'fr' => 'allons-y', 'ja' => '行きましょう', 'ko' => '갑시다', 'tr' => 'gidelim', 'ru' => 'пойдём', 'ar' => 'هيا بنا', 'az' => 'gedək'],
        'vaso' => ['en' => 'glass', 'de' => 'Glas', 'fr' => 'verre', 'ja' => 'グラス', 'ko' => '유리잔', 'tr' => 'bardak', 'ru' => 'стакан', 'ar' => 'كوب', 'az' => 'stəkan'],
        've' => ['en' => 'see', 'de' => 'sieht', 'fr' => 'voit', 'ja' => '見る', 'ko' => '보다', 'tr' => 'gör', 'ru' => 'вижу', 'ar' => 'أرى', 'az' => 'görürəm'],
        'vecino' => ['en' => 'neighbour', 'de' => 'Nachbar', 'fr' => 'voisin', 'ja' => '隣人', 'ko' => '이웃', 'tr' => 'komşu', 'ru' => 'сосед', 'ar' => 'جار', 'az' => 'qonşu'],
        'vegetariano' => ['en' => 'vegetarian', 'de' => 'vegetarisch', 'fr' => 'végétarien', 'ja' => 'ベジタリアン', 'ko' => '채식주의자', 'tr' => 'vejetaryen', 'ru' => 'вегетарианец', 'ar' => 'نباتي', 'az' => 'vegetarian'],
        'venir' => ['en' => 'come', 'de' => 'kommen', 'fr' => 'venir', 'ja' => '来る', 'ko' => '오다', 'tr' => 'gel', 'ru' => 'приходи', 'ar' => 'تعال', 'az' => 'gəl'],
        'ver' => ['en' => 'see', 'de' => 'sehen', 'fr' => 'voir', 'ja' => '見る', 'ko' => '보다', 'tr' => 'gör', 'ru' => 'вижу', 'ar' => 'أرى', 'az' => 'görürəm'],
        'verano' => ['en' => 'summer', 'de' => 'Sommer', 'fr' => 'été', 'ja' => '夏', 'ko' => '여름', 'tr' => 'yaz', 'ru' => 'лето', 'ar' => 'صيف', 'az' => 'yay'],
        'verdad' => ['en' => 'true', 'de' => 'wahr', 'fr' => 'vrai', 'ja' => '本当', 'ko' => '사실', 'tr' => 'doğru', 'ru' => 'правильно', 'ar' => 'صحيح', 'az' => 'düzgün'],
        'verdadero' => ['en' => 'true', 'de' => 'wahr', 'fr' => 'vrai', 'ja' => '本当', 'ko' => '사실', 'tr' => 'doğru', 'ru' => 'правильно', 'ar' => 'صحيح', 'az' => 'düzgün'],
        'verde' => ['en' => 'green', 'de' => 'grün', 'fr' => 'vert', 'ja' => '緑', 'ko' => '초록색', 'tr' => 'yeşil', 'ru' => 'зелёный', 'ar' => 'أخضر', 'az' => 'yaşıl'],
        'verduras' => ['en' => 'vegetables', 'de' => 'Gemüse', 'fr' => 'légumes', 'ja' => '野菜', 'ko' => '채소', 'tr' => 'sebze', 'ru' => 'овощи', 'ar' => 'خضروات', 'az' => 'tərəvəzlər'],
        'vi' => ['en' => 'I saw', 'de' => 'ich sah', 'fr' => 'j\'ai vu', 'ja' => '私は見た', 'ko' => '나는 보았다', 'tr' => 'gördüm', 'ru' => 'я видел', 'ar' => 'رأيت', 'az' => 'gördüm'],
        'viejo' => ['en' => 'old', 'de' => 'alt', 'fr' => 'vieux', 'ja' => '古い', 'ko' => '오래된', 'tr' => 'eski', 'ru' => 'старый', 'ar' => 'قديم', 'az' => 'köhnə'],
        'viento' => ['en' => 'wind', 'de' => 'Wind', 'fr' => 'vent', 'ja' => '風', 'ko' => '바람', 'tr' => 'rüzgâr', 'ru' => 'ветер', 'ar' => 'ريح', 'az' => 'külək'],
        'vino' => ['en' => 'wine', 'de' => 'Wein', 'fr' => 'vin', 'ja' => 'ワイン', 'ko' => '와인', 'tr' => 'şarap', 'ru' => 'вино', 'ar' => 'نبيذ', 'az' => 'şərab'],
        'vivo' => ['en' => 'I live', 'de' => 'ich wohne', 'fr' => 'j\'habite', 'ja' => '私は住んでいる', 'ko' => '나는 삽니다', 'tr' => 'yaşıyorum', 'ru' => 'я живу', 'ar' => 'أسكن', 'az' => 'yaşayıram'],
        'voy' => ['en' => 'I am going', 'de' => 'ich gehe', 'fr' => 'je vais', 'ja' => '私は行く', 'ko' => '나는 갈 것이다', 'tr' => 'gidiyorum', 'ru' => 'я иду', 'ar' => 'أذهب', 'az' => 'gedirəm'],
        'y' => ['en' => 'and', 'de' => 'und', 'fr' => 'et', 'ja' => 'と', 'ko' => '그리고', 'tr' => 've', 'ru' => 'и', 'ar' => 'و', 'az' => 'və'],
        'ya' => ['en' => 'already', 'de' => 'schon', 'fr' => 'déjà', 'ja' => 'もう', 'ko' => '이미', 'tr' => 'zaten', 'ru' => 'уже', 'ar' => 'بالفعل', 'az' => 'artıq'],
        'yo' => ['en' => 'I', 'de' => 'ich', 'fr' => 'je', 'ja' => '私', 'ko' => '나', 'tr' => 'ben', 'ru' => 'я', 'ar' => 'أنا', 'az' => 'mən'],
        'zanahoria' => ['en' => 'carrot', 'de' => 'Karotte', 'fr' => 'carotte', 'ja' => 'にんじん', 'ko' => '당근', 'tr' => 'havuç', 'ru' => 'морковь', 'ar' => 'جزر', 'az' => 'yerkökü'],
        'zumo' => ['en' => 'juice', 'de' => 'Saft', 'fr' => 'jus', 'ja' => 'ジュース', 'ko' => '주스', 'tr' => 'meyve suyu', 'ru' => 'сок', 'ar' => 'عصير', 'az' => 'şirə'],
        'él' => ['en' => 'he', 'de' => 'er', 'fr' => 'il', 'ja' => '彼', 'ko' => '그', 'tr' => 'o', 'ru' => 'он', 'ar' => 'هو', 'az' => 'o kişi'],
        'él es' => ['en' => 'he is', 'de' => 'er ist', 'fr' => 'il est', 'ja' => '彼は', 'ko' => '그는', 'tr' => 'o', 'ru' => 'он', 'ar' => 'هو', 'az' => 'o'],
    ];

    /** Native languages a learner can take a Spanish course in. */
    private const LANGS = ['en', 'de', 'fr', 'ja', 'ko'];

    /**
     * The ['i18n' => [...]] map for a Spanish word, ready to store in exercise
     * data. Falls back to the word itself if it isn't in the dictionary yet.
     *
     * @return array{i18n: array<string, string>}
     */
    public static function hint(string $spanish): array
    {
        return ['i18n' => self::meanings($spanish)];
    }

    /**
     * @return array<string, string>
     */
    public static function meanings(string $spanish): array
    {
        $key = mb_strtolower(trim($spanish));

        foreach (self::WORDS as $word => $translations) {
            if (mb_strtolower($word) === $key) {
                return $translations;
            }
        }

        // Not in the dictionary: show the Spanish word itself to every learner.
        return array_fill_keys(self::LANGS, $spanish);
    }

    /** Every Spanish word the dictionary knows (used for wrong-answer options). */
    public static function all(): array
    {
        return array_keys(self::WORDS);
    }

    public static function knows(string $spanish): bool
    {
        $key = mb_strtolower(trim($spanish));

        foreach (array_keys(self::WORDS) as $word) {
            if (mb_strtolower($word) === $key) {
                return true;
            }
        }

        return false;
    }
}
