<?php

namespace Database\Seeders\Support;

/**
 * Spanish word => its meaning in every native language a Spanish course supports
 * (English, German, French, Japanese, Korean).
 *
 * Spanish is the LEARNING language here, so exercise content (words, phrases,
 * tiles) is authored in Spanish, and only the hints/prompts are shown in the
 * learner's own language. Nothing user-facing is hardcoded: seeders pull from
 * here and store the result as an ['i18n' => [...]] map, which
 * ExerciseContentService resolves per request.
 *
 * This mirrors EnglishVocabulary and the other course dictionaries exactly, only
 * the language roles are swapped. Add a word here once and every unit can use it.
 */
class SpanishVocabulary
{
    private const WORDS = [
        'a' => ['en' => 'to', 'de' => 'zu', 'fr' => 'à', 'ja' => 'へ', 'ko' => '로'],
        'abierta' => ['en' => 'open', 'de' => 'offen', 'fr' => 'ouvert', 'ja' => '開いた', 'ko' => '열린'],
        'abierto' => ['en' => 'open', 'de' => 'offen', 'fr' => 'ouvert', 'ja' => '開いた', 'ko' => '열린'],
        'adiós' => ['en' => 'goodbye', 'de' => 'auf Wiedersehen', 'fr' => 'au revoir', 'ja' => 'さようなら', 'ko' => '안녕히 가세요'],
        'agua' => ['en' => 'water', 'de' => 'Wasser', 'fr' => 'eau', 'ja' => '水', 'ko' => '물'],
        'ahora' => ['en' => 'now', 'de' => 'jetzt', 'fr' => 'maintenant', 'ja' => '今', 'ko' => '지금'],
        'al' => ['en' => 'to the', 'de' => 'zum', 'fr' => 'au', 'ja' => 'へ', 'ko' => '로'],
        'alergia' => ['en' => 'allergy', 'de' => 'Allergie', 'fr' => 'allergie', 'ja' => 'アレルギー', 'ko' => '알레르기'],
        'algo' => ['en' => 'some', 'de' => 'etwas', 'fr' => 'du', 'ja' => 'いくつかの', 'ko' => '약간의'],
        'algo de' => ['en' => 'some', 'de' => 'etwas', 'fr' => 'du', 'ja' => '少しの', 'ko' => '약간의'],
        'alérgico' => ['en' => 'allergic', 'de' => 'allergisch', 'fr' => 'allergique', 'ja' => 'アレルギーの', 'ko' => '알레르기가 있는'],
        'amarillo' => ['en' => 'yellow', 'de' => 'gelb', 'fr' => 'jaune', 'ja' => '黄色', 'ko' => '노란색'],
        'amigo' => ['en' => 'friend', 'de' => 'Freund', 'fr' => 'ami', 'ja' => '友達', 'ko' => '친구'],
        'antes' => ['en' => 'before', 'de' => 'vor', 'fr' => 'avant', 'ja' => '前に', 'ko' => '전에'],
        'aquí' => ['en' => 'here', 'de' => 'hier', 'fr' => 'ici', 'ja' => 'ここ', 'ko' => '여기'],
        'aquí está' => ['en' => 'here is', 'de' => 'hier ist', 'fr' => 'voici', 'ja' => 'これが', 'ko' => '여기'],
        'arroz' => ['en' => 'rice', 'de' => 'Reis', 'fr' => 'riz', 'ja' => 'ご飯', 'ko' => '밥'],
        'ayer' => ['en' => 'yesterday', 'de' => 'gestern', 'fr' => 'hier', 'ja' => '昨日', 'ko' => '어제'],
        'azul' => ['en' => 'blue', 'de' => 'blau', 'fr' => 'bleu', 'ja' => '青', 'ko' => '파란색'],
        'azúcar' => ['en' => 'sugar', 'de' => 'Zucker', 'fr' => 'sucre', 'ja' => '砂糖', 'ko' => '설탕'],
        'años' => ['en' => 'years old', 'de' => 'Jahre alt', 'fr' => 'ans', 'ja' => '歳', 'ko' => '살'],
        'balanza' => ['en' => 'scales', 'de' => 'Waage', 'fr' => 'balance', 'ja' => 'はかり', 'ko' => '저울'],
        'barata' => ['en' => 'cheap', 'de' => 'billig', 'fr' => 'bon marché', 'ja' => '安い', 'ko' => '싼'],
        'barato' => ['en' => 'cheap', 'de' => 'billig', 'fr' => 'bon marché', 'ja' => '安い', 'ko' => '싼'],
        'bastante' => ['en' => 'enough', 'de' => 'genug', 'fr' => 'assez', 'ja' => '十分に', 'ko' => '충분히'],
        'bastantes' => ['en' => 'enough', 'de' => 'genug', 'fr' => 'assez', 'ja' => '十分に', 'ko' => '충분히'],
        'beber' => ['en' => 'drink', 'de' => 'trinken', 'fr' => 'boire', 'ja' => '飲む', 'ko' => '마시다'],
        'bebida' => ['en' => 'drink', 'de' => 'Getränk', 'fr' => 'boisson', 'ja' => '飲み物', 'ko' => '음료'],
        'bebo' => ['en' => 'drink', 'de' => 'trinke', 'fr' => 'bois', 'ja' => '飲む', 'ko' => '마시다'],
        'bebí' => ['en' => 'I drank', 'de' => 'ich trank', 'fr' => 'j\'ai bu', 'ja' => '私は飲んだ', 'ko' => '나는 마셨다'],
        'bien' => ['en' => 'well', 'de' => 'gut', 'fr' => 'bien', 'ja' => '元気', 'ko' => '잘'],
        'bienvenido' => ['en' => 'welcome', 'de' => 'willkommen', 'fr' => 'bienvenue', 'ja' => 'ようこそ', 'ko' => '환영합니다'],
        'blanco' => ['en' => 'white', 'de' => 'weiß', 'fr' => 'blanc', 'ja' => '白', 'ko' => '하얀색'],
        'bolsa' => ['en' => 'bag', 'de' => 'Tüte', 'fr' => 'sac', 'ja' => '袋', 'ko' => '봉투'],
        'bolígrafo' => ['en' => 'pen', 'de' => 'Kugelschreiber', 'fr' => 'stylo', 'ja' => 'ペン', 'ko' => '펜'],
        'bolígrafos' => ['en' => 'pens', 'de' => 'Kugelschreiber', 'fr' => 'stylos', 'ja' => 'ペン', 'ko' => '펜들'],
        'bonito' => ['en' => 'pretty', 'de' => 'hübsch', 'fr' => 'joli', 'ja' => 'かわいい', 'ko' => '예쁜'],
        'botella' => ['en' => 'bottle', 'de' => 'Flasche', 'fr' => 'bouteille', 'ja' => 'ボトル', 'ko' => '병'],
        'botellas' => ['en' => 'bottle', 'de' => 'Flasche', 'fr' => 'bouteille', 'ja' => 'ボトル', 'ko' => '병'],
        'buen' => ['en' => 'good', 'de' => 'gut', 'fr' => 'bon', 'ja' => '良い', 'ko' => '좋은'],
        'buena' => ['en' => 'good', 'de' => 'gut', 'fr' => 'bon', 'ja' => '良い', 'ko' => '좋은'],
        'bueno' => ['en' => 'good', 'de' => 'gut', 'fr' => 'bon', 'ja' => '良い', 'ko' => '좋은'],
        'buscar' => ['en' => 'to look for', 'de' => 'suchen', 'fr' => 'chercher', 'ja' => '探す', 'ko' => '찾다'],
        'cada' => ['en' => 'each', 'de' => 'jeder', 'fr' => 'chaque', 'ja' => 'それぞれの', 'ko' => '각각의'],
        'café' => ['en' => 'coffee', 'de' => 'Kaffee', 'fr' => 'café', 'ja' => 'コーヒー', 'ko' => '커피'],
        'caja' => ['en' => 'checkout', 'de' => 'Kasse', 'fr' => 'caisse', 'ja' => 'レジ', 'ko' => '계산대'],
        'cajero' => ['en' => 'cashier', 'de' => 'Kassierer', 'fr' => 'caissier', 'ja' => 'レジ係', 'ko' => '계산원'],
        'calendario' => ['en' => 'calendar', 'de' => 'Kalender', 'fr' => 'calendrier', 'ja' => 'カレンダー', 'ko' => '달력'],
        'caliente' => ['en' => 'hot', 'de' => 'heiß', 'fr' => 'chaud', 'ja' => '熱い', 'ko' => '뜨거운'],
        'calle' => ['en' => 'street', 'de' => 'Straße', 'fr' => 'rue', 'ja' => '通り', 'ko' => '거리'],
        'camarero' => ['en' => 'waiter', 'de' => 'Kellner', 'fr' => 'serveur', 'ja' => 'ウェイター', 'ko' => '웨이터'],
        'cambio' => ['en' => 'change', 'de' => 'Wechselgeld', 'fr' => 'monnaie', 'ja' => 'おつり', 'ko' => '거스름돈'],
        'camina' => ['en' => 'walk', 'de' => 'geht', 'fr' => 'marche', 'ja' => '歩く', 'ko' => '걷다'],
        'caminar' => ['en' => 'walk', 'de' => 'gehen', 'fr' => 'marcher', 'ja' => '歩く', 'ko' => '걷다'],
        'camino' => ['en' => 'walk', 'de' => 'gehe', 'fr' => 'marche', 'ja' => '歩く', 'ko' => '걷다'],
        'cancelar' => ['en' => 'to cancel', 'de' => 'stornieren', 'fr' => 'annuler', 'ja' => 'キャンセルする', 'ko' => '취소하다'],
        'cansado' => ['en' => 'tired', 'de' => 'müde', 'fr' => 'fatigué', 'ja' => '疲れた', 'ko' => '피곤한'],
        'carne' => ['en' => 'meat', 'de' => 'Fleisch', 'fr' => 'viande', 'ja' => '肉', 'ko' => '고기'],
        'caro' => ['en' => 'expensive', 'de' => 'teuer', 'fr' => 'cher', 'ja' => '高い', 'ko' => '비싼'],
        'carrito' => ['en' => 'trolley', 'de' => 'Einkaufswagen', 'fr' => 'chariot', 'ja' => 'カート', 'ko' => '카트'],
        'casa' => ['en' => 'house', 'de' => 'Haus', 'fr' => 'maison', 'ja' => '家', 'ko' => '집'],
        'cebolla' => ['en' => 'onion', 'de' => 'Zwiebel', 'fr' => 'oignon', 'ja' => '玉ねぎ', 'ko' => '양파'],
        'cerca' => ['en' => 'near', 'de' => 'nah', 'fr' => 'près', 'ja' => '近く', 'ko' => '가까이'],
        'cerrada' => ['en' => 'closed', 'de' => 'geschlossen', 'fr' => 'fermé', 'ja' => '閉じた', 'ko' => '닫힌'],
        'cerrado' => ['en' => 'closed', 'de' => 'geschlossen', 'fr' => 'fermé', 'ja' => '閉じた', 'ko' => '닫힌'],
        'cerveza' => ['en' => 'beer', 'de' => 'Bier', 'fr' => 'bière', 'ja' => 'ビール', 'ko' => '맥주'],
        'cesta' => ['en' => 'basket', 'de' => 'Korb', 'fr' => 'panier', 'ja' => 'かご', 'ko' => '바구니'],
        'chocolate' => ['en' => 'chocolate', 'de' => 'Schokolade', 'fr' => 'chocolat', 'ja' => 'チョコレート', 'ko' => '초콜릿'],
        'cielo' => ['en' => 'sky', 'de' => 'Himmel', 'fr' => 'ciel', 'ja' => '空', 'ko' => '하늘'],
        'cinco' => ['en' => 'five', 'de' => 'fünf', 'fr' => 'cinq', 'ja' => '五', 'ko' => '다섯'],
        'ciudad' => ['en' => 'town', 'de' => 'Stadt', 'fr' => 'ville', 'ja' => '町', 'ko' => '도시'],
        'cocina' => ['en' => 'kitchen', 'de' => 'Küche', 'fr' => 'cuisine', 'ja' => '厨房', 'ko' => '주방'],
        'cola' => ['en' => 'queue', 'de' => 'Schlange', 'fr' => 'file', 'ja' => '列', 'ko' => '줄'],
        'come' => ['en' => 'eat', 'de' => 'isst', 'fr' => 'mange', 'ja' => '食べる', 'ko' => '먹다'],
        'comer' => ['en' => 'eat', 'de' => 'essen', 'fr' => 'manger', 'ja' => '食べる', 'ko' => '먹다'],
        'como' => ['en' => 'like', 'de' => 'wie', 'fr' => 'comme', 'ja' => 'のように', 'ko' => '처럼'],
        'comparar' => ['en' => 'to compare', 'de' => 'vergleichen', 'fr' => 'comparer', 'ja' => '比べる', 'ko' => '비교하다'],
        'compartir' => ['en' => 'to share', 'de' => 'teilen', 'fr' => 'partager', 'ja' => '分ける', 'ko' => '나누다'],
        'comprar' => ['en' => 'to buy', 'de' => 'kaufen', 'fr' => 'acheter', 'ja' => '買う', 'ko' => '사다'],
        'comí' => ['en' => 'I ate', 'de' => 'ich aß', 'fr' => 'j\'ai mangé', 'ja' => '私は食べた', 'ko' => '나는 먹었다'],
        'con' => ['en' => 'with', 'de' => 'mit', 'fr' => 'avec', 'ja' => 'と一緒に', 'ko' => '와 함께'],
        'confirmar' => ['en' => 'to confirm', 'de' => 'bestätigen', 'fr' => 'confirmer', 'ja' => '確認する', 'ko' => '확인하다'],
        'contenta' => ['en' => 'glad', 'de' => 'froh', 'fr' => 'content', 'ja' => '嬉しい', 'ko' => '기쁜'],
        'contento' => ['en' => 'glad', 'de' => 'froh', 'fr' => 'content', 'ja' => '嬉しい', 'ko' => '기쁜'],
        'contiene' => ['en' => 'contains', 'de' => 'enthält', 'fr' => 'contient', 'ja' => '含む', 'ko' => '들어있다'],
        'continuar' => ['en' => 'continue', 'de' => 'weitergehen', 'fr' => 'continuer', 'ja' => '続ける', 'ko' => '계속하다'],
        'continúa' => ['en' => 'continue', 'de' => 'weitergehen', 'fr' => 'continue', 'ja' => '続ける', 'ko' => '계속하다'],
        'creo' => ['en' => 'I think', 'de' => 'ich denke', 'fr' => 'je pense', 'ja' => '私は思う', 'ko' => '나는 생각한다'],
        'creo que' => ['en' => 'I believe', 'de' => 'ich glaube', 'fr' => 'je crois', 'ja' => '私は信じる', 'ko' => '나는 믿는다'],
        'cruza' => ['en' => 'cross', 'de' => 'überqueren', 'fr' => 'traverse', 'ja' => '渡る', 'ko' => '건너다'],
        'cruzar' => ['en' => 'cross', 'de' => 'überqueren', 'fr' => 'traverser', 'ja' => '渡る', 'ko' => '건너다'],
        'cuatro' => ['en' => 'four', 'de' => 'vier', 'fr' => 'quatre', 'ja' => '四', 'ko' => '넷'],
        'cuchara' => ['en' => 'spoon', 'de' => 'Löffel', 'fr' => 'cuillère', 'ja' => 'スプーン', 'ko' => '숟가락'],
        'cuchillo' => ['en' => 'knife', 'de' => 'Messer', 'fr' => 'couteau', 'ja' => 'ナイフ', 'ko' => '나이프'],
        'cuenta' => ['en' => 'bill', 'de' => 'Rechnung', 'fr' => 'addition', 'ja' => '会計', 'ko' => '계산서'],
        'cuesta' => ['en' => 'costs', 'de' => 'kostet', 'fr' => 'coûte', 'ja' => 'かかる', 'ko' => '입니다'],
        'cuál' => ['en' => 'which', 'de' => 'welcher', 'fr' => 'quel', 'ja' => 'どれ', 'ko' => '어느'],
        'cuándo' => ['en' => 'when', 'de' => 'wann', 'fr' => 'quand', 'ja' => 'いつ', 'ko' => '언제'],
        'cuánto' => ['en' => 'how much', 'de' => 'wie viel', 'fr' => 'combien', 'ja' => 'いくら', 'ko' => '얼마'],
        'cuántos' => ['en' => 'how many', 'de' => 'wie viele', 'fr' => 'combien', 'ja' => 'いくつ', 'ko' => '몇 개'],
        'cálido' => ['en' => 'warm', 'de' => 'warm', 'fr' => 'doux', 'ja' => '暖かい', 'ko' => '따뜻한'],
        'cómo' => ['en' => 'how', 'de' => 'wie', 'fr' => 'comment', 'ja' => 'どう', 'ko' => '어떻게'],
        'cómo estás' => ['en' => 'how are you', 'de' => 'wie geht es dir', 'fr' => 'comment ça va', 'ja' => 'お元気ですか', 'ko' => '어떻게 지내세요'],
        'de' => ['en' => 'of', 'de' => 'von', 'fr' => 'de', 'ja' => 'の', 'ko' => '의'],
        'de verdad' => ['en' => 'really', 'de' => 'wirklich', 'fr' => 'vraiment', 'ja' => '本当に', 'ko' => '정말'],
        'debajo' => ['en' => 'under', 'de' => 'unter', 'fr' => 'sous', 'ja' => 'の下に', 'ko' => '아래에'],
        'del' => ['en' => 'of the', 'de' => 'vom', 'fr' => 'du', 'ja' => 'の', 'ko' => '의'],
        'delante' => ['en' => 'in front', 'de' => 'vorne', 'fr' => 'devant', 'ja' => '前に', 'ko' => '앞에'],
        'delicioso' => ['en' => 'delicious', 'de' => 'köstlich', 'fr' => 'délicieux', 'ja' => 'おいしい', 'ko' => '맛있는'],
        'demasiado' => ['en' => 'too much', 'de' => 'zu viel', 'fr' => 'trop', 'ja' => 'すぎます', 'ko' => '너무'],
        'deme' => ['en' => 'give me', 'de' => 'geben Sie mir', 'fr' => 'donnez-moi', 'ja' => 'ください', 'ko' => '주세요'],
        'derecha' => ['en' => 'right', 'de' => 'rechts', 'fr' => 'droite', 'ja' => '右', 'ko' => '오른쪽'],
        'descuento' => ['en' => 'discount', 'de' => 'Rabatt', 'fr' => 'réduction', 'ja' => '割引', 'ko' => '할인'],
        'despacio' => ['en' => 'slowly', 'de' => 'langsam', 'fr' => 'lentement', 'ja' => 'ゆっくり', 'ko' => '천천히'],
        'después' => ['en' => 'after', 'de' => 'nach', 'fr' => 'après', 'ja' => '後に', 'ko' => '후에'],
        'detrás' => ['en' => 'behind', 'de' => 'hinten', 'fr' => 'derrière', 'ja' => '後ろに', 'ko' => '뒤에'],
        'devolver la llamada' => ['en' => 'call back', 'de' => 'zurückrufen', 'fr' => 'rappeler', 'ja' => '折り返す', 'ko' => '다시 전화하다'],
        'devuelve' => ['en' => 'return', 'de' => 'zurückrufen', 'fr' => 'rappelle', 'ja' => '折り返す', 'ko' => '돌려주다'],
        'dieta' => ['en' => 'diet', 'de' => 'Diät', 'fr' => 'régime', 'ja' => '食事制限', 'ko' => '식단'],
        'diez' => ['en' => 'ten', 'de' => 'zehn', 'fr' => 'dix', 'ja' => '十', 'ko' => '열'],
        'difícil' => ['en' => 'hard', 'de' => 'schwer', 'fr' => 'difficile', 'ja' => '難しい', 'ko' => '어려운'],
        'dinero' => ['en' => 'money', 'de' => 'Geld', 'fr' => 'argent', 'ja' => 'お金', 'ko' => '돈'],
        'disculpe' => ['en' => 'excuse me', 'de' => 'entschuldigen Sie', 'fr' => 'excusez-moi', 'ja' => 'すみません', 'ko' => '실례합니다'],
        'dormir' => ['en' => 'sleep', 'de' => 'schlafen', 'fr' => 'dormir', 'ja' => '眠る', 'ko' => '자다'],
        'dos' => ['en' => 'two', 'de' => 'zwei', 'fr' => 'deux', 'ja' => '二', 'ko' => '둘'],
        'dos libros' => ['en' => 'two books', 'de' => 'zwei Bücher', 'fr' => 'deux livres', 'ja' => '二冊の本', 'ko' => '책 두 권'],
        'duerme' => ['en' => 'sleep', 'de' => 'schläft', 'fr' => 'dort', 'ja' => '眠る', 'ko' => '자다'],
        'duermo' => ['en' => 'sleep', 'de' => 'schlafe', 'fr' => 'dors', 'ja' => '眠る', 'ko' => '자다'],
        'dulce' => ['en' => 'sweet', 'de' => 'süß', 'fr' => 'sucré', 'ja' => '甘い', 'ko' => '단'],
        'dura' => ['en' => 'hard', 'de' => 'hart', 'fr' => 'dur', 'ja' => '硬い', 'ko' => '단단한'],
        'día' => ['en' => 'day', 'de' => 'Tag', 'fr' => 'jour', 'ja' => '日', 'ko' => '날'],
        'dólares' => ['en' => 'dollars', 'de' => 'Dollar', 'fr' => 'dollars', 'ja' => 'ドル', 'ko' => '달러'],
        'dónde' => ['en' => 'where', 'de' => 'wo', 'fr' => 'où', 'ja' => 'どこ', 'ko' => '어디'],
        'dónde está' => ['en' => 'where is', 'de' => 'wo ist', 'fr' => 'où est', 'ja' => 'どこですか', 'ko' => '어디입니까'],
        'e' => ['en' => 'and', 'de' => 'und', 'fr' => 'et', 'ja' => 'と', 'ko' => '그리고'],
        'edad' => ['en' => 'age', 'de' => 'Alter', 'fr' => 'âge', 'ja' => '年齢', 'ko' => '나이'],
        'efectivo' => ['en' => 'cash', 'de' => 'bar', 'fr' => 'espèces', 'ja' => '現金', 'ko' => '현금'],
        'el' => ['en' => 'the', 'de' => 'der', 'fr' => 'le', 'ja' => 'その', 'ko' => '그'],
        'elegir' => ['en' => 'to choose', 'de' => 'wählen', 'fr' => 'choisir', 'ja' => '選ぶ', 'ko' => '고르다'],
        'ella' => ['en' => 'she', 'de' => 'sie', 'fr' => 'elle', 'ja' => '彼女', 'ko' => '그녀'],
        'ella es' => ['en' => 'she is', 'de' => 'sie ist', 'fr' => 'elle est', 'ja' => '彼女は', 'ko' => '그녀는'],
        'en' => ['en' => 'in', 'de' => 'in', 'fr' => 'dans', 'ja' => 'の中に', 'ko' => '안에'],
        'en efectivo' => ['en' => 'cash', 'de' => 'in bar', 'fr' => 'en espèces', 'ja' => '現金で', 'ko' => '현금으로'],
        'en punto' => ['en' => 'o\'clock', 'de' => 'Uhr', 'fr' => 'heures', 'ja' => '時', 'ko' => '시'],
        'encantado' => ['en' => 'nice to meet you', 'de' => 'freut mich', 'fr' => 'enchanté', 'ja' => 'はじめまして', 'ko' => '반갑습니다'],
        'encontrar' => ['en' => 'to find', 'de' => 'finden', 'fr' => 'trouver', 'ja' => '見つける', 'ko' => '발견하다'],
        'enfermo' => ['en' => 'sick', 'de' => 'krank', 'fr' => 'malade', 'ja' => '病気', 'ko' => '아픈'],
        'ensalada' => ['en' => 'salad', 'de' => 'Salat', 'fr' => 'salade', 'ja' => 'サラダ', 'ko' => '샐러드'],
        'entonces' => ['en' => 'then', 'de' => 'dann', 'fr' => 'ensuite', 'ja' => 'それから', 'ko' => '그러면'],
        'entrante' => ['en' => 'starter', 'de' => 'Vorspeise', 'fr' => 'entrée', 'ja' => '前菜', 'ko' => '전채'],
        'eres' => ['en' => 'you are', 'de' => 'du bist', 'fr' => 'tu es', 'ja' => 'です', 'ko' => '입니다'],
        'es' => ['en' => 'is', 'de' => 'ist', 'fr' => 'est', 'ja' => 'です', 'ko' => '입니다'],
        'esa' => ['en' => 'it', 'de' => 'es', 'fr' => 'ce', 'ja' => 'それ', 'ko' => '그것'],
        'escuela' => ['en' => 'school', 'de' => 'Schule', 'fr' => 'école', 'ja' => '学校', 'ko' => '학교'],
        'ese' => ['en' => 'that', 'de' => 'jener', 'fr' => 'cette', 'ja' => 'あの', 'ko' => '저'],
        'eso' => ['en' => 'it', 'de' => 'es', 'fr' => 'ce', 'ja' => 'それ', 'ko' => '그것'],
        'esos' => ['en' => 'those', 'de' => 'jene', 'fr' => 'ces', 'ja' => 'あれらの', 'ko' => '저것들'],
        'espera' => ['en' => 'wait', 'de' => 'wartet', 'fr' => 'attends', 'ja' => '待つ', 'ko' => '기다리다'],
        'esperar' => ['en' => 'wait', 'de' => 'warten', 'fr' => 'attendre', 'ja' => '待つ', 'ko' => '기다리다'],
        'esta' => ['en' => 'this', 'de' => 'diese', 'fr' => 'cette', 'ja' => 'この', 'ko' => '이'],
        'esta noche' => ['en' => 'tonight', 'de' => 'heute Abend', 'fr' => 'ce soir', 'ja' => '今夜', 'ko' => '오늘 밤'],
        'estaba' => ['en' => 'I was', 'de' => 'ich war', 'fr' => 'j\'étais', 'ja' => 'でした', 'ko' => '였습니다'],
        'estación' => ['en' => 'station', 'de' => 'Bahnhof', 'fr' => 'gare', 'ja' => '駅', 'ko' => '역'],
        'este' => ['en' => 'this', 'de' => 'dieser', 'fr' => 'ce', 'ja' => 'この', 'ko' => '이'],
        'este es' => ['en' => 'this is', 'de' => 'das ist', 'fr' => 'c\'est', 'ja' => 'これは', 'ko' => '이분은'],
        'estos' => ['en' => 'these', 'de' => 'diese', 'fr' => 'ces', 'ja' => 'これらの', 'ko' => '이것들'],
        'estoy' => ['en' => 'am', 'de' => 'bin', 'fr' => 'suis', 'ja' => 'です', 'ko' => '입니다'],
        'está' => ['en' => 'is', 'de' => 'ist', 'fr' => 'est', 'ja' => 'です', 'ko' => '있다'],
        'estás' => ['en' => 'are', 'de' => 'bist', 'fr' => 'es', 'ja' => 'です', 'ko' => '입니다'],
        'evitar' => ['en' => 'to avoid', 'de' => 'vermeiden', 'fr' => 'éviter', 'ja' => '避ける', 'ko' => '피하다'],
        'excelente' => ['en' => 'excellent', 'de' => 'ausgezeichnet', 'fr' => 'excellent', 'ja' => '素晴らしい', 'ko' => '훌륭한'],
        'falso' => ['en' => 'false', 'de' => 'falsch', 'fr' => 'faux', 'ja' => '偽', 'ko' => '거짓'],
        'favor' => ['en' => 'please', 'de' => 'bitte', 'fr' => 'plaît', 'ja' => 'お願い', 'ko' => '부탁'],
        'feliz' => ['en' => 'happy', 'de' => 'glücklich', 'fr' => 'heureux', 'ja' => '幸せ', 'ko' => '행복한'],
        'fresa' => ['en' => 'strawberry', 'de' => 'Erdbeere', 'fr' => 'fraise', 'ja' => 'いちご', 'ko' => '딸기'],
        'fresca' => ['en' => 'fresh', 'de' => 'frisch', 'fr' => 'frais', 'ja' => '新鮮', 'ko' => '신선한'],
        'fresco' => ['en' => 'fresh', 'de' => 'frisch', 'fr' => 'frais', 'ja' => '新鮮', 'ko' => '신선한'],
        'fritas' => ['en' => 'fried', 'de' => 'Pommes', 'fr' => 'frites', 'ja' => 'フライド', 'ko' => '튀김'],
        'fruta' => ['en' => 'fruit', 'de' => 'Obst', 'fr' => 'fruit', 'ja' => '果物', 'ko' => '과일'],
        'frutas' => ['en' => 'fruits', 'de' => 'Früchte', 'fr' => 'fruits', 'ja' => '果物', 'ko' => '과일'],
        'fría' => ['en' => 'cold', 'de' => 'kalt', 'fr' => 'froid', 'ja' => '冷たい', 'ko' => '차가운'],
        'frío' => ['en' => 'cold', 'de' => 'kalt', 'fr' => 'froid', 'ja' => '冷たい', 'ko' => '차가운'],
        'fue' => ['en' => 'it was', 'de' => 'es war', 'fr' => 'c\'était', 'ja' => 'でした', 'ko' => '였습니다'],
        'fácil' => ['en' => 'easy', 'de' => 'einfach', 'fr' => 'facile', 'ja' => '簡単', 'ko' => '쉬운'],
        'gato' => ['en' => 'cat', 'de' => 'Katze', 'fr' => 'chat', 'ja' => '猫', 'ko' => '고양이'],
        'gatos' => ['en' => 'cats', 'de' => 'Katzen', 'fr' => 'chats', 'ja' => '猫', 'ko' => '고양이들'],
        'gira' => ['en' => 'turn', 'de' => 'abbiegen', 'fr' => 'tourne', 'ja' => '曲がる', 'ko' => '돌다'],
        'girar' => ['en' => 'turn', 'de' => 'abbiegen', 'fr' => 'tourner', 'ja' => '曲がる', 'ko' => '돌다'],
        'gluten' => ['en' => 'gluten', 'de' => 'Gluten', 'fr' => 'gluten', 'ja' => 'グルテン', 'ko' => '글루텐'],
        'gracias' => ['en' => 'thank you', 'de' => 'danke', 'fr' => 'merci', 'ja' => 'ありがとう', 'ko' => '감사합니다'],
        'gramo' => ['en' => 'gram', 'de' => 'Gramm', 'fr' => 'gramme', 'ja' => 'グラム', 'ko' => '그램'],
        'grande' => ['en' => 'big', 'de' => 'groß', 'fr' => 'grand', 'ja' => '大きい', 'ko' => '큰'],
        'habla' => ['en' => 'speak', 'de' => 'spricht', 'fr' => 'parle', 'ja' => '話す', 'ko' => '말하다'],
        'hablar' => ['en' => 'speak', 'de' => 'sprechen', 'fr' => 'parler', 'ja' => '話す', 'ko' => '말하다'],
        'hambriento' => ['en' => 'hungry', 'de' => 'hungrig', 'fr' => 'affamé', 'ja' => 'お腹がすいた', 'ko' => '배고픈'],
        'hamburguesa' => ['en' => 'burger', 'de' => 'Burger', 'fr' => 'hamburger', 'ja' => 'ハンバーガー', 'ko' => '햄버거'],
        'helado' => ['en' => 'ice cream', 'de' => 'Eis', 'fr' => 'glace', 'ja' => 'アイスクリーム', 'ko' => '아이스크림'],
        'hermana' => ['en' => 'sister', 'de' => 'Schwester', 'fr' => 'sœur', 'ja' => '姉妹', 'ko' => '자매'],
        'hermano' => ['en' => 'brother', 'de' => 'Bruder', 'fr' => 'frère', 'ja' => '兄弟', 'ko' => '형제'],
        'hermosa' => ['en' => 'beautiful', 'de' => 'schön', 'fr' => 'beau', 'ja' => '美しい', 'ko' => '아름다운'],
        'hermoso' => ['en' => 'beautiful', 'de' => 'schön', 'fr' => 'beau', 'ja' => '美しい', 'ko' => '아름다운'],
        'hielo' => ['en' => 'ice', 'de' => 'Eiswürfel', 'fr' => 'glaçons', 'ja' => '氷', 'ko' => '얼음'],
        'hola' => ['en' => 'hello', 'de' => 'hallo', 'fr' => 'bonjour', 'ja' => 'こんにちは', 'ko' => '안녕하세요'],
        'hora' => ['en' => 'hour', 'de' => 'Stunde', 'fr' => 'heure', 'ja' => '時間', 'ko' => '시간'],
        'hoy' => ['en' => 'today', 'de' => 'heute', 'fr' => 'aujourd\'hui', 'ja' => '今日', 'ko' => '오늘'],
        'huevo' => ['en' => 'egg', 'de' => 'Ei', 'fr' => 'œuf', 'ja' => '卵', 'ko' => '계란'],
        'huevos' => ['en' => 'eggs', 'de' => 'Eier', 'fr' => 'œufs', 'ja' => '卵', 'ko' => '계란'],
        'ingredientes' => ['en' => 'ingredients', 'de' => 'Zutaten', 'fr' => 'ingrédients', 'ja' => '材料', 'ko' => '재료'],
        'invierno' => ['en' => 'winter', 'de' => 'Winter', 'fr' => 'hiver', 'ja' => '冬', 'ko' => '겨울'],
        'ir' => ['en' => 'go', 'de' => 'gehen', 'fr' => 'aller', 'ja' => '行く', 'ko' => '가다'],
        'izquierda' => ['en' => 'left', 'de' => 'links', 'fr' => 'gauche', 'ja' => '左', 'ko' => '왼쪽'],
        'juntos' => ['en' => 'together', 'de' => 'zusammen', 'fr' => 'ensemble', 'ja' => '一緒に', 'ko' => '함께'],
        'kilo' => ['en' => 'kilo', 'de' => 'Kilo', 'fr' => 'kilo', 'ja' => 'キロ', 'ko' => '킬로'],
        'la' => ['en' => 'the', 'de' => 'die', 'fr' => 'la', 'ja' => 'その', 'ko' => '그'],
        'la cuenta' => ['en' => 'the bill', 'de' => 'die Rechnung', 'fr' => 'l\'addition', 'ja' => 'お会計', 'ko' => '계산서'],
        'las' => ['en' => 'the', 'de' => 'die', 'fr' => 'les', 'ja' => 'その', 'ko' => '그'],
        'leche' => ['en' => 'milk', 'de' => 'Milch', 'fr' => 'lait', 'ja' => '牛乳', 'ko' => '우유'],
        'leer' => ['en' => 'read', 'de' => 'lesen', 'fr' => 'lire', 'ja' => '読む', 'ko' => '읽다'],
        'lejos' => ['en' => 'far', 'de' => 'weit', 'fr' => 'loin', 'ja' => '遠く', 'ko' => '멀리'],
        'leo' => ['en' => 'read', 'de' => 'lese', 'fr' => 'lis', 'ja' => '読む', 'ko' => '읽다'],
        'libre' => ['en' => 'free', 'de' => 'frei', 'fr' => 'libre', 'ja' => '暇', 'ko' => '한가한'],
        'libro' => ['en' => 'book', 'de' => 'Buch', 'fr' => 'livre', 'ja' => '本', 'ko' => '책'],
        'libros' => ['en' => 'books', 'de' => 'Bücher', 'fr' => 'livres', 'ja' => '本', 'ko' => '책들'],
        'ligeras' => ['en' => 'light', 'de' => 'leicht', 'fr' => 'léger', 'ja' => '軽い', 'ko' => '가벼운'],
        'ligero' => ['en' => 'light', 'de' => 'leicht', 'fr' => 'léger', 'ja' => '軽い', 'ko' => '가벼운'],
        'limpio' => ['en' => 'clean', 'de' => 'sauber', 'fr' => 'propre', 'ja' => 'きれい', 'ko' => '깨끗한'],
        'lista' => ['en' => 'list', 'de' => 'Liste', 'fr' => 'liste', 'ja' => 'リスト', 'ko' => '목록'],
        'listo' => ['en' => 'ready', 'de' => 'bereit', 'fr' => 'prêt', 'ja' => '準備ができた', 'ko' => '준비된'],
        'litro' => ['en' => 'litre', 'de' => 'Liter', 'fr' => 'litre', 'ja' => 'リットル', 'ko' => '리터'],
        'litros' => ['en' => 'litre', 'de' => 'Liter', 'fr' => 'litre', 'ja' => 'リットル', 'ko' => '리터'],
        'llama' => ['en' => 'call', 'de' => 'ruft', 'fr' => 'appelle', 'ja' => '電話する', 'ko' => '전화하다'],
        'llamada' => ['en' => 'call', 'de' => 'Anruf', 'fr' => 'appel', 'ja' => '電話', 'ko' => '전화'],
        'llamar' => ['en' => 'call', 'de' => 'anrufen', 'fr' => 'appeler', 'ja' => '電話する', 'ko' => '전화하다'],
        'lleno' => ['en' => 'full', 'de' => 'voll', 'fr' => 'plein', 'ja' => 'いっぱい', 'ko' => '가득한'],
        'llevar' => ['en' => 'to carry', 'de' => 'tragen', 'fr' => 'porter', 'ja' => '運ぶ', 'ko' => '나르다'],
        'lluvia' => ['en' => 'rain', 'de' => 'Regen', 'fr' => 'pluie', 'ja' => '雨', 'ko' => '비'],
        'llámame' => ['en' => 'call me', 'de' => 'ruf mich an', 'fr' => 'appelle-moi', 'ja' => '電話して', 'ko' => '전화해'],
        'lo' => ['en' => 'it', 'de' => 'es', 'fr' => 'le', 'ja' => 'それ', 'ko' => '그것'],
        'lo siento' => ['en' => 'sorry', 'de' => 'Entschuldigung', 'fr' => 'désolé', 'ja' => 'ごめんなさい', 'ko' => '죄송합니다'],
        'los' => ['en' => 'the', 'de' => 'die', 'fr' => 'les', 'ja' => 'その', 'ko' => '그'],
        'lunes' => ['en' => 'Monday', 'de' => 'Montag', 'fr' => 'lundi', 'ja' => '月曜日', 'ko' => '월요일'],
        'madre' => ['en' => 'mother', 'de' => 'Mutter', 'fr' => 'mère', 'ja' => '母', 'ko' => '어머니'],
        'mantequilla' => ['en' => 'butter', 'de' => 'Butter', 'fr' => 'beurre', 'ja' => 'バター', 'ko' => '버터'],
        'manzana' => ['en' => 'apple', 'de' => 'Apfel', 'fr' => 'pomme', 'ja' => 'りんご', 'ko' => '사과'],
        'martes' => ['en' => 'Tuesday', 'de' => 'Dienstag', 'fr' => 'mardi', 'ja' => '火曜日', 'ko' => '화요일'],
        'mañana' => ['en' => 'morning', 'de' => 'Morgen', 'fr' => 'matin', 'ja' => '朝', 'ko' => '아침'],
        'me' => ['en' => 'me', 'de' => 'mich', 'fr' => 'moi', 'ja' => '私', 'ko' => '저'],
        'me siento' => ['en' => 'I feel', 'de' => 'ich fühle mich', 'fr' => 'je me sens', 'ja' => '私は感じる', 'ko' => '나는 느낍니다'],
        'mediodía' => ['en' => 'noon', 'de' => 'Mittag', 'fr' => 'midi', 'ja' => '正午', 'ko' => '정오'],
        'mejor' => ['en' => 'better', 'de' => 'besser', 'fr' => 'meilleur', 'ja' => 'もっと良い', 'ko' => '더 좋은'],
        'menos' => ['en' => 'less', 'de' => 'weniger', 'fr' => 'moins', 'ja' => 'より少ない', 'ko' => '덜'],
        'mensaje' => ['en' => 'message', 'de' => 'Nachricht', 'fr' => 'message', 'ja' => 'メッセージ', 'ko' => '메시지'],
        'menú' => ['en' => 'menu', 'de' => 'Menü', 'fr' => 'menu', 'ja' => 'メニュー', 'ko' => '메뉴'],
        'mesa' => ['en' => 'table', 'de' => 'Tisch', 'fr' => 'table', 'ja' => 'テーブル', 'ko' => '탁자'],
        'mi' => ['en' => 'my', 'de' => 'mein', 'fr' => 'mon', 'ja' => '私の', 'ko' => '나의'],
        'minutos' => ['en' => 'minutes', 'de' => 'Minuten', 'fr' => 'minutes', 'ja' => '分', 'ko' => '분'],
        'mirar' => ['en' => 'watch', 'de' => 'schauen', 'fr' => 'regarder', 'ja' => '見る', 'ko' => '보다'],
        'mismo' => ['en' => 'same', 'de' => 'gleich', 'fr' => 'même', 'ja' => '同じ', 'ko' => '같은'],
        'muy' => ['en' => 'very', 'de' => 'sehr', 'fr' => 'très', 'ja' => 'とても', 'ko' => '매우'],
        'más' => ['en' => 'more', 'de' => 'mehr', 'fr' => 'plus', 'ja' => 'もっと', 'ko' => '더'],
        'más tarde' => ['en' => 'later', 'de' => 'später', 'fr' => 'plus tard', 'ja' => '後で', 'ko' => '나중에'],
        'médico' => ['en' => 'doctor', 'de' => 'Arzt', 'fr' => 'médecin', 'ja' => '医者', 'ko' => '의사'],
        'mí' => ['en' => 'me', 'de' => 'mich', 'fr' => 'moi', 'ja' => '私', 'ko' => '저'],
        'naranja' => ['en' => 'orange', 'de' => 'Orange', 'fr' => 'orange', 'ja' => 'オレンジ', 'ko' => '오렌지'],
        'nata' => ['en' => 'cream', 'de' => 'Sahne', 'fr' => 'crème', 'ja' => 'クリーム', 'ko' => '크림'],
        'necesito' => ['en' => 'I need', 'de' => 'ich brauche', 'fr' => 'j\'ai besoin', 'ja' => '必要です', 'ko' => '필요합니다'],
        'negro' => ['en' => 'black', 'de' => 'schwarz', 'fr' => 'noir', 'ja' => '黒', 'ko' => '검은색'],
        'nieve' => ['en' => 'snow', 'de' => 'Schnee', 'fr' => 'neige', 'ja' => '雪', 'ko' => '눈'],
        'niño' => ['en' => 'child', 'de' => 'Kind', 'fr' => 'enfant', 'ja' => '子供', 'ko' => '아이'],
        'no' => ['en' => 'no', 'de' => 'nein', 'fr' => 'non', 'ja' => 'いいえ', 'ko' => '아니요'],
        'noche' => ['en' => 'night', 'de' => 'Nacht', 'fr' => 'nuit', 'ja' => '夜', 'ko' => '밤'],
        'nombre' => ['en' => 'name', 'de' => 'Name', 'fr' => 'nom', 'ja' => '名前', 'ko' => '이름'],
        'norte' => ['en' => 'north', 'de' => 'Norden', 'fr' => 'nord', 'ja' => '北', 'ko' => '북쪽'],
        'nube' => ['en' => 'cloud', 'de' => 'Wolke', 'fr' => 'nuage', 'ja' => '雲', 'ko' => '구름'],
        'nueces' => ['en' => 'nuts', 'de' => 'Nüsse', 'fr' => 'noix', 'ja' => 'ナッツ', 'ko' => '견과류'],
        'nueva' => ['en' => 'new', 'de' => 'neu', 'fr' => 'nouveau', 'ja' => '新しい', 'ko' => '새로운'],
        'nueve' => ['en' => 'nine', 'de' => 'neun', 'fr' => 'neuf', 'ja' => '九', 'ko' => '아홉'],
        'nuevo' => ['en' => 'new', 'de' => 'neu', 'fr' => 'nouveau', 'ja' => '新しい', 'ko' => '새로운'],
        'o' => ['en' => 'or', 'de' => 'oder', 'fr' => 'ou', 'ja' => 'または', 'ko' => '또는'],
        'ocho' => ['en' => 'eight', 'de' => 'acht', 'fr' => 'huit', 'ja' => '八', 'ko' => '여덟'],
        'ocupada' => ['en' => 'busy', 'de' => 'beschäftigt', 'fr' => 'occupé', 'ja' => '忙しい', 'ko' => '바쁜'],
        'ocupado' => ['en' => 'busy', 'de' => 'beschäftigt', 'fr' => 'occupé', 'ja' => '忙しい', 'ko' => '바쁜'],
        'otoño' => ['en' => 'autumn', 'de' => 'Herbst', 'fr' => 'automne', 'ja' => '秋', 'ko' => '가을'],
        'otro' => ['en' => 'another', 'de' => 'noch ein', 'fr' => 'encore', 'ja' => 'もう一つの', 'ko' => '하나 더'],
        'padre' => ['en' => 'father', 'de' => 'Vater', 'fr' => 'père', 'ja' => '父', 'ko' => '아버지'],
        'pagar' => ['en' => 'pay', 'de' => 'bezahlen', 'fr' => 'payer', 'ja' => '払う', 'ko' => '지불하다'],
        'pago' => ['en' => 'I pay', 'de' => 'ich bezahle', 'fr' => 'je paie', 'ja' => '私が払う', 'ko' => '제가 냅니다'],
        'pan' => ['en' => 'bread', 'de' => 'Brot', 'fr' => 'pain', 'ja' => 'パン', 'ko' => '빵'],
        'panadería' => ['en' => 'bakery', 'de' => 'Bäckerei', 'fr' => 'boulangerie', 'ja' => 'パン屋', 'ko' => '빵집'],
        'para' => ['en' => 'for', 'de' => 'für', 'fr' => 'pour', 'ja' => 'のために', 'ko' => '위해'],
        'para llevar' => ['en' => 'takeaway', 'de' => 'zum Mitnehmen', 'fr' => 'à emporter', 'ja' => '持ち帰り', 'ko' => '포장'],
        'para tomar aquí' => ['en' => 'eat in', 'de' => 'zum Hieressen', 'fr' => 'sur place', 'ja' => '店内で', 'ko' => '매장에서'],
        'parque' => ['en' => 'park', 'de' => 'Park', 'fr' => 'parc', 'ja' => '公園', 'ko' => '공원'],
        'pasillo' => ['en' => 'aisle', 'de' => 'Regal', 'fr' => 'rayon', 'ja' => '売り場', 'ko' => '진열대'],
        'pastel' => ['en' => 'cake', 'de' => 'Kuchen', 'fr' => 'gâteau', 'ja' => 'ケーキ', 'ko' => '케이크'],
        'patata' => ['en' => 'potato', 'de' => 'Kartoffel', 'fr' => 'pomme de terre', 'ja' => 'じゃがいも', 'ko' => '감자'],
        'patatas' => ['en' => 'potato', 'de' => 'Kartoffel', 'fr' => 'pomme de terre', 'ja' => 'じゃがいも', 'ko' => '감자'],
        'patatas fritas' => ['en' => 'fries', 'de' => 'Pommes', 'fr' => 'frites', 'ja' => 'フライドポテト', 'ko' => '감자튀김'],
        'pedido' => ['en' => 'order', 'de' => 'Bestellung', 'fr' => 'commande', 'ja' => '注文', 'ko' => '주문'],
        'pedir' => ['en' => 'to order', 'de' => 'bestellen', 'fr' => 'commander', 'ja' => '注文する', 'ko' => '주문하다'],
        'película' => ['en' => 'film', 'de' => 'Film', 'fr' => 'film', 'ja' => '映画', 'ko' => '영화'],
        'peor' => ['en' => 'worse', 'de' => 'schlechter', 'fr' => 'pire', 'ja' => 'もっと悪い', 'ko' => '더 나쁜'],
        'pequeña' => ['en' => 'small', 'de' => 'klein', 'fr' => 'petit', 'ja' => '小さい', 'ko' => '작은'],
        'pequeño' => ['en' => 'small', 'de' => 'klein', 'fr' => 'petit', 'ja' => '小さい', 'ko' => '작은'],
        'perfecto' => ['en' => 'perfect', 'de' => 'perfekt', 'fr' => 'parfait', 'ja' => '完璧', 'ko' => '완벽한'],
        'pero' => ['en' => 'but', 'de' => 'aber', 'fr' => 'mais', 'ja' => 'しかし', 'ko' => '하지만'],
        'perro' => ['en' => 'dog', 'de' => 'Hund', 'fr' => 'chien', 'ja' => '犬', 'ko' => '개'],
        'perros' => ['en' => 'dogs', 'de' => 'Hunde', 'fr' => 'chiens', 'ja' => '犬', 'ko' => '개들'],
        'personas' => ['en' => 'people', 'de' => 'Personen', 'fr' => 'personnes', 'ja' => '人', 'ko' => '명'],
        'pesada' => ['en' => 'heavy', 'de' => 'schwer', 'fr' => 'lourd', 'ja' => '重い', 'ko' => '무거운'],
        'pesado' => ['en' => 'heavy', 'de' => 'schwer', 'fr' => 'lourd', 'ja' => '重い', 'ko' => '무거운'],
        'pesar' => ['en' => 'to weigh', 'de' => 'wiegen', 'fr' => 'peser', 'ja' => '量る', 'ko' => '무게를 재다'],
        'pescado' => ['en' => 'fish', 'de' => 'Fisch', 'fr' => 'poisson', 'ja' => '魚', 'ko' => '생선'],
        'picante' => ['en' => 'spicy', 'de' => 'scharf', 'fr' => 'épicé', 'ja' => '辛い', 'ko' => '매운'],
        'pimienta' => ['en' => 'pepper', 'de' => 'Pfeffer', 'fr' => 'poivre', 'ja' => 'こしょう', 'ko' => '후추'],
        'plato' => ['en' => 'plate', 'de' => 'Teller', 'fr' => 'assiette', 'ja' => 'お皿', 'ko' => '접시'],
        'plátano' => ['en' => 'banana', 'de' => 'Banane', 'fr' => 'banane', 'ja' => 'バナナ', 'ko' => '바나나'],
        'poco' => ['en' => 'little', 'de' => 'wenig', 'fr' => 'peu', 'ja' => '少し', 'ko' => '조금'],
        'pollo' => ['en' => 'chicken', 'de' => 'Hähnchen', 'fr' => 'poulet', 'ja' => '鶏肉', 'ko' => '닭고기'],
        'poner' => ['en' => 'to put', 'de' => 'legen', 'fr' => 'mettre', 'ja' => '入れる', 'ko' => '넣다'],
        'por' => ['en' => 'for', 'de' => 'für', 'fr' => 'pour', 'ja' => 'のために', 'ko' => '위해'],
        'por favor' => ['en' => 'please', 'de' => 'bitte', 'fr' => 's\'il vous plaît', 'ja' => 'お願いします', 'ko' => '부탁합니다'],
        'por qué' => ['en' => 'why', 'de' => 'warum', 'fr' => 'pourquoi', 'ja' => 'なぜ', 'ko' => '왜'],
        'por separado' => ['en' => 'separately', 'de' => 'getrennt', 'fr' => 'séparément', 'ja' => '別々に', 'ko' => '따로'],
        'por supuesto' => ['en' => 'of course', 'de' => 'natürlich', 'fr' => 'bien sûr', 'ja' => 'もちろん', 'ko' => '물론'],
        'porque' => ['en' => 'because', 'de' => 'weil', 'fr' => 'parce que', 'ja' => 'なぜなら', 'ko' => '왜냐하면'],
        'postre' => ['en' => 'dessert', 'de' => 'Nachtisch', 'fr' => 'dessert', 'ja' => 'デザート', 'ko' => '디저트'],
        'precio' => ['en' => 'price', 'de' => 'Preis', 'fr' => 'prix', 'ja' => '値段', 'ko' => '가격'],
        'precios' => ['en' => 'prices', 'de' => 'Preise', 'fr' => 'prix', 'ja' => '値段', 'ko' => '가격'],
        'prefiero' => ['en' => 'I prefer', 'de' => 'ich bevorzuge', 'fr' => 'je préfère', 'ja' => '私は好む', 'ko' => '나는 선호한다'],
        'primavera' => ['en' => 'spring', 'de' => 'Frühling', 'fr' => 'printemps', 'ja' => '春', 'ko' => '봄'],
        'problema' => ['en' => 'problem', 'de' => 'Problem', 'fr' => 'problème', 'ja' => '問題', 'ko' => '문제'],
        'producto' => ['en' => 'product', 'de' => 'Produkt', 'fr' => 'produit', 'ja' => '商品', 'ko' => '상품'],
        'profesor' => ['en' => 'teacher', 'de' => 'Lehrer', 'fr' => 'professeur', 'ja' => '先生', 'ko' => '선생님'],
        'pronto' => ['en' => 'soon', 'de' => 'bald', 'fr' => 'bientôt', 'ja' => 'すぐに', 'ko' => '곧'],
        'propina' => ['en' => 'tip', 'de' => 'Trinkgeld', 'fr' => 'pourboire', 'ja' => 'チップ', 'ko' => '팁'],
        'próxima' => ['en' => 'next', 'de' => 'nächste', 'fr' => 'prochain', 'ja' => '次の', 'ko' => '다음'],
        'próximo' => ['en' => 'next', 'de' => 'nächste', 'fr' => 'prochain', 'ja' => '次の', 'ko' => '다음'],
        'pueblo' => ['en' => 'village', 'de' => 'Dorf', 'fr' => 'village', 'ja' => '村', 'ko' => '마을'],
        'puede' => ['en' => 'can', 'de' => 'können', 'fr' => 'pouvez', 'ja' => 'できる', 'ko' => '할 수 있다'],
        'puede usted' => ['en' => 'can you', 'de' => 'können Sie', 'fr' => 'pouvez-vous', 'ja' => 'できますか', 'ko' => '주시겠어요'],
        'puedo' => ['en' => 'I can', 'de' => 'ich kann', 'fr' => 'je peux', 'ja' => '私はできる', 'ko' => '나는 할 수 있다'],
        'punto' => ['en' => 'o\'clock', 'de' => 'Uhr', 'fr' => 'heures', 'ja' => '時', 'ko' => '시'],
        'que' => ['en' => 'than', 'de' => 'als', 'fr' => 'que', 'ja' => 'より', 'ko' => '보다'],
        'queso' => ['en' => 'cheese', 'de' => 'Käse', 'fr' => 'fromage', 'ja' => 'チーズ', 'ko' => '치즈'],
        'quiero' => ['en' => 'I want', 'de' => 'ich will', 'fr' => 'je veux', 'ja' => 'たいです', 'ko' => '나는 원한다'],
        'quisiera' => ['en' => 'I would like', 'de' => 'ich möchte', 'fr' => 'je voudrais', 'ja' => 'ください', 'ko' => '주세요'],
        'quizás' => ['en' => 'maybe', 'de' => 'vielleicht', 'fr' => 'peut-être', 'ja' => 'たぶん', 'ko' => '아마도'],
        'quién' => ['en' => 'who', 'de' => 'wer', 'fr' => 'qui', 'ja' => '誰', 'ko' => '누구'],
        'qué' => ['en' => 'what', 'de' => 'was', 'fr' => 'quoi', 'ja' => '何', 'ko' => '무엇'],
        'recibo' => ['en' => 'receipt', 'de' => 'Quittung', 'fr' => 'reçu', 'ja' => 'レシート', 'ko' => '영수증'],
        'recto' => ['en' => 'straight', 'de' => 'geradeaus', 'fr' => 'tout droit', 'ja' => 'まっすぐ', 'ko' => '똑바로'],
        'reloj' => ['en' => 'clock', 'de' => 'Uhr', 'fr' => 'horloge', 'ja' => '時計', 'ko' => '시계'],
        'reserva' => ['en' => 'booking', 'de' => 'Reservierung', 'fr' => 'réservation', 'ja' => '予約', 'ko' => '예약'],
        'reservar' => ['en' => 'to book', 'de' => 'reservieren', 'fr' => 'réserver', 'ja' => '予約する', 'ko' => '예약하다'],
        'restaurante' => ['en' => 'restaurant', 'de' => 'Restaurant', 'fr' => 'restaurant', 'ja' => 'レストラン', 'ko' => '식당'],
        'rojo' => ['en' => 'red', 'de' => 'rot', 'fr' => 'rouge', 'ja' => '赤', 'ko' => '빨간색'],
        'rápida' => ['en' => 'fast', 'de' => 'schnell', 'fr' => 'rapide', 'ja' => '速い', 'ko' => '빠른'],
        'rápido' => ['en' => 'fast', 'de' => 'schnell', 'fr' => 'rapide', 'ja' => '速い', 'ko' => '빠른'],
        'sabor' => ['en' => 'taste', 'de' => 'Geschmack', 'fr' => 'goût', 'ja' => '味', 'ko' => '맛'],
        'sal' => ['en' => 'salt', 'de' => 'Salz', 'fr' => 'sel', 'ja' => '塩', 'ko' => '소금'],
        'salado' => ['en' => 'salty', 'de' => 'salzig', 'fr' => 'salé', 'ja' => 'しょっぱい', 'ko' => '짠'],
        'sed' => ['en' => 'thirsty', 'de' => 'durstig', 'fr' => 'soif', 'ja' => 'のどが渇いた', 'ko' => '목마른'],
        'sediento' => ['en' => 'thirsty', 'de' => 'durstig', 'fr' => 'assoiffé', 'ja' => 'のどが渇いた', 'ko' => '목마른'],
        'seis' => ['en' => 'six', 'de' => 'sechs', 'fr' => 'six', 'ja' => '六', 'ko' => '여섯'],
        'semana' => ['en' => 'week', 'de' => 'Woche', 'fr' => 'semaine', 'ja' => '週', 'ko' => '주'],
        'separado' => ['en' => 'separately', 'de' => 'getrennt', 'fr' => 'séparément', 'ja' => '別々', 'ko' => '따로'],
        'servilleta' => ['en' => 'napkin', 'de' => 'Serviette', 'fr' => 'serviette', 'ja' => 'ナプキン', 'ko' => '냅킨'],
        'señor' => ['en' => 'sir', 'de' => 'mein Herr', 'fr' => 'monsieur', 'ja' => 'ムッシュ', 'ko' => '선생님'],
        'señora' => ['en' => 'madam', 'de' => 'gnädige Frau', 'fr' => 'madame', 'ja' => 'マダム', 'ko' => '부인'],
        'siento' => ['en' => 'feel', 'de' => 'fühle', 'fr' => 'sens', 'ja' => '感じる', 'ko' => '느끼다'],
        'siete' => ['en' => 'seven', 'de' => 'sieben', 'fr' => 'sept', 'ja' => '七', 'ko' => '일곱'],
        'silla' => ['en' => 'chair', 'de' => 'Stuhl', 'fr' => 'chaise', 'ja' => '椅子', 'ko' => '의자'],
        'sin' => ['en' => 'without', 'de' => 'ohne', 'fr' => 'sans', 'ja' => 'なし', 'ko' => '없이'],
        'sitio' => ['en' => 'seat', 'de' => 'Platz', 'fr' => 'place', 'ja' => '席', 'ko' => '자리'],
        'sobre' => ['en' => 'on', 'de' => 'auf', 'fr' => 'sur', 'ja' => 'の上に', 'ko' => '위에'],
        'sobre todo' => ['en' => 'especially', 'de' => 'besonders', 'fr' => 'surtout', 'ja' => '特に', 'ko' => '특히'],
        'sol' => ['en' => 'sun', 'de' => 'Sonne', 'fr' => 'soleil', 'ja' => '太陽', 'ko' => '해'],
        'son' => ['en' => 'are', 'de' => 'sind', 'fr' => 'sont', 'ja' => 'です', 'ko' => '입니다'],
        'sopa' => ['en' => 'soup', 'de' => 'Suppe', 'fr' => 'soupe', 'ja' => 'スープ', 'ko' => '수프'],
        'soy' => ['en' => 'I am', 'de' => 'ich bin', 'fr' => 'je suis', 'ja' => 'です', 'ko' => '입니다'],
        'sucio' => ['en' => 'dirty', 'de' => 'schmutzig', 'fr' => 'sale', 'ja' => '汚い', 'ko' => '더러운'],
        'supermercado' => ['en' => 'supermarket', 'de' => 'Supermarkt', 'fr' => 'supermarché', 'ja' => 'スーパー', 'ko' => '슈퍼마켓'],
        'supuesto' => ['en' => 'course', 'de' => 'natürlich', 'fr' => 'sûr', 'ja' => 'もちろん', 'ko' => '물론'],
        'sur' => ['en' => 'south', 'de' => 'Süden', 'fr' => 'sud', 'ja' => '南', 'ko' => '남쪽'],
        'sándwich' => ['en' => 'sandwich', 'de' => 'Sandwich', 'fr' => 'sandwich', 'ja' => 'サンドイッチ', 'ko' => '샌드위치'],
        'sí' => ['en' => 'yes', 'de' => 'ja', 'fr' => 'oui', 'ja' => 'はい', 'ko' => '네'],
        'también' => ['en' => 'also', 'de' => 'auch', 'fr' => 'aussi', 'ja' => 'も', 'ko' => '또한'],
        'tanto' => ['en' => 'as much', 'de' => 'genauso viel', 'fr' => 'autant', 'ja' => '同じくらい', 'ko' => '그만큼'],
        'tarde' => ['en' => 'evening', 'de' => 'Abend', 'fr' => 'soir', 'ja' => '夕方', 'ko' => '저녁'],
        'tarjeta' => ['en' => 'card', 'de' => 'Karte', 'fr' => 'carte', 'ja' => 'カード', 'ko' => '카드'],
        'tarta' => ['en' => 'tart', 'de' => 'Torte', 'fr' => 'tarte', 'ja' => 'タルト', 'ko' => '타르트'],
        'teléfono' => ['en' => 'phone', 'de' => 'Telefon', 'fr' => 'téléphone', 'ja' => '電話', 'ko' => '전화'],
        'tenedor' => ['en' => 'fork', 'de' => 'Gabel', 'fr' => 'fourchette', 'ja' => 'フォーク', 'ko' => '포크'],
        'tengo' => ['en' => 'I have', 'de' => 'ich habe', 'fr' => 'j\'ai', 'ja' => '私は持っている', 'ko' => '나는 가지고 있다'],
        'tiempo' => ['en' => 'weather', 'de' => 'Wetter', 'fr' => 'temps', 'ja' => '天気', 'ko' => '날씨'],
        'tienda' => ['en' => 'shop', 'de' => 'Geschäft', 'fr' => 'magasin', 'ja' => '店', 'ko' => '가게'],
        'todo' => ['en' => 'all', 'de' => 'alles', 'fr' => 'tout', 'ja' => 'すべて', 'ko' => '모든'],
        'tomar' => ['en' => 'have', 'de' => 'nehmen', 'fr' => 'prendre', 'ja' => '食べる', 'ko' => '먹다'],
        'tomate' => ['en' => 'tomato', 'de' => 'Tomate', 'fr' => 'tomate', 'ja' => 'トマト', 'ko' => '토마토'],
        'tomo' => ['en' => 'I\'ll have', 'de' => 'ich nehme', 'fr' => 'je prends', 'ja' => 'にします', 'ko' => '하겠습니다'],
        'total' => ['en' => 'total', 'de' => 'Gesamt', 'fr' => 'total', 'ja' => '合計', 'ko' => '총액'],
        'traer' => ['en' => 'to bring', 'de' => 'bringen', 'fr' => 'apporter', 'ja' => '持ってくる', 'ko' => '가져오다'],
        'tranquila' => ['en' => 'calm', 'de' => 'ruhig', 'fr' => 'calme', 'ja' => '落ち着いた', 'ko' => '차분한'],
        'tranquilo' => ['en' => 'calm', 'de' => 'ruhig', 'fr' => 'calme', 'ja' => '落ち着いた', 'ko' => '차분한'],
        'tres' => ['en' => 'three', 'de' => 'drei', 'fr' => 'trois', 'ja' => '三', 'ko' => '셋'],
        'triste' => ['en' => 'sad', 'de' => 'traurig', 'fr' => 'triste', 'ja' => '悲しい', 'ko' => '슬픈'],
        'trozo' => ['en' => 'slice', 'de' => 'Stück', 'fr' => 'part', 'ja' => '一切れ', 'ko' => '한 조각'],
        'tráigame' => ['en' => 'bring me', 'de' => 'bringen Sie mir', 'fr' => 'apportez-moi', 'ja' => '持ってきてください', 'ko' => '가져다주세요'],
        'tu' => ['en' => 'your', 'de' => 'dein', 'fr' => 'ton', 'ja' => 'あなたの', 'ko' => '당신의'],
        'té' => ['en' => 'tea', 'de' => 'Tee', 'fr' => 'thé', 'ja' => 'お茶', 'ko' => '차'],
        'tú' => ['en' => 'you', 'de' => 'du', 'fr' => 'tu', 'ja' => 'あなた', 'ko' => '당신'],
        'un' => ['en' => 'a', 'de' => 'ein', 'fr' => 'un', 'ja' => '一つの', 'ko' => '하나의'],
        'un poco' => ['en' => 'a little', 'de' => 'ein bisschen', 'fr' => 'un peu', 'ja' => '少し', 'ko' => '조금'],
        'una' => ['en' => 'a', 'de' => 'eine', 'fr' => 'une', 'ja' => '一つの', 'ko' => '하나의'],
        'una bebida' => ['en' => 'a drink', 'de' => 'ein Getränk', 'fr' => 'une boisson', 'ja' => '飲み物', 'ko' => '음료'],
        'uno' => ['en' => 'one', 'de' => 'eins', 'fr' => 'un', 'ja' => '一', 'ko' => '하나'],
        'unos' => ['en' => 'one', 'de' => 'eins', 'fr' => 'un', 'ja' => '一', 'ko' => '하나'],
        'uvas' => ['en' => 'grapes', 'de' => 'Trauben', 'fr' => 'raisin', 'ja' => 'ぶどう', 'ko' => '포도'],
        'vacía' => ['en' => 'empty', 'de' => 'leer', 'fr' => 'vide', 'ja' => '空', 'ko' => '빈'],
        'vacío' => ['en' => 'empty', 'de' => 'leer', 'fr' => 'vide', 'ja' => '空', 'ko' => '빈'],
        'vainilla' => ['en' => 'vanilla', 'de' => 'Vanille', 'fr' => 'vanille', 'ja' => 'バニラ', 'ko' => '바닐라'],
        'vale' => ['en' => 'okay', 'de' => 'okay', 'fr' => 'd\'accord', 'ja' => 'いいよ', 'ko' => '좋아요'],
        'vamos' => ['en' => 'let\'s go', 'de' => 'lass uns gehen', 'fr' => 'allons-y', 'ja' => '行きましょう', 'ko' => '갑시다'],
        'vaso' => ['en' => 'glass', 'de' => 'Glas', 'fr' => 'verre', 'ja' => 'グラス', 'ko' => '유리잔'],
        've' => ['en' => 'see', 'de' => 'sieht', 'fr' => 'voit', 'ja' => '見る', 'ko' => '보다'],
        'vecino' => ['en' => 'neighbour', 'de' => 'Nachbar', 'fr' => 'voisin', 'ja' => '隣人', 'ko' => '이웃'],
        'vegetariano' => ['en' => 'vegetarian', 'de' => 'vegetarisch', 'fr' => 'végétarien', 'ja' => 'ベジタリアン', 'ko' => '채식주의자'],
        'venir' => ['en' => 'come', 'de' => 'kommen', 'fr' => 'venir', 'ja' => '来る', 'ko' => '오다'],
        'ver' => ['en' => 'see', 'de' => 'sehen', 'fr' => 'voir', 'ja' => '見る', 'ko' => '보다'],
        'verano' => ['en' => 'summer', 'de' => 'Sommer', 'fr' => 'été', 'ja' => '夏', 'ko' => '여름'],
        'verdad' => ['en' => 'true', 'de' => 'wahr', 'fr' => 'vrai', 'ja' => '本当', 'ko' => '사실'],
        'verdadero' => ['en' => 'true', 'de' => 'wahr', 'fr' => 'vrai', 'ja' => '本当', 'ko' => '사실'],
        'verde' => ['en' => 'green', 'de' => 'grün', 'fr' => 'vert', 'ja' => '緑', 'ko' => '초록색'],
        'verduras' => ['en' => 'vegetables', 'de' => 'Gemüse', 'fr' => 'légumes', 'ja' => '野菜', 'ko' => '채소'],
        'vi' => ['en' => 'I saw', 'de' => 'ich sah', 'fr' => 'j\'ai vu', 'ja' => '私は見た', 'ko' => '나는 보았다'],
        'viejo' => ['en' => 'old', 'de' => 'alt', 'fr' => 'vieux', 'ja' => '古い', 'ko' => '오래된'],
        'viento' => ['en' => 'wind', 'de' => 'Wind', 'fr' => 'vent', 'ja' => '風', 'ko' => '바람'],
        'vino' => ['en' => 'wine', 'de' => 'Wein', 'fr' => 'vin', 'ja' => 'ワイン', 'ko' => '와인'],
        'vivo' => ['en' => 'I live', 'de' => 'ich wohne', 'fr' => 'j\'habite', 'ja' => '私は住んでいる', 'ko' => '나는 삽니다'],
        'voy' => ['en' => 'I am going', 'de' => 'ich gehe', 'fr' => 'je vais', 'ja' => '私は行く', 'ko' => '나는 갈 것이다'],
        'y' => ['en' => 'and', 'de' => 'und', 'fr' => 'et', 'ja' => 'と', 'ko' => '그리고'],
        'ya' => ['en' => 'already', 'de' => 'schon', 'fr' => 'déjà', 'ja' => 'もう', 'ko' => '이미'],
        'yo' => ['en' => 'I', 'de' => 'ich', 'fr' => 'je', 'ja' => '私', 'ko' => '나'],
        'zanahoria' => ['en' => 'carrot', 'de' => 'Karotte', 'fr' => 'carotte', 'ja' => 'にんじん', 'ko' => '당근'],
        'zumo' => ['en' => 'juice', 'de' => 'Saft', 'fr' => 'jus', 'ja' => 'ジュース', 'ko' => '주스'],
        'él' => ['en' => 'he', 'de' => 'er', 'fr' => 'il', 'ja' => '彼', 'ko' => '그'],
        'él es' => ['en' => 'he is', 'de' => 'er ist', 'fr' => 'il est', 'ja' => '彼は', 'ko' => '그는'],
    ];

    /** Native languages a learner can take a Spanish course in. */
    private const LANGS = ['en', 'de', 'fr', 'ja', 'ko'];

    /**
     * The ['i18n' => [...]] map for a Spanish word, ready to store in exercise
     * data. Falls back to the word itself if it isn't in the dictionary yet.
     *
     * @return array{i18n: array<string, string>}
     */
    public static function hint(string $spanish): array
    {
        return ['i18n' => self::meanings($spanish)];
    }

    /**
     * @return array<string, string>
     */
    public static function meanings(string $spanish): array
    {
        $key = mb_strtolower(trim($spanish));

        foreach (self::WORDS as $word => $translations) {
            if (mb_strtolower($word) === $key) {
                return $translations;
            }
        }

        // Not in the dictionary: show the Spanish word itself to every learner.
        return array_fill_keys(self::LANGS, $spanish);
    }

    /** Every Spanish word the dictionary knows (used for wrong-answer options). */
    public static function all(): array
    {
        return array_keys(self::WORDS);
    }

    public static function knows(string $spanish): bool
    {
        $key = mb_strtolower(trim($spanish));

        foreach (array_keys(self::WORDS) as $word) {
            if (mb_strtolower($word) === $key) {
                return true;
            }
        }

        return false;
    }
}
