<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Lets `exercise_instructions` describe the two newest exercise types.
 *
 * `exercises.type` already lists all seven, but the instructions table was
 * created earlier and still only allowed five. Writing an instruction for
 * `translate` or `paragraph_translation` failed with "Data truncated for column
 * 'exercise_type'", so those two types could never have an instruction in any
 * language, and both apps fell back to their hardcoded English label for them.
 *
 * Raw SQL for the same reason as the ad placement migration: Doctrine DBAL does
 * not model enums, and `$table->enum(...)->change()` quietly degrades to a
 * varchar on some driver versions, which would drop the constraint that makes
 * the column worth having.
 */
return new class extends Migration
{
    private const OLD = ['match_pairs', 'fill_blank', 'tap_word', 'listen_select', 'multiple_choice'];

    private const NEW = [
        'match_pairs', 'fill_blank', 'tap_word', 'listen_select',
        'multiple_choice', 'paragraph_translation', 'translate',
    ];

    public function up(): void
    {
        $this->setEnum(self::NEW);
    }

    public function down(): void
    {
        // Rows for the two new types have nowhere to go once the cases are
        // removed, and an instruction is regenerated by its seeder, so dropping
        // them is safe and keeps the rollback from failing on a constraint.
        DB::table('exercise_instructions')
            ->whereIn('exercise_type', ['paragraph_translation', 'translate'])
            ->delete();

        $this->setEnum(self::OLD);
    }

    private function setEnum(array $values): void
    {
        if (DB::connection()->getDriverName() !== 'mysql') {
            return;
        }

        $list = collect($values)->map(fn (string $value) => "'".$value."'")->implode(',');

        DB::statement("ALTER TABLE exercise_instructions MODIFY exercise_type ENUM({$list}) NOT NULL");
    }
};
